### DISCUSSION TITLE
Failed to read configuration file

### DISCUSSION THREAD

**Discussion by techpassionx** [tchiotludo/akhq#1001] [Q&A]
When I try to deploy AKHQ on AKS I get an error:
```
022-01-27 14:07:06,353 ←[1;31mERROR←[0;39m ←[35mmain      ←[0;39m ←[36mi.m.runtime.Micronaut     ←[0;39m Error starting Micronaut server: Failed to read configuration file: /app/application.yml
```

The configuration file(```application.yml```) looks like this:

```
akhq:
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]" # Logger format

# list of kafka cluster available for akhq
  connections:
    kafka-cluster-ssl:
      properties:
        bootstrap.servers: "FQDN-Addr-01:9093,FQDN-Addr-02:9093,FQDN-Addr-03:9093"
        security.protocol: SSL
        ssl.truststore.location: /app/truststore.jks
        ssl.truststore.password: PWD
        ssl.keystore.location: /app/keystore.jks
        ssl.keystore.password: PWD
        #ssl.key.password: PWD
```

```
```

I passed also read permission to the file in Dockerfile but that didn't help.

**Dockerfile**
```
FROM tchiotludo/akhq:0.20.0

# add ssl producer/consumer config and root ca file
ADD ./resources/ /app/

USER root
RUN chmod +r application.yml
RUN chmod +x gen-certs.sh
RUN ./gen-certs.sh
```

I created a docker container(without running it) locally and exported the content and all files inclusive application.yml were avaible in /app/ so I have no idea what is wrong with config. I hope somebody can help to find reason why I am getting error regarding reading the config file.
