### DISCUSSION TITLE
AKHQ KEYCLOAK roles mapping

### DISCUSSION THREAD

**Discussion by kosksq** [tchiotludo/akhq#1106] [Q&A]
Hi all, I currently facing KEYCLOAK roles mapping issue. This is part of my access token.
```
"roles": [
"admin"
],
"name": "xxx",
"preferred_username": "Test name",
"given_name": "xxx",
"family_name": "xxx",
```
For the access token, I have added the "admin" role to this user but it cannot be read by the AKHQ as I saw the roles are still the default group.
```
 akhq:
    security:
      oidc:
        enabled: true
        providers:
          oidc:
            label: "Login with keycloak"
            username-field: preferred_username
            groups-field: roles
            default-group: reader
            groups:
              - name: admin
                group:
                  - topic-reader
                  - topic-writer
```
![image](https://user-images.githubusercontent.com/74179948/170685242-07afd9d2-691b-45a7-81e6-4675f9250f1c.png)

If I remove the default group setting, I will redirect back to the login screen even successfully logged in and the roles in the cookie will be empty in this case. Any suggestion?
