### DISCUSSION TITLE
ACL for the user used by akhq to connect to kafka

### DISCUSSION THREAD

**Discussion by ghost** [tchiotludo/akhq#1108] [Q&A] [answered]
Hi,

Is there any recommendation on what ACLs are required for the user used by akhq to connect to kafka?

I have the below in place which works fine but I don't see "schema registry" and "connects" on the left panel of akhq, I guess I may be missing some permissions.

Can you please advise? Thanks.

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: akhq
  labels:
    strimzi.io/cluster: kafka-base
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: cluster
        name: "*"
      host: "*"
      operation: All
    - resource:
        type: topic
        name: "*"
      host: "*"
      operation: All
    - resource:
        type: group
        name: "*"
      host: "*"
      operation: All
    - resource:
        type: transactionalId
        name: "*"
      host: "*"
      operation: All
```

**Comment by tchiotludo** [comment, marked as answer]
The connect & schema registry tabs on left panels are only based on AKHQ configuration of the cluster and don't depend on ACL on Kafka clusters, so you must have a mistake on the `application.yml` configuration

**Reply by ghost** [reply]
Thanks for your reply. I have the application.yml below, could you please let me know where the problem is?

```
micronaut:
  security:
    enabled: true
    ldap:
      default:
        enabled: true
        context:
          server: 'ldaps://xxx:636'
          managerDn: 'xxx@xxx'
          managerPassword: 'xxx'
        search:
          base: "OU=xxx,DC=xxx,DC=xxx,DC=com"
          filter: "sAMAccountName={0}"
        groups:
          enabled: true
          base: "OU=xxx,DC=xxx,DC=xxx,DC=com"
          filter: "member={0}"
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
akhq:
  connections:
    Lab:
      properties:
        bootstrap.servers: "kafka-base-kafka-bootstrap.kafka-base:9093"
        security.protocol: SSL
        ssl.keystore.location: /app/kafka.client.keystore.jks
        ssl.keystore.password: xxx
        ssl.key.password: xxx
        ssl.truststore.location: /app/kafka.client.truststore.jks
        ssl.truststore.password: xxx
  security:
    default-group: no-roles
    groups:
      xxx:
        name: xxx
        roles:
          - topic/read
          - topic/data/read
          - group/read
        attributes:
          topics-filter-regexp:
            - "xxx.*"
    ldap:
      groups:
        - name: "xxx"
          groups:
            - admin
```
