### DISCUSSION TITLE
Configure HTTPS with AKHQ using micronaut properties

### DISCUSSION THREAD

**Discussion by jheinitz** [tchiotludo/akhq#1149] [Q&A] [answered]
Hello,

I tried to configure AKHQ to listen on HTTPS directly without using an NGINX as a reverse-proxy in my docker setup. I was some kind of sucessful and managed to get AKHQ to listen on port 443 using HTTPS. I now want to use the `micronaut.server.http-to-https-redirect` property in order to redirect HTTP traffic to HTTPS. I thought that activating `micronaut.server.dual-protocol` should do the trick, but it does not. 

this is what works in order to have AKHQ listening on port 443:
```
micronaut:
  ssl:
    enabled: true
    key-store:
      alias: mykey
      path: file:/etc/ssl/private/akhq.keystore2.p12
      password: <password>
      type: PKCS12
    trust-store:
      path: file:/etc/ssl/private/akhq.truststore.jks
      password: <password>
      type: JKS
    port: 443
```

Is it possible to have AKHQ listening on port 80 AND 443 and automatically redirect traffic on port 80 to 443 or do I still need an NGINX to redirect the traffic?

the reason for having HTTPS on AKHQ directly is to have the real IP address of the clientin the AKHQ logs.

Thanks and best regards

Jens

PS: AKHQ is listening with HTTP on port 28081. Why?

**Comment by jheinitz** [comment, marked as answer]
Hello,

I'm not sure what I missed in my first approach, but here is how it works:

```
micronaut:
  ssl:
    enabled: true
    key-store:
      path: file:/etc/ssl/private/akhq.keystore.p12
      password: <password>
      type: PKCS12
    trust-store:
      path: file:/etc/ssl/private/akhq.truststore.jks
      password: passw0rd
      type: JKS
    port: 443
  server:
    dual-protocol: true
    http-to-https-redirect: true
    port: 80
```

Sorry, for this.

Kind regards

Jens
