### DISCUSSION TITLE
unable to get oauth enabled with azure ad ,

### DISCUSSION THREAD

**Discussion by hari819** [tchiotludo/akhq#1172] [Q&A] [answered]
Hello ,

i am trying to enable oauth on akhq using azure ad in the latest version of akhq, i have followed the link [https://akhq.io/docs/configuration/authentifications/oidc.html](url)  and made changes in the values.yaml files , but i am not even able to get the login page of  azure ad , i can still see the tool is running without any authentication , it just lists all the kafka topics without asking for any login,

```## Or you can also use configmap for the configuration...
configuration:
  akhq:
    server:
      access-log:
        enabled: true
        name: org.akhq.log.access

##... and secret for connection information
existingSecrets: ""
# name of the existingSecret
secrets:
    micronaut:
      security:
        enabled: true
        oauth2:
          enabled: true
          clients:
            oauth:
              client-id: xxxx
              client-secret: xxxx
              scopes:
                - email
                - openid
                - groups
                - profile
              openid:
                issuer: xxxx
    security:
      oidc:
        enabled: true
        providers:
          azuread:
            label: "Login with Azure AD"
            username-field: email
            use-oidc-claim: true
    akhq:
      connections:
        kafka-cluster:
          properties:
            bootstrap.servers: "kafka-service:9092"
      logger:
        levels:
          org.akhq: TRACE
          io.micronaut: TRACE```


please can someone verify if i am missing something?  , i did a search in issues and discussions , could not make out what am i missing , i have enabled trace logs and the pod logs show,  

`__ __ _ _
| \/ (_) ___ _ __ ___ _ __ __ _ _ _| |_
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| | | | | (__| | | (_) | | | | (_| | |_| | |_
|_| |_|_|\___|_| \___/|_| |_|\__,_|\__,_|\__|
Micronaut (v3.2.2)
2022-08-14 03:35:53,079 [34mINFO [0;39m [35mmain [0;39m [36mi.m.c.e.DefaultEnvironment[0;39m Established active environments: [k8s, cloud, secrets]
2022-08-14 03:35:53,939 [31mWARN [0;39m [35mmain [0;39m [36mo.a.c.JwtSecurityWarning [0;39m
2022-08-14 03:35:53,940 [31mWARN [0;39m [35mmain [0;39m [36mo.a.c.JwtSecurityWarning [0;39m ##############################################################
2022-08-14 03:35:53,940 [31mWARN [0;39m [35mmain [0;39m [36mo.a.c.JwtSecurityWarning [0;39m # SECURITY WARNING #
2022-08-14 03:35:53,940 [31mWARN [0;39m [35mmain [0;39m [36mo.a.c.JwtSecurityWarning [0;39m ##############################################################
2022-08-14 03:35:53,940 [31mWARN [0;39m [35mmain [0;39m [36mo.a.c.JwtSecurityWarning [0;39m
2022-08-14 03:35:53,940 [31mWARN [0;39m [35mmain [0;39m [36mo.a.c.JwtSecurityWarning [0;39m You still use the default jwt secret.
2022-08-14 03:35:53,940 [31mWARN [0;39m [35mmain [0;39m [36mo.a.c.JwtSecurityWarning [0;39m This known secret can be used to impersonate anyone.
2022-08-14 03:35:53,940 [31mWARN [0;39m [35mmain [0;39m [36mo.a.c.JwtSecurityWarning [0;39m Please change 'micronaut.security.token.jwt.signatures.secret.generator.secret' configuration, or ask your administrator to do it !
2022-08-14 03:35:53,940 [31mWARN [0;39m [35mmain [0;39m [36mo.a.c.JwtSecurityWarning [0;39m
2022-08-14 03:35:53,940 [31mWARN [0;39m [35mmain [0;39m [36mo.a.c.JwtSecurityWarning [0;39m ##############################################################
2022-08-14 03:35:53,940 [31mWARN [0;39m [35mmain [0;39m [36mo.a.c.JwtSecurityWarning [0;39m
2022-08-14 03:35:55,951 [34mINFO [0;39m [35mmain [0;39m [36mi.m.runtime.Micronaut [0;39m Startup completed in 6007ms. Server Running: http://akhq-6cb7598fdd-qh9p2:8080`

Thanks,

**Comment by hari819** [comment]
``` ## Or you can also use configmap for the configuration...
configuration:
  akhq:
    server:
      access-log:
        enabled: true
        name: org.akhq.log.access

##... and secret for connection information
existingSecrets: ""
# name of the existingSecret
secrets:
    micronaut:
      security:
        enabled: true
        oauth2:
          enabled: true
          clients:
            oauth:
              client-id: xxxx
              client-secret: xxxx
              scopes:
                - email
                - openid
                - groups
                - profile
              openid:
                issuer: xxxx
    security:
      oidc:
        enabled: true
        providers:
          azuread:
            label: "Login with Azure AD"
            username-field: email
            use-oidc-claim: true
    akhq:
      connections:
        kafka-cluster:
          properties:
            bootstrap.servers: "kafka-service:9092"
      logger:
        levels:
          org.akhq: TRACE
          io.micronaut: TRACE ```

**Comment by hari819** [comment]
i did not have any basic-auth enabled , so please could you let me know how do i first disable the UI without any login

**Comment by hari819** [comment]
@tchiotludo  , please could you provide some hints based on the shared configuration if i am missing something ,

**Comment by tchiotludo** [comment, marked as answer]
@hari819 
```yaml

secrets:
  micronaut:
    security:
      enabled: true
      oauth2:
        enabled: true
        clients:
          oauth:
            client-id: xxxx
            client-secret: xxxx
            scopes:
              - email
              - openid
              - groups
              - profile
            openid:
              issuer: xxxx
  security:
    oidc:
      enabled: true
      providers:
        azuread:
          label: "Login with Azure AD"
          username-field: email
          use-oidc-claim: true

  akhq:
    connections:
      kafka-cluster:
        properties:
          bootstrap.servers: "kafka-service:9092"

    security:
      default-group: no-roles # disabled the ui without login 
      oidc:
        enabled: true
        providers:
          azuread: # enable oidc in akhq 
            label: "Login with Azure AD"
            username-field: email
            use-oidc-claim: true
            groups-field: roles
            default-group: topic-reader
```
Mistake : 
- `akhq.security.default-group: no-roles` to disable the ui without login 
- you are putting the akhq configuration for oidc on the `micronaut` section 


See : 
- https://akhq.io/docs/configuration/authentifications/oidc.html
- https://akhq.io/docs/configuration/authentifications/groups.html
