### DISCUSSION TITLE
Black Screen on login page

### DISCUSSION THREAD

**Discussion by nomopo45** [tchiotludo/akhq#1173] [Q&A]
Hello, 

I just installed akhq on AWS EKS.

Everything was working fine without login but now that i enable oauth login i have a black screen when i go on the login page.
![image](https://user-images.githubusercontent.com/67263927/181190414-e2b537c4-57cf-43b7-bdc4-3f549e9dfabe.png)

Below are my values.yaml

```
data "template_file" "values" {
  template = <<EOF
# imagePullSecrets:
#  - name: my-repository-secret
image:
  repository: tchiotludo/akhq
  tag: "" # uses Chart.AppVersion by default

# custom annotations (example: for prometheus)
annotations: {}
  #prometheus.io/scrape: 'true'
  #prometheus.io/port: '8080'
  #prometheus.io/path: '/prometheus'

podAnnotations: {}

# custom labels
labels: {}
  # custom.label: 'true'

podLabels: {}

## You can put directly your configuration here... or add java opts or any other env vars
extraEnv: []
# - name: AKHQ_CONFIGURATION
#   value: |
#       akhq:
#         secrets:
#           docker-kafka-server:
#             properties:
#               bootstrap.servers: "kafka:9092"
# - name: JAVA_OPTS
#   value: "-Djavax.net.ssl.trustStore=/usr/local/openjdk-11/lib/security/cacerts -Djavax.net.ssl.trustStorePassword=password"
# - name: CLASSPATH
#   value: "/any/additional/jars/desired.jar:/go/here.jar"

## Or you can also use configmap for the configuration...
configuration:
  akhq:
    server:
      access-log:
        enabled: false
        name: org.akhq.log.access
    secrets:
      docker-kafka-server:
        properties:
          bootstrap.servers: kafka.kafka.svc.cluster.local
    security:
      default-group: no-roles
      oidc:
        enabled: true
        providers:
          google:
            label: "Login with Google"
            username-field: email
            groups-field: roles
            default-group: reader
            users:
              - username: "myusername@mydomain.com"
                groups:
                  - admin
    micronaut:
      security:
        enabled: true
        oauth2:
          enabled: true
          clients:
            google:
              client-id: "myclient-id"
              client-secret: "myclient-secret"
              openid:
                issuer: "https://accounts.google.com"


##... and secret for connection information
existingSecrets: ""
# name of the existingSecret
secrets:
  akhq:
    connections:
      my-cluster-plain-text:
        properties:
          bootstrap.servers: "kafka.kafka.svc.cluster.local:9092"
#        schema-registry:
#          url: "http://schema-registry:8085"
#          type: "confluent"
#          basic-auth-username: basic-auth-user
#          basic-auth-password: basic-auth-pass
#        connect:
#          - name: "my-connect"
#            url: "http://connect:8083"
#            basic-auth-username: basic-auth-user
#            basic-auth-password: basic-auth-pass

kafkaSecrets: []
#Provide extra base64 encoded kubernetes secrets (keystore/truststore)

# Any extra volumes to define for the pod (like keystore/truststore)
extraVolumes: []

# Any extra volume mounts to define for the akhq container
extraVolumeMounts: []

# Specify ServiceAccount for pod
serviceAccountName: null
serviceAccount:
  create: false
  #annotations:
  #  eks.amazonaws.com/role-arn: arn:aws:iam::123456789000:role/iam-role-name-here

# Add your own init container or uncomment and modify the example.
initContainers: {}
#   create-keystore:
#     image: "openjdk:11-slim"
#     command: ['sh', '-c', 'keytool']
#     volumeMounts:
#      - mountPath: /tmp
#        name: certs

# Configure the Pod Security Context
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext: {}
  # runAsNonRoot: true
  # runAsUser: 1000

# Configure the Container Security Context
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
containerSecurityContext: {}
  # allowPrivilegeEscalation: false
  # privileged: false
  # capabilities:
  #   drop:
  #     - ALL
  # runAsNonRoot: true
  # runAsUser: 1001
  # readOnlyRootFilesystem: true

service:
  enabled: true
  type: LoadBalancer
  port: 443
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${data.aws_acm_certificate.cert.arn}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
    service.beta.kubernetes.io/aws-load-balancer-alpn-policy: "HTTP2Preferred"
    ${var.global_domain}/dns-type: private
    external-dns.alpha.kubernetes.io/access: private
    external-dns.alpha.kubernetes.io/hostname: akhq.${var.domain}
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Environment=${var.environment},Projet=${var.projet},TimestampLastUpdate=${var.timestamp}

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths:
    - /
  hosts:
    - akhq.demo.com
  tls: []
  #  - secretName: akhq-tls
  #    hosts:
  #      - akhq.demo.com

readinessProbe:
  prefix: "" # set same as `micronaut.server.context-path`

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector:
  ${var.nodeSelector}

tolerations: []

affinity: {}

EOF  
}
```

**Comment by nomopo45** [comment]
When i curl, i have this response : 

```
curl -i -X POST -H "Content-Type: application/json" \
       -d '{ "configuredLevel": "TRACE" }' \
       https://akhq.mydomain.com/ui/login
HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 2480
Connection: keep-alive

<!doctype html><html lang="en"><head><meta charset="utf-8"/><base href="/ui/"><link rel="icon" href="/ui/favicon.ico"/><link rel="manifest" href="/ui/manifest.json"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#33b5e5"/><script>const AKHQ_PREFIX_UI="/ui",AKHQ_PREFIX_PATH=function(){const n="/ui".split("/");return n.pop(),n.join("/")}()</script><meta name="description" content="Kafka GUI for Apache Kafka to manage topics, topics data, consumers group, schema registry, connect and more..."/><title>AKHQ</title><link href="/ui/static/css/2.1e4ddb81.chunk.css" rel="stylesheet"><link href="/ui/static/css/main.ae4160af.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(e){function r(r){for(var n,f,l=r[0],a=r[1],i=r[2],c=0,s=[];c<l.length;c++)f=l[c],Object.prototype.hasOwnProperty.call(o,f)&&o[f]&&s.push(o[f][0]),o[f]=0;for(n in a)Object.prototype.hasOwnProperty.call(a,n)&&(e[n]=a[n]);for(p&&p(r);s.length;)s.shift()();return u.push.apply(u,i||[]),t()}function t(){for(var e,r=0;r<u.length;r++){for(var t=u[r],n=!0,l=1;l<t.length;l++){var a=t[l];0!==o[a]&&(n=!1)}n&&(u.splice(r--,1),e=f(f.s=t[0]))}return e}var n={},o={1:0},u=[];function f(r){if(n[r])return n[r].exports;var t=n[r]={i:r,l:!1,exports:{}};return e[r].call(t.exports,t,t.exports,f),t.l=!0,t.exports}f.m=e,f.c=n,f.d=function(e,r,t){f.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},f.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},f.t=function(e,r){if(1&r&&(e=f(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(f.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof e)for(var n in e)f.d(t,n,function(r){return e[r]}.bind(null,n));return t},f.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return f.d(r,"a",r),r},f.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},f.p="/ui/";var l=this["webpackJsonpakhq-front-end"]=this["webpackJsonpakhq-front-end"]||[],a=l.push.bind(l);l.push=r,l=l.slice();for(var i=0;i<l.length;i++)r(l[i]);var p=a;t()}([])</script><script src="/ui/static/js/2.99281356.chunk.js"></script><script src="/ui/static/js/main.ac2796e7.chunk.js"></script></body></html>%
```

This : You need to enable JavaScript to run this app, i checked in my chrome settings javascript is enable do you know why this happen ?

**Comment by nomopo45** [comment]
And this is the error in the console : 

![image](https://user-images.githubusercontent.com/67263927/182098204-036ed60b-4b6a-4266-ad60-cfca4a146faf.png)

**Comment by tchiotludo** [comment]
For the curl that will output more logs, the port is not the 8080 but the the 28081, see here : https://akhq.io/docs/debug.html#monitoring-endpoint

**Comment by nomopo45** [comment]
Hello It was a problem in my values.tf files now it's working you can find my below values to see the difference : 

```
## Or you can also use configmap for the configuration...
configuration:
  akhq:
    server:
      access-log:
        enabled: false
        name: org.akhq.log.access
    security:
      oidc:
        enabled: true
        providers:
          google:
            label: "Login with Google"
            username-field: email
            default-group: no-roles
            users:
              - username: me@mydomain.com
                groups:
                  - admin

##... and secret for connection information
existingSecrets: ""
# name of the existingSecret
secrets:
  micronaut:
    security:
      enabled: true
      oauth2:
        enabled: true
        clients:
          google:
            client-id: "my-client-id"
            client-secret: "my-client-secret"
            openid:
              issuer: "https://accounts.google.com"
     
  akhq:
    connections:
      my-cluster-plain-text:
        properties:
          bootstrap.servers: "kafka.kafka.svc.cluster.local:9092"
```

**Reply by nomopo45** [reply]
But now i have one last problem i don't know if you can help me,

When i click on Login with Google, the request URL will be http://akhq.mydomain.com/oauth/callback/google....... instead of https do you know why ?

![image](https://user-images.githubusercontent.com/67263927/185893417-ca554723-b6e5-4d33-9a3d-ea5aae2c05b7.png)

**Reply by tchiotludo** [reply]
You probably need this configuration (to adapt depending on your reverse proxy): 
```yaml 
micronaut:
  server:
    host-resolution:
      host-header: Host
      protocol-header: X-Forwarded-Proto
```
