### DISCUSSION TITLE
kubernetes akhq - Couldn't find any clusters

### DISCUSSION THREAD

**Discussion by marcelosauter** [tchiotludo/akhq#1202] [Q&A] [answered]
Good afternoon I'm configuring akhq using helm on a k8s cluster helm upgrade --install akhq akhq/akkh --values=values.yml 

I am getting the issue .
`{"message":"Couldn't find any clusters on your configuration file, please ensure that the configuration file is loaded correctly",`

How need be the values?
I am using like some this.

I have kafka in the same namespace.
```yaml
secrets: |
  kafkahq:
    connections:
      cluster-name:
        properties:
          bootstrap.servers: "kafka:9092"
        connect:
          url: ""
```

**Comment by tchiotludo** [comment, marked as answer]
Long time I didn't see that 🤣 
You are using the `kafkahq` configuration 3 years late, the project is rename to AKHQ so the configuration must be `akhq:`

**Reply by marcelosauter** [reply]
hum.. let me try...

**Reply by marcelosauter** [reply]
But i seems my pod is not working..
 Warning  Unhealthy  23s               kubelet, 10.0.10.118  Liveness probe failed: dial tcp 10.244.2.89:28081: connect: connection refused
  Warning  Unhealthy  0s (x3 over 20s)  kubelet, 10.0.10.118  Readiness probe failed: Get "http://10.244.2.89:28081/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

```yaml
secrets: |
  akhq:
    connections:
      my-cluster-plain-text:
        properties:
          bootstrap.servers:xxxx
```
