### DISCUSSION TITLE
[helm-chart] Clarify that `configuration` and `extraEnv` values cannot be used simultaneously

### DISCUSSION THREAD

**Discussion by SergiyKolesnikov** [tchiotludo/akhq#1203] [Ideas]
The documentation (and a comment in the values.yaml) should mention that the `configuration` and `extraEnv` (with `AKHQ_CONFIGURATION`) values cannot be set simultaneously, because the AKHQ container will fail to start.

The default `helm/akhq/values.yaml` sets `configuration` value. If now we also set `AKHQ_CONFIGURATION` in the `extraEnv` value, the AKHQ container will fail to start with the error:
```
/usr/local/bin/docker-entrypoint.sh: 6: cannot create /app/application.yml: Read-only file system
```
`docker-entrypoint.sh` errors out because it tries to write the contents of the `AKHQ_CONFIGURATION` environment variable to the read-only `/app/application.yml` file. The file is read-only because a ConfigMap (with settings from the `configuration` value) has been mounted into it already.

For `extraEnv` with `AKHQ_CONFIGURATION` to work, the `configuration` value must be set to `false`, so that the ConfigMap is not mounted and `/app/application.yml` can be written. For example:
```
extraEnv:
  - name: AKHQ_CONFIGURATION
    value: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
          server:
            access-log:
              enabled: false
              name: org.akhq.log.access

configuration: false
```
