### DISCUSSION TITLE
Using Kafka with LDAP and Open Policy Agent

### DISCUSSION THREAD

**Discussion by grosswilerp** [tchiotludo/akhq#1205] [General]
Hi @tchiotludo.

I was following this tutorial:
https://github.com/instaclustr/kafka-ldap-integration/blob/master/docs/index.md

And set up everything accordingly.

At last, I was replacing the AclAuthorizer class with the Open Policy Agent since I would like to do authorization with it instead. 
`authorizer.class.name=org.openpolicyagent.kafka.OpaAuthorizer`
This works fine for producers and consumers with their specific JAAS configuration.

Now I wanted to use AKHQ as well, however I noticed that after authenticating with LDAP, it then connects to Kafka with the hardcoded user in the configuration (in this case `srvkafkabroker`):
```
micronaut:
  security:
    enabled: true
    ldap:
      default:
        enabled: true
        context:
          server: "ldap://localhost:10389"
          attributes:
            - "uid"
          managerDn: "uid=admin,ou=system"
          managerPassword: "secret"
        search:
          base: "ou=users,dc=security,dc=example,dc=com"
          attributes:
            - "uid"
        groups:
          enabled: true
          base: "ou=groups,dc=security,dc=example,dc=com"
          attributes:
            - "cn"
          subtree: true
          filter: "member={0}"

akhq:
  connections:
    local:
      properties:
        bootstrap.servers: "localhost:9092"
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="srvkafkabroker" password="broker";
```

That means that Open Policy Agent can not really do any authorization on a per user basis since it is always looking up for `srvkafkabroker` only.

I was wondering if there is a different way to solve this issue, or if I am doing something wrong. Or is there a way that after authenticating in AKHQ via LDAP, that username and password is then also being used to connect to Kafka?

Maybe by replacing some variables in the config dynamically with the logged in user in AKHQ:
`        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="{0}" password="{1}";`

Any help or suggestions are welcome.

Here is the link to Open Policy Agent for Kafka Authorization:
https://www.openpolicyagent.org/docs/latest/kafka-authorization/
