### DISCUSSION TITLE
Basic Auth won't work

### DISCUSSION THREAD

**Discussion by alexsilva1337** [tchiotludo/akhq#1208] [Q&A] [answered]
Hello, everyone!
I'm having a hard time trying to set up basic auth on AKHQ
For context, I'm using the quick preview [docker-compose.yml](https://raw.githubusercontent.com/tchiotludo/akhq/master/docker-compose.yml) (the only tweak I made on that file is that I pointed to where my application.yml is in my host to /app/application.yml in the container). My application.yml is currently this:

```
akhq:
  connections:
    docker-kafka-server:
      properties:
        bootstrap.servers: "kafka:9092"
      schema-registry:
        url: "http://schema-registry:8085"
      connect:
        - name: "connect"
          url: "http://connect:8083"
micronaut:
  security:
    enabled: true
akhq.security:
  basic-auth:
    - username: admin
      password: df829b958863dc6262028d77b6bb83dd48bc12ffc37d0022d1449bcd0c4d505f
      groups:
      - admin
    - username: reader
      password: d8b5b79f1d606d6e56b6ab5ab70d86f6bb0b75e00728dfe5c5a04f20675ec2cb
      groups:
      - reader
```
   
But whenever my AKHQ container starts it overwrites my application.yml thus deleting the basic auth config.

What I'm trying to do is simply run AKHQ with Basic Auth using Docker, that's all. If anyone could help me do just that, I'd be immensely grateful.

Thanks for y'all attention!
