### DISCUSSION TITLE
enable okta authentication for AKHQ

### DISCUSSION THREAD

**Discussion by Tejeshwarraju** [tchiotludo/akhq#1221] [Q&A]
Hi Team,

we are trying to enable okta authentication for AKHQ, we enabled below configuration as mention in the documentation https://akhq.io/docs/configuration/authentifications/oidc.html. 

we get a login link on the app but when we try to login to the application we get a 400 response.
```yaml
micronaut:
      security:
        enabled: true
        oauth2:
          enabled: true
          clients:
            okta:
              client-id: "XXX"
              client-secret: "XXXX"
              scopes:
                - email
                - openid
                - groups
                - profile
              openid:
                issuer: "https://XXX.okta.com"
                configuration-path: "/.well-known/openid-configuration"
    akhq:
      security:
        default-group: no-role
        oidc:
          enabled: true
          providers:
            okta:
              label: "Login with Okta"
              groups-field: roles
              groups:
                - name: mathematicians
                  groups:
                    - topic-reader
                - name: scientists
                  groups:
                    - topic-reader
                    - topic-writer
```
ERROR: Bad Request
Your request resulted in an error. The 'redirect_uri' parameter must be a Login redirect URI in the client app settings: https://XXX-admin.okta.com/admin/app/oidc_client/instance/XXXX#tab-general

are we missing something here ?
what should be the authorization endpoint for okta ?
