### DISCUSSION TITLE
How to set HTTP Response Headers in configuration?

### DISCUSSION THREAD

**Discussion by AdiWehrli** [tchiotludo/akhq#1232] [Q&A] [answered]
Hello everybody,

Is there a way to define _HTTP Response Headers_ via configuration in e.g. `application.yml`? I did not find any hints or documentation about this.

Maybe it could be defined somehow like this?
```yaml
micronaut:
  http:
    headers:
      - "Referrer-Policy=no-referrer"
      - "Content-Type=application/json"
```

Thanks very much in advance for any support.

Best regards,
Adi
