### DISCUSSION TITLE
Mounting of truststore / keystore

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [tchiotludo/akhq#1300] [Q&A] [answered]
According to the official [example](https://github.com/tchiotludo/akhq/blob/dev/application.example.yml#L120), the `ssl.truststore.location` is (or can be) found at the path `/app/truststore.jks`

How is this mount achieved in the corresponding pod since from what I can see in the deployment [template](https://github.com/tchiotludo/akhq/blob/dev/helm/akhq/templates/deployment.yaml
) there is no such volume created?

**Comment by tchiotludo** [comment]
You should mount it yourself using volume & volume mount, see here: 
https://github.com/tchiotludo/akhq/blob/5c4b3e6c868b099d7310e12eae277426206ec901/helm/akhq/values.yaml#L66-L70

**Comment by pantelis-karamolegkos** [comment]
Thanks for this. I assume these two values will take care both the volume and the volumeMount.

Will the volume be of type secret? (citing the official [example](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod))

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
      optional: false # default setting; "mysecret" must exist
```
