### DISCUSSION TITLE
Split sensitive and non-sensitive info when deploying on kubernetes using helm

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [tchiotludo/akhq#1304] [Q&A] [answered]
I see an example [here](https://github.com/tchiotludo/akhq/blob/dev/docs/docs/configuration/helm.md) about how to set a `values.yaml` file when deploying with `helm`.

The problem is that `values.yaml` include both sensitive

e.g.

```yaml
  akhq:
    security:
      enabled: true
      default-group: no-roles        
      basic-auth:
        - username: changeme
          password: changeme
          groups:
            - admin
        - username: changeme
          password: changeme
          groups:
            - reader
```

and non-sensitive info.

Is there an example somewhere about how to split this information when deploying using `helm`?
