### DISCUSSION TITLE
Log level configuration not taken into account

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [tchiotludo/akhq#1314] [Q&A] [answered]
I am trying to debug a `no healthy upstream` error for  an `akhq` instance deployed on `kubernetes` using `helm`.

The service is behind `istio` FWIW.

I am `curl`-ing the service from another pod inside the cluster:

```
bash-5.1$ curl akhq
no healthy upstream
```

pod logs

```
2022-12-14 19:38:27,545 INFO  main       i.m.c.e.DefaultEnvironment Established active environments: [k8s, cloud, gcp]
2022-12-14 19:38:28,706 INFO  main       i.m.runtime.Micronaut      Startup completed in 1928ms. Server Running: http://akhq-oeoeoe5-qtvld:8080
```

from inside the pod:

```
akhq@akhq-6cc7c5cf85-qtvld:/app$ cat application.yml
akhq:
  server:
    access-log:
      enabled: true
      levels:
        io.micronaut: TRACE
        org.akhq: TRACE
      name: org.akhq.log.access
```

```
akhq@akhq-6cc7c5cf85-qtvld:/app$ cat application-secrets.yml
akhq:
  connections:
    staging-ssl:
      properties:
        bootstrap.servers: "kafka-provider.com:11111"
        security.protocol: SSL
        ssl.truststore.location: /app/truststore.jks
        ssl.truststore.password: XXXXXXXXXXX
        ssl.keystore.location: /app/keystore.jks
        ssl.keystore.password: XXXXXXXXXXX
        ssl.key.password: XXXXXXXXXXX
```

Aren't these 2 configurations supposed to be merged?

**Comment by tchiotludo** [comment, marked as answer]
You are mixing 2 loggers configuration, you want to enabled [micronaut global configuration](https://docs.micronaut.io/snapshot/guide/index.html#loggingConfiguration) that is at root of the configuration : 
```yaml
logger:
  levels:
    io.micronaut: TRACE
    org.akhq: TRACE
akhq:
  server:
    access-log:
      enabled: true
      name: org.akhq.log.access
```

The both configuration is merged at startup
