### DISCUSSION TITLE
Using 2 or more LDAP sources for auth.

### DISCUSSION THREAD

**Discussion by Daishirus** [tchiotludo/akhq#1350] [Q&A] [answered]
Hello, is there are any way to use more than 1 LDAP server as source (for example two domains in Active Directory) for authentication?

**Comment by tchiotludo** [comment, marked as answer]
You can see [here](https://akhq.io/docs/configuration/authentifications/ldap.html), `default` is a server but you can have multiple : 
See [here](https://micronaut-projects.github.io/micronaut-security/latest/guide/#configuration) :
> The LDAP authentication in Micronaut supports configuration of one or more LDAP servers to authenticate with. Each server has it’s own settings and can be enabled or disabled.

Like this:
```yaml 
micronaut:
  security:
    enabled: true
    ldap:
      first:
        enabled: true
        context:
          server: 'ldap://ldap.forumsys.com:389'
          managerDn: 'cn=read-only-admin,dc=example,dc=com'
          managerPassword: 'password'
        search:
          base: "dc=example,dc=com"
        groups:
          enabled: true
          base: "dc=example,dc=com"
      second:
        enabled: true
        context:
          server: 'ldap://ldap.blabla.com'
          managerDn: 'cn=read-only-admin,dc=example,dc=com'
          managerPassword: 'password'
        search:
          base: "dc=example,dc=com"
        groups:
          enabled: true
          base: "dc=example,dc=com"
```
