### DISCUSSION TITLE
no oauth link in the login ui

### DISCUSSION THREAD

**Discussion by lekpamartin** [tchiotludo/akhq#1380] [Q&A]
Hi,
I have deployed docker dev tag to test oauth2. I configured like descibed in application.example.yml. 

Docker version is 20.10.22

The container start without error in log but in the login ui I don't have link to oauth2. 

Any idea?

Thx

**Comment by tchiotludo** [comment]
Please add more relevant information for people to help you like configuration snippet.

**Comment by lekpamartin** [comment]
An extract of my config : 
```yaml
micronaut:
  security:
    enabled: true
    oauth2:
      enabled: true
      clients:
        myoauth:
          client-id: "XX"
          client-secret: "YYY"
          scopes:
            - matricule
          openid:
            issuer: "ZZZZ"
          authorization:
            url: ZZZ
          token:
            url: ZZZZ
            auth-method: client-secret-post


akhq:
  security:
    default-group: no-roles
    myoauth:
      enabled: true
      providers:
        myoauth:
          label: "Login with myoauth"
          username-field: matricule
```
