### DISCUSSION TITLE
AKHQ cluster works but doesn't show GUI

### DISCUSSION THREAD

**Discussion by Railac** [tchiotludo/akhq#1414] [Q&A]
config file 
```yaml
akhq:
  connections:
    my-kafka-test:
      properties:
        bootstrap.servers: "ip1:9092,ip2:9092,ip3:9092"
      schema-registry:
        url: "http://schema-registry:8085"
      connect:
        - name: "connect"
          url: "http://connect:8083"
      ksqldb:
        - name: "ksqldb"
          url: "http://ksqldb:8088"
```

![image](https://user-images.githubusercontent.com/42927186/222328586-0e96905b-5458-4a4f-bad7-827cf9cbdd3e.png)

site error message -> Connection refused at ip.
