### DISCUSSION TITLE
How can we access `/prometheus` endpoint without auth?

### DISCUSSION THREAD

**Discussion by LittleWat** [tchiotludo/akhq#1436] [Q&A] [answered]
Hello! I am using AKHQ OIDC feature with Keycloak and want to make my Prometheus scrape the Prometheus endpoint.
https://akhq.io/docs/debug.html#monitoring-endpoint

However, I cannot solve the ` Request GET, /bad-request, no token found.` error.
I want to make my Prometheus scrape the Prometheus endpoint without auth. 
How can I solve this?

Here is my config.

```yaml
akhq@foo-xxx:/$ cat config.yaml
micronaut:
  application:
    name: metrics
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
  endpoints:
    prometheus:
      sensitive: false
  server:
    host-resolution:
      host-header: Host
      protocol-header: X-Forwarded-Proto
  security:
    enabled: true
    endpoints:
      login:
        path: "/login"
      logout:
        path: "/logout"
        get-allowed: true
    oauth2:
      enabled: true
      clients:
        oidc:
          grant-type: authorization_code
          client-id: <foo>
          client-secret: <foo>
          openid:
            issuer:<foo>
akhq:
  server:
    access-log:
      enabled: true

  connections:
    kafka-cluster:
      properties:
        bootstrap.servers: <foo>
  security:
    default-group: no-roles
    groovy:
      enabled: true
      file: |
        package org.akhq.utils;
        class GroovyCustomClaimProvider implements ClaimProvider {
          @Override
          ClaimResponse generateClaim(ClaimRequest request) {
            ClaimResponse res = ClaimResponse.builder().build()
           <foo...>
            return res
          }
        }

    oidc:
      enabled: true
      providers:
        oidc:
          username-field: preferred_username
          groups-field: groups
```

I enabled the logging:

```shell
curl -i -X POST -H "Content-Type: application/json" \
       -d '{ "configuredLevel": "TRACE" }' \
       http://localhost:28081/loggers/io.micronaut.security


curl -i -X POST -H "Content-Type: application/json" \
       -d '{ "configuredLevel": "TRACE" }' \
       http://localhost:28081/loggers/org.akhq.configs
```

And the log is as follows:

```log
kafka-monitor 2023-03-27 04:36:14,123 DEBUG pGroup-1-4 .t.r.HttpHeaderTokenReader Looking for bearer token in Authorization header
kafka-monitor 2023-03-27 04:36:14,123 DEBUG pGroup-1-4 s.t.r.DefaultTokenResolver Request CUSTOM, *, no token found.
kafka-monitor 2023-03-27 04:36:14,123 DEBUG pGroup-1-4 .m.s.r.InterceptUrlMapRule One or more of the IP patterns matched the host address [127.0.0.6]. Conti
nuing request processing.
kafka-monitor 2023-03-27 04:36:14,123 DEBUG pGroup-1-4 .m.s.r.InterceptUrlMapRule No url map pattern exact match found for path [*] and method [CUSTOM]. Sea
rching in patterns with no defined method.
kafka-monitor 2023-03-27 04:36:14,123 DEBUG pGroup-1-4 .m.s.r.InterceptUrlMapRule No url map pattern match found for path [*]. Returning unknown.
kafka-monitor 2023-03-27 04:36:14,123 DEBUG pGroup-1-4 i.m.s.f.SecurityFilter     Authorized request CUSTOM *. No rule provider authorized or rejected the r
equest.
kafka-monitor 2023-03-27 04:36:14,124 DEBUG pGroup-1-4 .t.r.HttpHeaderTokenReader Looking for bearer token in Authorization header
kafka-monitor 2023-03-27 04:36:14,124 DEBUG pGroup-1-4 s.t.r.DefaultTokenResolver Request GET, /bad-request, no token found.
kafka-monitor 2023-03-27 04:36:14,124 DEBUG pGroup-1-4 .m.s.r.InterceptUrlMapRule One or more of the IP patterns matched the host address [127.0.0.6]. Conti
nuing request processing.
kafka-monitor 2023-03-27 04:36:14,124 DEBUG pGroup-1-4 .m.s.r.InterceptUrlMapRule No url map pattern exact match found for path [/bad-request] and method [G
ET]. Searching in patterns with no defined method.
kafka-monitor 2023-03-27 04:36:14,124 DEBUG pGroup-1-4 .m.s.r.InterceptUrlMapRule No url map pattern match found for path [/bad-request]. Returning unknown.
kafka-monitor 2023-03-27 04:36:14,124 DEBUG pGroup-1-4 i.m.s.f.SecurityFilter     Authorized request GET /bad-request. No rule provider authorized or reject
ed the request.
```

Any ideas are appreciated 🙇 Thanks in advance!

**Comment by tchiotludo** [comment, marked as answer]
The Prometheus url is `http://localhost:28081/prometheus` and enabled by default

**Reply by LittleWat** [reply]
Thank you for your quick reply!
Yes, I can access `http://localhost:28081/prometheus` inside the AKHQ and get the metrics.

Let me elaborate on my situation.
The akhq is deployed as k8s deployment with istio-injection.

I can access ` curl -v <svc>.<ns>:28081/prometheus`  from the other pod of a different namespace.

Here is the `Service` and `ServiceMonitor` settings.
```yaml
$ kubectl get servicemonitors.monitoring.coreos.com <foo> -oyaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: <foo>
  namespace: <foo>
spec:
  endpoints:
  - interval: 5s
    path: /prometheus
    port: prometheus-http
    scheme: https
    tlsConfig:
      caFile: /etc/prom-certs/root-cert.pem
      certFile: /etc/prom-certs/cert-chain.pem
      insecureSkipVerify: true
      keyFile: /etc/prom-certs/key.pem
  selector:
    matchLabels:
      app:  <foo>

$ kubectl get service -n  <foo>  <foo> -oyaml
apiVersion: v1
kind: Service
metadata:
  name:  <foo>
  namespace:  <foo>
spec:
  clusterIP:  <foo>
  clusterIPs:
  -  <foo>
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: prometheus-http
    port: 28081
    protocol: TCP
    targetPort: 28081
  selector:
    app:  <foo>
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

But the prometheus keep getting the following error....

```log
ts=2023-03-27T06:21:34.124Z caller=scrape.go:1328 level=debug component="scrape manager" scrape_pool=serviceMonitor/<foo>/<foo>/0 target=https://10.13.95.36:28081/prometheus msg="Scrape failed" err="Get \"https://10.13.95.36:28081/prometheus\": unexpected EOF"
```

What do you think is the reason for this...? Sorry for bothering you 🙇

**Reply by tchiotludo** [reply]
I don't know anything about istio, but the scheme of the endpoint is http not https, maybe it's the reason ?

**Reply by LittleWat** [reply]
Thank you for your reply!

My coworker finds the cause. The problem was in `Service`

Adding ` appProtocol: http` solved this issue.
https://github.com/prometheus/prometheus/issues/10213#issuecomment-1064280828

```yaml
apiVersion: v1
kind: Service
metadata:
  namespace: <foo>
  name: <foo>
spec:
  ports:
  - name: web-http
    port: 8080
    targetPort: 8080
  - name: prometheus-http
    port: 28081
    targetPort: 28081
    appProtocol: http # <<===
  selector:
    app: kafka-monitor 
```

Sorry for the disturbance and thank you for your help 🙇‍♂️
