### DISCUSSION TITLE
AKHQ failed to connect issue when running in a Linux RHEL VM

### DISCUSSION THREAD

**Discussion by mtukus** [tchiotludo/akhq#1450] [Q&A] [answered]
Hi all,

I run the following command on a Azure RHEL Linux VM: podman run -d --name akhq_mert -p 8080:8080 -v /tmp/application.yml:/app/application.yml docker.io/tchiotludo/akhq:0.23.0

The application.yml  I provide is:
```yaml
micronaut:
  server:
    cors:
      enabled: true
    host: 0.0.0.0
    port: 8080

akhq:
  connections:
    dev:
      properties:
        bootstrap.servers: "20.86.65.24:9092, 20.86.65.62:9092, 20.86.65.203:9092"
```

Besides host:0.0.0.0 I also tried running 'host' with the values host:localhost  and host:public_ip_address_myvm. Port 8080 is opened for outbound and inbound connections in Azure. 

However, for each case I can' t open the GUI in my browser through http://publicipvm:8080 and when I inspect my podman container I get:

"Failed to connect to localhost port 8080 after 0 ms: Connection refused"

Has anyone ever faced such a problem?
