### DISCUSSION TITLE
Updated way to kill the the login button?

### DISCUSSION THREAD

**Discussion by jessetandor** [tchiotludo/akhq#1480] [Q&A]
I read through : https://github.com/tchiotludo/akhq/issues/361

And added the following to my config but the login button still shows on 0.23.0 :

```
    micronaut:
      security:
        enabled: true
        endpoints:
          login:
            enabled: false
          logout:
            enabled: false
      server:
            port: xxxx
```

Did i miss something?
