### DISCUSSION TITLE
Modification time of key store could not be obtained

### DISCUSSION THREAD

**Discussion by guilhermedra3data** [tchiotludo/akhq#1482] [Q&A]
Hello,

I'm strugging with a simple problem that I don't understand what is going on. I have my kafka running in a k8s cluster, deployed with strimzi operator. I current use TLS auth to comunicate to the broker, and it works fine if I do some producer or consumer script with kafka-python lib. But I keep getting this error in my log pod, when I try to access akhq service:
**Modification time of key store could not be obtained** 

This is how I'm using the connection config:

```
secrets:
  akhq:
    connections:
      data-streaming:
        properties:
          bootstrap.servers: "my-bootstrap.kafka.svc.cluster.local:9094"
          security.protocol: SSL          
          ssl.truststore.location: /cluster-certificate/ca.crt
          ssl.truststore.password: "<password ca.crt>"
          ssl.keystore.type: "PKCS12"
          ssl.keystore.location: /user-certificate/user.p12
          ssl.keystore.password: "<password user.p12>"
          ssl.key.password: "<password user.p12>"
          client.id: "user-producer"
          group.id: "*"
        connect:
          - name: "kafka-connect-landing"
            url: "kafka-connect-landing-connect-api:8083"
```

The user.p12 and ca.crt files I'm creating a volume into the container, so that is the correct folder:
![image](https://github.com/tchiotludo/akhq/assets/112498128/4b4a4a81-e959-4e0b-af40-81dc63e5ffb2)

Anyone can help to fix that? My akhq doesn't show anything, just get an Internal Error.
Thanks

**Comment by tchiotludo** [comment]
Humm quickly, the certificate must absolute, so I think it should be :  
```
ssl.truststore.location: /app/cluster-certificate/ca.crt
```
(and the same for the certificate)

**Reply by guilhermedra3data** [reply]
It didn't work :disappointed: 

Now I got the error:

![image](https://github.com/tchiotludo/akhq/assets/112498128/f4b256af-1149-4c8a-844f-efbc168b7849)

![image](https://github.com/tchiotludo/akhq/assets/112498128/a17051c9-ef51-4b8f-a55a-3870518a6246)

I also already tried to change the **ssl.truststore.type** to "PEM" type but I got a diferent error about password can't be informed when the type is PEM.
So, I'm running in circles now.

My current connection properties are:
```
secrets:
  akhq:
    connections:
      data-streaming:
        properties:
          bootstrap.servers: "my-bootstrap.kafka.svc.cluster.local:9094"
          security.protocol: SSL          
          ssl.truststore.location: /app/cluster-certificate/ca.crt
          ssl.truststore.password: "<password ca.crt>"
          ssl.keystore.type: "PKCS12"
          ssl.keystore.location: /app/user-certificate/user.p12
          ssl.keystore.password: "<password user.p12>"
          ssl.key.password: "<password user.p12>"
          client.id: "user-producer"
          group.id: "*"
        connect:
          - name: "kafka-connect-landing"
            url: "kafka-connect-landing-connect-api:8083"
```

I've already tried: file permissions, folder permissions, broker port to 9092, 9093 and other connections config formats, but no success at all.

**Reply by tchiotludo** [reply]
Can you provide the full stacktrace please ?

**Reply by guilhermedra3data** [reply]
@tchiotludo I got it, finally! Here it is, the final connection properties that works:

```
secrets:
  akhq:
    connections:
      data-streaming:
        properties:
          bootstrap.servers: "my-bootstrap.kafka.svc.cluster.local:9094"
          security.protocol: SSL   
          ssl.truststore.type: "PEM"       
          ssl.truststore.location: /app/cluster-certificate/ca.crt
          ssl.keystore.type: "PKCS12"
          ssl.keystore.location: /app/user-certificate/user.p12
          ssl.keystore.password: "<password user.p12>"
          ssl.key.password: "<password user.p12>"
          client.id: "kafka-user-connect-landing"
          
        connect:
          - name: "kafka-connect-landing"
            url: "kafka-connect-landing-connect-api:8083"

# Any extra volumes to define for the pod (like keystore/truststore)
extraVolumes: 
  - name: kafka-user-secret
    secret:
      secretName: kafka-user-connect-landing
  - name: kafka-cluster-secret
    secret:
      secretName: data-streaming-cluster-ca-cert

# Any extra volume mounts to define for the akhq container
extraVolumeMounts:
  - name: kafka-user-secret
    mountPath: /app/user-certificate
  - name: kafka-cluster-secret
    mountPath: /app/cluster-certificate

```

Changes that I did:

- I changed the client.id to use my connect sink KafkaUser (what I think doen't really matter here)
- I defined **ssl.truststore.type** as **PEM**
- I removed the **ssl.truststore.password** that doesn't seem necessary. Then KafkaAdminClient class was pointing this error, that so I took off. 
- I removed the **group.id** that is not necessary according KafkaAdminClient class message

It's working extremely well. Just one thing keeps getting erro: ACLS function. When I try to access, it shows the message: 
**Request Request(processor=12, connectionId=192.168.2.178:9094-192.168.3.9:28709-299438, session=Session(User:CN=kafka-user-connect-landing,/192.168.3.9), listenerName=ListenerName(EXTERNAL-9094), securityProtocol=SSL, buffer=null, envelope=None) is not authorized.**

The akhq log doesn't show to much, just a warning that didn't help to much:
![image](https://github.com/tchiotludo/akhq/assets/112498128/6a900912-2a0a-4f22-8a63-ef54e51113a4)

I dont even know if it is about de ACLS error.

For now, for what I need, it works fine! Thanks. If you know anything about the ACLS problem, let me know. :smiley:
