### DISCUSSION TITLE
AKHQ v0.24.0 has initial support for KSQLDB or not?

### DISCUSSION THREAD

**Discussion by JoaoJarr** [tchiotludo/akhq#1486] [Q&A]
Hi, 

I'm trying to test v0.24.0 with KSQLDB, since the release notes indicate that it already has initial support:

**ksql: initial ksql support (#1324) (David Weber)**

But no matter what i put in the config, the KSQLDB option never appears in the menu, like is shown in case (#1324) images :

[https://user-images.githubusercontent.com/1021324/210272484-05999614-275d-4209-97e0-f40b6a02033a.png?_sm_au_=ifHQjtRSHqZKsVbN07sLNK7tvGQv3](https://user-images.githubusercontent.com/1021324/210272484-05999614-275d-4209-97e0-f40b6a02033a.png?_sm_au_=ifHQjtRSHqZKsVbN07sLNK7tvGQv3)

The configuration is:

```
akhq:
  connections:
    kafka-corp-prd:
      properties:
        bootstrap.servers: "127.0.0.1:25999"
        sasl.mechanism: PLAIN
        security.protocol: SASL_PLAINTEXT
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='adminuser' password='xxxxxx';
      schema-registry:
        url: "http://127.0.0.1:25000" # schema registry url (optional)
        type: "confluent" # schema registry type (optional). Supported types are "confluent" (default) or "tibco"
        # Basic Auth user / pass
        basic-auth-username: adminuser
        basic-auth-password: xxxxxxxxx
        #properties: # standard kafka properties (optional)
      ksqldb:
        - name: ksqldb
          url: "http://127.0.0.1:8088"
          #basic-auth-username: adminuser
          #basic-auth-password: xxxxxxxxx
      connect:
        - name: ckpxxx01
          url: "http://127.0.0.1:25001"
          # Basic Auth user / pass (optional)
          basic-auth-username: adminuser
          basic-auth-password: xxxxxxxxx
        - name: ckpxxx02
          url: "http://127.0.0.1:25002"
          # Basic Auth user / pass (optional)
          basic-auth-username: adminuser
          basic-auth-password: xxxxxxxxx
``` 

All the other options work fine (connect, schema registry). Only ksqldb does not appear in the menus.
I'm using the docker image (latest), which I downloaded today. The web page shows version v0.24.0.

Does this version have support for KSQLDB or not?

Thanks
