### DISCUSSION TITLE
Can't use REST API

### DISCUSSION THREAD

**Discussion by chih-chen** [tchiotludo/akhq#1518] [Q&A]
Hi! 

I configured the OIDC authentication using Keycloak IDP and works like a charm!
But when trying to access the REST API, I get an html response saying: `You need to enable JavaScript to run this app.`

I think that the problem is maybe related to the OIDC authentication, since it needs the browser to perform the authorization code flow. But shouldn't it accept a Bearer Token generated by the Keycloak directly? 

Any help would be appreciated! Thanks! 

Here is the full configuration:
```yml
micronaut:
  security:
    enabled: true
    oauth2:
      enabled: true
      clients:
        keycloak:
          client-id: "akhq"
          openid:
            issuer: "http://keycloak/realms/internal"
    redirect:
      login-success: "/ui"
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET}
  server:
    port: 8080
    context-path: "/akhq"
akhq:
  security:
    default-group: no-roles
    oidc:
      enabled: true
      providers:
        keycloak:
          label: "Login with keycloak"
          username-field: preferred_username
          use-oidc-claim: true
          default-group: reader
  connections:
    local:
      properties:
        bootstrap.servers: "kafka:9092"
```
