### DISCUSSION TITLE
Multiple brokers

### DISCUSSION THREAD

**Discussion by KoushikMaharaj** [tchiotludo/akhq#1528] [Q&A] [answered]
Hello, 
    Can we add multiple brokers for same cluster? If yes how?
     I am using following application.yml for testing locally.

```yaml
micronaut:
  server:
    port: 7072

akhq:
  connections:
    local:
      properties:
        bootstrap.servers: localhost:9092
  ui-options:
    topic:
      default-view: ALL
      skip-consumer-groups: false
      skip-last-record: true
      show-all-consumer-groups: true
    topic-data:
      sort: NEWEST
      date-time-format: ISO
```
