### DISCUSSION TITLE
Structure difference between v0.16 to v0.24

### DISCUSSION THREAD

**Discussion by matigoal** [tchiotludo/akhq#1545] [General]
Hello,

I change akhq version 0.16 to the last 0.24 but i think may be the structure change for the mapping of groups and the permissions filters.
Here is an extract from my application.yml version 0.16:

```
 security:
    enabled: true
    default-group: default
    groups:
      default: no-roles
      ORIGIN-GROUP:
        name: ORIGIN-GROUP
        roles:
          - node/read
          - acls/read
        attributes:
          topics-filter-regexp:
             - "^*$"
      GROUP-FIRST:
        name: GROUP-FIRST
        roles:
          - topic/read
          - topic/insert
          - topic/delete
          - topic/config/update
          - node/read
          - topic/data/read
          - topic/data/insert
          - topic/data/delete
          - group/read
          - group/offsets/update
          - registry/read
          - acls/read
        attributes:
          topics-filter-regexp:
             - "^.*group1.*-pcr1.*$"
             - "^.*group1.*-pcdn.*$"
      GROUP-SECOND:
        name: GROUP-SECOND
        roles:
          - topic/read
          - topic/data/read
          - group/read
          - registry/read
          - acls/read
        attributes:
          topics-filter-regexp:
             - "^.*group2.*-pcr1.*$"
             - "^.*group2.*-pcdn.*$"

```
But in the last version 0.24 i see this change [1][2] for declare the default-group:
```

security:
   enabled: true
   default-group: no-roles
   groups:
    no-roles:
     ORIGIN-GROUP:
       name: ORIGIN-GROUP
       roles:
         - node/read
         - acls/read
       attributes:
         topics-filter-regexp:
            - "^*$"
     GROUP-FIRST:
       name: GROUP-FIRST
       roles:
         - topic/read
         - topic/insert
         - topic/delete
         - topic/config/update
         - node/read
         - topic/data/read
         - topic/data/insert
         - topic/data/delete
         - group/read
         - group/offsets/update
         - registry/read
         - acls/read
       attributes:
         topics-filter-regexp:
            - "^.*group1.*-pcr1.*$"
            - "^.*group1.*-pcdn.*$"
     GROUP-SECOND:
       name: GROUP-SECOND
       roles:
         - topic/read
         - topic/data/read
         - group/read
         - registry/read
         - acls/read
       attributes:
         topics-filter-regexp:
            - "^.*group2.*-pcr1.*$"
            - "^.*group2.*-pcdn.*$"
```

What's the good use for define my default-group the example 1 or the example 2 for the last version 0.24?
Because the user is not filter by the regex and it's merge between us(user).

Thank you for your help in advance.

[1] https://akhq.io/docs/configuration/authentifications/external.html

[2] https://github.com/tchiotludo/akhq/blob/0.24.0/application.example.yml
