### DISCUSSION TITLE
Filter a subset of connections (cluster aliases configured in yaml) for groups

### DISCUSSION THREAD

**Discussion by lvillaca** [tchiotludo/akhq#1593] [Q&A] [answered]
Hi, I am doing a POC integrating AKHQ with an IDP provider, and it's working fine so far, apart from 1 requirement we need: we handle authentication of several users from several groups, and we want to expose only a subset of the configured connections (friendly cluster names, which appear on left menu) for all users.

If I understood it, this has been identified [here](https://github.com/tchiotludo/akhq/pull/1472#pullrequestreview-1485502598). Reading [this doc](https://akhq.io/docs/configuration/authentifications/groups.html) I assumed regex patterns could be used for that (via `clusters`), but that setting seems to be ignored. 

Also the clusters regex used in [this example](https://github.com/tchiotludo/akhq/blob/dev/application.example.yml) do not relate to cluster friendly names, so I guess I was not right in my assumption.

Here is an example of my config, could you please verify and advise? I am using release [0.24.0](https://github.com/tchiotludo/akhq/releases/tag/0.24.0).

```yaml
akhq:
  security:
    groups:
      limited-reader-a:
        - role: topic-read
          clusters: ["cla.*"]
        - role: topic-data-read
          clusters: ["cla.*"]
        - role: node-read
          clusters: ["cla.*"]
        - role: consumer-read
          clusters: ["cla.*"]
      limited-reader-b:
        - role: topic-read
          clusters: ["clb.*"]
        - role: topic-data-read
          clusters: ["clb.*"]
        - role: node-read
          clusters: ["clb.*"]
        - role: consumer-read
          clusters: ["clb.*"]

  connections:
    cla-dev:
      properties:
        bootstrap.servers: "kafka:9091"
...
    cla-e2e:
      properties:
        bootstrap.servers: "kafka:9092"
...
    clb-dev:
      properties:
        bootstrap.servers: "kafka:9093"
```

Also tried using the `roles` list and a single `clusters` for the group, but no luck there also:

```yaml
akhq:
  security:
    groups:
      limited-reader-a:
        roles:
          - topic/read
          - node/read
          - topic/data/read
          - group/read
          - registry/read
          - acls/read
          - connect/read
        clusters: ["cla.*"]

```

Thanks in advance
