### DISCUSSION TITLE
New RBAC settings (on dev branch) - UI updates?

### DISCUSSION THREAD

**Discussion by lvillaca** [tchiotludo/akhq#1598] [Q&A]
Firstly, congrats for the tool, seems really great!

I've been testing a feature on `dev` branch, especially leveraging the new RBAC settings. I am checking a setting where the same group can mix read-only permissions for some clusters and admin permissions for others. This is how I've mapped this group:

```yaml
      tested-group:
        - role: node-admin
          clusters: [ "clustera.*" ]
        - role: group-read
          clusters: [ "clustera.*" ]
        - role: topic-admin
          clusters: [ "clustera.*" ]
        - role: connect-admin
          clusters: [ "clustera.*" ]
        - role: registry-admin
          clusters: [ "clustera.*" ]
        - role: node-read
          clusters: [ "clusterb.*" ]
        - role: group-read
          clusters: [ "clusterb.*" ]
        - role: topic-read
          clusters: [ "clusterb.*" ]
        - role: connect-rw
          clusters: [ "clusterb.*" ]
        - role: connect-cluster-read
          clusters: [ "clusterb.*" ]
        - role: registry-read
          clusters: [ "clusterb.*" ]
```

I can see the backend responds fine (for "admin" clusters I can create/delete topics, for the read-only ones it's not allowed). In case the user does not have permissions for an action and tries it, redirect to login screen happens. 

Not sure if it's planned for the next release, but UI items are exposed for all mapped clusters even though the user only has admin permission on a subset of those. This only happens when the group mixes admin and read-only permissions for different cluster subsets.
![image](https://github.com/tchiotludo/akhq/assets/22486128/5e2c5fce-639a-4e85-b841-352f16f825d7)

If the UI was also adjusted, for the read-only clusters, to appear like when the user has only read roles, it would be awesome, as the user wouldn't even have the option to try it in the 1st place, and wouldn't be redirected to the login screen (counter-intuitive).
![image](https://github.com/tchiotludo/akhq/assets/22486128/f85ea5f2-2f7a-4eb4-abca-00fe0b6300bc)

Thanks
