### DISCUSSION TITLE
Custom groups not working with ldap

### DISCUSSION THREAD

**Discussion by yertym** [tchiotludo/akhq#1610] [Q&A]
I'm having trouble getting my own defined groups/roles to work. When I use pre-defined groups like `admin` or `reader` it works  but not using the config below
```
 akhq:
      security:
        default-group: reader
        groups:
          devreadwrite:
            role: topicmanager
        ldap:
          groups:
          - name: group1
            groups:
              - devreadwrite
        roles:
          topicmanager:
          - actions:
            - READ
            - CREATE
            - UPDATE
            - DELETE
            - READ_CONFIG
            - ALTER_CONFIG
            resources:
            - TOPIC
            - TOPIC_DATA
```

The logs show the user1 is in group1
```
Group search returned [[othergroup, anothergroup, group1]] for user [user1]
```
However the user ends up with no roles
```
Generated claim set: {sub=user1, nbf=1698702992, connectsFilterRegexp=[], roles=[], iss=akhq, exp=1698706592, iat=1698702992, consumerGroupsFilterRegexp=[], topicsFilterRegexp=[]}
```
I figure it must be a configuration problem but I can't see why
