### DISCUSSION TITLE
How to configure OIDC callback for dex?

### DISCUSSION THREAD

**Discussion by jslusher** [tchiotludo/akhq#1611] [Q&A]
Hi, I'm trying to get a dex IdP working and I'm having trouble locating configuration for the callback URL. Following instruction in the 0.24.0 docs, here's my oidc condifguration so far:

```yaml
akhq:
  connections:
    strimzi-sdlc:
      properties:
        ...
  security:
    default-group: reader
    ...
micronaut:
  security:
    oauth2:
      enabled: true
      clients:
        dex:
          client-id: "akhq"
          client-secret: "akhq"
          openid:
            issuer: "https://dex.my.domain.com"
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "REDACTED"
oidc:
  enabled: true
  providers:
    dex:
      label: "dex oidc"
      username-field: akhq
      groups-field: roles
      default-group: reader
      groups:
        - name: acl-platform@my_domain.com
          groups:
            - admins
```
I tried `/oauth/callback/oidc` but nothing seems to be listening there. Any guidance would be appreciated.
