### DISCUSSION TITLE
No redirecting on login page.

### DISCUSSION THREAD

**Discussion by vimal5433** [tchiotludo/akhq#1623] [Q&A]
Hi AKHQ,

We are using akhq for our server which using kafka service, I want to place auth for akhq but it's still redirecting on server url without authentication, Please suggest on that. my configurations are given below.

```yaml
micronaut:
  security:
    redirect:
      login-success: "/ui"
      forbidden:
        url: "/ui/login/forbidden"
      unauthorized:
        url: "/ui/login/unauthorized"
      login-failure: "/ui/login/failed"
      logout:  "/ui" 
```
