### DISCUSSION TITLE
Login Button not shown.

### DISCUSSION THREAD

**Discussion by vimal5433** [tchiotludo/akhq#1625] [Q&A]
Hi AKHQ,

We are useing akhq for kafka, now it's openly not any authentication. I want to place an authentication but there are no getting login button. Please help on that.

We are using for akhq
AKHQ docker compose file
AKHQ Version 0.24.0

My docker compose file
```yaml
version: "3.8"

services:
  akhq:
    image: tchiotludo/akhq
    ports:
      - "9021:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "localhost:7092,localhost:7093,localhost:7094"
              schema-registry:
                url: "http://localhost:8081"
      MICRONAUT_SECURITY_CONFIGURATION: |
        micronaut:
            enabled: true
            interceptor-url-map:
              - pattern: /login
                access:
                  - permitAll()
              - pattern: /secured/**
                access:
                  - isAuthenticated()
          security:
            redirect:
              login-success: "/ui"
              forbidden:
                url: "/ui/login/forbidden"
              unauthorized:
                url: "/ui/login/unauthorized"
              login-failure: "/ui/login/failed"
              logout:  "/ui"


            basic-authentication:
              enabled: true
              realms:
                - name: micronaut
                  username: admin
                  password: ChangeMe@123
```
