### DISCUSSION TITLE
Configuration SSO with Okta

### DISCUSSION THREAD

**Discussion by PLeS207** [tchiotludo/akhq#1815] [Q&A]
Hello team I'm trying to configure SSO with Okta
AKHQ deployed via Helm chart v0.25.0
When I try to open the web page nothing happens it does not suggest logging in with Okta OIDC, and it even hasn't login button
Maybe I make a mistake in the configuration
```
configuration:
  micronaut:
    security:
      endpoints:
        logout:
          get-allowed: true                
      oauth2:
        enabled: true
        clients:
          oidc:
            client-id: "xxx"
            client-secret: "xxx"
            openid:
              issuer: '{{ Values.okta_url }}/oauth2/default'                    
  akhq:
    security:
      roles:
        topic-read:
          - resources: [ "TOPIC", "TOPIC_DATA" ]
            actions: [ "READ" ]
          - resources: [ "TOPIC" ]
            actions: [ "READ_CONFIG" ]
        topic-admin:
          - resources: [ "TOPIC", "TOPIC_DATA" ]
            actions: [ "READ", "CREATE", "DELETE" ]
          - resources: [ "TOPIC" ]
            actions: [ "UPDATE", "READ_CONFIG", "ALTER_CONFIG" ]
        group-read:
          - resources: [ "CONSUMER_GROUP" ]
            actions: [ "READ" ]
  
      default-group: topic-reader
      groups:
        admin:
          - role: node-admin
          - role: topic-admin
          - role: group-read
        topic-reader:
          - role: topic-read
        topic-reader-project-prod:
          - role: topic-read
            patterns: ["project.*"]
            clusters: ["prod.*"]        
    oidc:
      enabled: true
      providers:
        oidc:
          label: "Login with OIDC"
          username-field: preferred_username
          groups-field: roles
          default-group: topic-reader         
    server:
      access-log:
        enabled: true
        name: org.akhq.log.access            
    connections:
      msk: 
        properties:
          bootstrap.servers: {{ $.Values.msk_bootstrap_brokers }}
          security.protocol: SASL_SSL
          sasl.mechanism: SCRAM-SHA-512
          sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="{{ $.Values.msk_user_name }}" password="{{ $.Values.msk_user_password }}";
```
