### DISCUSSION TITLE
Since 0.25.1, cannot list topic messages and content

### DISCUSSION THREAD

**Discussion by djeanprost** [tchiotludo/akhq#1880] [Q&A]
Hello,

Unfortunatly, I don't have many informations to give for this topic, but I cannot list topic content in 0.25.1 although it works in 0.25.0.
I have no logs in server log to share. The only stuff I get is a 504 of my application gateway which I don't get when using 0.25.0

I cannot reproduce easily because I need to upgrade then downgrade.
Could this be related to my problem #1843 ?

**Comment by AlexisSouquiere** [comment]
We won't be able to help without more details... 
Please share you application.yml to help identifying a misconfiguration. 
Please check again in the log. If it's due to a timeout issue, there is probably a call that a taking to much time. Logs are showing the call duration

**Reply by djeanprost** [reply]
Hello @AlexisSouquiere 

Thank you answering to a so dry problem report.
I finally managed to get more information. I do confirm that there is something that doesn't work anymore in my case when using 0.25.1 although everything works well in 0.25.0.

Here is my akhq configuration for a start
```
akhq:
  connections:
    dev:
      properties:
        bootstrap.servers: srv-int-misc001.local:9093,srv-int-misc002.local:9093,srv-int-misc003.local:9093
    dev-build:
      properties:
        bootstrap.servers: srv-int-misc001.local:9098,srv-int-misc002.local:9098,srv-int-misc003.local:9098
    int:
      properties:
        bootstrap.servers: srv-int-misc001.local:9092,srv-int-misc002.local:9092,srv-int-misc003.local:9092
    int-build:
      properties:
        bootstrap.servers: srv-int-misc001.local:9099,srv-int-misc002.local:9099,srv-int-misc003.local:9099
    learn:
      properties:
        bootstrap.servers: srv-int-misc001.local:9097,srv-int-misc002.local:9097,srv-int-misc003.local:9097
    zh:
      properties:
        bootstrap.servers: srv-int-misc001.local:9094,srv-int-misc002.local:9094,srv-int-misc003.local:9094
    mut:
      properties:
        bootstrap.servers: srv-int-misc001.local:9101,srv-int-misc002.local:9101,srv-int-misc003.local:9101
    rec:
      properties:
        bootstrap.servers: srv-int-misc001.local:9095,srv-int-misc002.local:9095,srv-int-misc003.local:9095
    rec-build:
      properties:
        bootstrap.servers: srv-int-misc001.local:9100,srv-int-misc002.local:9100,srv-int-misc003.local:9100
    sbx:
      properties:
        bootstrap.servers: srv-int-misc001.local:9102,srv-int-misc002.local:9102,srv-int-misc003.local:9102
    zyv:
      properties:
        bootstrap.servers: srv-int-misc001.local:9096,srv-int-misc002.local:9096,srv-int-misc003.local:9096
  security:
    basic-auth:
    - groups:
      - admin
      password: toto
      username: admin
    - groups:
      - reader
      password: toto
      username: reader
    default-group: no-roles
    ldap:
      groups:
      - groups:
        - admin
        name: grp-prem-stg-adm-akhq
      - groups:
        - reader
        name: grp-prem-stg-usr-akhq
  server:
    access-log:
      enabled: false
      name: org.akhq.log.access
micronaut:
  security:
    enabled: true
    ldap:
      default:
        context:
          managerDn: CN=svc-app-stag-akhq,OU=AKHQ
          managerPassword: to
          properties:
          - java.naming.referral: follow
          server: ldap://local:389
        enabled: true
        groups:
          base: DC=LOCAL
          enabled: true
          filter: member={0}
          subtree: true
        search:
          base: DC=LOCAL
          filter: userPrincipalName={0}
          subtree: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: toto
```

on 0.25.1, here is what does'nt work 
![image](https://github.com/user-attachments/assets/2297726c-661d-4cae-b816-94ad3546d9b2)
I always get a 504 for the request `/api/dev/topic/facture.hospi.create/data?sort=Oldest&partition=All`. By the way, the topic is empty if it has something to do with the problem.
here is an excerpt of the log I get
```
2024-08-14 13:42:40,482 INFO  io-executor-thread-6 org.akhq.log.access [Date: 2024-08-14T13:42:40.482258001Z] [Duration: 0 ms] [Url: GET /ui/dev/topic/facture.hospi.create/data] [Status: 200] [Ip: /10.14.7.3] [User: admindje@externe.toto.fr] [User: admindje@externe.toto.fr]
2024-08-14 13:42:40,892 INFO  io-executor-thread-1 org.akhq.log.access [Date: 2024-08-14T13:42:40.885490293Z] [Duration: 7 ms] [Url: GET /api/dev/topic/facture.hospi.create/configs] [Status: 200] [Ip: /10.14.8.3] [User: admindje@externe.toto.fr]
2024-08-14 13:42:41,225 INFO  io-executor-thread-3 org.akhq.log.access [Date: 2024-08-14T13:42:40.928561817Z] [Duration: 300 ms] [Url: GET /api/dev/topic/facture.hospi.create/partitions] [Status: 200] [Ip: /10.14.9.3] [User: admindje@externe.toto.fr]
```

on 0.25.0, the display of the content of the topic works correctly, I never get the 504 for the display of the topic.

Can you help please ?
