### DISCUSSION TITLE
0.25 ACLs breaking change - patterns

### DISCUSSION THREAD

**Discussion by MaxenceVacheron** [tchiotludo/akhq#1883] [Q&A] [answered]
Hi,
I don't understand how I am supposed to update my application.yml for 0.25.1 version.
Old version was :
```
          topics-filter-regexp:
            - "^projectA_topic$" # Individual topic
            - "^projectB_.*$" # Topic group
          connects-filter-regexp:
            - "^test.*$"
          consumer-groups-filter-regexp:
            - "consumer.*"
 ```
 And new version only specify "patterns" in the group section 
 ```
     groups:
      topic-reader-pub:
        - role: topic-reader
          patterns: [ "pub.*" ]
```

How do I differentiate connect filters and topics filters ?

**Comment by AlexisSouquiere** [comment, marked as answer]
You differentiate filters based on the role you link them to. The pub.* pattern is only linked to the topic-reader role, which is, according to its name, a role that gives access to topics, not connectors. If you do something like this

```yaml
    groups:
      reader-pub:
        - role: topic-reader
           patterns: [ "pub.*" ]
        - role: connector-reader
           patterns: [ "test.*" ]
```

You will be able to apply 2 different patterns for topics and connectors (if the connector-reader role is defined correctly)
