### DISCUSSION TITLE
avoid mixing roles and attributes

### DISCUSSION THREAD

**Discussion by leonardotorresaltez** [tchiotludo/akhq#1886] [Q&A]
Hello .

i have the rolbindings.yaml file for akhq , and i want to know how to prevent the following behavior.

I have two roles:

- ROLE 1 : a role to update offset in apple.* topics
- ROLE 2: a role to read pears.* topics

When a user has asigned these two roles, then the user can update the offset in apple.*  (expected) and pears.* (not expected) topics.

How can i prevent the user update offsets in  pears .* topics ?  
Are there extension points in AKHQ then could i change the default behavior ?

ROLE 1
```yaml
        apple-reader:
          name: apple-reader
          roles: 
            - topic/data/read
            - group/offsets/update
          attributes:
            topics-filter-regexp:
              - "apple.*"
            consumer-groups-filter-regexp
              - "apple.*"
```

ROLE 2
```yaml
        pears-reader:
          name: pears-reader
          roles: 
            - topic/data/read
            - group/offsets/update
          attributes:
            topics-filter-regexp:
              - "pears.*"
            consumer-groups-filter-regexp:
              - "pears.*"
```

regards,
Leonardo
