### DISCUSSION TITLE
Can't connect to Kafka from AKHQ

### DISCUSSION THREAD

**Discussion by Vinayl6288** [tchiotludo/akhq#1887] [Q&A] [answered]
Sir,

Looking for some help in resolving AKHQ connectivity issue with Kafka running on my kubernetes.

Steps followed to install AKHQ: 
1) Add Helm Repo : `helm repo add akhq https://akhq.io/`
2) Update Helm Repos: `helm repo update`
3) Clone AKHQ github `git clone https://github.com/tchiotludo/akhq` & end values.yaml as below.

```

configuration:
  akhq:
    server:
      access-log:
        enabled: false
        name: org.akhq.log.access
    clients-defaults:
      consumer:
        properties:
          group.id: tss-akhq-consumer
    connections:
      tss-confluent-cloud:
        properties:
          bootstrap.servers: "PLAINTEXT://data-dev-cp-kafka-headless:9092"
          sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="2YOS7RROZHA5SMDW" password="HdAIayHCtL6An+szHd5b5Q3dT0wV20yW9+7KtqdeT0K0ffL4HezrnhPhmUr+C1vw";
          sasl.mechanism: PLAIN
          security.protocol: PLAINTEXT
          schema-registry:
            url: "http://data-dev-cp-schema-registry:8081"
            properties:
              ssl.protocol: PLAINTEXT
          connect:
            - name: connect
              url: "http://data-dev-cp-kafka-connect:8083"
      topic:
        skip-consumer-groups: true

```
4)  Install AKHQ: `cd akhq/helm/akhq` and `helm install akhq-release-name  akhq/akhq --namespace=akhq --values=values.yaml`

Observation:
AKHQ is getting installed but has connectivity issue with Kafka 

![image](https://github.com/user-attachments/assets/c3556635-f289-4f3d-a0b7-f528992dd974)

[akhq-pod.log](https://github.com/user-attachments/files/16426005/akhq-pod.log)
