### DISCUSSION TITLE
Github Auth can't filter based on organization.

### DISCUSSION THREAD

**Discussion by zenigmadev** [tchiotludo/akhq#1911] [Q&A]
I use github auth method and it works well but when i try to limit based on organization instead of specifying the users like below it doesn't work and get the log below. I can login with user1 with github login yet can't if I don't specify it on user section.

```
akhq:
  <...other config non releated to issue....>
  security:
`    oauth2:
      enabled: true
      providers:
        github:
          label: "Login with GitHub"
          username-field: login
          default-group: no-role
          organizations:
            - "organization_name"
          groups:
            - organization: "organization_name"
              groups:
                - reader
          users:
            - username: user1
              groups:
                - reader`
```
                
                
```
micronaut:
  server:
    port: 1111
    host-resolution:
      host-header: Host
      protocol-header: X-Forwarded-Proto
  security:
    enabled: true
    oauth2:
      enabled: true
      clients:
        github:
          client-id: "secret"
          client-secret: "secret"
          scopes:
            - user:email
            - read:user
            - read:org
          authorization:
            url: https://github.com/login/oauth/authorize
          token:
            url: https://github.com/login/oauth/access_token
            auth-method: client-secret-post
```

`2024-08-15 15:12:19,264 INFO  pGroup-1-7 org.akhq.log.access        [Date: 2024-08-15T15:12:19.259643557+03:00] [Duration: 5 ms] [Url: GET /oauth/login/github] [Status: 302] [Ip: /10.1.34.12] [User: user_from_org]
2024-08-15 15:12:20,371 INFO  pGroup-1-8 org.akhq.log.access        [Date: 2024-08-15T15:12:20.370996991+03:00] [Duration: 0 ms] [Url: OPTIONS /ui/static/css/main.8e11c20e.css.map] [Status: 200] [Ip: /10.1.34.12] [User: Anonymous]
2024-08-15 15:12:20,388 INFO  pGroup-1-9 org.akhq.log.access        [Date: 2024-08-15T15:12:20.387894552+03:00] [Duration: 0 ms] [Url: GET /ui/static/css/main.8e11c20e.css.map] [Status: 200] [Ip: /10.1.34.12] [User: Anonymous]
2024-08-15 15:12:37,446 INFO  pGroup-1-5 org.akhq.log.access        [Date: 2024-08-15T15:12:36.68783706+03:00] [Duration: 758 ms] [Url: GET /oauth/callback/github] [Status: 303] [Ip: /10.1.34.12] [User: Anonymous]
2024-08-15 15:12:37,502 INFO  pGroup-1-6 org.akhq.log.access        [Date: 2024-08-15T15:12:37.502648464+03:00] [Duration: 0 ms] [Url: GET /ui] [Status: 200] [Ip: /10.1.34.12] [User: Anonymous]
2024-08-15 15:12:37,598 INFO  pGroup-1-7 org.akhq.log.access        [Date: 2024-08-15T15:12:37.598111529+03:00] [Duration: 0 ms] [Url: GET /ui/static/js/main.b18c0753.js] [Status: 200] [Ip: /10.1.34.12] [User: user_from_org]
2024-08-15 15:12:37,650 INFO  pGroup-1-8 org.akhq.log.access        [Date: 2024-08-15T15:12:37.650556777+03:00] [Duration: 0 ms] [Url: GET /ui/static/css/main.8e11c20e.css] [Status: 200] [Ip: /10.1.34.12] [User: user_from_org]
2024-08-15 15:12:37,834 INFO  pGroup-1-9 org.akhq.log.access        [Date: 2024-08-15T15:12:37.834789891+03:00] [Duration: 0 ms] [Url: GET /ui/static/css/main.8e11c20e.css.map] [Status: 200] [Ip: /10.1.34.12] [User: user_from_org]
2024-08-15 15:12:38,116 INFO  r-thread-2 org.akhq.log.access        [Date: 2024-08-15T15:12:38.115223236+03:00] [Duration: 1 ms] [Url: GET /api/me] [Status: 200] [Ip: /10.1.34.12] [User: user_from_org]
2024-08-15 15:12:38,118 INFO  r-thread-2 org.akhq.log.access        [Date: 2024-08-15T15:12:38.115234398+03:00] [Duration: 3 ms] [Url: GET /api/auths] [Status: 200] [Ip: /10.1.34.12] [User: user_from_org]
2024-08-15 15:12:38,143 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2024-08-15T15:12:38.14335125+03:00] [Duration: 0 ms] [Url: GET /ui/static/js/main.b18c0753.js.map] [Status: 200] [Ip: /10.1.34.12] [User: user_from_org]
2024-08-15 15:12:38,147 INFO  r-thread-2 org.akhq.log.access        [Date: 2024-08-15T15:12:38.1464961+03:00] [Duration: 1 ms] [Url: GET /api/cluster] [Status: 200] [Ip: /10.1.34.12] [User: user_from_org]
2024-08-15 15:12:38,198 INFO  r-thread-2 org.akhq.log.access        [Date: 2024-08-15T15:12:38.196354032+03:00] [Duration: 1 ms] [Url: GET /api/cluster] [Status: 200] [Ip: /10.1.34.12] [User: user_from_org]
2024-08-15 15:12:38,202 INFO  pGroup-1-7 org.akhq.log.access        [Date: 2024-08-15T15:12:38.202384647+03:00] [Duration: 0 ms] [Url: GET /ui/manifest.json] [Status: 200] [Ip: /10.1.34.12] [User: Anonymous]
2024-08-15 15:12:38,215 INFO  pGroup-1-8 org.akhq.log.access        [Date: 2024-08-15T15:12:38.214882862+03:00] [Duration: 0 ms] [Url: GET /ui/ui/static/media/icon.383e5fd93919da4ccf1b1d78c73ab176.svg] [Status: 200] [Ip: /10.1.34.12] [User: user_from_org]
2024-08-15 15:12:38,334 INFO  pGroup-1-9 org.akhq.log.access        [Date: 2024-08-15T15:12:38.334602041+03:00] [Duration: 0 ms] [Url: GET /ui/static/media/fontawesome-webfont.20fd1704ea223900efa9.woff2] [Status: 200] [Ip: /10.1.34.12] [User: user_from_org]
2024-08-15 15:12:40,231 INFO  r-thread-2 org.akhq.log.access        [Date: 2024-08-15T15:12:40.230460045+03:00] [Duration: 0 ms] [Url: GET /] [Status: 307] [Ip: /10.1.68.7] [User: Anonymous]
2024-08-15 15:12:40,237 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2024-08-15T15:12:40.236848878+03:00] [Duration: 0 ms] [Url: GET /ui] [Status: 200] [Ip: /10.1.68.7] [User: Anonymous]`
