### DISCUSSION TITLE
Custom groups with OIDC

### DISCUSSION THREAD

**Discussion by Lars5678** [tchiotludo/akhq#2130] [Q&A]
I have configured AKHQ so that the user has to log in via OIDC with Keycloak.

```
security:
  roles:
    write:
      - resources: [ "TOPIC", "TOPIC_DATA" ]
        actions: [ "READ", "CREATE", "UPDATE" ]
      - resources: [ "TOPIC" ]
        actions: [ "READ_CONFIG" ]
      - resources: [ "CONSUMER_GROUP" ]
        actions: [ "READ", "UPDATE_OFFSET" ]
  default-group: no-roles
  groups:
    writer:
      - role: write
  oidc:
    enabled: true
    providers:
      keycloak:
        label: "Login with Keycloak"
        username-field: "upn"
        groups-field: roles
        default-group: no-roles
        groups:
          - name: kafka-reader
            groups:
              - reader
          - name: kafka-admin
            groups: 
              - admin
          - name: kafka-writer
            groups: 
              - writer
```

If I assign the user the role "kafka-reader" or "kafka-admin" in Keycloak, everything works as expected. In AKHQ, the predefined groups "admin" and "reader" are used. 

```
  "roles": [
    "kafka-reader"
  ]
```

```
  "roles": [
    "kafka-admin"
  ]
```

However, I need a third group in AKHQ that gives the user more permissions than "reader" but fewer than "admin." I called it "writer."

If I assign the user the role "kafka-writer" in Keycloak, I can't log in. It seems like I'm running into the "no-roles" case.

```
  "roles": [
    "kafka-writer"
  ]
```

What am I doing wrong, or where is my thinking error?
