### DISCUSSION TITLE
security configuration for many groups that have the same roles

### DISCUSSION THREAD

**Discussion by jorgheymans** [tchiotludo/akhq#548] [Q&A]
Hi,

We have about 15 teams currently using the same akhq instance. Each team should only have access to its own topics and we do this by prefixing the topic name. How do i concisely reflect this in AKHQ configuration without having to duplicate the `akhq-user` security block and each time have a different `topics-filter-regexp` per team ?

```
  security:
    default-group: no-roles
    groups:
      akhq-user
        name: akhq-user
        roles:
          - topic/read
          - node/read
          - topic/data/read
          - group/read
          - registry/read
          - acls/read
          - connect/read
        attributes:
          topics-filter-regexp: "TOPIC_A_.*"
    ldap:
      groups:
        - name: GROUP_A
          groups:
            - akhq-user
```

**Comment by tchiotludo** [comment]
For now, there is no others ways, maybe except using [yaml anchor](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/) ? 
Your use case can be interesting for the ACL revamp [here](https://github.com/tchiotludo/akhq/issues/523) if you have any idea ?

**Reply by jorgheymans** [reply]
Just when i thought yaml could not get any uglier, I'll try out the anchors :-)

Up until 0.14, this configuration worked and allowed us to do this:

```
  security:
    default-group: 
      - no-roles
    groups:
      abc:
        roles: [] 
        attributes:
          topics-filter-regexp: "abc.*"
    ldap:
      group:
        group-abc: 
          name: LDAP_ADM
          groups:
            - abc
            - reader
```
