### DISCUSSION TITLE
Configuring Schema Registry HTTPS connection

### DISCUSSION THREAD

**Discussion by brunomfcabral** [tchiotludo/akhq#575] [Q&A]
Hey guys!

So we've been trying to configure AKHQ connection to Schema Registry and I wonder if you could help us out on this one.

Our schema registry deployment does not require authentication but connection is encrypted with certificates signed by our internal CA.

So we figured out our yaml section of helm chart should look like this:
```yaml
schema-registry:
  url: "https://cp-schema-registry.schema-registry.svc.cluster.local:8085"
  type: "confluent"
  properties:
    ssl.ca.location: /app/schema-registry/ca.pem
```
We've checked the volumes and the certificate is indeed in this path.

But we get the following error bc it is not finding the certificate:
![image](https://user-images.githubusercontent.com/29949178/106186751-72d36a00-6183-11eb-845a-c5cac38053a5.png)

Does anyone have a hint?

Thanks!
