### DISCUSSION TITLE
Ldap nested groups

### DISCUSSION THREAD

**Discussion by julienmmm** [tchiotludo/akhq#673] [Q&A] [answered]
Hello,

We have successfully configured ldap authentication/authorization in AKHQ. Iit works well with direct group membership but I could not find anyway (even in the micronaut documentation) to use nested groups ==> if a user is mebmer of a group which is itself a member of another group for which a mapping exist in the akhq configuration file then the access is denied.
Below is my ldap group search filter.
attribute: "cn" filter: "(&(objectclass=group)(member={0}))"

any idea if it is possible and how?

Thanks!

**Comment by tchiotludo** [comment]
Sorry I don't know LDAP a lot in order to help you ... 
I don't even know if it's possible !

**Comment by julienmmm** [comment, marked as answer]
From a general perspective yes it, some applications can fetch indirect group membership (a group member of a group).
Maybe I should check more in details the micronaut ldap configuration.

Thanks for the response!

**Comment by SpiderX** [comment]
It is possible via [LDAP_MATCHING_RULE_IN_CHAIN](https://learn.microsoft.com/en-us/windows/win32/adsi/search-filter-syntax)

```
        search:
          enabled: true
          subtree: true
          base: "DC=example,DC=net"
          filter: "sAMAccountName={0}"
        groups:
          enabled: true
          base: "OU=Project,OU=Projects,OU=Company,DC=example,DC=net"
          subtree: true
          filter: '(member:1.2.840.113556.1.4.1941:={0})'
```
