### DISCUSSION TITLE
How to disable delete on compacting topics?

### DISCUSSION THREAD

**Discussion by sverrehu** [tchiotludo/akhq#721] [Q&A] [answered]
Hi! We try to set up a read-only AKHQ, but have not figured out how to disable the dustbin/delete for data on compacting topics. We allow access to anonymous users with the following roles:

```
    default-group: read-only
    groups:
      read-only:
        name: read-only
        roles:
          - topic/read
          - topic/data/read
          - node/read
          - group/read
          - registry/read
          - acls/read
          - connect/read
```

And although everything is `*/read`, the delete icon shows up, and lets the user insert a `null`-entry into the compacting topic.

Browsing the code gives the impression that `canDeleteRecords` is based solely on the fact that the topic is compacting, and not on the roles given to the user. What is the correct approach to make a read-only instance of AKHQ?
