### DISCUSSION TITLE
Oauth2 Authentication not working

### DISCUSSION THREAD

**Discussion by naveen8384** [tchiotludo/akhq#869] [Q&A] [answered]
I configured oauth2 authentication but after logging in successfully again it is redirecting to login page. This is the configuration I am using.

       `micronaut:
            oauth2:
              enabled: true
              clients:
                oauth:
                  client-id: "<client-id>"
                  client-secret: "<secret>"
                  openid:
                    issuer: "<issuer>"
        akhq:
          security:
            default-group: no-roles
            oidc:
              enabled: true
              providers:
                oauth:
                  label: "Login with SSO"
                  username-field: email
                  groups-field: roles
                  default-group: topic-reader`

In API request for /me I see logged as true and username is null. Am I missing anything?

![image](https://user-images.githubusercontent.com/4356276/137864449-78e66a9a-8703-4255-8751-44815cf295d1.png)

**Comment by tchiotludo** [comment]
Here is a working with google OIDC :

```yaml
micronaut:
  security:
    enabled: true
      oauth2:
        enabled: true
        clients:
          oauth:
            client-id: "<client-id>"
            client-secret: "<secret>"
            openid:
              issuer: "<issuer>"
akhq:
  security:
    default-group: no-roles
    oidc:
      enabled: true
      providers:
        google:
          label: "Login with Google"
          username-field: email
          default-group: reader
          users:
            - username: youremail@gmail.com
              groups:
                - admin
```

I think your `username-field` is wrong and you should map to correct one. 

You can enable more debug output with configuration below to find the right field  : 

```yaml 
logger:
  levels:
    io.micronaut.security: TRACE
    org.akhq.configs: TRACE
```

**Reply by naveen8384** [reply]
Hi @tchiotludo, I found that groups is missing in scope. If we add groups in scope then oauth is returning groups for that user. Is there anyway we can provide scopes explicitly?

company.com/oauth/restv1/authorize?scope=**openid+email+profile**&response_type=code=

**Reply by tchiotludo** [reply]
Seems that there is configuration [here](https://micronaut-projects.github.io/micronaut-security/latest/guide/#oauth2-configuration)

**Comment by naveen8384** [comment, marked as answer]
Thanks @tchiotludo ,
This configuration worked.
```yaml
      oauth2:
          enabled: true
          clients:
            oauth:
              client-id: "<client-id>"
              client-secret: "<secret>"
              scopes: 
                - email
                - openid
                - groups
                - profile              
              openid:
                issuer: "<issuer>"
```
