### DISCUSSION TITLE
Callback URI from login is HTTP Want to Change to HTTPS

### DISCUSSION THREAD

**Discussion by sunnvsp** [tchiotludo/akhq#877] [Q&A]
Can we add a feature for the callback URL with HTTPS, since my ingress was blocked by the HTTP?

**Comment by tchiotludo** [comment]
Micronaut try to detect if behind a reverse proxy the scheme of the callback url. 
If your ingress use a non standard Header, you can customize it to match the headers. Here is an example that make it work for GKE ingress  : 
```yaml 
    micronaut:
      server:
        host-resolution:
          host-header: Host
          protocol-header: X-Forwarded-Proto

````

**Comment by ClaudioMascaro** [comment]
Has anybody found a solution for this? It doesn't seems to solve for nginx-ingress-controller in EKS

**Reply by tchiotludo** [reply]
Are you using the last version ? with micronaut 3.X there is an enhancement on this part

**Reply by ClaudioMascaro** [reply]
Sorry for answering late, this is exactly what I did to solve :grin:
in newer version of micronaut you can inform a absolute URL in callback uri
```yaml
  micronaut:
    security:
      enabled: true
      oauth2:
        enabled: true
        callback-uri: https://your-callback-url
```
