### DISCUSSION TITLE
Sort topic data

### DISCUSSION THREAD

**Discussion by jjoyson** [tchiotludo/akhq#878] [Q&A]
The topic data sorting option does not seem to work for me. Am I doing something wrong?

Here is my configuration:
```
akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: ...
              schema-registry:
                url: ...
              connect:
                - name: ...
                  url: ...
              options:
                topic-data:
                  sort: NEWEST
                ui-options:
                  topic-data:
                    sort: NEWEST
          topic-data:
            sort: NEWEST
          ui-options:
            topic-data:
              sort: NEWEST
```
             
I tried all the different combinations from the documentation and some responses from posts here. But always sorts by OLDEST when the compose is run

**Comment by tchiotludo** [comment]
made a quick test : 

```yaml 
akhq:
  ui-options:
    topic:
      default-view: ALL
    topic-data:
      sort: NEWEST

```

it's works well directly, maybe you have some settings your localStorage.
- type F12 to devtool console 
- localStorage.clear()
- hit f5
