### DISCUSSION TITLE
SSL connection towards Kafka when deploying with Helm

### DISCUSSION THREAD

**Discussion by neuwerld2** [tchiotludo/akhq#891] [Q&A]
Hello!

I am trying to understand how to use SSL certificates with my helm chart to be able to connect to Kafka. I am not sure how to get my certificates in to the application. Would appreciate some help if somebody could maybe point me in the right direction.

**Comment by neuwerld2** [comment]
Since my certificates exist in k8s as secrets I thought that would be an easy way to load them or to maybe use kafkaSecrets but I can't understand how to define the keystore/truststore. And after that I am not sure how to configure my connection to use these kafkaSecrets.

**Comment by tchiotludo** [comment]
An example configuration for ssl can be found [here](https://akhq.io/docs/configuration/brokers.html#ssl-kafka-cluster). 
In order to mount secret on the pods and since the secrets already exist on your k8s, I would use this values configuration : 
https://github.com/tchiotludo/akhq/blob/82c5b94a56b0684714762ea998b001af7aee4018/helm/akhq/values.yaml#L67-L70
In order to mount existing secrets and bind it into

**Reply by neuwerld2** [reply]
Sorry my bad I don't have them as secrets in k8s, looked at the wrong secrets, I have them as files. Don't understand how to configure the helm chart to copy them into the application.
I have looked at the exampled that exists but cant figure it out, I am very new to k8s :)

I think maybe I should use extraVolumes ?

**Reply by tchiotludo** [reply]
In this case, you will need to create a custom charts (that [embed](https://helm.sh/docs/helm/helm_dependency/#helm) akhq charts) and add the secret in a [custom template](https://helm.sh/docs/chart_best_practices/templates/#helm). 

Or simple transform the certificate to base64 and add it [kafkaSecrets](https://github.com/tchiotludo/akhq/blob/81dcc4a5bf238f7708551ff77bc8861335de54c1/helm/akhq/templates/secret.yaml) values, but after will need still to mount `extraVolumes` & `extraVolumeMounts`

**Reply by neuwerld2** [reply]
I have transformed the keystores to base64 endoded strings now and configured it like this:
```yaml
kafkaSecrets:
  kafka-dev-truststore.jks: |-
    {base64encodedString}
  kafka-dev-user-keystore.jks: |-
    {base64encodedString}
```
Is this correct? {base64encodedString} is actually the string that I got and dont want to paste :)
What is the next step after this if this looks ok?

**Reply by tchiotludo** [reply]
It's over the scope of this project, since it's only k8s stuff. 

Mostly I think : 

```yaml 
extraVolumeMounts:
  - name: truststore-volume
    mountPath: /app/ssl
extraVolumes:
  - name: truststore-volume
    projected:
      sources:
        - secret:
            name: aiven-kafka-secrets
            items:
              - key: kafka-dev-truststore.jks
                path: truststore.jks
              - key: kafka-dev-user-keystore.jks
                path: keystore.jks
```
Go to the pods and you must see the secrets on dir `/app/ssl` then you will have to [configure akhq](https://akhq.io/docs/configuration/brokers.html#ssl-kafka-cluster) to use them. 

PS: I have a doubt that the keystore can be in jks format
