### DISCUSSION TITLE
Unable to start Micronaut server on port: 8080

### DISCUSSION THREAD

**Discussion by thedje** [tchiotludo/akhq#922] [Q&A] [answered]
Hi,

I wanted to change version of akhq (from 0.16.0 to 0.19.0) and I have the following error: 
```
akhq    | 2021-11-24 09:22:58,943 ERROR main       i.m.runtime.Micronaut      Error starting Micronaut server: Unable to start Micronaut server on port: 8080
akhq    | io.micronaut.http.server.exceptions.ServerStartupException: Unable to start Micronaut server on port: 8080
akhq    |       at io.micronaut.http.server.netty.NettyHttpServer.bindServerToHost(NettyHttpServer.java:505)
akhq    |       at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:323)
akhq    |       at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:114)
akhq    |       at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:77)
akhq    |       at java.base/java.util.Optional.ifPresent(Unknown Source)
akhq    |       at io.micronaut.runtime.Micronaut.start(Micronaut.java:75)
akhq    |       at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
akhq    |       at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
akhq    |       at org.akhq.App.main(App.java:27)
akhq    | Caused by: java.net.BindException: Address already in use
```
At the level of my docker-compose, I only changed the version: 
```
diff docker-compose-0-16-0.yml docker-compose.yml
5c5
<     image: tchiotludo/akhq:0.16.0
---
>     image: tchiotludo/akhq:0.19.0
15a16
>
```

At the micronaut conf level, I put :
```
micronaut:
  security:
    enabled: true
    # LDAP configuration
    ldap:
      default:
        enabled: true
        context:
          server: 'ldaps://xxxxxx'
          managerDn: 'cn=xxxxx'
          managerPassword: 'xxxxxx'
        search:
          base: ""
        groups:
          enabled: true
          base: al"

akhq:
  connections:
```
Did I forget something?

**Comment by tchiotludo** [comment]
Please provider to full docker-compose please ?

**Reply by thedje** [reply]
here it is : 

```
version: '3.8'
services:
  akhq:
    image: tchiotludo/akhq:0.19.0
    container_name: akhq
    network_mode: host
    restart: "no"
    environment:
      JAVA_OPTS: "-Djavax.net.ssl.trustStore=/xxxx -Djavax.net.ssl.trustStorePassword=xxxx"
    volumes:
      - /etc/security/kafka:/etc/kafka/secrets
      - /data/docker-compose/akhq/conf/application.yml:/app/application.yml

    restart: unless-stopped
```

**Comment by tchiotludo** [comment, marked as answer]
This only mean that on your host (since you are using the `network_mode: host`), the network port`8080` is already used, just find the process using it or change the akhq port : 
```yaml 
micronaut: 
  server: 
    port: 28080
```
