### DISCUSSION TITLE
configure where akhq logs

### DISCUSSION THREAD

**Discussion by jgrammen-agilitypr** [tchiotludo/akhq#975] [Q&A] [answered]
I have look through the documentation and various links but i cannot find any information on how to configure where akhq logs. 

How does one set the file/destination for the logging?
```
logger:
   levels:
     root: DEBUG
     org.akhq.configs: TRACE
     io.micronaut.security: TRACE
akhq:
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]" # Logger format
```
