### ISSUE TITLE
Header-auth not working properly

### ISSUE THREAD

**Issue by hyde404** [tchiotludo/akhq#1012]
Hello,

I would like to use header-auth config as an "authorizer".
The service is deployed on k8s and uses a oauth2-proxy container as a sidecar to log users with openAM.
We are able to login through oauth2 process and we get headers we want like `X-Forwarded-Groups` and `X-Forwarded-Email`.
To make sure these headers are forwarded, I added a "middleman" container which logs headers from oauth2.  

So it looks like that 
oauth2-proxy <----> middleman container <-----> akhq

This is what I log from the middleman : 

```
{
	'Host': 'akhq.smt-int01.smt.mt.mycompany.com', 
	'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36', 
	'Accept': 'application/json, text/plain, */*', 
	'Accept-Encoding': 'gzip, deflate, br', 
	'Accept-Language': 'fr-FR,fr;q=0.9', 
	'Cookie': '_ga=GA1.2.86470029.1643888228; _gid=GA1.2.1245042040.1643888228; _oauth2_proxy=<SOME COOKIE>, 
	'Referer': 'https://akhq.test-int.smt.mt.mycompany.com/ui/int/topic', 
	'Sec-Ch-Ua': '" Not;A Brand";v="99", 
	"Google Chrome";v="97", 
	"Chromium";v="97"', 
	'Sec-Ch-Ua-Mobile': '?0', 
	'Sec-Ch-Ua-Platform': '"Windows"', 
	'Sec-Fetch-Dest': 'empty', 
	'Sec-Fetch-Mode': 'cors', 
	'Sec-Fetch-Site': 'same-origin', 
	'X-Forwarded-Email': 'catelyn.lannister@mycompany.com', 
	'X-Forwarded-For': '10.111.136.135, 10.144.201.118', 
	'X-Forwarded-Groups': 'fed_identite@app_3625,fed_identite@imbrique,rid@rid_moa_sid,rid@@admins,rid@rid_moe_rid,fed_identite@app_5356,fed_identite@frsid', 
	'X-Forwarded-Port': '443', 
	'X-Forwarded-Proto': 'https'
}
``` 

And this is the piece of config I use in akhq  

```yaml
akhq:
  connections:
    ass:
      properties:
        bootstrap.servers: <BROKERS URL>
        security.protocol: SSL
    dev:
      properties:
        bootstrap.servers: <BROKERS URL>
        security.protocol: SSL
    int:
      properties:
        bootstrap.servers: <BROKERS URL>
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username=<USERNAME> password=<PASSWORD>;
        sasl.mechanism: SCRAM-SHA-512
        security.protocol: SASL_SSL
    sandbox:
      properties:
        bootstrap.servers: <BROKERS URL>
        security.protocol: SSL
  security:
    default-group: test-topic-reader
    groups:
      test-admin:
        attributes:
          connects-filter-regexp:
          - .*
          consumer-groups-filter-regexp:
          - .*
          topics-filter-regexp:
          - .*
        name: test-admin
        roles:
        - topic/read
        - topic/insert
        - topic/delete
        - topic/config/update
        - node/read
        - node/config/update
        - topic/data/read
        - topic/data/insert
        - topic/data/delete
        - group/read
        - group/delete
        - group/offsets/update
        - registry/read
        - registry/insert
        - registry/update
        - registry/delete
        - registry/version/delete
        - acls/read
        - connect/read
        - connect/insert
        - connect/update
        - connect/delete
        - connect/state/update
      test-no-role:
        name: test-no-role
        roles: []
      test-topic-reader:
        attributes:
          topics-filter-regexp:
          - .*
        name: test-topic-reader
        roles:
        - topic/read
    header-auth:
      default-group: test-topic-reader
      groups:
      - groups:
        - test-admin
        name: fed_identite@app_3625
      groups-header: X-Forwarded-Groups
      groups-header-separator: ','
      ip-patterns:
      - 0.0.0.0
      user-header: X-Forwarded-Email
      users:
      - groups:
        - test-admin
        username: catelyn.lannister@mycompany.com
```

For some reason I don't get, the role applied for all user tested will be test-topic-reader.
When I try with `catelyn.lannister@mycompany.com`, it is also test-topic-reader role which is applied...  

I tried to activate debug trace as suggested in https://akhq.io/docs/debug.html#debugging-authentication, but I still don't see any related issue.  

Could you please assist me with this ? 

Thank you !
