### ISSUE TITLE
/topic/data endpoint is not honouring akhq.topic-data.size

### ISSUE THREAD

**Issue by nightswimmings** [tchiotludo/akhq#1026]
It keeps returning the default count number 50, even if akhq's application.yml contains the key 
akhq:
   topic-data:
        size: 2000

**Comment by tchiotludo** [comment]
Looking at code, we never used this option, so normal it don't work. I think a quick fix was possible but need more time to handle this. 
PR are welcome :+1:

**Comment by tchiotludo** [comment]
Exactly. 
Or you can change this : 
```yaml 
akhq: 
  clients-defaults:
    consumer:
      properties:
        max.poll.records: 50
```
that will do the job I think
