### ISSUE TITLE
AKHQ works but doesn't show GUI

### ISSUE THREAD

**Issue by lamoboos223** [tchiotludo/akhq#1031]
![image](https://user-images.githubusercontent.com/35597031/156171957-574c8c3a-7dbb-4458-af6f-ffa67be80766.png)
as you can see i'm launching AKHQ throug the main class, didn't make any jars.

i sat the configuration file with new secret as recommended and i have added the kafka clusters

```yaml
akhq:
  # list of kafka cluster available for akhq
  connections:
    mykafka:
      properties: # standard kafka properties (optional)
        bootstrap.servers: "kafka0:9092,kafka1:9092,kafka2:9092"
```

but the UI shows nothing. I'm using release 0.20.0.

this is the stack trace:

```
2022-03-01 15:43:20,435 INFO  pGroup-1-5 org.akhq.log.access        [Date: 2022-03-01T15:43:20.4357595+03:00] [Duration: 0 ms] [Url: GET /ui] [Status: 200] [Ip: /0:0:0:0:0:0:0:1] [User: Anonymous]
2022-03-01 15:43:20,458 INFO  pGroup-1-6 org.akhq.log.access        [Date: 2022-03-01T15:43:20.4587618+03:00] [Duration: 0 ms] [Url: GET /ui/ui/static/css/2.1e4ddb81.chunk.css] [Status: 200] [Ip: /0:0:0:0:0:0:0:1] [User: Anonymous]
2022-03-01 15:43:20,459 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2022-03-01T15:43:20.4587618+03:00] [Duration: 0 ms] [Url: GET /ui/ui/static/css/main.b92fc08e.chunk.css] [Status: 200] [Ip: /0:0:0:0:0:0:0:1] [User: Anonymous]
2022-03-01 15:43:20,459 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2022-03-01T15:43:20.4587618+03:00] [Duration: 0 ms] [Url: GET /ui/ui/static/js/2.d78602c4.chunk.js] [Status: 200] [Ip: /0:0:0:0:0:0:0:1] [User: Anonymous]
2022-03-01 15:43:20,469 INFO  pGroup-1-8 org.akhq.log.access        [Date: 2022-03-01T15:43:20.4697619+03:00] [Duration: 0 ms] [Url: GET /ui/ui/static/js/main.3838d2d5.chunk.js] [Status: 200] [Ip: /0:0:0:0:0:0:0:1] [User: Anonymous]
2022-03-01 15:43:20,478 INFO  pGroup-1-7 org.akhq.log.access        [Date: 2022-03-01T15:43:20.4767623+03:00] [Duration: 0 ms] [Url: GET /ui/ui/manifest.json] [Status: 200] [Ip: /0:0:0:0:0:0:0:1] [User: Anonymous]
2022-03-01 15:43:20,484 INFO  pGroup-1-9 org.akhq.log.access        [Date: 2022-03-01T15:43:20.4847596+03:00] [Duration: 0 ms] [Url: GET /ui/ui/favicon.ico] [Status: 200] [Ip: /0:0:0:0:0:0:0:1] [User: Anonymous]
```

**Comment by lamoboos223** [comment]
![image](https://user-images.githubusercontent.com/35597031/156171957-574c8c3a-7dbb-4458-af6f-ffa67be80766.png)
as you can see i'm launching AKHQ throug the main class, didn't make any jars.

i sat the configuration file with new secret as recommended and i have added the kafka clusters


```yaml
akhq:
  # list of kafka cluster available for akhq
  connections:
    mykafka:
      properties: # standard kafka properties (optional)
        bootstrap.servers: "kafka0:9092,kafka1:9092,kafka2:9092"
```

but the UI shows nothing. I'm using release 0.20.0.

this is the stack trace:

```
2022-03-01 15:43:20,435 INFO  pGroup-1-5 org.akhq.log.access        [Date: 2022-03-01T15:43:20.4357595+03:00] [Duration: 0 ms] [Url: GET /ui] [Status: 200] [Ip: /0:0:0:0:0:0:0:1] [User: Anonymous]
2022-03-01 15:43:20,458 INFO  pGroup-1-6 org.akhq.log.access        [Date: 2022-03-01T15:43:20.4587618+03:00] [Duration: 0 ms] [Url: GET /ui/ui/static/css/2.1e4ddb81.chunk.css] [Status: 200] [Ip: /0:0:0:0:0:0:0:1] [User: Anonymous]
2022-03-01 15:43:20,459 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2022-03-01T15:43:20.4587618+03:00] [Duration: 0 ms] [Url: GET /ui/ui/static/css/main.b92fc08e.chunk.css] [Status: 200] [Ip: /0:0:0:0:0:0:0:1] [User: Anonymous]
2022-03-01 15:43:20,459 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2022-03-01T15:43:20.4587618+03:00] [Duration: 0 ms] [Url: GET /ui/ui/static/js/2.d78602c4.chunk.js] [Status: 200] [Ip: /0:0:0:0:0:0:0:1] [User: Anonymous]
2022-03-01 15:43:20,469 INFO  pGroup-1-8 org.akhq.log.access        [Date: 2022-03-01T15:43:20.4697619+03:00] [Duration: 0 ms] [Url: GET /ui/ui/static/js/main.3838d2d5.chunk.js] [Status: 200] [Ip: /0:0:0:0:0:0:0:1] [User: Anonymous]
2022-03-01 15:43:20,478 INFO  pGroup-1-7 org.akhq.log.access        [Date: 2022-03-01T15:43:20.4767623+03:00] [Duration: 0 ms] [Url: GET /ui/ui/manifest.json] [Status: 200] [Ip: /0:0:0:0:0:0:0:1] [User: Anonymous]
2022-03-01 15:43:20,484 INFO  pGroup-1-9 org.akhq.log.access        [Date: 2022-03-01T15:43:20.4847596+03:00] [Duration: 0 ms] [Url: GET /ui/ui/favicon.ico] [Status: 200] [Ip: /0:0:0:0:0:0:0:1] [User: Anonymous]
```

**Comment by tchiotludo** [comment]
Please provide : 
- AKHQ version using ?
- Deployment type ? Jar / Docker / k8s 
- Look at JS console (F12 on chrome) and provide error ?

**Comment by lamoboos223** [comment]
- release 0.20.0
- deployment is jar
- console output is: 
![image](https://user-images.githubusercontent.com/35597031/156172641-7ffab07e-ae6b-4892-b329-efb147ffc14d.png)

**Comment by tchiotludo** [comment]
humm really strange, can you provide the source code off js files please ? 
f12 + click on files at right with expected token <

**Comment by lamoboos223** [comment]
```html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <base href="./ui/">
        <link rel="icon" href="./ui/favicon.ico"/>
        <link rel="manifest" href="./ui/manifest.json"/>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>
        <meta name="theme-color" content="#33b5e5"/>
        <meta name="html-head" content="replace">
        <script>
            const AKHQ_PREFIX_UI = "./ui"
              , AKHQ_PREFIX_PATH = function() {
                const n = "./ui".split("/");
                return n.pop(),
                n.join("/")
            }()
        </script>
        <meta name="description" content="Kafka GUI for Apache Kafka to manage topics, topics data, consumers group, schema registry, connect and more..."/>
        <title>Tawakkalna AKHQ</title>
        <link href="./ui/static/css/2.1e4ddb81.chunk.css" rel="stylesheet">
        <link href="./ui/static/css/main.b92fc08e.chunk.css" rel="stylesheet">
    </head>
    <body>
        <noscript>You need to enable JavaScript to run this app.</noscript>
        <div id="root"></div>
        <script>
            !function(e) {
                function r(r) {
                    for (var n, f, l = r[0], a = r[1], i = r[2], c = 0, s = []; c < l.length; c++)
                        f = l[c],
                        Object.prototype.hasOwnProperty.call(o, f) && o[f] && s.push(o[f][0]),
                        o[f] = 0;
                    for (n in a)
                        Object.prototype.hasOwnProperty.call(a, n) && (e[n] = a[n]);
                    for (p && p(r); s.length; )
                        s.shift()();
                    return u.push.apply(u, i || []),
                    t()
                }
                function t() {
                    for (var e, r = 0; r < u.length; r++) {
                        for (var t = u[r], n = !0, l = 1; l < t.length; l++) {
                            var a = t[l];
                            0 !== o[a] && (n = !1)
                        }
                        n && (u.splice(r--, 1),
                        e = f(f.s = t[0]))
                    }
                    return e
                }
                var n = {}
                  , o = {
                    1: 0
                }
                  , u = [];
                function f(r) {
                    if (n[r])
                        return n[r].exports;
                    var t = n[r] = {
                        i: r,
                        l: !1,
                        exports: {}
                    };
                    return e[r].call(t.exports, t, t.exports, f),
                    t.l = !0,
                    t.exports
                }
                f.m = e,
                f.c = n,
                f.d = function(e, r, t) {
                    f.o(e, r) || Object.defineProperty(e, r, {
                        enumerable: !0,
                        get: t
                    })
                }
                ,
                f.r = function(e) {
                    "undefined" != typeof Symbol && Symbol.toStringTag && Object.defineProperty(e, Symbol.toStringTag, {
                        value: "Module"
                    }),
                    Object.defineProperty(e, "__esModule", {
                        value: !0
                    })
                }
                ,
                f.t = function(e, r) {
                    if (1 & r && (e = f(e)),
                    8 & r)
                        return e;
                    if (4 & r && "object" == typeof e && e && e.__esModule)
                        return e;
                    var t = Object.create(null);
                    if (f.r(t),
                    Object.defineProperty(t, "default", {
                        enumerable: !0,
                        value: e
                    }),
                    2 & r && "string" != typeof e)
                        for (var n in e)
                            f.d(t, n, function(r) {
                                return e[r]
                            }
                            .bind(null, n));
                    return t
                }
                ,
                f.n = function(e) {
                    var r = e && e.__esModule ? function() {
                        return e.default
                    }
                    : function() {
                        return e
                    }
                    ;
                    return f.d(r, "a", r),
                    r
                }
                ,
                f.o = function(e, r) {
                    return Object.prototype.hasOwnProperty.call(e, r)
                }
                ,
                f.p = "./ui/";
                var l = this["webpackJsonpakhq-front-end"] = this["webpackJsonpakhq-front-end"] || []
                  , a = l.push.bind(l);
                l.push = r,
                l = l.slice();
                for (var i = 0; i < l.length; i++)
                    r(l[i]);
                var p = a;
                t()
            }([])
        </script>
        <script src="./ui/static/js/2.d78602c4.chunk.js"></script>
        <script src="./ui/static/js/main.3838d2d5.chunk.js"></script>
    </body>
</html>

```

**Comment by tchiotludo** [comment]
Humm really strange, you have the html, not the js.
Can you provide the full configuration as yaml and the command line you use to start the application please ?

**Comment by lamoboos223** [comment]
```yaml
micronaut:
  application:
    name: akhq
  io:
    watch:
      paths: src/main
      restart: false # enabled dev server with env vars MICRONAUT_IO_WATCH_RESTART=true
  server:
    thread-selection: AUTO
    max-request-size: 10MB
    read-idle-timeout: 10m
    write-idle-timeout: 10m
    idle-timeout: 10m
    netty:
      max-chunk-size: 10MB
  router:
    static-resources:
      react:
        paths: classpath:ui
        mapping: "/ui/**"
      static:
        paths: classpath:static
        mapping: "/static/**"
      swagger:
        paths: classpath:META-INF/swagger
        mapping: "/swagger/**"
  security:
    enabled: true
    authentication: cookie
    endpoints:
      login:
        path: "/login"
        enabled: false
      logout:
        path: "/logout"
        get-allowed: true
        enabled: false
    token:
      jwt:
        enabled: true
        cookie:
          enabled: true
          cookie-same-site: strict
        signatures:
          secret:
            generator:
              secret: "lama"

    redirect:
      login-success: "${micronaut.server.context-path:}/ui"
      forbidden:
        url: "${micronaut.server.context-path:}/ui/login/forbidden"
      unauthorized:
        url: "${micronaut.server.context-path:}/ui/login/unauthorized"
      login-failure: "${micronaut.server.context-path:}/ui/login/failed"
      logout:  "${micronaut.server.context-path:}/ui"
    intercept-url-map:
      - pattern: "${micronaut.server.context-path:}/ui/**"
        access: "isAnonymous()"
      - pattern: "${micronaut.server.context-path:}/static/**"
        access: "isAnonymous()"
      - pattern: "${micronaut.server.context-path:}/swagger/**"
        access: "isAnonymous()"


  caches:
    kafka-wrapper:
      record-stats: true
      expire-after-write: 0s

jackson:
  serialization:
    writeDatesAsTimestamps: false

endpoints:
  all:
    port: 28081
    enabled: true
    sensitive: false
  health:
    details-visible: ANONYMOUS
  loggers:
    write-sensitive: false


akhq:
  # list of kafka cluster available for akhq
  connections:
    lama:
      properties: # standard kafka properties (optional)
        bootstrap.servers: "kafka0:9092,kafka1:9092,kafka2:9092"

  server:
    access-log:
      enabled: true
      name: org.akhq.log.access
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]"
      filters:
        - "((?!/health).)*"

  clients-defaults:
    consumer:
      properties:
        max.poll.records: 50
        isolation.level: read_committed
        # group.id: Akhq
        enable.auto.commit: "false"
        default.api.timeout.ms: 15000

  pagination:
    page-size: 25
    threads: 16

  avro-serializer:
    json.serialization.inclusions:
      - NON_NULL

  topic:
    replication: 1
    retention: 86400000
    partition: 1
    internal-regexps:
      - "^_.*$"
      - "^.*_schemas$"
      - "^.*connect-config$"
      - "^.*connect-offsets$1"
      - "^.*connect-status$"
    stream-regexps:
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"

  topic-data:
    size: 50
    poll-timeout: 1000
    kafka-max-message-length: 1000000

  security:
    default-group: admin
    groups:
      admin:
        name: admin
        roles:
        - topic/read
        - topic/insert
        - topic/delete
        - topic/config/update
        - node/read
        - node/config/update
        - topic/data/read
        - topic/data/insert
        - topic/data/delete
        - group/read
        - group/delete
        - group/offsets/update
        - registry/read
        - registry/insert
        - registry/update
        - registry/delete
        - registry/version/delete
        - acls/read
        - connect/read
        - connect/insert
        - connect/update
        - connect/delete
        - connect/state/update
      reader:
        name: reader
        roles:
        - topic/read
        - node/read
        - topic/data/read
        - group/read
        - registry/read
        - acls/read
        - connect/read
      no-roles:
        name: no-roles
        roles: []
```


and i start my application from here:
![image](https://user-images.githubusercontent.com/35597031/156175511-b13fd19d-1355-4213-8020-f70fd641705c.png)
