### ISSUE TITLE
CORB when running behind an OAuth proxy

### ISSUE THREAD

**Issue by ebrard** [tchiotludo/akhq#104]
We run kafkahq behind an OAuth proxy to manage user connection (a simple pass-through), after a first successful access and rendering we get CORB message at the next reload from both Safari and Chrome for all non-html resources (CSS, SVG, JS scripts...) like this:

```
Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://auth.thereplaceddomain.io/oauth_sign_in?rd=https://kafka-hq.thereplaceddomain.com%2Fstatic%2Fcss%2Fmain.css".
Cross-Origin Read Blocking (CORB) blocked cross-origin response <URL> with MIME type text/html. See <URL> for more details.
```

Is this somehow a known limitation, is there anything I could tweak in the configuration or code ?

**Comment by tchiotludo** [comment]
Yes it's possible with micronaut : 
https://docs.micronaut.io/latest/guide/index.html#cors
Just enabled cors and tune configuration for your domain in the same configuration files than kafkahq.

**Comment by ebrard** [comment]
I've modified my configuration as such:
```
micronaut:
  server:
      cors:
          enabled: true
  configurations:
      web:
          exposedHeaders:
              - Content-Type
              - Authorization
kafkahq:
  connections:
    kafka-testing:
      properties:
        bootstrap.servers: "kafka-stack.kafka:9092"
      schema-registry:
        url: "schema-registry.schema-registry:80"
      connect:
        url: "http://kafka-connect.main:8083"
```
but I still have the same issue :/
Is this the right configuration format ? I mean with the `micronaut` section ?

**Comment by tchiotludo** [comment]
To be honest, I never try but as I understand micronaut docs, you are on the right way. 

I would try with this to be really too large but must works: 
```yaml 
micronaut:
  server:
      cors:
          enabled: true
kafkahq: *
```
> By only enabling CORS processing, a "wide open" strategy will be adopted that will allow requests from any origin.

And after restrict by domain : 

```yaml 
micronaut:
  server:
      cors:
          enabled: true
          configurations:
            all:
              allowedOrigins:
                - ^http(|s):\/\/auth\.thereplaceddomain\.io$
```

**Comment by ebrard** [comment]
So this doesn't work. Also I found out that reaching a non-existing page doesn't give a 404 but loop in some weird state or goes to the login/forbidden page, is that expected ?

**Comment by tchiotludo** [comment]
Quite busy this weeks, but I'll try to reproduce on nexts weeks on my side but seems really weird. 
It's micronaut that give the feature, and to be honest, I will be really surprised if it's a bug on their side.

For the non 404, it's a wanted behaviour from micronaut to avoid the possibility to scan url without a correct login. The behaviour can't be changed for now.
I have a ticket about that here : https://github.com/micronaut-projects/micronaut-security/issues/6

**Comment by tchiotludo** [comment]
long time without any activity here ! 
I've seen that you keep a fork just because this issue. 

Would like to find a solution. 

For another project, I've to enabled some cors trouble and just add this : 
```
micronaut:
  server:
    cors:
      enabled: true
```
This works well (too wide open but works) 

Do you have tried ? 
This configuration don't work for you ?
