### ISSUE TITLE
LDAPS user access

### ISSUE THREAD

**Issue by ls50800977** [tchiotludo/akhq#1041]
Hi,

I am having trouble getting LDAPS connection working for my AKHQ.

My application.yml is as follows:

```yaml
micronaut:
  security:
    enabled: true
    ldap:
      default:
        enabled: true
        context:
          server: 'ldaps://xxx.dev:636'
          managerDn: 'xxx'
          managerPassword: 'xxx'
        search:
          base: "OU=x,OU=x,DC=x,DC=x,DC=x"
        groups:
          enabled: true
          base: "OU=x,OU=x,OU=tx,DC=x,DC=x,DC=x"
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "secreto"
    logging:
      level:
        ROOT: DEBUG
akhq:
  connections:
    default:
      properties:
        bootstrap.servers: "kafka-base-kafka-bootstrap:9093"
        security.protocol: SSL
        ssl.keystore.location: /app/certs/kafka.client.keystore.jks
        ssl.keystore.password: xxx
        ssl.key.password: xxx
        ssl.truststore.location: /app/certs/kafka.client.truststore.jks
        ssl.truststore.password: xxx
  security:
    groups:
      admin:
        name: admin
        roles:
          - topic/read
        attributes:
          topics-filter-regexp:
            - "^kafka.test$"
    ldap:
      groups:
        - name: "Kafka Administrators"
          groups:
             - admin`
```
I've tried the openssl command on the container which managed to talk to the domain controller. There's complaint about trust cert because it's internal CA signed which I've loaded in jvm.options.

My major concern is I found no way to get helpful logs. 

The only thing I could see is `2022-03-15 19:08:34,416 [31mWARN [0;39m [35mr-thread-1[0;39m [36mu.LoginFailedEventListener[0;39m Login failed reason UNKNOWN, username unknown, message Unknown` which cannot indicate any actual error.

Ideally, I would like to verify: 1) the container can talk to the domain controller and the internal signed vert is accepted, 2) there's no issue finding users and groups on the AD

Can you please advise how I can turn on a much more detailed logging and any clue of where the problem is?

Thanks,
Rick
