### ISSUE TITLE
Add read only access to some topics and read delete update access to some topics for a group

### ISSUE THREAD

**Issue by saimounima** [tchiotludo/akhq#1074]
We have a requirement to configure read only access for some topics A, B, C and read delete update access for some topics D,E,F for a group xyz.

Is there a possibility to do such configuration? Any inputs on this would be helpful.

Existing configuration for the xyz group has some topics read delete access, need to configure read only access for remaining  topics other than mentioned in the topics filter to the same group. Below is the akhq configuration example.
```yaml
micronaut:
          security:
            enabled: true
            oauth2:
              enabled: true
              clients:
                sso:
                  client-id: "<client-id>"
                  client-secret: "<client-secret>"
                  openid:
                    issuer: "<issuer>"
 akhq:
          security:
            default-group: no-roles
            groups:
              xyz:
                name: xyz
                roles:
                  - topic/read
                  - topic/delete
                  - topic/config/update
                  - topic/data/read
                  - topic/data/insert
                attributes:
                  topics-filter-regexp:
                    - ".*abc.*"
```
