### ISSUE TITLE
Failed to use Docker image

### ISSUE THREAD

**Issue by sergey-morenets** [tchiotludo/akhq#1085]
Hi 

I tried to use AKHQ in the Docker Compose configuration:

```
---
version: '3.8'
services:
  kafka:
    build: 
      context: .
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 8080:8080
```

I specified "kafka:9092" as Bootstrap server. However when I reviewed AKHQ logs I noticed that it used localhost instead:

`[AdminClient clientId=adminclient-1] Connection to node 1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.`

And AKHQ failed to perform any of the management operations from UI

**Comment by tchiotludo** [comment]
Here is a kafka config that work both for container or from host : 

```yaml 
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    volumes:
      - kafka-data:/var/lib/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://local:9092
    depends_on:
      - zookeeper
    ports:
      - 127.13.9.8:9092:9092
    networks:
      local:
        aliases:
        - local
    restart: unless-stopped
```

**Comment by sergey-morenets** [comment]
@tchiotludo Thank you for the quick response. Please note that I don't use Zookeeper. It's mentioned in the Kafka config:

`      KAFKA_PROCESS_ROLES: 'broker,controller'`

So is it possible to use AKHQ with Kafka but without Zookeeper?

**Comment by tchiotludo** [comment]
Never tried by myself, but I don't have any dependencies with zookeeper so I pretty sure that yes you can use Kraft with AKHQ

**Comment by sergey-morenets** [comment]
Hi @tchiotludo 

I performed deep investigation of this issue and found the reason why Akhq client failed to work with Kafka.
So if I use this environment setting for Kafka container then Akhq works without issues:

`KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'`

But If add PLAINTEXT_HOST attribute:

`KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092`

then Akhq client doesn't work properly because it tries to connect to localhost:9092 and not to kafka:29092. Not sure why it happens. I used the latest setting value for Kowl or Confluent Control Center and didn't experience any issues.

**Comment by tchiotludo** [comment]
here is a working docker compose without zookeeper: 
```yaml 
version: '3.8'
services:
  kafka:
    image: quay.io/strimzi/kafka:latest-kafka-3.1.0-amd64
    command:
      [
        "sh",
        "-c",
        "export CLUSTER_ID=$$(bin/kafka-storage.sh random-uuid) && bin/kafka-storage.sh format -t $$CLUSTER_ID -c config/kraft/server.properties && bin/kafka-server-start.sh config/kraft/server.properties --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} --override listeners=$${KAFKA_LISTENERS}",
      ]
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:29092"
    ports:
      - 28080:8080
```
Since i don't know what image you are using, I provide one from strimzy
