### ISSUE TITLE
unable to use secrets using by micronaut basic authentification

### ISSUE THREAD

**Issue by QualoZe0t** [tchiotludo/akhq#1099]
Hi,

I would like to use as final solution aws external secret manager where will be stored username and password and using micronaut for basic authentification. Problem is that i have created test opaque kube secrets.. example
`kubectl create secret generic akhq-secrets --from-literal=username:user --from-literal=password=testP@ssword`

values.yaml

```
extraEnv:
  - name: USERNAME
    valueFrom:
      secretKeyRef:
        name: akhq-secrets
        key: username
  - name: PASSWORD
    valueFrom:
      secretKeyRef:
        name: akhq-secrets
        key: password

configuration:
  akhq:
    server:
      access-log:
        enabled: true
        name: org.akhq.log.access
    connections:
      local:
        properties:
          bootstrap.servers: XXX
    endpoints:
      preprod:
        enabled: true
        sensitive: true
    security:
      basic-auth:
        - username: '${USERNAME}'
          password: '${PASSWORD}'
          groups:
          - admin
  micronaut:
    security:
      enabled: true
      default-group: no-roles
      token:
        jwt:
          signatures:
            secret:
              generator:
                secret: XXX
```

unfortunately once i will execute helm uprage i see environment variable in pod with username and password but application.yml is ignoring this env variables ... can someone figure out how to properly define ?

I want to avoid to put before installing helm any shell script which will decode base64 and then make sha256

Thanks for help
