### ISSUE TITLE
Format access-log

### ISSUE THREAD

**Issue by ericmagna** [tchiotludo/akhq#1154]
Hi,

With the file 
Hello,

In the application.example.yml file I have an example for formatting the accesslog file.

I would like to add the call size.

How can I make this addition?

Thank you for your help.

**Extracting the example configuration**

```yaml
akhq:
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]" # Logger format
```
