### ISSUE TITLE
Login Page Issue with Basic Auth

### ISSUE THREAD

**Issue by luisdalves** [tchiotludo/akhq#1165]
Hey guys, first of all great product!
I'm facing out some issues enabling basic-auth with the login page. After enable this feature I'm being redirected to /ui/login but there is no textbox to input username or password.
I'm running akhq on eks and was deployed using helm chart v0.2.8 and I'm doing a port-forward to reach the application.
Here is my values.yaml
```
configuration:
  akhq:
    server:
      access-log:
        enabled: true
        name: org.akhq.log.access # Logger name
        format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]"

secrets:
  akhq:
    connections:
      my-cluster:
        properties:
          bootstrap.servers: xxxx:9092,xxxx:9092,xxxx:9092" 
    security:
      default-group: no-roles
      groups:
        admin:
         roles:
           - topic/read
           - topic/insert
           - topic/delete
           - topic/config/update
           - node/read
           - topic/data/read
           - topic/data/insert
           - topic/data/delete
           - group/read
           - group/delete
           - group/offsets/update
           - registry/read
           - registry/insert
           - registry/update
           - registry/delete
           - registry/version/delete
    basic-auth:
      - username: admin
        password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        groups:
        - admin
  micronaut:
    security:
      enabled: true
      token:
        jwt:
          signatures:
            secret:
              generator:
                secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
Thanks for you help guys!
