### ISSUE TITLE
User in basic-auth can only get the authorized access from one of his groups

### ISSUE THREAD

**Issue by kyleli666** [tchiotludo/akhq#1170]
### Description
I have several kafka cluster A and B managed in one AKHQ.

1. I want to have all topic and consumer group read access in kafka A and B.
2. I want to add one more topic/data/read access only to kafka A, but not kafka B.
3. All kafka A's topic can match  "^Market.*"

so I feel I can impliment with this configuration in basic-auth: (admin is ommited)
```yaml
  # Auth & Roles (optional)
  security:
    default-group: no-access # Default groups for all the user even unlogged user
    groups:
      all-reader: # unique key
        name: all-reader # Other group
        roles:
          - topic/read
          - group/read
      kafka-a-reader: # unique key
        name: kafka-a-reader # Other group
        roles:
          - topic/data/read
        attributes:
          topics-filter-regexp:
            - "^Market.*"
    # Basic auth configuration
    basic-auth:
      - username: read-only
        password: # Password in sha256
        groups: # Groups for the user
          - kafka-a-reader
          - all-reader
```
### Result
But finally, I can only read topic, topic data, and consumer group as per "^Market.*"  in kafka A, and cannot see any topic from kafka B. Somehow consumer group in kafka B can be read.
It seems basic-auth user's "groups" is using some AND logic not OR logic, so that I can only get a smaller access, which I feel is against this multi-"groups" config design.

### Expect

1. I can read topic and group from kafka A and B.
2. I can also read topic data but only in kafka A.
