### ISSUE TITLE
Helm deployment: Readiness probe failed on k8s

### ISSUE THREAD

**Issue by thomas-chauvet** [tchiotludo/akhq#1176]
I have some trouble running AKHQ on k8s with the basic installation.

I just create a new namespace called `monitoring` on k8s (version `v1.21.4`).

I simply deployed the base helm chart: 

```bash
helm upgrade --install akhq \
        akhq/akhq \
        --namespace "monitoring" \
        --debug
```

I always end up with:

```error
Readiness probe failed: Get "http://x.x.x.x:28081/health": dial tcp x.x.x.x:28081: connect: connection refused 
```

Maybe I don't use a good version.

Any tips on how to fix this?

Thanks!

I ran in debug mode, here are the logs:

```
history.go:56: [debug] getting history for release akhq
upgrade.go:142: [debug] preparing upgrade for akhq
upgrade.go:150: [debug] performing update for akhq
upgrade.go:322: [debug] creating upgraded release for akhq
client.go:229: [debug] checking 3 resources for changes
client.go:512: [debug] Looks like there are no changes for ConfigMap "akhq"
client.go:512: [debug] Looks like there are no changes for Service "akhq"
client.go:250: [debug] Created a new Deployment called "akhq" in monitoring

upgrade.go:157: [debug] updating status for upgraded release for akhq
Release "akhq" has been upgraded. Happy Helming!
NAME: akhq
LAST DEPLOYED: Wed Aug 17 18:20:56 2022
NAMESPACE: monitoring
STATUS: deployed
REVISION: 3
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
annotations: {}
configuration:
  akhq:
    server:
      access-log:
        enabled: false
        name: org.akhq.log.access
containerSecurityContext: {}
existingSecrets: ""
extraEnv: []
extraVolumeMounts: []
extraVolumes: []
image:
  repository: tchiotludo/akhq
  tag: ""
ingress:
  annotations: {}
  enabled: false
  hosts:
  - akhq.demo.com
  ingressClassName: ""
  paths:
  - /
  tls: []
initContainers: {}
kafkaSecrets: []
labels: {}
nodeSelector: {}
podAnnotations: {}
podLabels: {}
readinessProbe:
  prefix: ""
resources: {}
secrets: {}
securityContext: {}
service:
  annotations: null
  enabled: true
  labels: {}
  port: 80
  type: ClusterIP
serviceAccount:
  create: false
serviceAccountName: null
tolerations: []

HOOKS:
MANIFEST:
---
# Source: akhq/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: akhq
  labels:
    app.kubernetes.io/name: akhq
    helm.sh/chart: akhq-0.2.8
    app.kubernetes.io/instance: akhq
    app.kubernetes.io/managed-by: Helm
data:
  application.yml: |
    akhq:
      server:
        access-log:
          enabled: false
          name: org.akhq.log.access
---
# Source: akhq/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: akhq
  labels:
    app.kubernetes.io/name: akhq
    helm.sh/chart: akhq-0.2.8
    app.kubernetes.io/instance: akhq
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: akhq
    app.kubernetes.io/instance: akhq
---
# Source: akhq/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq
  labels:
    app.kubernetes.io/name: akhq
    helm.sh/chart: akhq-0.2.8
    app.kubernetes.io/instance: akhq
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: akhq
      app.kubernetes.io/instance: akhq
  template:
    metadata:
      annotations:
        checksum/config: 29aad503d9d302f1fb8791e1c5f1ea60304a2e9976c224dad0b15610da6dcc42
      labels:
        app.kubernetes.io/name: akhq
        app.kubernetes.io/instance: akhq
    spec:
      serviceAccountName: default
      containers:
        - name: akhq
          image: "tchiotludo/akhq:0.21.0"
          imagePullPolicy: Always
          env:
          volumeMounts:
            - name: config
              mountPath: /app/application.yml
              subPath: application.yml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: management
              containerPort: 28081
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: management
          readinessProbe:
            httpGet:
              path: /health
              port: management
          resources:
            {}
      volumes:
      - name: config
        configMap:
          name: akhq
```
