### ISSUE TITLE
Protobuf schemas in apicurio schema registry 

### ISSUE THREAD

**Issue by p1ppus** [tchiotludo/akhq#1185]
When using protobuf schemas in our apicurio registry akhq is unable to deserialize the content of the message. Events without schema id can successfully be deserialized with corresponding descriptor files. Only after assigning schema ids akhq is unable to parse the data.

"Error in GUI: Error deserializing Protobuf message for id xx"
![image](https://user-images.githubusercontent.com/112345484/187171270-0b81e050-a2dd-4eec-925d-90f72977aff6.png)

The documentation explicitly states for AVRO that messages using schema registry are automatically decoded if the schema registry is configured. But for PROTOBUF there is no such mention, only info about how to create desc files.

Does akhq allow to use (apicurio) schema registry in conjunction with proto schemas or is it not supported?

Parts of our config
```
akhq:
      connections:
        xxx-kafka:
          deserialization:
            protobuf:
              descriptors-folder: /opt/protodesc
              topics-mapping:
              - descriptor-file: authr_doc.desc
                topic-regex: .*authr_doc
                value-message-type: com.xxxx.xxx.xxx.protobuf.authr_doc.Authr_doc
              #More Proto desc file mappings
          properties:
            bootstrap.servers: SSL://xxx-kafka-bootstrap:9092
            security.protocol: SSL
            #MORE SSL Config
          schema-registry:
            type: confluent
            url: http://apicurio-registry:8008/apis/ccompat/v6
```
