### ISSUE TITLE
AKHQ aggregates all the access roles (i.e topic/read, topic/write etc..) and applies to all the topics defined in topic/consumer filter-regex.

### ISSUE THREAD

**Issue by spareslant** [tchiotludo/akhq#1196]
If a user is a member of multiple AKHQ groups, AKHQ aggregates all the access roles (i.e topic/read, topic/write etc..) and applies to all the topics defined in topic/consumer filter-regex.

e.g. Take the following AKHQ config

```yaml
  security:
    default-group: no-roles
    groups:
      a-topic-reader:
        name: a-topic-reader
        roles:
          - topic/read
        attributes:
          topics-filter-regexp:
            - "^aTopic$"
      b-topic-all:
        name: b-topic-all
        roles:
          - topic/read
          - topic/config/update
        attributes:
          topics-filter-regexp:
            - "^bTopic$"

    # Ldap Groups configuration (when using ldap)
    ldap:
      users:
        - username: bUser1
          groups:
            - a-topic-reader
            - b-topic-all
```

From above config it appears that ldap user bUser1 
* should have only read permission on aTopic and
* should have read and update permission on bTopic.

But it turns out that bUser1 can read and update both aTopic and bTopic.

enabling Auth Debug logs shows this

```
 Generated claim set: {sub=bUser1, nbf=1662110498, connectsFilterRegexp=[], roles=[topic/read, topic/config/update], iss=akhq, exp=1662114098, iat=1662110498, consumerGroupsFilterRegexp=[], topicsFilterRegexp=[^aTopic$, ^bTopic$]}
```
