### ISSUE TITLE
injecting css docker compose question to change background color

### ISSUE THREAD

**Issue by FrankMormino** [tchiotludo/akhq#1212]
I am trying to change the background color to be red - from the example here [Inject some css or javascript](https://akhq.io/docs/configuration/akhq.html#inject-some-css-or-javascript) it gave me the main structure I need in order to get this added to the docker-compose yml file which once i run it - should reflect. 

I tried to implement the change below and wasn't able to see it reflect :

_note: i just ran a docker-compose up -d after i added these values to existing akhq instance that's running_

```
  akhq:
    image: tchiotludo/akhq:latest
    restart: always
    environment:
      html-head: |
        <style type="text/css">
          body {
            background-color: red !important
        }
        </style>
```

Any direction here is greatly appreciated.

Thanks

**Comment by FrankMormino** [comment]
![image](https://user-images.githubusercontent.com/45765756/191064177-8fa7ecc7-99de-4d26-b8c9-63a1056858b5.png)
updating issue to closed since i had to add it inside the AKHQ_CONFIGURATION config.
```
  akhq:
    # build:
    #   context: .
    image: tchiotludo/akhq:latest
    restart: always

    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          html-head: |
            <style type="text/css">
              body {
                background-color: red !important
            }
            </style>

````
