### ISSUE TITLE
Configuring Azure hosted kafka-connect behind API Management not possible 

### ISSUE THREAD

**Issue by TomHuesler** [tchiotludo/akhq#1229]
Dear all
We're running several kafka-connect's in different 'data-centers' (local, onPrem, Azure). Configuring the Azure kafka-connect in AkHQ seems impossible....

To secure the Azure deployment, we use the Azure API mangement with a subscription key, what leads to an URL like:
https://my-resource-group-apim.azure-api.net/?subscription-key=23432432423499898798987

In such a case AkHQ fails to show the kafka-connect.

Desired state:
- Allow users to pass security parameters in a distinct configuration property.
- Such parameters shall be added at the end of the URL (after all the relative paths added by AkHQ)

Sample docker-compose snippet:
```yaml
  akhq:
    image: tchiotludo/akhq:0.22.0
    container_name: akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            ccloud:
              properties:
                bootstrap.servers: "${CONNECT_BOOTSTRAP_SERVERS}"
                security.protocol: SASL_SSL
                sasl.mechanism: PLAIN
                sasl.jaas.config: "${CONNECT_AKHQ_JAAS_CONFIG}"
              schema-registry:
                url: "${CONNECT_SCHEMA_REGISTRY_URL}"
                basic-auth-username: "${CONNECT_SCHEMA_REGISTRY_USER_NAME}"
                basic-auth-password: "${CONNECT_SCHEMA_REGISTRY_USER_PASSWORD}"
              connect:
                - name: "localhost"
                  url: "${CONNECT_URL}"
                - name: "aveniq"
                  url: "${CONNECT_AVENIQ_URL}"
                - name: "azure"
                  url: "https://resource-group-apim.azure-api.net/test?subscription-key=keyValue"
      CONNECT_URL: ${CONNECT_URL}
      CONNECT_AVENIQ_URL: ${CONNECT_AVENIQ_URL}
   ports:
      - 8084:8080
```
