### ISSUE TITLE
No data is displayed in the topics

### ISSUE THREAD

**Issue by MrKribel** [tchiotludo/akhq#1270]
Hello. I am experimenting with access rights separation. I want to make only the administrator have access to the data (can view and modify).

```
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true

akhq:
  connections:    
    yandex:
      properties:
       .....

  security:
    default-group: topic-reader # Default groups for all the user even unlogged user
    # Groups definition
    groups:
      admin: # unique key
        name: admin # Group name
        roles:  # roles for the group
          - topic/read
          - topic/insert
          - topic/delete
          - topic/config/update
          - node/read
          - node/config/update
          - topic/data/read
          - topic/data/insert
          - topic/data/delete
          - group/read
          - group/delete
          - group/offsets/update
          - registry/read
          - registry/insert
          - registry/update
          - registry/delete
          - registry/version/delete
          - acls/read
          - connect/read
          - connect/insert
          - connect/update
          - connect/delete
          - connect/state/update
        attributes:
          # Regexp list to filter topic available for group
          topics-filter-regexp:
            - "test.*"
          # Regexp list to filter connect configs visible for group
          connects-filter-regexp:
            - "^test.*$"
          # Regexp list to filter consumer groups visible for group
          consumer-groups-filter-regexp:
            - "consumer.*"
      topic-reader: # unique key
        name: topic-reader # Other group
        roles:
          - topic/read
        attributes:
          topics-filter-regexp:
            - "test\\.reader.*"

    # Basic auth configuration
    basic-auth:
      - username: admin
        password: "$2a$12$pass"
        passwordHash: BCRYPT
        groups: 
          - admin
          - topic-reader
  
micronaut:
  server:
    port: 53452
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
```
There are no errors, everything starts well. I do get data to the whole system, except for the topic information .

i see topic -> test_pos   39.562 KB but when I click on it, I get a response "No data available".
