### ISSUE TITLE
Not all topics are displayed 

### ISSUE THREAD

**Issue by MrKribel** [tchiotludo/akhq#1290]
My configuration file: 

```
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true

akhq:
  connections:
    yandex:
      properties:
        bootstrap.servers: "rc1a-38....475e6tm8.mdb.yandexcloud.net:9091"
        security.protocol: SSL
        ssl.truststore.location: /tmp/ssl.jks
        ssl.truststore.password: g....m..
        sasl.mechanism: SCRAM-SHA-512
        security.protocol: SASL_SSL
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="admin_kafka" password="g...j..............";
  topic-data:
    sort: OLDEST # default sort order (OLDEST, NEWEST) (default: OLDEST)
    size: 25 # max record per page (default: 50)
    poll-timeout: 5000 # The time, in milliseconds, spent waiting in poll if data is not available in the buffer.

  security:
    default-group: topic-reader # Default groups for all the user even unlogged user
    # Groups definition
    groups:
      admin: # unique key  
        name: admin # Group name
        roles:  # roles for the group
          - topic/read
          - topic/insert   
          - topic/delete   
          - topic/config/update
          - node/read
          - node/config/update
          - topic/data/read
          - topic/data/insert
          - topic/data/delete
          - group/read
          - group/delete   
          - group/offsets/update
          - registry/read  
          - registry/insert
          - registry/update
          - registry/delete
          - registry/version/delete
          - acls/read
          - connect/read   
          - connect/insert 
          - connect/update 
          - connect/delete
          - connect/state/update
     
      topic-reader: # unique key
        name: topic-reader # Other group
        roles:
          - topic/read
        attributes:
          topics-filter-regexp:
            - "test\\.reader.*"

    # Basic auth configuration
    basic-auth:
      - username: admin
        password: "$2a$12$FgMSDRk..../KRziLXN2"
        passwordHash: BCRYPT
        groups: 
          - admin
          - topic-reader

micronaut:
  server:
    port: 53452
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
```

There are no errors. User has read access to all topics. 

But the user sees only two topics... What to do? Set a timeout somewhere?
