### ISSUE TITLE
Helm chart with default values fails when unquoting bootstrap servers

### ISSUE THREAD

**Issue by tamis-laan** [tchiotludo/akhq#1294]
I followed the install guide for installation:
``` bash
helm repo add akhq https://akhq.io/
```

The values.yaml is taken from artifact hub ( https://artifacthub.io/packages/helm/akhq/akhq?modal=values )
I unquoted the extraEnv as followed:
``` yaml
## You can put directly your configuration here... or add java opts or any other env vars
extraEnv:
 - name: AKHQ_CONFIGURATION
   value: |
       akhq:
         secrets:
           docker-kafka-server:
             properties:
               bootstrap.servers: "kafka:9092"
# - name: JAVA_OPTS
#   value: "-Djavax.net.ssl.trustStore=/opt/java/openjdk/lib/security/cacerts -Djavax.net.ssl.trustStorePassword=password"
# - name: CLASSPATH
#   value: "/any/additional/jars/desired.jar:/go/here.jar"
```

I then install the chart:
``` bash
helm upgrade -f values.yaml --install akhq akhq/akhq
```

I get the following error:
``` bash
> kubectl logs pod/akhq-6dc8fdb9c4-hmhrm
/usr/local/bin/docker-entrypoint.sh: 6: cannot create /app/application.yml: Read-only file system
```
