### ISSUE TITLE
Login form does not show up when using basic authentication

### ISSUE THREAD

**Issue by chikeo** [tchiotludo/akhq#1296]
When using basic authenticaton, the landing page attempts to redirect to /ui/login but it stays blank, the login form does not show up. In the logs, I see that User shows up as blank
I see something like
`User - `

My configuration is as follows:

```yaml
        micronaut:
          security:
            enabled: true
        configuration:
          akhq:
            server:
              access-log:
                enabled: true
                name: org.akhq.log.access
            # Auth & Roles (optional)
            security:
              default-group: no-roles # Default groups for all the user even unlogged user
              # Groups definition
              groups:
                admin: # unique key
                  name: admin # Group name
                  roles:  # roles for the group
                    - topic/read
                    - topic/insert
                    - topic/delete
                    - topic/config/update
                    - node/read
                    - node/config/update
                    - topic/data/read
                    - topic/data/insert
                    - topic/data/delete
                    - group/read
                    - group/delete
                    - group/offsets/update
                    - registry/read
                    - registry/insert
                    - registry/update
                    - registry/delete
                    - registry/version/delete
                    - acls/read
                    - connect/read
                    - connect/insert
                    - connect/update
                    - connect/delete
                    - connect/state/update
                  attributes:
                    # Regexp list to filter topic available for group
                    topics-filter-regexp:
                      - ".*"
                    # Regexp list to filter connect configs visible for group
                    connects-filter-regexp:
                      - ".*"
                    # Regexp list to filter consumer groups visible for group
                    consumer-groups-filter-regexp:
                      - ".*"
                topic-reader: # unique key
                  name: topic-reader # Other group
                  roles:
                    - topic/read
                    - node/read
                    - topic/data/read
                    - group/read
                    - registry/read
                    - acls/read
                    - connect/read
                  attributes:
                    topics-filter-regexp:
                      - ".*"
                    connects-filter-regexp:
                      - ".*"
                    consumer-groups-filter-regexp:
                      - ".*"

              # Basic auth configuration
              basic-auth:
                - username: name # Username
                  password: a-password-sha256 # Password in sha256
                  groups: # Groups for the user
                    - admin
                - username: name2 # Username
                  password: a-second-password-sha256 # Password in sha256
                  groups: # Groups for the user
                    - topic-reader
```

Please does anyone know why this is the case? I am using just pure basic authentication and not using LDAP, OIDC etc. Thank you very much.

**Comment by tchiotludo** [comment]
```yaml
micronaut:
  security:
    enabled: true
akhq:
  security:
    basic-auth:
      user:
        password: d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1
        groups:
        - admin
```
here is a minimal configuration that is working, I see the you have a strange `configuration:` on your example and `akhq:` is not indented properly

**Comment by chikeo** [comment]
Thank you for your prompt response. It is a helm chart with a k8s cluster. Your default values.yaml file had `configuration:` in it under which server and I presume security are indented.

**Comment by tchiotludo** [comment]
Yes, starting like that : 

```yaml 
        configuration:
          micronaut:
            security:
              enabled: true
          akhq:
```
