### ISSUE TITLE
No clusters found in configuration file despite configuration being correct

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [tchiotludo/akhq#1309]
Deploying using `helm` and the pod never starts.

The pod logs do not indicate any errors.

However from within the pod:

```
akhq@akhq-6cf9c87fcc-vh22b:/app$ curl http://localhost:28081/health
{"message":"Couldn't find any clusters on your configuration file, please ensure that the configuration file is loaded correctly","_links":{"self":{"href":"/health","templated":false}}}
```

Also from within the pod:

```
akhq@akhq-6cf9c87fcc-xpx2l:/app$ cat application-secrets.yml
akhq:
  connections:
    staging-ssl:
      properties:
        bootstrap.servers: "kafka.my-provider:11111"
        security.protocol: SSL
        ssl.truststore.location: /app/truststore.jks
        ssl.truststore.password: XXXXXXXXXXXXXX
        ssl.keystore.location: /app/keystore.jks
        ssl.keystore.password: XXXXXXXXXXXXXX
        ssl.key.password: XXXXXXXXXXXXXX
```
