### ISSUE TITLE
akhq ignoring sort topics by NEWEST

### ISSUE THREAD

**Issue by kribel** [tchiotludo/akhq#1318]
my config:

```
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true

akhq:
  connections:
    yandex:
      properties:
        bootstrap.servers: "rc1a-38.m...et:9091"
        security.protocol: SSL
        ssl.truststore.location: /tmp/ssl.jks
        ....

  topic-data:
    sort: NEWEST # default sort order (OLDEST, NEWEST) (default: OLDEST)
    size: 25 # max record per page (default: 50)
    poll-timeout: 5000 # The time, in milliseconds, spent waiting in poll if data is not available in the buffer.
    ui-options:
      topic-data:
      sort: NEWEST

  security:
    default-group: topic-reader # Default groups for all the user even unlogged user
    # Groups definition
    groups:
      admin: # unique key  
        name: admin # Group name
        roles:  # roles for the group
          - topic/read
          - topic/insert   
          - topic/delete   
          - topic/config/update
          - node/read
          - node/config/update
          - topic/data/read
          - topic/data/insert
          - topic/data/delete
          - group/read
          - group/delete   
          - group/offsets/update
          - registry/read  
          - registry/insert
          - registry/update
          - registry/delete
          - registry/version/delete
          - acls/read
          - connect/read   
          - connect/insert 
          - connect/update 
          - connect/delete
          - connect/state/update

      topic-reader: # unique key
        name: topic-reader # Other group
        roles:
          - topic/read

    # Basic auth configuration
    basic-auth:
      - username: admin
        password: "$2a.....XN2"
        passwordHash: BCRYPT
        groups: 
          - admin
          - topic-reader
          - 
micronaut:
  server:
    port: 5321
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
```
how do I change the configuration file so that topics are sorted by NEWEST?
Thank you you are the best!
