### ISSUE TITLE
[akhq/helm - configuration] Connect akhq to kafka

### ISSUE THREAD

**Issue by n1vgabay** [tchiotludo/akhq#1328]
Hi fellas,

I'm struggling to connect **akhq** to **Kafka**.

**System:**
Kubernetes cluster (EKS) latest version 1.24 version.
Kafka version 19.1.3.
schema registry version 7.0.0.

**Issue:**
After init the service the UI is established via ingress, but when the page is loaded we see nothing.
So basically it looks like it should show the login because of the page color but we can't see anything.

Connection to kafka: (probably the issue)
```
      akhq:
        security:
          enabled: true
          default-group: no-roles        
          basic-auth:
            - username: <user>
              password: <pass>
              groups:
                - admin
            - username: <user>
              password: <pass>
              groups:
                - reader
        connections:
          veego-dev-plain-text:  
            my-cluster-plain-text:
              properties:
                bootstrap.servers: "default-kafka-headless:9092"
                # security.protocol: SASL_SSL
                # sasl.mechanism: SCRAM-SHA-512
                sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="<kafka user client>" password="<kafka pass client>";
            schema-registry:
              url: "<schema url>:8081"
```

I don't see any logs from the pod.

How can I debug it? What am I missing? What's wrong with those configurations?

Thanks for helping!
