### ISSUE TITLE
AKHQ can't connect to kafka brokers - authentication failed.

### ISSUE THREAD

**Issue by n1vgabay** [tchiotludo/akhq#1330]
Any ideas what's missing here?

```
2023-01-04 10:13:57,211 WARN  inclient-1 o.a.k.c.NetworkClient      [AdminClient clientId=adminclient-1] Connection to node -1 (default-kafka-headless/10.0.21.162:9092) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.
```

My helm configuration is like this:
```
configuration:
      akhq:
        connections:
          <cluster>:
            properties:
              bootstrap.servers: "default-kafka-headless:9092"
              security.protocol: SASL_SSL
              sasl.mechanism: PLAIN
              sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="<user>" password="<pass>";
            schema-registry:
              url: "<URL>"
```

Thanks.
