### ISSUE TITLE
AKHQ listenning address when run with systemd

### ISSUE THREAD

**Issue by StefThomas** [tchiotludo/akhq#1348]
Hi,

I installed AKHQ standalone. If I run it manually it listens on __http://my_server_hostname:8080__, but when I run it with systemd, then it listens on __http://localhost:8080__.

Why does it differ?

My AKHQ systemd unit file looks like this:

```
[Unit]
Description=AKHQ Service
After=network-online.target
Requires=network-online.target

[Service]
Type=simple
Restart=on-failure
User=kafka
Group=kafka

ExecStart=/usr/bin/java -Dmicronaut.config.files=/home/kafka/akhq-application.yml -jar /home/kafka/akhq.jar
KillSignal=SIGINT
WorkingDirectory=/home/kafka

[Install]
WantedBy=multi-user.target
```
__/home/kafka/akhq.jar__ is a symlink to __/home/kafka/akhq-0.23.0-all.jar__

My Java is OpenJDK 19.

My AKHQ configuration file is the following (user/password and other sensitive information replaced with xxxxx):

```
#logger:
#  levels:
#     org.akhq.configs: TRACE
#     io.micronaut: DEBUG
#     io.micronaut.security.ldap: TRACE
#     io.micronaut.configuration.security: TRACE

micronaut:
  security:
    enabled: true
    # Ldap authenticaton configuration
    ldap:
      default:
        enabled: true
        context:
          server: 'ldap://xxxxx:389'
          managerDn: 'cn=xxxxx,ou=xxxxx,dc=xxxxx,dc=xxxxx,dc=xxxxx'
          managerPassword: 'xxxxx'
        search:
          base: "ou=xxxxx,dc=xxxxx,dc=xxxxx,dc=xxxxx"
        groups:
          enabled: true
          base: "ou=xxxxx,ou=xxxxx,dc=xxxxx,dc=xxxxx,dc=xxxxx"
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: 'xxxxx'

akhq:
  connections:
    Armorique: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "xxxxx:9092,xxxxx:9092,xxxxx:9092,xxxxx:9092"

  security:
    default-group: admin # Default groups for all the user even unlogged user
    # Groups definition
    groups:
      admin: # unique key
        name: admin # Group name
        roles:  # roles for the group
          - topic/read
          - topic/insert
          - topic/delete
          - topic/config/update
          - node/read
          - node/config/update
          - topic/data/read
          - topic/data/insert
          - topic/data/delete
          - group/read
          - group/delete
          - group/offsets/update
          - registry/read
          - registry/insert
          - registry/update
          - registry/delete
          - registry/version/delete
          - acls/read
          - connect/read
          - connect/insert
          - connect/update
          - connect/delete
          - connect/state/update
        attributes:
          # Regexp list to filter topic available for group
          topics-filter-regexp:
            - ".*"
          # Regexp list to filter connect configs visible for group
          connects-filter-regexp:
            - ".*"
          # Regexp list to filter consumer groups visible for group
          consumer-groups-filter-regexp:
            - "consumer.*"
      topic-reader: # unique key
        name: topic-reader # Other group
        roles:
          - topic/read
        attributes:
          topics-filter-regexp:
            - "reader.*"

    # Basic auth configuration
    basic-auth:
      - username: kafka-admin # Username
        password: xxxxx # Password in sha256
        groups: # Groups for the user
          - admin
          - topic-reader

    # Ldap Groups configuration (when using ldap)
    ldap:
      default-group: topic-reader
      groups:
        #- name: group-ldap-1
        #  groups: # Akhq groups list
        #    - topic-reader
        - name: xxxxx
          groups:
            - admin
      users:
        #- username: riemann # ldap user id
        #  groups: # Akhq groups list
        #    - topic-reader
        - username: xxxxx
          groups:
            - admin

    # Header configuration (reverse proxy)
    header-auth:
      user-header: x-akhq-user # mandatory (the header name that will contain username)
      #groups-header: x-akhq-group # optional (the header name that will contain groups separated by groups-header-separator)
      #groups-header-separator: ',' # optional (separator, defaults to ',')
      #ip-patterns: [127.0.0.*] # optional (Java regular expressions for matching trusted IP addresses, '0.0.0.0' matches all addresses)
      default-group: topic-reader
      groups:
        - name: header-admin-group
          groups:
            - admin
      #users: # optional
      #  - username: header-user # username matching the `user-header` value
      #    groups: # list of groups / additional groups
      #      - topic-reader
      #  - username: header-admin
      #    groups:
      #      - admin

    # Data masking configuration
    data-masking:
      filters:
        - description: "Masks value for secret-key fields"
          search-regex: '"(secret-key)":".*"'
          replacement: '"$1":"xxxx"'
        - description: "Masks last digits of phone numbers"
          search-regex: '"([\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?)[0-9]{4,6}"'
          replacement: '"$1xxxx"'
```
