### ISSUE TITLE
Basic Authentiction doesnt seems to work properly

### ISSUE THREAD

**Issue by sajiljosephs** [tchiotludo/akhq#1359]
Basic Authentiction doesnt seems to work properly. 
Error: Wrong username or password 
WARN  Group-1-12 u.LoginFailedEventListener Login failed reason CREDENTIALS_DO_NOT_MATCH, username unknown, message Credentials Do Not Match

Please find the yml config below

akhq:
  security:
    default-group: reader
    basic-auth:
      - username: admin
        password: 6b3a55e0261b0304143f805a24924d0c1c44524821305f31d9277843b8a10f4e
        groups:
          - admin

**Comment by AlexisSouquiere** [comment]
Did you follow this ? https://akhq.io/docs/configuration/authentifications/basic-auth.html
Use the following user

``` yaml
    - username: admin
      password: "d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1"
      groups:
      - admin
```

if you want to login with admin / pass
