### ISSUE TITLE
Akhq fails to work in Docker environment

### ISSUE THREAD

**Issue by sergey-morenets** [tchiotludo/akhq#1363]
Hi

This is my docker-compose.yml that works previously but Akhq fails to list the topics for the latest versions (0.23.0, dev):

```
---
version: '3.9'
services:
  kafka:
    build: 
      context: src/main/docker
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 
  akhq:
    image: tchiotludo/akhq:dev
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 8080:8080
      - 28081:28081
```

Here is error message in the browser console:

`Timed out waiting for a node assignment. Call: listTopics
`
Here's logs:

```
kafka-training-akhq-1  |  __  __ _                                  _   
kafka-training-akhq-1  | |  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
kafka-training-akhq-1  | | |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
kafka-training-akhq-1  | | |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
kafka-training-akhq-1  | |_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
kafka-training-akhq-1  |   Micronaut (v3.7.3)
kafka-training-akhq-1  | 
kafka-training-akhq-1  | 2023-02-03 12:30:25,485 [34mINFO [0;39m [35mmain      [0;39m [36mi.m.runtime.Micronaut     [0;39m Startup completed in 1286ms. Server Running: http://4d96600dd161:8080
kafka-training-akhq-1  | 2023-02-03 12:30:48,481 [34mINFO [0;39m [35mpGroup-1-3[0;39m [36morg.akhq.log.access       [0;39m [Date: 2023-02-03T12:30:48.471884Z] [Duration: 9 ms] [Url: GET /ui/docker-kafka-server/topic] [Status: 200] [Ip: /172.18.0.1] [User: -]
kafka-training-akhq-1  | 2023-02-03 12:30:48,551 [34mINFO [0;39m [35mpGroup-1-3[0;39m [36morg.akhq.log.access       [0;39m [Date: 2023-02-03T12:30:48.551332Z] [Duration: 0 ms] [Url: GET /ui/static/js/main.fc03db2c.js] [Status: 200] [Ip: /172.18.0.1] [User: -]
kafka-training-akhq-1  | 2023-02-03 12:30:48,589 [34mINFO [0;39m [35mpGroup-1-4[0;39m [36morg.akhq.log.access       [0;39m [Date: 2023-02-03T12:30:48.589229Z] [Duration: 0 ms] [Url: GET /ui/static/css/main.8e11c20e.css] [Status: 200] [Ip: /172.18.0.1] [User: -]
kafka-training-akhq-1  | 2023-02-03 12:30:49,412 [34mINFO [0;39m [35mr-thread-1[0;39m [36morg.akhq.log.access       [0;39m [Date: 2023-02-03T12:30:48.89821Z] [Duration: 514 ms] [Url: GET /api/me] [Status: 200] [Ip: /172.18.0.1] [User: -]
kafka-training-akhq-1  | 2023-02-03 12:30:49,412 [34mINFO [0;39m [35mr-thread-2[0;39m [36morg.akhq.log.access       [0;39m [Date: 2023-02-03T12:30:48.89821Z] [Duration: 514 ms] [Url: GET /api/auths] [Status: 200] [Ip: /172.18.0.1] [User: -]
kafka-training-akhq-1  | 2023-02-03 12:30:49,443 [34mINFO [0;39m [35mr-thread-4[0;39m [36morg.akhq.log.access       [0;39m [Date: 2023-02-03T12:30:49.441871Z] [Duration: 1 ms] [Url: GET /api/cluster] [Status: 200] [Ip: /172.18.0.1] [User: -]
kafka-training-akhq-1  | 2023-02-03 12:30:49,443 [34mINFO [0;39m [35mr-thread-2[0;39m [36morg.akhq.log.access       [0;39m [Date: 2023-02-03T12:30:49.440595Z] [Duration: 2 ms] [Url: GET /api/cluster] [Status: 200] [Ip: /172.18.0.1] [User: -]
kafka-training-akhq-1  | 2023-02-03 12:30:49,464 [34mINFO [0;39m [35mpGroup-1-4[0;39m [36morg.akhq.log.access       [0;39m [Date: 2023-02-03T12:30:49.464484Z] [Duration: 0 ms] [Url: GET /ui/ui/static/media/icon.383e5fd93919da4ccf1b1d78c73ab176.svg] [Status: 200] [Ip: /172.18.0.1] [User: -]
kafka-training-akhq-1  | 2023-02-03 12:30:49,523 [34mINFO [0;39m [35mpGroup-1-4[0;39m [36morg.akhq.log.access       [0;39m [Date: 2023-02-03T12:30:49.522726Z] [Duration: 0 ms] [Url: GET /ui/static/media/logo.ba7c128db2ff905fdb6f.svg] [Status: 200] [Ip: /172.18.0.1] [User: -]
kafka-training-akhq-1  | 2023-02-03 12:30:49,561 [34mINFO [0;39m [35mpGroup-1-3[0;39m [36morg.akhq.log.access       [0;39m [Date: 2023-02-03T12:30:49.561031Z] [Duration: 0 ms] [Url: GET /ui/static/media/fontawesome-webfont.20fd1704ea223900efa9.woff2] [Status: 200] [Ip: /172.18.0.1] [User: -]
kafka-training-akhq-1  | 2023-02-03 12:31:49,613 [31mWARN [0;39m [35mr-thread-4[0;39m [36morg.akhq.log.access       [0;39m [Date: 2023-02-03T12:30:49.505883Z] [Duration: 60107 ms] [Url: GET /api/docker-kafka-server/topic] [Status: 409] [Ip: /172.18.0.1] [User: -]
kafka-training-akhq-1  | 2023-02-03 12:31:49,821 [34mINFO [0;39m [35mpGroup-1-7[0;39m [36morg.akhq.log.access       [0;39m [Date: 2023-02-03T12:31:49.820833Z] [Duration: 0 ms] [Url: GET /ui/static/js/main.fc03db2c.js.map] [Status: 200] [Ip: /172.18.0.1] [User: -]
```
