### ISSUE TITLE
 OIDC authorization error - AuthenticationMethod.WINDOWS_CLIENT_AUTHENTICATION

### ISSUE THREAD

**Issue by kosarevevg** [tchiotludo/akhq#1376]
good afternoon. Perhaps someone has faced a similar problem. I set up authentication via OIDC, click the authorize button in akhq, a redirect to the authorization page occurs, I log in and get an error
```json
{"message":"No enum constant io.micronaut.security.oauth2.endpoint.AuthenticationMethod.WINDOWS_CLIENT_AUTHENTICATION","_links":{"self":{"href":"/oauth/callback/oidc?code=AAAAAAAAAAAAAAAAAAAAAA.ekq6Q3MO2wgbChIJIPqsb5hgjmY.Z4vJejCLoZVVSpA-0RTi3c_-jFoBo1GVqvbckSD9KdCABls60voXDGvyn-0V2pZbrb0lVs3r8OZS7G5TJR09vL6lZZzRIqVapicfSZT55jW2MXNP0IQaFI-TCiZVimKMRwQwIO_fRI1mvJRCsC264lVdStXLRxU_Rg_OOIraXAXWoQ4--g6JlXwm_6WjO4yKahFttIMWHbarmexw26hxIKkYSi9ejmYNumH7IhhG7eJW8m05PkeaMJ1hn8XZGYIBcGIEqRXUHR3I2nbr2QFGSM93s4SMXuq1EGSOAkXjSILQKliuwkmhmvPHnkd1Q5OZj3iA-krW9SBPrAitXghl8g&state=eyJyZWRpcmVjdFVyaSI6Imh0dHA6Ly8xOTIuMTY4LjE0LjIwMy9vYXV0aC9jYWxsYmFjay9vaWRjIiwibm9uY2UiOiI3ZjQ5ODBkZS1lYzBiLTQ1NmQtYTRhYy1hMjhhNTEyODVlNjkifQ==","templated":false}}}
```
the compose method is specified in the client_secret_post
```yaml
version: '3.6'
services:
  akhq:
    image: tchiotludo/akhq
    restart: always
    environment:
      AKHQ_CONFIGURATION: |
        micronaut:
          security:
            enabled: true
            oauth2:
              enabled: true
              clients:
                oidc:
                  client-id: "client-id"
                  client-secret: "client-secret"
                  openid:
                    issuer: "https://server/adfs"   
                  token:
                    url: "https://server/adfs/oauth2/token/"
                    auth-method: "client_secret_post"
                  user-info:
                    url: https://server/adfs/userinfo
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "192.168.14.203:9092"
              schema-registry:
                url: "http://192.168.14.203:8085"
          security:
            default-group: no-roles   
            oidc:
              enabled: true
              providers:
                oidc:
                  label: "Login with OIDC"
                  username-field: preferred_username
                  groups-field: roles
                  default-group: topic-reader
                  groups:
                    - name: oidc-admin-group
                      groups:
                        - admin
                  users:
                    - username: einstein
                      groups:
                        - admin                                                                               
    ports:
      - 80:8080
```

![image](https://user-images.githubusercontent.com/42740693/218707319-ea7bf75b-a0e9-4713-a22b-423ae042925e.png)
