### ISSUE TITLE
Still able to create topics with `group: reader` through the API

### ISSUE THREAD

**Issue by Lazzaretti** [tchiotludo/akhq#1395]
I created an akhq instance with the `default-group: reader`:
```
  akhq:
    security:
      default-group: reader 
```

Then I checked if the role was applied. 
* In the UI, the create topic button is not visible anymore
* Also, the API seems to suggest that I am a reader `curl http://myakhq/api/me  -H 'Accept: application/json, text/plain, */*'` returns `{"logged":false,"roles":["acls","acls/read","connect","connect/read","group","group/read","node","node/read","registry","registry/read","topic","topic/data","topic/data/read","topic/read"]}`

However, with the API I am still able to create a topic: 
```
curl 'http://myakhq/api/cluster/topic' -H 'Accept: application/json, text/plain, */*' -H 'Content-Type: application/json;charset=UTF-8' --data-raw '{"cluster":"cluster","name":"new-topic","partition":1,"replication":1,"configs":{"cleanup.policy":"delete","retention.ms":86400000}}'
```

It returns
```
{"name":"new-topic","internal":false,"partitions":[{"id":0,"topic":"new-topic","nodes":[{"id":0,"host":"kafka-0.kafka-headless.default.svc.cluster.local","port":9092,"leader":true,"inSyncReplicas":true}],"logDir":[{"brokerId":0,"path":"/bitnami/kafka/data","topic":"new-topic","partition":0,"size":0,"offsetLag":0,"future":false}],"firstOffset":0,"lastOffset":0,"logDirSize":0,"leader":{"id":0,"host":"kafka-0.kafka-headless.default.svc.cluster.local","port":9092,"leader":true,"inSyncReplicas":true}}],"size":0,"logDir":[{"brokerId":0,"path":"/bitnami/kafka/data","topic":"new-topic","partition":0,"size":0,"offsetLag":0,"future":false}],"internalTopic":false,"streamTopic":false,"replicaCount":1,"inSyncReplicaCount":1,"logDirSize":0}
```` 
and the new topic is also visible in the UI.

Am I doing something wrong?

I'm using the docker image `tchiotludo/akhq:0.23.0`

**Comment by tchiotludo** [comment]
Looking quickly at the code, I don't find any issues. 
Maybe you can share your configuration file? 
Because I see that you use any credential on curl, that seems to be weird with a security enable :thinking:

**Comment by Lazzaretti** [comment]
Hey @tchiotludo
Thanks for the fast reply!

I installed it via helm `akhq/akhq` from https://akhq.io/.

My configurations are: 
```
configuration:
  akhq:
    connections:
      cluster:
        properties:
          bootstrap:
            servers: <serverurl>
        schema-registry:
          url: <schemaurl>
    security:
      default-group: reader 
```

I used port-forwarding to the service `kubectl port-forward svc/akhq -n default 8001:80`

**Comment by tchiotludo** [comment]
Look at [these](https://akhq.io/docs/configuration/authentifications/jwt.html): we need to enable security and set you JWT secret

**Comment by Lazzaretti** [comment]
Ahh great!

So with the additional setting, it works.
```
        micronaut:
          security:
            enabled: true
            token:
              jwt:
                signatures:
                  secret:
                    generator:
                      secret: <secret>
```


However, shouldn't the UI act the same way as the API? To me, that's quite dangerous if the `default-group` setting without a token configuration gets applied in the UI but not in the API.
Most people probably think they applied the security group correctly, and it gets applied everywhere.

Also, the [groups doc](https://akhq.io/docs/configuration/authentifications/groups.html) doesn't mention that behavior at all.
