### ISSUE TITLE
Updated way to kill the the login button?

### ISSUE THREAD

**Issue by jessetandor** [tchiotludo/akhq#1433]
I read through : https://github.com/tchiotludo/akhq/issues/361

And added the following to my k8s configmap but the login button still shows:

```
    micronaut:
      security:
        enabled: true
        endpoints:
          login:
            enabled: false
          logout:
            enabled: false
      server:
            port: xxxx
```

Did i miss something?
