### ISSUE TITLE
Protobuf deserialization config is not found for topic

### ISSUE THREAD

**Issue by s1apped** [tchiotludo/akhq#1476]
Hey.

I'm having problem configuring protobuf deserialization using descriptor files. I'm following example https://akhq.io/docs/configuration/protobuf.html but for some reason seeing below in logs:

`DEBUG r-thread-1 ProtobufToJsonDeserializer Protobuf deserialization config is not found for topic `

```
    configuration:
      akhq:
        connections:
          akhq_cluster:
            properties:
              bootstrap.servers: "kafka:9092"
          kafka:
            properties:
              bootstrap.servers: "kafka:9092"
            deserialization:
              protobuf:
                descriptors-folder: "/app/protobuf_desc"
                topics-mapping:
                  - topic-regex: "events.topic1.test1"
                    descriptor-file-base64: "base64here"
                    value-message-type: "com.events.v1.Ticket"
                  - topic-regex: "events.topic1.test2"
                    descriptor-file-base64: "base64here"
                    value-message-type: "com.events.v1alpha1.Company"
```
I have tried with and without descriptors-folder.

Thank you!
