### ISSUE TITLE
Issue with OIDC login in version 0.24

### ISSUE THREAD

**Issue by hari819** [tchiotludo/akhq#1478]
hello team,

recently i have updated to 0.24 version to mitigate the existing vulnerabilities in 0.23 version.
Noticed this issue where users are unable to login using Azure AD setup via OIDC configuration ,  I can see the akhq-secret in kubernetes cluster showing the value of client-secret as XXX instead of actual value , where as in case of 0.23 version it is showing the actual secret value ,

since the secret is going as XXX in the actual request sent to Azure AD ,  we see the below error in the akhq logs and users are unable to login ,

```
Trace ID: af30ab52-6e19-4308-8fe9-bf38d20da200
Correlation ID: 3d6cf1d4-2efe-4f6b-b7ee-e71abd1e4290
Timestamp: 2023-05-02 09:51:24Z, errorUri: https://login.microsoftonline.com/error?code=7000215
io.micronaut.http.client.exceptions.HttpClientResponseException: error: invalid_client, errorDescription: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '<REDACTED>'.
Trace ID: af30ab52-6e19-4308-8fe9-bf38d20da200
Correlation ID: 3d6cf1d4-2efe-4f6b-b7ee-e71abd1e4290
Timestamp: 2023-05-02 09:51:24Z, errorUri: https://login.microsoftonline.com/error?code=7000215
	at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.makeErrorFromRequestBody(DefaultHttpClient.java:2221)
	at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.buildResponse(DefaultHttpClient.java:2194)

```

Please could you help , @tchiotludo

**Comment by ashkp29** [comment]
@tchiotludo We are trying to enable login using Azure AD setup (OIDC Configuration) but we are seeing below error in pod logs. 

Error: 
ERROR r-thread-5 o.a.c.ErrorController      Bean of type io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata with name quailfier azuread is disabled. Failed to retrieve OpenID configuration for azuread
io.micronaut.context.exceptions.DisabledBeanException: Bean of type io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata with name quailfier azuread is disabled. Failed to retrieve OpenID configuration for azuread
WARN  r-thread-3 org.akhq.log.access  [Duration: 1204 ms] [Url: GET /oauth/login/azuread] [Status: 500] [Ip: /xx.xx.xx.xx] [User: Anonymous]

Here is the configuration file that we are using.

```
micronaut:
  security:
    enabled: true
    oauth2:
      enabled: true
      clients:
        azuread:
          client-id: "xxxxxxx"
          client-secret: "xxxxxxxx"
          openid:
            issuer: "https://login.microsoftonline.com/xxxxxxxxxx/vx.x/.well-known/openid-configuration"
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: xxxxxxxxxxxxxxx

akhq:
  connections:
    kafka-1:
      properties:
        bootstrap.servers: "kafka:9094"
        security.protocol: ssl
        ssl.truststore.location: /app/truststore.jks
        ssl.truststore.password: xxxxxxx
        ssl.keystore.location: /app/keystore.jks
        ssl.keystore.password: xxxxxxx
        ssl.key.password: xxxxxxx
        ssl.keystore.type: "JKS"
        ssl.endpoint.identification.algorithm: ""

  security:
    default-group: no-roles
    oidc:
      enabled: true
      providers:
        azuread:
          label: "Login with Azure"
          username-field: email
          use-oidc-claim: true
          default-group: no-roles
  clients-defaults:
    consumer:
      properties:
        default.api.timeout.ms: 60000
  ui-options:
    topic-data:
      sort: NEWEST
```
  
@hari819 If Azure OIDC logging worked with 0.23.0, could you please verify what was wrong in our configuration file and assist with the correct one?
