### ISSUE TITLE
Login/logout issues with Keycloak OIDC

### ISSUE THREAD

**Issue by Adman** [tchiotludo/akhq#1485]
Hello, I have two issues when logging in / logging out of akhq using Keycloak.

First of all, my application is located under location `https://<my-domain>/kafka/`
**Login**
After pressing "Login with SSO" button, I'm successfully logged in, the `/kafka/api/me` endpoint correctly returns my username as well as roles. However, `https://<my-domain>/kafka/oauth/callback/keycloak` returns the redirect location to `/kafka/kafka/ui`, which obviously doesn't exist and therefore I'm again redirected to `/kafka/ui/login`. This happens indefinitely. However, if I manually change URL to `/kafka/ui`, I'm logged in and able to browse the application.

**Logout**
Clicking on "logout" button redirects me to `/kafka/logout`, which tries to redirect me to `/kafka/kafka/ui`, which again, doesn't exist and I'm redirected to `/kafka/ui/login`. However, it seems I'm still logged in, because after modifying the URL to `/kafka/ui` (or just `/kafka/`), I get inside the application and `/kafka/api/me` returns email as well as roles.

I'm passing the `MICRONAUT_SECURITY_TOKEN_JWT_SIGNATURES_SECRET_GENERATOR_SECRET` as an environmental variable.

The `kafka/api/me` returns `{"logged":true,"username":"<my-email>","roles":["group","group/read","topic","topic/data","topic/data/read","topic/read"]}`

My config
```yaml
micronaut:
  security:
    enabled: true
    # OIDC authentication configuration
    oauth2:
      enabled: true
      callback-uri: "https://<my-domain>/kafka/oauth/callback/keycloak"
      clients:
        keycloak:
          client-id: <client-id>
          client-secret: <client-secret>
          openid:
            issuer: "<issuer-url>"
            configuration-path: "/.well-known/openid-configuration"
  server:
    context-path: "/kafka"
    host-resolution:
      host-header: Host
      protocol-header: X-Forwarded-Proto

akhq:
  # Auth & Roles (optional)
  security:
    default-group: no-roles # Default groups for all the user even unlogged user
    # Groups definition
    groups:
      no-roles:
        name: no-roles
        roles: [ ]
      topic-reader:
        name: topic-reader
        roles:
          - topic/read
          - topic/data/read
          - group/read

    # OIDC configuration
    oidc:
      enabled: true
      providers:
        keycloak:
          label: "Login with XXXX"
          username-field: preferred_username
          groups-field: roles
          default-group: no-roles
          groups:
            - name: kafka-monitor
              groups:
                - topic-reader
```

I checked some related issues like https://github.com/tchiotludo/akhq/issues/534, https://github.com/tchiotludo/akhq/issues/607 , but nothing helped.

cc @tchiotludo
