### ISSUE TITLE
Helm: Ingress with pathType ImplementationSpecific not working

### ISSUE THREAD

**Issue by cinimins** [tchiotludo/akhq#1508]
Hi,

the ingress in my cluster is not working. It forwards to `/ui` but then outputs `No server is available to handle this request`.

My values.yaml looks like this (I left out tls and cert-manager/acme annotations):

```yaml
ingress:
  enabled: true
  paths:
    - /
  hotsts:
    - my.host
  annotations:
    ncp/http-redirect: "true"
```

When modifying the ingress to use `pathType: Prefix` (instead of `ImplementationSpecific`), it works. My default ingressclass is nsx, but it also doesn't work with nginx.

My current workaround is to deploy my own ingress instead of using the one from the helm chart. Is there a cleaner way?
