### ISSUE TITLE
Github / OAuth2 working but has several bugs

### ISSUE THREAD

**Issue by pavilalopes** [tchiotludo/akhq#1516]
I've successfully got GitHub SSO working, but it's very glitchy:

- Bug 1: even though login succeeds, upon return from the Oauth callback I'm redirected to the login page again. (I can then manually navigate to /ui and am logged in)
- Bug 2: logout doesn't work. I'm redirected to the login page but the JWT cookie is not deleted. I can, again, manually navigate to /ui and see that I'm logged in. I can logout by deleting the cookie in developer tools.

Running version 0.24.0

Relevant configuration bits:
```yaml
micronaut:
  server:
    context-path: "/kafkahq"
    host-resolution:
      host-header: Host
      protocol-header: X-Forwarded-Proto
  security:
    # Use GitHub for SSO
    enabled: true
    oauth2:
      enabled: true
      clients:
        github:
          client-id: "xxx"
          client-secret: "xxx"
          scopes:
            - user:email
            - read:user
          authorization:
            url: https://github.com/login/oauth/authorize
          token:
            url: https://github.com/login/oauth/access_token
            auth-method: client-secret-post

akhq:
  security:
    default-group: no-roles
    oauth2:
      enabled: true
      providers:
        github:
          label: "Login with GitHub"
          username-field: login
          users:
            - username: xxx
              groups: [admin]

  connections:
    # snipped
```
