### ISSUE TITLE
ldap roles

### ISSUE THREAD

**Issue by Rbsn-joses** [tchiotludo/akhq#1529]
hello, I'm trying to implement authentication via ldap, it works, but when I log in, I'm not sent to the page with the topics.

It looks like my configuration is wrong and it's not getting the roles

 my group test:
 cn=admin,ou=groups,dc=example,dc=org
 my user
 uid=user-admin,ou=people,dc=example,dc=org
my group reader only:
cn=akhq,ou=groups,dc=example,dc=org
user only
uid=rodolfo-teste,ou=people,dc=example,dc=org

logs

2023-07-07 16:46:24,611 DEBUG pGroup-1-4 .ApplicationEventPublisher Publishing event: io.micronaut.security.event.TokenValidatedEvent[source=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb2Jzb24tam9zZSIsIm5iZiI6MTY4ODc0ODM4MywiY29ubmVjdHNGaWx0ZXJSZWdleHAiOltdLCJyb2xlcyI6W10sImlzcyI6ImFraHEiLCJleHAiOjE2ODg3NTE5ODMsImlhdCI6MTY4ODc0ODM4MywiY29uc3VtZXJHcm91cHNGaWx0ZXJSZWdleHAiOltdLCJ0b3BpY3NGaWx0ZXJSZWdleHAiOltdfQ.6Pf6FEqvR9v-GkUYA-78l1_bIr64De-VVQV5GUCAvPc]

2023-07-07 16:46:24,612 DEBUG pGroup-1-4 i.m.s.f.SecurityFilter Attributes: sub=>user-admin, nbf=>Fri Jul 07 16:46:23 UTC 2023, connectsFilterRegexp=>[], roles=>[], iss=>akhq, exp=>Fri Jul 07 17:46:23 UTC 2023, iat=>Fri Jul 07 16:46:23 UTC 2023, consumerGroupsFilterRegexp=>[], topicsFilterRegexp=>[] 

2023-07-07T16:46:24.612437489Z 2023-07-07 16:46:24,612 DEBUG pGroup-1-3 .ApplicationEventPublisher Publishing event: io.micronaut.security.event.TokenValidatedEvent[source=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb2Jzb24tam9zZSIsIm5iZiI6MTY4ODc0ODM4MywiY29ubmVjdHNGaWx0ZXJSZWdleHAiOltdLCJyb2xlcyI6W10sImlzcyI6ImFraHEiLCJleHAiOjE2ODg3NTE5ODMsImlhdCI6MTY4ODc0ODM4MywiY29uc3VtZXJHcm91cHNGaWx0ZXJSZWdleHAiOltdLCJ0b3BpY3NGaWx0ZXJSZWdleHAiOltdfQ.6Pf6FEqvR9v-GkUYA-78l1_bIr64De-VVQV5GUCAvPc] 

2023-07-07T16:46:24.613039418Z 2023-07-07 16:46:24,612 DEBUG pGroup-1-4 i.m.s.rules.IpPatternsRule One or more of the IP patterns matched the host address [*******]. Continuing request processing. 

2023-07-07T16:46:24.613066479Z 2023-07-07 16:46:24,612 DEBUG pGroup-1-4 .m.s.r.InterceptUrlMapRule No url map pattern exact match found for path [/ui/static/media/fontawesome-webfont.20fd1704ea223900efa9.woff2] and method [GET]. Searching in patterns with no defined method. 

2023-07-07T16:46:24.613076144Z 2023-07-07 16:46:24,612 DEBUG pGroup-1-3 i.m.s.f.SecurityFilter Attributes: sub=>user-admin
, nbf=>Fri Jul 07 16:46:23 UTC 2023, connectsFilterRegexp=>[], roles=>[], iss=>akhq, exp=>Fri Jul 07 17:46:23 UTC 2023, iat=>Fri Jul 07 16:46:23 UTC 2023, consumerGroupsFilterRegexp=>[], topicsFilterRegexp=>[] 

2023-07-07T16:46:24.613085711Z 2023-07-07 16:46:24,612 DEBUG pGroup-1-4 .m.s.r.InterceptUrlMapRule Url map pattern found for path [/ui/static/media/fontawesome-webfont.20fd1704ea223900efa9.woff2]. Compar
ing roles. 
2023-07-07T16:46:24.613094118Z 2023-07-07 16:46:24,612 DEBUG pGroup-1-4 m.s.r.AbstractSecurityRule The given roles [[isAnonymous(), isAuthenticated()]] matched one or more of the required roles [[isAnonymous()]]. Allowing the request 

2023-07-07T16:46:24.613102667Z 2023-07-07 16:46:24,612 DEBUG pGroup-1-4 i.m.s.f.SecurityFilter Authorized request GET /ui/static/media/fontawesome-webfont.20fd1704ea223900efa9.woff2. The rule provider 
io.micronaut.security.rules.ConfigurationInterceptUrlMapRule authorized the request. 

2023-07-07T16:46:24.613207008Z 2023-07-07 16:46:24,613 DEBUG pGroup-1-3 i.m.s.rules.IpPatternsRule One or more of the IP patterns matched the host address [*******]. Continuing request processing. 

2023-07-07T16:46:24.613690774Z 2023-07-07 16:46:24,613 DEBUG pGroup-1-3 .m.s.r.InterceptUrlMapRule No url map pattern exact match found for path [/ui/ui/static/media/icon.383e5fd93919da4ccf1b1d78c73ab176.svg] and method [GET]. Searching in patterns with no defined method. 
2023-07-07T16:46:24.613761613Z 2023-07-07 16:46:24,613 DEBUG pGroup-1-3 .m.s.r.InterceptUrlMapRule Url map pattern found for path [/ui/ui/static/media/icon.383e5fd93919da4ccf1b1d78c73ab176.svg]. Comparing roles. 

2023-07-07 16:46:24,613 DEBUG pGroup-1-3 m.s.r.AbstractSecurityRule The given roles [[isAnonymous(), isAuthenticated()]] matched one or more of the required roles [[isAnonymous()]]. Allowing the request 

2023-07-07T16:46:24.614022923Z 2023-07-07 16:46:24,613 DEBUG pGroup-1-3 i.m.s.f.SecurityFilter Authorized request GET /ui/ui/static/media/icon.383e5fd93919da4ccf1b1d78c73ab176.svg. The rule provider io.micronaut.security.rules.ConfigurationInterceptUrlMapRule authorized the request.

2023-07-07 16:46:24,614 INFO pGroup-1-3 org.akhq.log.access [Date: 2023-07-07T16:46:24.614142Z] [Duration: 0 ms] [Url: GET /ui/ui/static/media/icon.383e5fd93919da4ccf1b1d78c73ab176.svg] [Status: 200] [Ip: /********] [User: ruser-admin] 

2023-07-07T16:46:24.616476591Z 2023-07-07 16:46:24,616 DEBUG pGroup-1-3 .s.n.RoutingInBoundHandler Response 200 - GET /ui/ui/static/media/icon.383e5fd93919da4ccf1b1d78c73ab176.svg 

2023-07-07T16:46:24.617050376Z 2023-07-07 16:46:24,616 DEBUG pGroup-1-3 .ApplicationEventPublisher Publishing event: io.micronaut.http.context.event.HttpRequestReceivedEvent[source=GET /ui/ui/static/media/icon.383e5fd93919da4ccf1b1d78c73ab176.svg] 

2023-07-07T16:46:24.617073068Z 2023-07-07 16:46:24,616 DEBUG pGroup-1-3 .ApplicationEventPublisher Publishing event: io.micronaut.http.context.event.HttpRequestTerminatedEvent[source=GET /ui/ui/static/media/icon.383e5fd93919da4ccf1b1d78c73ab176.svg]

2023-07-07 16:46:24,617 INFO pGroup-1-4 org.akhq.log.access [Date: 2023-07-07T16:46:24.613452Z] [Duration: 0 ms] [Url: GET /ui/static/media/fontawesome-webfont.20fd1704ea223900efa9.woff2] [Status: 200] [Ip: /********] [User: user-admin]

2023-07-07 16:46:24,623 DEBUG pGroup-1-4 .ApplicationEventPublisher Publishing event: io.micronaut.http.context.event.HttpRequestReceivedEvent[source=GET /ui/static/media/fontawesome-webfont.20fd1704ea223900efa9.woff2] 

2023-07-07T16:46:24.623634449Z 2023-07-07 16:46:24,623 DEBUG pGroup-1-4 .ApplicationEventPublisher Publishing event: io.micronaut.http.context.event.HttpRequestTerminatedEvent[source=GET /ui/static/media/fontawesome-webfont.20fd1704ea223900efa9.woff2]

2023-07-07 16:46:25,784 DEBUG pGroup-1-7 .ApplicationEventPublisher Publishing event: io.micronaut.http.context.event.HttpRequestTerminatedEvent[source=GET /ui/static/js/main.b18c0753.js.map]
2023-07-07 16:46:31,963 DEBUG pGroup-1-8 .s.n.RoutingInBoundHandler Request GET /ui/static/media/logo.ba7c128db2ff905fdb6f.svg

2023-07-07 16:46:31,966 DEBUG pGroup-1-8 .t.r.HttpHeaderTokenReader Looking for bearer token in Authorization header

2023-07-07 16:46:31,966 DEBUG pGroup-1-8 s.t.r.DefaultTokenResolver Request GET, /ui/static/media/logo.ba7c128db2ff905fdb6f.svg, no token found.

2023-07-07 16:46:31,966 DEBUG pGroup-1-8 i.m.s.rules.IpPatternsRule One or more of the IP patterns matched the host address [******]. Continuing request processing.

2023-07-07 16:46:31,967 DEBUG pGroup-1-8 .m.s.r.InterceptUrlMapRule No url map pattern exact match found for path 
[/ui/static/media/logo.ba7c128db2ff905fdb6f.svg] and method [GET]. Searching in patterns with no defined method.

2023-07-07 16:46:31,967 DEBUG pGroup-1-8 .m.s.r.InterceptUrlMapRule Url map pattern found for path [/ui/static/media/logo.ba7c128db2ff905fdb6f.svg]. Comparing roles.

2023-07-07 16:46:31,967 DEBUG pGroup-1-8 m.s.r.AbstractSecurityRule The given roles [[isAnonymous()]] matched one or more of the required roles [[isAnonymous()]]. Allowing the request

2023-07-07 16:46:31,967 DEBUG pGroup-1-8 i.m.s.f.SecurityFilter Authorized request GET /ui/static/media/logo.ba7c128db2ff905fdb6f.svg. The rule provider io.micronaut.security.rules.ConfigurationInterceptUrlMapRule authorized the request.

2023-07-07 16:46:31,968 INFO pGroup-1-8 org.akhq.log.access [Date: 2023-07-07T16:46:31.967811Z] [Duration: 0 ms] [Url: GET /ui/static/media/logo.ba7c128db2ff905fdb6f.svg] [Status: 200] [Ip: /*******] [User: Anonymous]

2023-07-07 16:46:31,976 DEBUG pGroup-1-8 .ApplicationEventPublisher Publishing event: io.micronaut.http.context.event.HttpRequestReceivedEvent[source=GET /ui/static/media/logo.ba7c128db2ff905fdb6f.svg]

2023-07-07 16:46:31,976 DEBUG pGroup-1-8 .ApplicationEventPublisher Publishing event: io.micronaut.http.context.event.HttpRequestTerminatedEvent[source=GET /ui/static/media/logo.ba7c128db2ff905fdb6f.svg]

configuration: 

```yaml
logger:
   levels:
     #root: DEBUG
     org.akhq.configs: TRACE
     io.micronaut: DEBUG
     io.micronaut.security.ldap: TRACE
     io.micronaut.configuration.security: TRACE
     java.security: TRACE
micronaut:
  security:
    enabled: true
    ldap:
      default:
        enabled: true
        context:
          server: 'ldap://localhost:389'
          managerDn: 'cn=admin,dc=example,dc=org'
          managerPassword: 'admin'
        search:
          base: "ou=people,dc=example,dc=org"
          filter: "uid={0}"
        groups:
          enabled: true
          base: "ou=groups,dc=example,dc=org"
        
akhq:
  security:
    ldap:
      groups:
        - name: admin   # This is your active directory group name just the part of the CN
          groups:
            - admin
    roles:
      node-read:
        - resources: [ "NODE" ]
          actions: [ "READ", "READ_CONFIG" ]
      node-admin:
        - resources: [ "NODE" ]
          actions: [ "READ", "READ_CONFIG", "ALTER_CONFIG" ]
      topic-read:
        - resources: [ "TOPIC", "TOPIC_DATA" ]
          actions: [ "READ" ]
        - resources: [ "TOPIC" ]
          actions: [ "READ_CONFIG" ]
      topic-admin:
        - resources: [ "TOPIC", "TOPIC_DATA" ]
          actions: [ "READ", "CREATE", "DELETE" ]
        - resources: [ "TOPIC" ]
          actions: [ "UPDATE", "READ_CONFIG", "ALTER_CONFIG" ]
      connect-rw:
        - resources: [ "CONNECTOR" ]
          actions: [ "READ", "CREATE", "UPDATE_STATE" ]
      connect-admin:
        - resources: [ "CONNECTOR" ]
          actions: [ "READ", "CREATE", "UPDATE_STATE", "DELETE" ]
      registry-read:
        - resources: [ "SCHEMA" ]
          actions: [ "READ" ]
      registry-admin:
        - resources: [ "SCHEMA" ]
          actions: [ "READ", "CREATE", "UPDATE", "DELETE", "DELETE_VERSION" ]
      group-read:
        - resources: [ "CONSUMER_GROUP" ]
          actions: [ "READ" ]
      connect-cluster-read:
        - resources: [ "CONNECT_CLUSTER" ]
          actions: [ "READ" ]
      ksqldb-admin:
        - resources: [ "KSQLDB" ]
          actions: [ "READ", "EXECUTE" ]

    default-group: admin # Default groups for all the user even unlogged user
    # Groups definition
    groups:
      admin:
        - role: node-admin
        - role: topic-admin
        - role: connect-admin
        - role: registry-admin
        - role: group-read
        - role: connect-cluster-read
        - role: ksqldb-admin
      topic-reader:
        - role: topic-read
        - role: registry-admin
      topic-reader-dev:
        - role: topic-read
          clusters: ["dev"]
        - role: registry-admin
          clusters: ["dev"]
      topic-reader-project-prod:
        - role: topic-read
          patterns: ["project.*"]
          clusters: ["prod.*"]
        - role: registry-admin
          patterns: ["project.*"]
          clusters: ["prod.*"]
   
  connections:
    local:
      properties:
        bootstrap.servers: "localhost:9092"
      schema-registry:
        url: "http://localhost:8081"
      connect:
        - name: "connect"
          url: "http://localhost:8083"
      ksqldb:
        - name: "ksqldb"
          url: "http://localhost:8088"
```

![Captura de tela de 2023-07-07 13-55-16](https://github.com/tchiotludo/akhq/assets/67319032/4bdf9ad0-5483-4b0d-b897-41d484fb7b15)
