### ISSUE TITLE
Cannot login when using a custom default-group

### ISSUE THREAD

**Issue by alexissellier** [tchiotludo/akhq#1540]
Hello,

I use the version 0.24.0, and I have this configuration regarding the `security` part

```
  configuration:
    akhq:
      security:
        default-group: extended-reader
        groups:
          extended-reader:
            - role: reader
            - role: consumer-admin  
        roles:
          consumer-admin:
            - resources: ["CONSUMER_GROUP"]
              actions: ["READ", "UPDATE_OFFSET", "DELETE_OFFSET"]
```

But when the default-group is set to `extended-read`, I cannot logged in anymore, having a react error in the browser
```Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops```

Do I miss something ?
