### ISSUE TITLE
No subject alternative names matching, but identification.algorithm set

### ISSUE THREAD

**Issue by autokilla47** [tchiotludo/akhq#1548]
I'm trying to describe the connection AKHQ to schema-registry with this configurations:
```
akhq:
  connections:
    kafka:
      properties:
        bootstrap.servers: "10.10.10.10:9092"
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-256
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret";
        ssl.truststore.location: /app/secrets/kafka.truststore.jks
        ssl.truststore.password: confluent
        ssl.keystore.location: /app/secrets/kafka.keystore.jks
        ssl.keystore.password: confluent
        ssl.key.password: confluent
        ssl.endpoint.identification.algorithm: " "
      schema-registry:
        url: "https://10.10.10.10:8081"
        type: "confluent"
        properties:
          bootstrap.servers: "10.10.10.10:9092"
          ssl.security.protocol: SASL_SSL
          ssl.sasl.mechanism: SCRAM-SHA-256
          #sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret" ssl.endpoint.identification.algorithm=""; <-- try this
          schema.registry.ssl.keystore.location: /app/secrets/kafka.keystore.jks
          schema.registry.ssl.keystore.password: confluent
          schema.registry.ssl.truststore.location: /app/secrets/kafka.truststore.jks
          schema.registry.ssl.truststore.password: confluent
          schema.registry.ssl.key.password: confluent
          ssl.endpoint.identification.algorithm: " " <-- try this
          #kafkastore.ssl.endpoint.identification.algorithm: " " <-- try this
          #schema.registry.kafkastore.ssl.endpoint.identification.algorithm: " " <-- try this
          #schema.registry.ssl.endpoint.identification.algorithm: " " <-- try this
```
Tried several options for **identification.algorithm** but still get the error:
`Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address 10.10.10.10 found
        at java.base/sun.security.util.HostnameChecker.matchIP(Unknown Source)
        at java.base/sun.security.util.HostnameChecker.match(Unknown Source)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
        ... 45 common frames omitted
`
Yes, there is no mention in my certificate of **IP** just hostname. In the config of Kafka and Schema-registry in my docker-compose file I have set **ssl.endpoint.identification.algorithm = " "**.
No problem with connection AKHQ to Kafka.

I can't figure out what I'm doing wrong or what's missing.

Images:
zookeeper: confluentinc/cp-zookeeper:7.0.1
kafka: confluentinc/cp-kafka:7.0.1
schema-registry: confluentinc/cp-schema-registry:7.0.1
akhq: tchiotludo/akhq:0.24.0
