### ISSUE TITLE
Github SSO kept redirecting back to `/ui/login`

### ISSUE THREAD

**Issue by g9yuayon** [tchiotludo/akhq#1551]
I tried to get Github SSO working on the latest dev branch by following the instructions on [akhq.io](https://akhq.io/docs/configuration/authentifications/github.html), and the [guide on guides.microanut.io](https://guides.micronaut.io/latest/micronaut-oauth2-github-gradle-java.html). I could see the login page, but when I clicked on the button "Login with GitHub", Akhq redirected the page back to `/ui/login`. 

Tracing the calls, I could see that `oauth/login/github` got called, and AKHQ server's error controller returned a HTTP 307 with redirect location '/ui/login'. Since the frontend of AKHQ ran on `http://localhost:3000` and the server ran on `http://localhost:8080`. Since I set the variable `REACT_APP_BASE_URL` to the value "http://localhost:8080", the redirected `/ui/login` was expanded to `http://localhost:8080/ui/login`, which resulted in an HTTP 404. 

Since another issue said GitHub SSO did work, could someone help me figure out what I did wrong or how to debug this issue further? 

The configuration on the `micronaut.security` section: 
```
    default-group: no-roles
    oauth2:
      enabled: true
      clients:
        github:
          client-id: "xxx"
          client-secret: "yyy"
          scopes:
            - user:email
            - read:user
            - read:org
          authorization:
            url: https://github.com/login/oauth/authorize
            token:
              url: https://github.com/login/oauth/access_token
              auth-method: client-secret-post
```

The configuration on the `akhq.security`:
```
    oauth2:
      enabled: true
      providers:
        github:
          label: "Login with GitHub"
          username-field: login
          users:
            - username: auser
              groups:
                # the corresponding akhq groups (eg. topic-reader/writer or akhq default groups like admin/reader/no-role)
                - topic-reader
                - topic-writer
```
