### ISSUE TITLE
Application does not show any logs and the container is killed

### ISSUE THREAD

**Issue by marcosschroh** [tchiotludo/akhq#1559]
Thanks for this awesome project. I have an issue/question regarding the deployment into k8s.

I have run the application locally with a docker container and it works fine, however when deploying it with helm and only see:

```bash
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.8.8)


Killed
```

Some context:
- I am running on both cases the same image: `0.24.0`.
- Before the container is restarted I can see that the `application.yml` has the proper  values:

```yaml
akhq:
  connections:
    cluster:
      properties:
        bootstrap.servers: b-1.my-cluster:9094,b-2.my-cluster:9094
        security.protocol: PLAINTEXT
  server:
    access-log:
      enabled: true
      name: org.akhq.log.access
```
- The values.yaml

```yaml
image:
  repository: tchiotludo/akhq
  tag: 0.24.0

networkPolicy:
  enabled: false

logger:
  levels:
    root: DEBUG
    org.akhq.configs: DEBUG
    io.micronaut: DEBUG
    io.micronaut.security.ldap: DEBUG
    io.micronaut.configuration.security: DEBUG
    java.security: DEBUG
    org.akhq: DEBUG
    io.micronaut: DEBUG

ingress:
  enabled: true
  labels:
    app: akhq
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - my-host.com
  paths:
    - /

securityContext:
  runAsUser: 1000

configuration:
  akhq:
    server:
      access-log:
        enabled: true
        name: org.akhq.log.access
    connections:
      cluster:
        properties:
          bootstrap.servers: "b-1.my-cluster:9094,b-2.my-cluster:9094"
          security.protocol: PLAINTEXT

readinessProbe:
  enabled: false

livenessProbe:
  enabled: false
```

If I do not include the `cluster` configuration still I have the same situation, so it seems that the application is not able to start regardless the config. Did I configure the logger properly?

Do you have any ideas what it could be? Thanks
