### ISSUE TITLE
AKHQ UI not loading when topic/*/configs not found "Page Not Found"

### ISSUE THREAD

**Issue by josue-sanchez-wabtec** [tchiotludo/akhq#1560]
Hello @AlexisSouquiere @tchiotludo ,

I am comparing the behavior on akhq:0.24.0 and dev tags related to not having the config section for a specific topic.

0.24.0 test:
I am accessing a topic page but I am getting the "Page not found error" but it is allowing me to load the UI page to check other sections as Data, Partitions, etc.

![image](https://github.com/tchiotludo/akhq/assets/114017629/d57fb9e7-35d9-4885-a0d2-b0ef9e79cc31)

With dev tag I am not able to get this page loaded:

But I am getting more console errors apart from the 404 related to the configs path. Specifically a filter error that could be related to the info fetched to show the UI completelly.
![image](https://github.com/tchiotludo/akhq/assets/114017629/a5a823f4-fded-4d59-a265-6db5ee3c82cc)

I think this ticket could be related https://github.com/tchiotludo/akhq/issues/540. But then makes me also think, was this supported on 0.24.0 and then on dev branch something was changed ?

May you provide me some workaround for this?

I am using this basic configuration:
```
micronaut:
  security:
    enabled: true
akhq.security:
  default-group: no-roles
  basic-auth:
    - username: feature_admin
      password: "<omitted>"
      groups:
      - admin
akhq:
  connections:
    Feature-Internal-All:
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';

    Shared-External:
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';

```
