### ISSUE TITLE
Not mappings custom group/role

### ISSUE THREAD

**Issue by ShulcevVA** [tchiotludo/akhq#1563]
login OK, but AKHQ stays on the login page!

```
micronaut:
  security:
    enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
akhq:
  security:
     roles:
      admins-all:
        - resources: [ "NODE" ]
          actions: [ "READ", "READ_CONFIG", "ALTER_CONFIG" ]
     groups:
      superadmin:
        - role: admins-all
          clusters: [ ".*" ]
          patterns: [ ".*" ]

     basic-auth:
        - username: user # Username
          password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # Password in sha256
          groups: # Groups for the user
            - superadmin

```
But it is works on deault roles admin, reader https://akhq.io/docs/configuration/authentifications/groups.html
Where get name for this  'clusters: [ ".*" ]' ?
I don't understand this 'patterns', 'clusters' and issue https://github.com/tchiotludo/akhq/discussions/1093

**Comment by marcosschroh** [comment]
I am facing the same issue using oauth2 with `AKHQ, 0.24.0`. The login pages shows, then I am redirected to the provider and after login it redirects to the login page again (`ui/login`). 

If I `GET` the endpoint `https:/my-domian/api/me` shows `{"logged":true,"username":"null"}`. I. would. think hat the username mapping is wrong but I have configured to user the `email` (which exist).

Config:

```yaml
# backend authntication
  secrets:
    micronaut:
      security:
        enabled: true
        oauth2:
          enabled: true
          clients:
            oauth2:
              client-id: a-client-id
              client-secret: a-secreet
              scopes:
                - openid
                - profile
                - email
                - nickname
              openid:
                issuer: https://my-domian.org
                configuration-path: /openid/.well-known/openid-configuration/

  configuration:
    akhq:
      server:
          ...
       
      security:
        default-group: no-roles
        enabled: true
        roles:
          topic-reader:
            - resources: [ "TOPIC", "TOPIC_DATA" ]
              actions: [ "READ" ]
            - resources: [ "TOPIC" ]
              actions: [ "READ_CONFIG" ]
        groups:
          topic-reader-pub:
            - role: topic-reader
              patterns: [ "pub.*" ]
        oidc:
          enabled: true
          providers:
            oauth2:
              label: Login with OIDC
              default-group: no-roles
              username-field: email
              users:
                - username: marcos.@blabla.com
                  groups:
                    # the corresponding akhq groups (eg. topic-reader/writer or akhq default groups like admin/reader/no-role)
                    - topic-reader-pub
              groups:
                # the name of the user role set in your oidc provider and associated with your user (eg. in keycloak this would be a client role)
                - name: my_group
                  groups:
                    # the corresponding akhq groups (eg. topic-reader/writer or akhq default groups like admin/reader/no-role)
                    - topic-reader-pub
```

Any ideas?
