### ISSUE TITLE
When producing to topic Schemas List is not Shown

### ISSUE THREAD

**Issue by josue-sanchez-wabtec** [tchiotludo/akhq#1583]
I am trying to produce a topic that need a specific "Value Schema" to be set but I not able to see the list of subjects that I have in my schema registry. It seems so king of error to connect to the schema registry part:
![image](https://github.com/tchiotludo/akhq/assets/114017629/2cb6825b-a2c8-4650-a498-9f481c551efc)

Schema registry:
![image](https://github.com/tchiotludo/akhq/assets/114017629/ff5cce24-a8c8-4619-a9d7-5f23fbc3c5e6)
As you can see I have 7 entries actually but none of these are shown in the search list when trying to produce.

I am not able to see any error doing an inspect or even enabling debugs in the akhq isntance.

May you help me with some clarification about why I am having this error? Thank you in advance.

I am using dev akhq version.

My configuration is something like this:

```
micronaut:
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: <omitted>
  server:
    netty:
      maxHeaderSize: 16384
akhq.security:
  roles:
    node-admin:
      - resources: [ "NODE" ]
        actions: [ "READ", "READ_CONFIG", "ALTER_CONFIG" ]
    topic-admin:
      - resources: [ "TOPIC", "TOPIC_DATA" ]
        actions: [ "READ", "CREATE", "DELETE" ]
      - resources: [ "TOPIC" ]
        actions: [ "UPDATE", "READ_CONFIG", "ALTER_CONFIG" ]
    registry-admin:
      - resources: [ "SCHEMA" ]
        actions: [ "READ", "CREATE", "UPDATE", "DELETE", "DELETE_VERSION" ]
    group-read:
      - resources: [ "CONSUMER_GROUP" ]
        actions: [ "READ" ]
  default-group: no-roles
  basic-auth:
    - username: feature_admin
      password: <omitted>
      groups:
      - admin
    - username: feature_1
      password: <omitted>
      groups:
      - feature-1-group
    - username: feature_2
      password: <omitted>
      groups:
      - feature-2-group
    - username: feature_3
      password: <omitted>
      groups:
      - feature-3-group
    - username: feature_4
      password: <omitted>
      groups:
      - feature-4-group
.
.
.
    - username: feature_122
      password: <omitted>
      groups:
      - feature-122-group
    - username: feature_123
      password: <omitted>
      groups:
      - feature-123-group
    - username: feature_124
      password: <omitted>
      groups:
      - feature-124-group
    - username: feature_125
      password: <omitted>
      groups:
      - feature-125-group
  groups:
    admin:
      - role: node-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-internal-all$", "^shared-external$" ]
      - role: topic-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-internal-all$", "^shared-external$" ]
      - role: registry-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-internal-all$", "^shared-external$" ]
      - role: group-read
        patterns: [ ".*" ]
        clusters: [ "^feature-internal-all$", "^shared-external$" ]
    feature-1-group:
      - role: node-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-1$" ]
      - role: topic-admin
        patterns: [ "topic-feature-us-internal-1-.*" ]
        clusters: [ "^feature-1$" ]
      - role: registry-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-1$" ]
      - role: group-read
        patterns: [ ".*" ]
        clusters: [ "^feature-1$" ]
    feature-2-group:
      - role: node-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-2$" ]
      - role: topic-admin
        patterns: [ "topic-feature-us-internal-2-.*" ]
        clusters: [ "^feature-2$" ]
      - role: registry-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-2$" ]
      - role: group-read
        patterns: [ ".*" ]
        clusters: [ "^feature-2$" ]
    feature-3-group:
      - role: node-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-3$" ]
      - role: topic-admin
        patterns: [ "topic-feature-us-internal-3-.*" ]
        clusters: [ "^feature-3$" ]
      - role: registry-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-3$" ]
      - role: group-read
        patterns: [ ".*" ]
        clusters: [ "^feature-3$" ]
    feature-4-group:
      - role: node-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-4$" ]
      - role: topic-admin
        patterns: [ "topic-feature-us-internal-4-.*" ]
        clusters: [ "^feature-4$" ]
      - role: registry-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-4$" ]
      - role: group-read
        patterns: [ ".*" ]
        clusters: [ "^feature-4$" ]


...

    feature-122-group:
      - role: node-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-122$" ]
      - role: topic-admin
        patterns: [ "topic-feature-us-internal-122-.*" ]
        clusters: [ "^feature-122$" ]
      - role: registry-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-122$" ]
      - role: group-read
        patterns: [ ".*" ]
        clusters: [ "^feature-122$" ]
    feature-123-group:
      - role: node-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-123$" ]
      - role: topic-admin
        patterns: [ "topic-feature-us-internal-123-.*" ]
        clusters: [ "^feature-123$" ]
      - role: registry-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-123$" ]
      - role: group-read
        patterns: [ ".*" ]
        clusters: [ "^feature-123$" ]
    feature-124-group:
      - role: node-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-124$" ]
      - role: topic-admin
        patterns: [ "topic-feature-us-internal-124-.*" ]
        clusters: [ "^feature-124$" ]
      - role: registry-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-124$" ]
      - role: group-read
        patterns: [ ".*" ]
        clusters: [ "^feature-124$" ]
    feature-125-group:
      - role: node-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-125$" ]
      - role: topic-admin
        patterns: [ "topic-feature-us-internal-125-.*" ]
        clusters: [ "^feature-125$" ]
      - role: registry-admin
        patterns: [ ".*" ]
        clusters: [ "^feature-125$" ]
      - role: group-read
        patterns: [ ".*" ]
        clusters: [ "^feature-125$" ]

akhq:
  connections:
    Feature-Internal-All:
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
    
    Shared-External:
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';


    Feature-1:
      schema-registry:
        url: https://feature-1.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
      

    Feature-2:
      schema-registry:
        url: https://feature-2.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
      

    Feature-3:
      schema-registry:
        url: https://feature-3.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
      

    Feature-4:
      schema-registry:
        url: https://feature-4.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';

...

    Feature-112:
      schema-registry:
        url: https://feature-112.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
      

    Feature-113:
      schema-registry:
        url: https://feature-113.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
      

    Feature-114:
      schema-registry:
        url: https://feature-114.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
      

    Feature-115:
      schema-registry:
        url: https://feature-115.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
      

    Feature-116:
      schema-registry:
        url: https://feature-116.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
      

    Feature-117:
      schema-registry:
        url: https://feature-117.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
      

    Feature-118:
      schema-registry:
        url: https://feature-118.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
      

    Feature-119:
      schema-registry:
        url: https://feature-119.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
      

    Feature-120:
      schema-registry:
        url: https://feature-120.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
      

    Feature-121:
      schema-registry:
        url: https://feature-121.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
      

    Feature-122:
      schema-registry:
        url: https://feature-122.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
      

    Feature-123:
      schema-registry:
        url: https://feature-123.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
      

    Feature-124:
      schema-registry:
        url: https://feature-124.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
      

    Feature-125:
      schema-registry:
        url: https://feature-125.<omitted>:443/schema-registry
        type: confluent
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<OMITTED>' password='<omitted>';
```

**Comment by tchiotludo** [comment]
Do you have any error on the server log and on the chrome console?

**Comment by josue-sanchez-wabtec** [comment]
![image](https://github.com/tchiotludo/akhq/assets/114017629/2c848d86-5095-4567-8f68-cf2276d20c4f)

So when I have this situation I am getting:

![image](https://github.com/tchiotludo/akhq/assets/114017629/41101f2c-5f95-4be2-8c67-73daa2226ab6)

I think this is not conclusive. On logs I am not getting any error, or bad http code or anything I can say like that.

This are avro messages messages, I am not sure if there is something related to this.

**Comment by josue-sanchez-wabtec** [comment]
I when into my schema registry section and saw some warnings:

`│ 2023-09-22 20:18:28,753 DEBUG pGroup-1-3 .t.r.HttpHeaderTokenReader Looking for bearer token in Authorization header                                                                                               │
│ 2023-09-22 20:18:28,753 DEBUG pGroup-1-3 s.t.r.DefaultTokenResolver Token eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZWF0dXJlXzE1IiwibmJmIjoxNjk1NDEyODk1LCJyb2xlcyI6WyJpc0F1dGhlbnRpY2F0ZWQoKSJdLCJpc3MiOiJha2hxIiwiZ3JvdXB │
│ zIjp7ImZlYXR1cmUtMTUtZ3JvdXAiOlt7InJvbGUiOiJub2RlLWFkbWluIiwicGF0dGVybnMiOlsiLioiXSwiY2x1c3RlcnMiOlsiXmZlYXR1cmUtMTUkIl19LHsicm9sZSI6InRvcGljLWFkbWluIiwicGF0dGVybnMiOlsicGRzMi1mZWF0dXJlLXVzLWludGVybmFsLTE1LS4qI │
│ l0sImNsdXN0ZXJzIjpbIl5mZWF0dXJlLTE1JCJdfSx7InJvbGUiOiJyZWdpc3RyeS1hZG1pbiIsInBhdHRlcm5zIjpbIi4qIl0sImNsdXN0ZXJzIjpbIl5mZWF0dXJlLTE1JCJdfSx7InJvbGUiOiJncm91cC1yZWFkIiwicGF0dGVybnMiOlsiLioiXSwiY2x1c3RlcnMiOlsiXmZ │
│ lYXR1cmUtMTUkIl19XX0sImV4cCI6MTY5NTQxNjQ5NSwiaWF0IjoxNjk1NDEyODk1fQ.mce4aBILGkK5id2qw4djDc484bUenEnPJauGPCOaACM found in request GET /api/feature-15/schema                                                        │
│ 2023-09-22 20:18:28,753 DEBUG pGroup-1-3 i.m.s.t.j.v.JwtValidator   Validating signed JWT                                                                                                                          │
│ 2023-09-22 20:18:28,754 DEBUG pGroup-1-3 i.m.s.f.SecurityFilter     Attributes: sub=>feature_15, nbf=>Fri Sep 22 20:01:35 UTC 2023, roles=>[isAuthenticated()], iss=>akhq, groups=>{feature-15-group=[{role=node-a │
│ dmin, patterns=[.*], clusters=[^feature-15$]}, {role=topic-admin, patterns=[pds2-feature-us-internal-15-.*], clusters=[^feature-15$]}, {role=registry-admin, patterns=[.*], clusters=[^feature-15$]}, {role=group- │
│ read, patterns=[.*], clusters=[^feature-15$]}]}, exp=>Fri Sep 22 21:01:35 UTC 2023, iat=>Fri Sep 22 20:01:35 UTC 2023                                                                                              │
│ 2023-09-22 20:18:28,755 DEBUG pGroup-1-3 i.m.s.f.SecurityFilter     Authorized request GET /api/feature-15/schema. The rule provider org.akhq.security.rule.AKHQSecurityRule authorized the request.               │
│ 2023-09-22 20:18:28,946 WARN  -thread-23 org.apache.avro.Schema     Ignored the <omitted>.<omitted>.id.logicalType property ("uuid"). It should probably be nested ins │
│ ide the "type" for the field.                                                                                                                                                                                      │
│ 2023-09-22 20:18:29,003 WARN  -thread-23 org.apache.avro.Schema     Ignored the <omitted>.<omitted>.id.logicalType property ("uuid"). It should probably be nested ins │
│ ide the "type" for the field.                                                                                                                                                                                      │
│ 2023-09-22 20:18:29,003 INFO  -thread-14 org.akhq.log.access        [Date: 2023-09-22T20:18:28.755653Z] [Duration: 247 ms] [Url: GET /api/feature-15/schema] [Status: 200] [Ip: /127.0.0.1] [User: feature_15]     │
│ 2023-09-22 20:18:48,701 DEBUG pGroup-1-4 .t.r.HttpHeaderTokenReader Looking for bearer token in Authorization header                                                                                               │
│ 2023-09-22 20:18:48,701 DEBUG pGroup-1-3 .t.r.HttpHeaderTokenReader Looking for bearer token in Authorization header                                                                                               │
│ 2023-09-22 20:18:48,701 DEBUG pGroup-1-4 s.t.r.DefaultTokenResolver Request GET, /health, no token found.                                                                                                          │
│ 2023-09-22 20:18:48,701 DEBUG pGroup-1-3 s.t.r.DefaultTokenResolver Request GET, /health, no token found.                                                                                                          │
│ 2023-09-22 20:18:48,701 DEBUG pGroup-1-4 i.m.s.rules.IpPatternsRule One or more of the IP patterns matched the host address [10.92.112.100]. Continuing request processing.                                        │
│ 2023-09-22 20:18:48,701 DEBUG pGroup-1-3 i.m.s.rules.IpPatternsRule One or more of the IP patterns matched the host address [10.92.112.100]. Continuing request processing.                                        │
│ 2023-09-22 20:18:48,701 DEBUG pGroup-1-3 .m.s.r.InterceptUrlMapRule No url map pattern exact match found for path [/health] and method [GET]. Searching in patterns with no defined method.                        │
│ 2023-09-22 20:18:48,701 DEBUG pGroup-1-4 .m.s.r.InterceptUrlMapRule No url map pattern exact match found for path [/health] and method [GET]. Searching in patterns with no defined method.                        │
│ 2023-09-22 20:18:48,701 DEBUG pGroup-1-3 .m.s.r.InterceptUrlMapRule No url map pattern match found for path [/health]. Returning unknown.                                                                          │
│ 2023-09-22 20:18:48,701 DEBUG pGroup-1-4 .m.s.r.InterceptUrlMapRule No url map pattern match found for path [/health]. Returning unknown.                                                                          │
│ 2023-09-22 20:18:48,701 DEBUG pGroup-1-3 .s.r.SensitiveEndpointRule health endpoint is not sensitive. Allowing the request.                                                                                        │
│ 2023-09-22 20:18:48,702 DEBUG pGroup-1-3 i.m.s.f.SecurityFilter     Authorized request GET /health. The rule provider io.micronaut.security.rules.SensitiveEndpointRule authorized the request.                    │
│ 2023-09-22 20:18:48,702 DEBUG pGroup-1-4 .s.r.SensitiveEndpointRule health endpoint is not sensitive. Allowing the request.                                                                                        │
│ 2023-09-22 20:18:48,702 DEBUG pGroup-1-4 i.m.s.f.SecurityFilter     Authorized request GET /health. The rule provider io.micronaut.security.rules.SensitiveEndpointRule authorized the request.`

**Comment by josue-sanchez-wabtec** [comment]
I want to add more info as I am testing now with a simple akhq config file

```
micronaut:
  security:
    enabled: true
akhq.security:
  default-group: no-roles
  basic-auth:
    - username: feature_admin
      password: "<omitted>"
      groups:
      - admin
akhq:
  connections:
    Feature-Internal:
      schema-registry:
        url: "https://<omitted>:443/schema-registry"
        type: "confluent"
        basic-auth-username: <omitted>
        basic-auth-password: <omitted>
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<omitted>' password='<omitted>';
    Shared-External:
      ui-options:
        topic-data:
          sort: NEWEST
      properties:
        bootstrap.servers: <omitted>
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<omitted>' password='<omitted>';

```

I can see still the error associated to topics in which the schema values is set.

With akhq:0.24.0:
 
 
![image](https://github.com/tchiotludo/akhq/assets/114017629/a907d15d-f9d0-4369-a1a8-76ad1ec0f0d5)

When I clic the copy icon:
![image](https://github.com/tchiotludo/akhq/assets/114017629/b032fe4d-28d7-4805-ba5d-8cffd49544ad)

I can see the "Value Schema" box shows me a list of the schema registry subjects:
![image](https://github.com/tchiotludo/akhq/assets/114017629/4847aa46-5015-48a8-be0c-b8286d008bd4)

These are the logs since I see the topic entry with the schema value set and then I press the copy icon and clic into the "Value Schema list":

<img width="1493" alt="image" src="https://github.com/tchiotludo/akhq/assets/114017629/a7f83cca-1c38-4998-8ced-f6c561f787a9">

Consoles Logs:
![image](https://github.com/tchiotludo/akhq/assets/114017629/6206cd2b-78ba-45fa-839f-72e2649242d8)


Now, just if I change the version to the dev latest one (akhq:dev) I am not able to see the schema registry subject list:

![image](https://github.com/tchiotludo/akhq/assets/114017629/94d151d1-35f0-483d-a7bc-cb27814e183f)


Logs:
<img width="1487" alt="image" src="https://github.com/tchiotludo/akhq/assets/114017629/cc98e6dd-feed-4fb7-8b89-0895a68d3004">

Console Logs:
![image](https://github.com/tchiotludo/akhq/assets/114017629/0f9d4036-f4f7-449e-b62c-2e4cc4488f92)
