### ISSUE TITLE
LDAP: Set LDAP user session expirey in Helm deploy

### ISSUE THREAD

**Issue by Robbie558** [tchiotludo/akhq#1596]
We are currently running v0.18 in our K8s cluster, and authenticate using LDAP.  

We wish to extend the default session expiry for users connecting with LDAP, but cant find documentation relating to this. I can see that this has been discussed generally before in [Issue 157](https://github.com/tchiotludo/akhq/issues/157), and can also see from  [Issue 80](https://github.com/tchiotludo/akhq/issues/80) that this is configurable whilst using the JWT authorisation model.

**Comment by AlexisSouquiere** [comment]
If you want to increase the default 1h expiration time for the JWT token, you can check https://micronaut-projects.github.io/micronaut-security/latest/guide/#jwtGenerator. I think the `micronaut.security.token.generator.access-token.expiration` parameter is what you are looking for

**Comment by Robbie558** [comment]
Thanks @AlexisSouquiere, 

I have implemented this in our ConfigMap alongside our LDAP configuration, but it does not appear to have affected the JWT token expiration (I am on BST and just logged in):

![image](https://github.com/tchiotludo/akhq/assets/69847427/50c6e908-6080-48c9-b5b6-469bcb2bf56e)

An extract from the ConfigMap after the change is as follows:
```
Data
====
AKHQ_CONFIGURATION:
----
micronaut:
  security:
    ldap:
      default:
        enabled: true
        context:
          server: <server>
          managerDn: <dn>
          managerPassword: <password>
        search:
          filter: '(sAMAccountName={0})'
          base: <base>
        groups:
          enabled: true
          filter: "(member={0})"
          base: <base>
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    token:
      generator:
        access-token:
          expiration: 7200
```
