### ISSUE TITLE
External roles and attributes mapping breaking if patterns are too long

### ISSUE THREAD

**Issue by mat-patrickschmelter** [tchiotludo/akhq#1621]
Hello there,

after successfully implementing and testing an external roles and attributes mapper for the new AKHQ dev version on a small Kafka cluster with little permissions, we tried to deploy the config to our production cluster.

There, it immediately broke and did not give us any error messages.

After some investigation we found out, that if we lower the amount of characters inside the patterns in the response of the role mapper, we could successfully log back in. Changing order or exchanging patterns for others did nothing, until we added back in character by character of a next pattern.

At some point it just stopped working completely.

We noticed that the point of breaking is close to 6000 characters in the response of /auth/me

Role Mapper response:
```
const generateResponse = (pattern) => {
    const responseBody = {
        "groups": {
            "default": [
                {
                    "role": "default",
                    "patterns": pattern, // ["topic1", "topic2", "topic3", ...]
                    "clusters": [
                        ".*"
                    ]
                }
            ]
        }
    };

    return {
        statusCode: 200,
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(responseBody)
    };
};
```

AKHQ config:
```
akhq:
  security:
    default-group: no-roles
    rest:
      enabled: true
      url: "__role_mapper_uri__"
    roles:
      default:
      - actions: [ "READ" ]
        resources: [ "TOPIC", "TOPIC_DATA", "CONSUMER_GROUP", "CONNECT_CLUSTER", "CONNECTOR", "SCHEMA", "NODE", "ACL", "KSQLDB" ]
      - actions: [ "READ_CONFIG" ]
        resources: [ "TOPIC", "NODE" ]
```

/auth/me response before breaking:
```
{
    "logged": true,
    "username": "my@mail.com",
    "roles": [
        {
            "resources": [
                "TOPIC",
                "TOPIC_DATA",
                "CONSUMER_GROUP",
                "CONNECT_CLUSTER",
                "CONNECTOR",
                "SCHEMA",
                "NODE",
                "ACL",
                "KSQLDB"
            ],
            "actions": [
                "READ"
            ],
            "patterns": [
                "topic1",
                "topic2",
                "topic3",
                ...
            ],
            "clusters": [
                ".*"
            ]
        },
        {
            "resources": [
                "TOPIC",
                "NODE"
            ],
            "actions": [
                "READ_CONFIG"
            ],
            "patterns": [
                "topic1",
                "topic2",
                "topic3",
                ...
            ],
            "clusters": [
                ".*"
            ]
        }
    ]
}
```

/auth/me response after breaking:
```
{"logged":false}
```

AKHQ logs
```
stay silent
```

**Comment by AlexisSouquiere** [comment]
@mat-patrickschmelter the default Micronaut configuration in AKHQ uses a cookie to store the JWT token. By doing that token must be < 4Kk. I think your token is bigger so you should change the `micronaut.security.authentication` setting to `bearer` instead of `cookie` and maybe increase also the netty max header size (`micronaut.server.netty.maxHeaderSize to a greater` to 16384 - default is 8Kb)

**Comment by mat-patrickschmelter** [comment]
@AlexisSouquiere unfortunately after changing the `micronaut.security.authentication` to `bearer`, the external role mapper no longer gets called

**Comment by AlexisSouquiere** [comment]
Can you please put your `akhq.security`, `micronaut.*` parts of your application.yml ?

**Comment by mat-patrickschmelter** [comment]
```
micronaut:
  server:
    port: 5000
    access-log:
      enabled: true
      name: org.akhq.log.access
    netty:
      max-header-size: 16384
  security:
    enabled: true
    callback-uri: "https://akhq.url/oauth/callback/oidc"
    oauth2:
      enabled: true
      clients:
        oidc:
          client-id: "akhq-client"
          client-secret: __secret__
          openid:
            issuer: "__keycloak_url__"
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: __secret__
              jws-algorithm: HS256
akhq:
  security:
    default-group: no-roles
    rest:
      enabled: true
      url: "__role_mapper_endpoint__"
    oidc:
      enabled: true
      providers:
        oidc:
          label: "Login"
          username-field: email
          groups-field: roles
          default-group: default
    roles:
      default:
      - actions: [ "READ" ]
        resources: [ "TOPIC", "TOPIC_DATA", "CONSUMER_GROUP", "CONNECT_CLUSTER", "CONNECTOR", "SCHEMA", "NODE", "ACL", "KSQLDB" ]
      - actions: [ "READ_CONFIG" ]
        resources: [ "TOPIC", "NODE" ]
```
