### ISSUE TITLE
Unable to Login to AKHQ Using OIDC (Okta)

### ISSUE THREAD

**Issue by pdpxy** [tchiotludo/akhq#1679]
Hello!

Was hoping you can help and apologies in advance if I'm missing something obvious.
I have AKHQ setup and we're trying to integrate it with Okta for access and authentication.

When I try to go to AKHQ, I am properly redirected to the Issuer Provider page, and when I try to authenticate, I get a "failed" response and when I check the AKHQ logs, I get the following:
`WARN pGroup-1-1 u.LoginFailedEventListener Login failed reason CUSTOM, username unknown, message Exception during Authentication: use-oidc-claim config requires attribute roles in the OIDC claim`

In my configuration, here's what I placed (I only pasted the security block from micronaut and akhq):

``` yaml
micronaut:
    security:
      enabled: true
      # Okta authentication configuration
      authentication: idtoken
      oauth2:
        enabled: true
        clients:
          okta:
            client-id: <MY_CLIENT_ID>
            client-secret: <MY_CLIENT_SECRET>
            openid:
              issuer: <ISSUER>
            scopes:
              - profile
              - email
              - openid
      endpoints:
        logout:
            get-allowed: true

security:
      roles:
        node-read:
          - resources: [ "NODE" ]
            actions: [ "READ", "READ_CONFIG" ]
        node-admin:
          - resources: [ "NODE" ]
            actions: [ "READ", "READ_CONFIG", "ALTER_CONFIG" ]
        topic-read:
          - resources: [ "TOPIC", "TOPIC_DATA" ]
            actions: [ "READ" ]
          - resources: [ "TOPIC" ]
            actions: [ "READ_CONFIG" ]
        topic-admin:
          - resources: [ "TOPIC", "TOPIC_DATA" ]
            actions: [ "READ", "CREATE", "DELETE" ]
          - resources: [ "TOPIC" ]
            actions: [ "UPDATE", "READ_CONFIG", "ALTER_CONFIG" ]
        registry-read:
          - resources: [ "SCHEMA" ]
            actions: [ "READ" ]
        registry-admin:
          - resources: [ "SCHEMA" ]
            actions: [ "READ", "CREATE", "UPDATE", "DELETE", "DELETE_VERSION" ]
        group-read:
          - resources: [ "CONSUMER_GROUP" ]
            actions: [ "READ" ]
        group-admin:
          - resources: [ "CONSUMER_GROUP" ]
            actions: [ "READ", "UPDATE_OFFSET", "DELETE_OFFSET" ]
      # Groups definition
      groups:
        admin:
          - role: node-admin
          - role: topic-admin
          - role: registry-admin
          - role: group-admin
        topic-reader:
          - role: node-read
          - role: topic-read
          - role: registry-read
          - role: group-read
        consumer-group-editor:
          - role: node-read
          - role: topic-read
          - role: registry-read
          - role: group-admin
      # OIDC
      oidc:
        enabled: true
        providers:
          okta:
            label: "Login with Okta"
            username-field: preferred_username
            groups-field: roles
            default-group: topic-reader
            use-oidc-claim: true
```

Hoping you guys can help.
Thanks!
