### ISSUE TITLE
[Helm] Indentation error with multiple `ImagePullSecrets`

### ISSUE THREAD

**Issue by kmarilleau** [tchiotludo/akhq#1680]
Hi,

My team found the following error on the helm chart [deployment template](https://github.com/tchiotludo/akhq/blob/dev/helm/akhq/templates/deployment.yaml#L44):

Example of a values with a list of `imagePullSecrets`:
```yaml
  - name: foo-pull-secret
  - name: bar-pull-secret
```

Expected result:
```yaml
    [...]
    spec:
      imagePullSecrets:
        - name: foo-pull-secret
        - name: bar-pull-secret
    [...]
```

Got:
```yaml
    [...]
    spec:
      imagePullSecrets:
                - name: foo-pull-secret
        - name: bar-pull-secret
    [...]
```

You should replace this:
```yaml
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | indent 8 }}
```

By:
```yaml
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
```
