### ISSUE TITLE
OIDC login with keycloak doesn't work!

### ISSUE THREAD

**Issue by mokhos** [tchiotludo/akhq#1715]
Hi, I'm sorry if the issue may be repetitive to open, but I couldn't find a sample template for enabling OIDC login with keycloak.

I went through different issues like https://github.com/tchiotludo/akhq/issues/1631#issuecomment-1851884337 and https://github.com/tchiotludo/akhq/issues/1666, but still not able to make this to work. 

I'm using `0.24.0` version.

Here is my application-secrets.yaml:

```
  application-secrets.yml: |-
    akhq:
      [CONNECTION_CONFIG]
      security:
        default-group: no-roles
        basic-auth:
          - username: reader
            password: "reader"
            groups: 
            - reader
        oidc:
          enabled: true
          providers:
            oidc:
              label: "Login with Keycloak"
              username-field: preferred_username
              default-group: no-roles
              use-oidc-claim: true
    micronaut:
      security:
        enabled: true
        default-group: no-roles
        callback-uri: "https://akhq-url/oauth/callback/oidc"
        oauth2:
          enabled: true
          clients:
            oidc:
              grant-type: password
              client-id: "akhq"
              client-secret: "apG52xxxxxpIPJ"
              openid:
                issuer: https://keycloak-url/realms/test
                configuration-path: "/.well-known/openid-configuration"
        token:
          jwt:
            signatures:
              secret:
                generator:
                  secret: "SOME_SECRET"
```

Here is how the logs look like: https://pastebin.com/JHNv9XJS

There is no erros or warning or such. When I click on the `login with keycloak` button, nothing happens.

It would be appreciated, if someone could check my config and tell me what am I missing!

Thanks in advance.

**Comment by mokhos** [comment]
I managed to change some configs and the login request now goes to keycloak, I put my username and password and it just returns to the login page! I paste once again my config and the logs for anyone that could maybe take a look.

application-secrets.yaml:
```
  security:
    default-group: no-roles
    basic-auth:
      - username: reader
        password: "5e88489xxxxxx2a11ef721d1542d8"
        groups: 
        - reader
    oidc:
      enabled: true
      providers:
        oidc:
          label: "Login with Keycloak"
          username-field: preferred_username
          default-group: default
micronaut:
  security:
    enabled: true
    default-group: no-roles
    callback-uri: "https://akhq.url/oauth/callback/oidc"
    redirect:
      login-success: "/ui"
    oauth2:
      enabled: true
      clients:
        oidc:
          client-id: "akhq"
          client-secret: "SOMESECRET"
          openid:
            issuer: https://keycloak.url/realms/test

    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "SOMESECRET"
```

The new logs: https://pastebin.com/qmYHtZdD

**Comment by vasili439** [comment]
I managed to make it work with:
```
application-secrets.yaml:
micronaut:
  security:
    enabled: true
    oauth2:
      enabled: true
      clients:
        oidc:
          client-id: "akhq"
          client-secret: "blablaKEY"
          openid:
            issuer: https://keycloak.domain.com/realms/my-realm
akhq:
  connections:
    kafka1:
      properties:
        bootstrap.servers: "kafka-0.domain.com:9092,kafka-1.domain.com:9092,kafka-2.domain.com:9092"
        sasl.mechanism: PLAIN
        security.protocol: SASL_PLAINTEXT
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username=kafka password="kafka_password";
      schema-registry:
        url: "http://schem-reg.domain.com:8081"
        type: "confluent"                                                                            
        basic-auth-username: "admin"                                                                 
        basic-auth-password: "SR_PASS"                                              

and helm values:

    existingSecrets: akhq-connections
    configuration:
      akhq:
        server:
          access-log:
            enabled: true
            name: org.akhq.log.access
        security:
          default-group: group1
          groups:
            group1:
              name: group1
              roles:
                - node/read
            group2:
              name: group2
              roles:
                - topic/read
                - topic/insert
......
          oidc:
            enabled: true
            providers:
              oidc:
                label: "Login with Keycloak"
                username-field: preferred_username
                groups-field: roles
                default-group: group1

                groups:
                - name: group2
                  groups:
                    - KC_group2
```

**Comment by mokhos** [comment]
@vasili439 so you don't have this redirect to login page problem? because the only difference between your and my config is the group definition, but that should not affect on the redirect thing. I suspected this has maybe something to do with https://github.com/tchiotludo/akhq/discussions/1297

**Comment by vasili439** [comment]
> @vasili439 so you don't have this redirect to login page problem? because the only difference between your and my config is the group definition, but that should not affect on the redirect thing. I suspected this has maybe something to do with #1297

no. everything works as expected

**Comment by alwibrm** [comment]
@mokhos This is the typical behaviour when you have insufficient permissions for AKHQ.

**Comment by mokhos** [comment]
> @mokhos This is the typical behaviour when you have insufficient permissions for AKHQ.

Thanks for your reply. What are you suggesting? Do I need to change the default group from `no-roles` to some defined roles?

**Comment by mokhos** [comment]
> @mokhos That depends on your desired permission model (roles & groups). For testing purposes you could try the default group "reader". But keep in mind that anyone will have read access without any restrictions on clusters.

I have added now this default configuration https://akhq.io/docs/configuration/authentifications/oidc.html#oidc, but still redirect happens! I defined one role for test in keycloak, but I'm not sure if that's correct. maybe a tip here?

**Comment by alwibrm** [comment]
@mokhos Maybe it's easier when you first try to check the permissions without any keycloak mapping by defining and assigning a default role. When you get this working you can link it to a group/role in Keycloak. You get redirected if your permissions are not sufficient.

**Comment by mokhos** [comment]
@alwibrm Thanks for the tip!

I finally managed to solve the problem and this is my configuration for others in the future:

```
    akhq:
      security:
        default-group: no-roles # Default groups for all the user even unlogged user
        # Groups definition
        groups:
          no-roles:
            name: no-roles
            roles: [ ]
          topic-reader:
            name: topic-reader
            roles:
              - topic/read
              - topic/data/read
              - group/read
          admin:
            name: admin
            roles:
              - topic/read
              - topic/insert
              - topic/delete
              - topic/config/update
              - node/read
              - node/config/update
              - topic/data/read
              - topic/data/insert
              - topic/data/delete
              - group/read
              - group/delete
              - group/offsets/update
              - registry/read
              - registry/insert
              - registry/update
              - registry/delete
              - registry/version/delete
              - acls/read
              - connect/read
              - connect/insert
              - connect/update
              - connect/delete
              - connect/state/update
        basic-auth:
          - username: reader
            password: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
            groups: 
            - reader
        oidc:
          enabled: true
          providers:
            oidc:
              label: "Login with Keycloak"
              username-field: preferred_username
              groups-field: roles
              default-group: topic-reader
              groups:
                # the name of the user role set in your oidc provider and associated with your user (eg. in keycloak this would be a client role)
                - name: topic-reader
                  groups:
                    # the corresponding akhq groups (eg. topic-reader/writer or akhq default groups like admin/reader/no-role)
                    - topic-reader
                - name: topic-writer
                  groups:
                    - admin
              users:
                - username: akhq_admin
                  groups:
                    - admin
```

So don't let the similar names confuse you. The groups defined under `akhq.security.groups` belong to akhq. You can name them differently. The ones defined under `akhq.security.oidc.providers.oidc.groups` belong to the OIDC provider which then need to interconnect to AKHQ's group!(read the comments)
