### ISSUE TITLE
Continuous Login Page Redirection Issue in AKHQ with Basic Auth Correct Credentials

### ISSUE THREAD

**Issue by venkateswarlu-vajrala-fs-vv** [tchiotludo/akhq#1777]
I'm encountering an issue while attempting to log in to AKHQ using the credentials I generated. Every time I try to log in, it continuously redirects me back to the login page.

Even after inputting the correct credentials, I'm still redirected to the login page.

The response from /api/me is as follows:
```json
{
  "logged": true,
  "username": "admin"
}

```
Docker image name: tchiotludo/akhq

Configuration
```yaml
    micronaut:
      security:
        enabled: true
        token:
          jwt:
            signatures:
              secret:
                generator:
                  secret: ""
    akhq:
      security:
        roles:
          node-read:
            - resources: [ "NODE" ]
              actions: [ "READ", "READ_CONFIG" ]
          node-admin:
            - resources: [ "NODE" ]
              actions: [ "READ", "READ_CONFIG", "ALTER_CONFIG" ]
          topic-read:
            - resources: [ "TOPIC", "TOPIC_DATA" ]
              actions: [ "READ" ]
            - resources: [ "TOPIC" ]
              actions: [ "READ_CONFIG" ]
          topic-admin:
            - resources: [ "TOPIC", "TOPIC_DATA" ]
              actions: [ "READ", "CREATE", "DELETE" ]
            - resources: [ "TOPIC" ]
              actions: [ "UPDATE", "READ_CONFIG", "ALTER_CONFIG" ]
          connect-rw:
            - resources: [ "CONNECTOR" ]
              actions: [ "READ", "CREATE", "UPDATE_STATE" ]
          connect-admin:
            - resources: [ "CONNECTOR" ]
              actions: [ "READ", "CREATE", "UPDATE_STATE", "DELETE" ]
          registry-read:
            - resources: [ "SCHEMA" ]
              actions: [ "READ" ]
          registry-admin:
            - resources: [ "SCHEMA" ]
              actions: [ "READ", "CREATE", "UPDATE", "DELETE", "DELETE_VERSION" ]
          group-read:
            - resources: [ "CONSUMER_GROUP" ]
              actions: [ "READ" ]
          connect-cluster-read:
            - resources: [ "CONNECT_CLUSTER" ]
              actions: [ "READ" ]
          ksqldb-admin:
            - resources: [ "KSQLDB" ]
              actions: [ "READ", "EXECUTE" ]
        default-group: noroles
        groups:
          admin:
            - role: node-admin
            - role: topic-admin
            - role: connect-admin
            - role: registry-admin
            - role: group-read
            - role: connect-cluster-read
            - role: ksqldb-admin
          reader:
            - role: topic-read
            - role: registry-admin
          noroles: []
        basic-auth:
          - username: admin
            password: ""
            passwordHash: SHA256
            groups:
              - admin
          - username: reader
            password: ""
            passwordHash: SHA256
            groups:
              - reader
      connections:
        docker-kafka-server:
          properties:
            bootstrap.servers: ""
            security.protocol: SASL_SSL
            sasl.mechanism: AWS_MSK_IAM
            sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required awsDebugCreds=true;
            sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
            ssl.truststore.location: ${JAVA_HOME}/lib/security/cacerts
            ssl.truststore.password: changeit
```
