### ISSUE TITLE
Anonymous user has no role and always redirect to login page. [0.25.0]

### ISSUE THREAD

**Issue by jinseok-k** [tchiotludo/akhq#1786]
I have upgraded akhq from 0.24.0 to 0.25.0 by changing jar file and config.
I modified security configs according to application.example.yml.
Admin user logins fine, but anonymous user can not view anything.

**Authentication method: basic auth**

Security configs like this..
```
akhq:
  security:
    roles: -> same as example
    groups- > same as example
    default-group: topic-reader
    # Basic auth configuration
    basic-auth:
      - username: admin
        password: xxx
        groups: # Groups for the user
          - admin
```

/api/me response comparison...
```
GET /api/me (0.25.0)
{
  "logged": false
}

GET /api/me (0.24.0)
{
  "logged": false,
  "roles": [
    "group",
    "group/read"
    "topic",
    "topic/data"
    "topic/data/read",
    "topic/read"
   ]
}
```

**Comment by AlexisSouquiere** [comment]
What do you mean by anonymous user with basic auth ? Someone tries to login with "john/doe" (non existing user) and in 0.24.0 he was logged in with the default group ?

**Comment by jinseok-k** [comment]
Anonymous user means accessing akhq without logging in. I have allowed all users to use akhq by read without logging in.
If you access without logging in, you will be displayed in the log as an anonymous user.

**Comment by AlexisSouquiere** [comment]
Ok I think I understand. The behaviour changed a bit because enabling basic-auth in 0.25.0 forces user to login whereas in 0.24.0 user could use the app (with rights given by the default group) and eventually login with the admin account to get more rights. Is it what you saw when switching to 0.25.0 ?

**Comment by drazul** [comment]
I have a similar problem, but my configuration is different (I pasted it at the end).

I updated the server to latest (0.25.0) using the same configuration from the previous version (0.24.0) and the read-only users get an empty list of roles when they are logged:

Answer to `/api/me` on version 0.24.0:
```
{
    "logged": true,
    "username": "drazul",
    "roles": [
        "acls",
        "acls/read",
        "connect",
        "connect/read",
        "group",
        "group/read",
        "node",
        "node/read",
        "registry",
        "registry/read",
        "topic",
        "topic/data",
        "topic/data/read",
        "topic/read"
    ]
}
``` 

Answer to `/api/me` on the version 0.25.0:
```
{"logged":true,"username":"drazul"}
```

This is my OIDC configuration
```
    oidc:
      enabled: true
      providers:
        oidc:
          label: "Login with OIDC"
          username-field: preferred_username
          groups-field: roles
          default-group: no-roles
          groups:
            - name: akhq-read-only
              groups:
                - topic-reader
            - name: akhq-admin
              groups:
                - admin
```

**Comment by drazul** [comment]
@AlexisSouquiere Oh, I didn't see that. Thanks!

I only checked the release notes on the release page https://github.com/tchiotludo/akhq/releases/tag/0.25.0 (I see there is a warning there, but no link to the documentation)

**Comment by jinseok-k** [comment]
@AlexisSouquiere Thanks for answer. 
Yes, I saw in 0.25.0

So, if basic auth is enabled in version 0.25.0, does it mean that all users will need to log in?

Is there a way to use it with read permission without logging in like in 0.24.0?

**Comment by AlexisSouquiere** [comment]
@jinseok-k yes but it's not the expected behaviour it seems to be a regression. I think I missed something when introducing the new RBAC about unlogged user when security is enabled. Let's me check and fix it. 
In the meantime, creating a reader user in basic auth with topic-reader group will solve the issue but I'll find a way to have the same behaviour as 0.24.0

**Comment by jinseok-k** [comment]
@AlexisSouquiere Thank you for your quick support.

**Comment by pkuhlu** [comment]
@AlexisSouquiere I'm using GitHub SSO to authenticate and authentication succeeds. However the `default-group` doesn't apply to the signed in users who are not customized.

For example, the default group is reader, and only `user-2` is customized. All the login non-user-2 users cannot read anything on the UI. The error in the browser inspector's  console is like 403 forbidden.

```yml
default-group: reader # Default groups for all the user even unlogged user

       users:
            - username: user-2
              groups:
                # the corresponding akhq groups (eg. topic-reader/writer or akhq default groups like admin/reader/no-role)
                - reader
```

Could you give any hints? Thanks.
