### ISSUE TITLE
AKHQ throws an UnkownHostException with glue as schema registry

### ISSUE THREAD

**Issue by bdekonin** [tchiotludo/akhq#1791]
We host our AKHQ on AWS ECS, following [this](https://akhq.io/docs/configuration/schema-registry/glue.html) guide. This is the current implementation of our application.yaml
```
akhq:
  connections:
    cluster-server:
      properties:
          bootstrap.servers: ${BOOTSTRAP_BROKERS}
          security.protocol: SASL_SSL
          sasl.mechanism: AWS_MSK_IAM
          sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required awsDebugCreds=true;
          sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
      schema-registry:
          url: "http://schema-registry:8085/"
          type: "glue"
          glueSchemaRegistryName: "MskGlueRegistry"
          awsRegion: ${REGION}
```

When trying this we get the following error

```
java.net.UnknownHostException: schema-registry at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source) at java.base/java.net.Socket.connect(Unknown Source) at java.base/sun.net.NetworkClient.doConnect(Unknown Source) at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source) at java.base/sun.net.www.http.HttpClient.New(Unknown Source) at java.base/sun.net.www.http.HttpClient.New(Unknown Source) at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source) at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:312) at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:408) at io.confluent.kafka.schemaregistry.client.rest.RestService.getAllSubjects(RestService.java:1111) at io.confluent.kafka.schemaregistry.client.rest.RestService.getAllSubjects(RestService.java:1096) at org.akhq.repositories.SchemaRegistryRepository.all(SchemaRegistryRepository.java:104) at org.akhq.controllers.SchemaController.listAll(SchemaController.java:56) at org.akhq.controllers.$SchemaController$Definition$Exec.dispatch(Unknown Source) at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461) at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4276) at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:236) at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:488) at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:465) at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87) at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211) at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141) at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:193) at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211) at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141) at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:193) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source)
```
<img width="1423" alt="Screenshot 2024-05-27 at 12 49 50" src="https://github.com/tchiotludo/akhq/assets/60445103/ef96cc20-83a3-4906-93bc-ecc3871f92ed">

In the network tab, we get a 500 error on the following call, but we can't seem to find out the reason.
`https://<OUR_SERVER>.io/api/cluster-server/schema?&search=&page=1`
