### ISSUE TITLE
Manually apply avro schema to specific topics/messages

### ISSUE THREAD

**Issue by mrjackbo** [tchiotludo/akhq#181]
Thanks for the useful tool. This is a feature request.

In my application, I do not serialize the avro schema reference in the message header, but all producers and consumers explicitly know which schema belongs to which topic, and they pull the schema from the registry only once at startup.

This means that kafkahq cannot deserialize the messages, because it cannot choose the schema automatically. It would be useful to have an option in the topic/message view gui, which allows the user to choose a schema from the registry with which the messages should be deserialized.

**Comment by tchiotludo** [comment]
Hello, 

I think I see your feature request ! 
You use Kafka Schema Registry, but your consumer / producer have a mapping from topic to schema id, right ? 
In this case, you just serialize only the avro content to Kafka (without magic bytes with schema id like a standard app) ? 

If it true ,what you think about configuration (on application.yml) with topic name & schema id in order to decrypt avro by configuration instead of ui  ?

**Comment by mrjackbo** [comment]
> You use Kafka Schema Registry, but your consumer / producer have a mapping from topic to schema id, right ?
In this case, you just serialize only the avro content to Kafka (without magic bytes with schema id like a standard app) ?

Correct. We have had issues since the Hortonworks registry and the Confluent registry use different magic bytes/headers, and various libraries are developed with different registries in mind, so we just skipped writing the headers altogether.

Configuration via the yaml file would be great.

**Comment by tchiotludo** [comment]
Ok noted ! 
It's a little bit specific but not a huge work 👍

**Comment by tsavenko** [comment]
> If it true ,what you think about configuration (on application.yml) with topic name & schema id in order to decrypt avro by configuration instead of ui ?

I am ok doing that, but it doesn't seem to work. There are no errors displayed in the log and the application starts normally. However, it doesn't seem to be serializing the messages (I am trying to post messages via UI and have them go through Avro serializer)
Here's the configuration I tried: 

```
# default kafka properties for each clients, available for admin / producer / consumer 
(optional)
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed
    producer:
      schema-registry:
        url: "http://localhost:8081"
      schema.id: 61
      kafka.topic.name: testtopic
      properties:
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
```

@tchiotludo I hope I'm just messing up this configuration and that's why it doesn't work :) Thanks in advance for your input!
