### ISSUE TITLE
0.25.1 allows admin access without logging in

### ISSUE THREAD

**Issue by t0ffel** [tchiotludo/akhq#1854]
Section of the config.
```
          akhq:
            security:
              roles:
                node-read:
                  - resources: [ "NODE" ]
                    actions: [ "READ", "READ_CONFIG" ]
                node-admin:
                  - resources: [ "NODE" ]
                    actions: [ "READ", "READ_CONFIG", "ALTER_CONFIG" ]
                topic-read:
                  - resources: [ "TOPIC", "TOPIC_DATA" ]
                    actions: [ "READ" ]
                  - resources: [ "TOPIC" ]
                    actions: [ "READ_CONFIG" ]
                topic-admin:
                  - resources: [ "TOPIC", "TOPIC_DATA" ]
                    actions: [ "READ", "CREATE", "DELETE" ]
                  - resources: [ "TOPIC" ]
                    actions: [ "UPDATE", "READ_CONFIG", "ALTER_CONFIG" ]
                registry-read:
                  - resources: [ "SCHEMA" ]
                    actions: [ "READ" ]
                registry-admin:
                  - resources: [ "SCHEMA" ]
                    actions: [ "READ", "CREATE", "UPDATE", "DELETE", "DELETE_VERSION" ]
                group-read:
                  - resources: [ "CONSUMER_GROUP" ]
                    actions: [ "READ" ]
                group-admin:
                  - resources: [ "CONSUMER_GROUP" ]
                    actions: [ "READ", "UPDATE_OFFSET", "DELETE_OFFSET" ]
              # Groups definition
              groups:
                admin:
                  - role: node-admin
                  - role: topic-admin
                  - role: registry-admin
                  - role: group-admin
                topic-reader:
                  - role: node-read
                  - role: topic-read
                  - role: registry-read
                  - role: group-read
                consumer-group-editor:
                  - role: node-read
                  - role: topic-read
                  - role: registry-read
                  - role: group-admin
              # OIDC
              oidc:
                enabled: true
                providers:
                  okta:
                    label: "Login with Okta"
                    username-field: preferred_username
                    groups-field: groups
                    default-group: no-roles
                    #use-oidc-claim: true
```

akhq.security.oidc.providers.okta.default-group is `no-roles`, in 0.25.0 - it always prompts to log in.
in 0.25.1 akhq gives admin-level access w/o requiring to log in.
