### ISSUE TITLE
Disable alternative DNS name matching for hostname (SSLHandshakeException)

### ISSUE THREAD

**Issue by dschweinbenz** [tchiotludo/akhq#1857]
When accessing the schema registry in AKHQ i receive the error "Internal Server Error: No subject alternative DNS name matching schema-registry found.". The logs indicate:
```
No subject alternative DNS name matching schema-registry found.
javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching schema-registry found.
```

I am using docker to set up my environment locally and i am using SSL authentication. I know i could just add the DNS name of the container's hostname into the client certificate but the docs also mention that there is the option "`ssl.endpoint.identification.algorithm`" to disable the verification. Nevertheless this doesn't work if i enable it on the schema registry side. **Is there any possibility to disable the client check in AKHQ to connect to the schema-registry using SSL without a valid DNS name inside the client certificate?** 

I have the following configuration:
```
      schema-registry:
        url: "https://schema-registry:8083"
        properties:
          schema.registry.ssl.keystore.location: "/secret/client-creds/kafka.client.keystore.pkcs12"
          schema.registry.ssl.keystore.password: "<pass>"
          schema.registry.ssl.key.password: "<pass>"
          schema.registry.ssl.truststore.location: "/secret/client-creds/kafka.client.truststore.pkcs12"
          schema.registry.ssl.truststore.password: "<pass>"
          schema.registry.ssl.endpoint.identification.algorithm:
```

Base docs for the hostname verification: "Clients automatically check the SSL certificate of the Schema Registry servers and compare it with where they connected. This is called hostname verification"
