### ISSUE TITLE
Regexp topics filtering (topics-filter-regexp) not working in version 0.25.1

### ISSUE THREAD

**Issue by user-lpt** [tchiotludo/akhq#1866]
The **topics-filter-regexp** parameter is ignored, so all groups can see all topics, including Kafka internal ones (__consumer_offsets and so). I guess this behavior is only in version 0.25.1, because older versions (0.21.0 and 0.24.0) worked well.

This is part of my **new not working** config (0.25.1):
```
security:
  default-group: no-roles
  groups:
    topic_writer:
    - attributes:
        topics-filter-regexp:
        - PREFIX-.*
      role: writer
  ldap:
    groups:
    - groups:
      - topic_writer
      name: akhq_writers
  roles:
    writer:
    - actions:
      - READ
      - CREATE
      - DELETE
      - UPDATE
      - READ_CONFIG
      resources:
      - TOPIC
    - actions:
      - READ
      - CREATE
      - UPDATE
      resources:
      - TOPIC_DATA
```

This is part of my **old working** config (0.24.0):
```
security:
  default-group: no-roles
  groups:
    topic-writer:
      name: topic-writer
      attributes:
        topics-filter-regexp:
        - PREFIX-.*
      roles:
      - topic/read
      - topic/data/read
      - topic/data/insert
      - topic/insert
      - topic/delete
      - topic/config/update
  ldap:
    groups:
    - groups:
      - topic-writer
      name: akhq_writers
```

Thank you
