### ISSUE TITLE
Java Error after Login via Azure AD OIDC

### ISSUE THREAD

**Issue by petkovp** [tchiotludo/akhq#1874]
Hello,

I have akhq configuration witl login via Azure AD, but after type my credential I have following error: 
**Field required java.util.map but got string**, a cannot see any menu or options in AKHQ UI
<img width="355" alt="image" src="https://github.com/user-attachments/assets/d6f9cd41-fafc-4529-aed7-b351b06d79cf">

My configuration is:
```
micronaut:
  security:
    enabled: true
    oauth2:
      callback-uri: "https://AKHQ URL/oauth/callback/oidc"
      clients:
        github:
          client-id: CLIENT-ID
          client-secret: CLIENT-SECRET
          openid:
            issuer: AZURE AD URL ISSUER
          scopes:
            - email
            - profile
            - openid
akhq:
  server:
    access-log:
      enabled: true
      name: org.akhq.log.access
  security:
    default-group: no-roles
    oauth2:
      enabled: true
      providers:
        github:
          label: "Login with AzureAD"
          username-field: preferred_username
          groups-field: roles
          default-group: no-roles
          groups:
            - name: AZURE AD GROUP ID
              groups: admin
``` 

Can someone help me with this issue!

**Comment by petkovp** [comment]
Fixed my issue like change a configuration, the right config is:
```
micronaut:
  security:
    enabled: true
    oauth2:
      callback-uri: "https://AKHQ URL/oauth/callback/oidc"
      clients:
        github:
          client-id: CLIENT-ID
          client-secret: CLIENT-SECRET
          openid:
            issuer: AZURE AD URL ISSUER
          scopes:
            - email
            - profile
            - openid
akhq:
  server:
    access-log:
      enabled: true
      name: org.akhq.log.access
  security:
    default-group: no-roles
    oidc:
      enabled: true
      providers:
        github:
          label: "Login with AzureAD"
          username-field: preferred_username
          groups-field: roles
          default-group: no-roles
          groups:
            - name: AZURE AD GROUP MAP NAME
              groups: 
                - admin
```
