### ISSUE TITLE
0.25 ACLs breaking change - LDAP patterns

### ISSUE THREAD

**Issue by MaxenceVacheron** [tchiotludo/akhq#1882]
Hi,
I don't understand how I am supposed to update my application.yml for 0.25.1 version.
Old version was :
```
          topics-filter-regexp:
            - "^projectA_topic$" # Individual topic
            - "^projectB_.*$" # Topic group
          connects-filter-regexp:
            - "^test.*$"
          consumer-groups-filter-regexp:
            - "consumer.*"
 ```
 And new version only specify "patterns" in the group section 
 ```
     groups:
      topic-reader-pub:
        - role: topic-reader
          patterns: [ "pub.*" ]
```

How do I differentiate connect filters and topics filters ?
