### ISSUE TITLE
Using Confluent Schema Registry since v0.25.0: Magic byte and Schema ID not removed from beginning of value

### ISSUE THREAD

**Issue by Rob3681** [tchiotludo/akhq#1890]
Starting with version 0.25.0 (and also 0.25.1), the bytes at positions 0-4 (magic byte + schema ID) are not removed from the beginning of a record value that was produced using a schema from the Confluent Schema Registry. This means that a JSON value is not displayed formatted, but instead as a one-liner. Furthermore, the data cannot be copied so easily with CTRL+A + CTRL+C; an empty string is written to the clipboard.

![v0.25.1](https://github.com/user-attachments/assets/5d43be23-d82c-4e27-afa1-49008374d57b)

![v0.25.1](https://github.com/user-attachments/assets/58013bf8-55f8-45fe-9227-e1404fe4c879)

I use the following configuration:

```
akhq:
  connections:
    test:
      properties:
        bootstrap.servers: abc.europe-west3.gcp.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: >-
          org.apache.kafka.common.security.plain.PlainLoginModule required
          username="KAFKA-API-KEY"
          password="KAFKA-API-SECRET";
      schema-registry:
        url: https://xyz.europe-west3.gcp.confluent.cloud
        type: confluent
        basic-auth-username: SR-API-KEY
        basic-auth-password: SR-API-SECRET
```

Access to the schema registry generally works. It is recognized that the value was produced using a schema from the Confluent Schema Registry, I can display the schema content and I can also specify the schema when producing a message.

With the identical configuration, the problem does not occur in version 0.24.0:

![v0.24.0](https://github.com/user-attachments/assets/88e14832-50d3-4373-aa09-2684993314a8)

![v0.24.0](https://github.com/user-attachments/assets/0fe4a0d1-b003-4910-a98b-31489de6a386)
