### ISSUE TITLE
Missing checks for permission on GroupController

### ISSUE THREAD

**Issue by alwibrm** [tchiotludo/akhq#1936]
With the following role definitions:
```yaml
      group-read:
        - resources:
            - CONSUMER_GROUP
          actions:
            - READ
      offset-reset:
        - resources:
            - CONSUMER_GROUP
          actions:
            - UPDATE_OFFSET
            - DELETE_OFFSET
```
and the following group definitions:
```yaml
      akhq-reader:
        - role: group-read
      akhq-manager:
        - role: offset-reset
          patterns:
            - ^myconsumergroup.*$
```
a user assigned to both groups (akhq-reader and akhq-manager) can update the offset of any and all topics, even when they're not matching the pattern of "_^myconsumergroup.*$_".

Most of the controllers are implementing permission checks by callig `AbstractController#checkIfClusterAndResourceAllowed`. This checks seem to be missing in the `GroupController`.
