### ISSUE TITLE
akhq 0.25.1 cannot read data from topic

### ISSUE THREAD

**Issue by vasili439** [tchiotludo/akhq#1987]
Hi! We faced with the issue when we try to browse topic data. For some kafka clusters I get 503/504 and for some time to getting data increased compare to 0.24.0. No errors in browser's console. No errors when I enable trace logs. Everything what helped us to resolve the issue is rollback to 0.25.0. Can we investigate the root cause?

**Comment by nirousseau** [comment]
I have also experienced the same issue, rolled back to 0.25.0 and it works like charm.
0.25.1 somehow introduced a regression.

**Comment by AlexisSouquiere** [comment]
@vasili439, @nirousseau is it possible for you to try again by changing this setting ? Try to put a low value like 5000
 
```yaml
akhq:
  clients-defaults:
    consumer:
      properties:
        max.poll.records: 25000
```

For the higher response time I think it comes from this one:

```yaml
akhq:
  topic-data:
    poll-timeout: 10000
```

Basically with the default configuration, AKHQ tries to fetch 25K records for each poll and if there are less than 25k, waits 10s until the timeout
