### ISSUE TITLE
Audit Logging of AKHQ actions

### ISSUE THREAD

**Issue by Kris686** [tchiotludo/akhq#1992]
### Discussed in https://github.com/tchiotludo/akhq/discussions/1888

<div type='discussions-op-text'>

<sup>Originally posted by **0nurulusoy** July 31, 2024</sup>
Got it! Here is the revised version of your question:

I want to enable audit logging in AKHQ to log activities such as:

- Logging in with different user accounts
- Viewing topics and consumer groups
- Creating or deleting topics
- Modifying configurations

I followed the documentation [here](https://akhq.io/docs/configuration/akhq.html#audit), first created the topic by hand on Kafka, and used the provided configuration. However, it does not log anything to the topic. Auto-create is enabled, so I also expected AKHQ to create the topic, but it didn't, what am i missing? It doesn't have example on the [https://github.com/tchiotludo/akhq/blob/dev/application.example.yml](url).</div>

**Comment by Kris686** [comment]
I've encountered the same issue with audit logs creation, I'm using helm chart installation method with following config: 
```
  configuration:
    akhq:
      audit:
        enabled: true
        cluster-id: kafka-cluster-001
        topic-name: auditlogs
```
There are no errors and warnings in pod's logs.
