### ISSUE TITLE
Visibility issue with connectors matching specific patterns in AKHQ UI

### ISSUE THREAD

**Issue by njavadi-clgx** [tchiotludo/akhq#2035]
### Description:
I am experiencing an issue where specific Kafka connectors are not visible in the AKHQ UI, even though they can be seen in other tools such as Conduktor. The connectors match the pattern `xya-abc-.*`, and according to the AKHQ configuration, users in the group `xyz-abc-nonprd-sa` (sanitized) have the necessary roles to view these connectors.
### Additional Information:
- AKHQ Version: 0.25.2
- This issue is critical as it affects visibility and management of Kafka connectors via AKHQ for user groups.
### Configuration Snippet :
```
akhq:
  security:
    groups:
      akhq-groups:
        - role: akhq-roles
          patterns:
            - "xya-abc-.*"

    roles:
      akhq-roles:
        - resources: ["CONNECTOR"]
          actions: ["READ", "UPDATE_STATE"]

    basic-auth:
      - username: admin
        password: [sanitized]
        groups:
          - admin

    ldap:
      groups:
        - name: xyz-abc-nonprd-sa
          groups:
            - akhq-groups
```
