### ISSUE TITLE
Unauthorized Error on Accessing Configs Tab Despite Correct Permissions

### ISSUE THREAD

**Issue by njavadi-clgx** [tchiotludo/akhq#2048]
**Describe the bug**
When attempting to access the 'configs' tab under one of the connectors, I am unexpectedly redirected to the login page. An error stating “Unauthorized: missing permission on resource CONNECT_CLUSTER and action READ” is displayed, despite the fact that the user has the required `CONNECT_CLUSTER` resource and `READ` action permissions explicitly added.

**To Reproduce**
1. Log in with a user that has CONNECT_CLUSTER and READ permissions.
2. Go to Connectors.
3. Click on 'configs' for any connector.
4. See error and redirection to login page.

**Expected behavior**
The expected behavior is that the 'configs' tab should open and display the configurations without any authorization issues since the permissions are correctly set.

**Screenshots**
![Image](https://github.com/user-attachments/assets/75932409-a93a-46f6-9001-cf0247328b48)

![Image](https://github.com/user-attachments/assets/5c59e0f4-7715-4942-b7af-560f3feaba11)

![Image](https://github.com/user-attachments/assets/7b5f3ffb-9bc2-4d31-b1c6-9edba7da820a)

**Environment :**
- AKHQ version:  0.25.2

**Additional context**
I don't see the same issue when user with **admin** role permission tries to click on Connector's Configs Tab

**Comment by nicolasdelvat** [comment]
Hello,

It works on my end on 0.25.1, it's not obvious but the user is linked to a group and a group is linked to a role since 0.25.0
Here is the documentation for the group : https://akhq.io/docs/configuration/authentifications/groups.html
For the basic-auth : https://akhq.io/docs/configuration/authentifications/basic-auth.html
It looks like this in the conf file :
```yaml
micronaut:
  security:
    enabled: true
```
```yaml
akhq:
  security:
    default-group: no-roles
    roles:
      custom-reader:
        - resources: [ "CONNECT_CLUSTER" ]
          actions: [ "READ" ]
        - resources: [ "CONNECTOR" ]
          actions: [ "READ" , "UPDATE_STATE"]
    groups:
      test:
        - role: custom-reader
    basic-auth:
      - username: admin
        password: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        groups:
          - test
```
