### ISSUE TITLE
roles mapping from azure entra id is not working

### ISSUE THREAD

**Issue by youcefguichi** [tchiotludo/akhq#2128]
I setup akhq with azure entra id, the sso works fine and the user can logging, however mapping app roles from the entra app, to setup a proposer permissions is not working as expected / nor showing any logs that help me track the issue, can someone help me spot the issue? am i missing something?

/api/me
```yaml
logged	true
username. "user@email.no"
roles:
```

Based on my understanding the akhq will extract app roles from the jwt  and then map it to a group:

```
groups:
  - name: reader-test # this one is an app roles that should be injected in the jwt and akhq extract it from there
    groups:
      - topic-reader-test   
```

here is the full config:

```yaml
configuration:
  akhq:
    security:
      enabled: true
      roles:
        topic-reader:
          - resources: [ "TOPIC", "TOPIC_DATA" ]
            actions: [ "READ" ]
          - resources: [ "TOPIC" ]
            actions: [ "READ_CONFIG" ]
      groups:
        topic-reader-test:
          - role: topic-reader
            patterns: [ "test.*" ]
        no-roles: []    
      oidc:
        enabled: true
        providers:
          azure:
            label: "Click here to Login with Azure"
            username-field: email
            groups-field: roles
            default-group: topic-reader
            groups:
              - name: reader-test # this one is an app roles that should be injected in the jwt and akhq extract it from there
                groups:
                  - topic-reader-test    
    server:
      access-log:
        enabled: true
        name: org.akhq.log.access
  micronaut:
    security:
      enabled: true
      oauth2:
        enabled: true
        clients:
          azure:
            client-id:  "<client-id>"
            client-secret: "<client-secret>"
            scopes:
              - openid
              - email
              - profile
            openid:
              issuer: "https://login.microsoftonline.com/tenant-id/v2.0"
```
