### ISSUE TITLE
Unauthorized redirects to login even though I'm already authorized

### ISSUE THREAD

**Issue by ndemyanchuk-booking** [tchiotludo/akhq#2131]
Hi, I'm testing AKHQ (0.25.1) with my OIDC provider (Okta) and the authentication works well, I am able to login using it. 
I am also using [external roles and attribute mapping](https://akhq.io/docs/configuration/authentifications/external.html) functionality to lookup groups for each user. This also works well, e.g. I can only see topics which I'm supposed to see. 

But then in the consumer groups section I can see consumer groups that read topics that I'm not supposed to be able to access. 
When I press on the topic name, I get an `Unauthorized` error message and get redirected to the login page `/ui/login`, and it prompts me to login again. The problem is that I am already logged in. If I just go to the `/ui` page in my browser - it shows me the list of the topics and the regular UI. 

What I would expect is for the redirect not to happen, or perhaps login page to recognize that I'm already logged in, and redirect me further to the main AKHQ page. 

Please let me know if this is possible to achieve. I've tried to play with `micronaut.security.redirect` values but AKHQ seems to be ignoring those and keep redirecting me to login page instead. 

Here's current relevant configuration part

```
micronaut:
  security:
    enabled: true
    callback-uri: https://akhq.<redacted>.com/oauth/callback
    redirect:
      login-success: "/ui"
      forbidden:
        enabled: false
        url: "/ui"
      unauthorized:
        enabled: false
        url: "/ui"

    oauth2:
      enabled: true
      clients:
        okta:
          scopes:
            - openid
            - email
            - profile
            - groups
          client-id: "<redacted>"
          client-secret: "<redacted>"
          openid:
            issuer: https://<redacted>.okta.com/
            configuration-path: "/.well-known/openid-configuration"
  # server:
  #   context-path: "" # if behind a reverse proxy, path to akhq without trailing slash (optional). Example: akhq is
  #                    # behind a reverse proxy with url http://my-server/akhq, set context-path: "/akhq".
  #                    # Not needed if you're behind a reverse proxy with subdomain http://akhq.my-server/
  server:
    port: 80
    ssl:
      enabled: true
      port: 443
      buildSelfSigned: true


akhq:
  security:
    oidc:
      enabled: true
      providers:
        okta:
          label: "Login with Okta"
          username-field: preferred_username
          use-oidc-claim: false
    redirect: false
    default-group: no-roles
    rest:
      enabled: true
      url: http://localhost:8088
    roles:
      topic-reader:
        - resources: ["TOPIC"]
          actions: ["READ", "READ_CONFIG"]
        - resources: ["TOPIC_DATA"]
          actions: ["READ"]
        - resources: ["CONSUMER_GROUP"]
          actions: ["READ"]
      group-reader:
        - resources: ["CONSUMER_GROUP", "SCHEMA"]
          actions: ["READ"]
      topic-writer:
        - resources: ["TOPIC_DATA"]
          actions: ["CREATE", "UPDATE"]
```
