### ISSUE TITLE
Topic Not Visible with Exact Regex Pattern, but Visible with Wildcard Prefix

### ISSUE THREAD

**Issue by njavadi-clgx** [tchiotludo/akhq#2250]
**Expected Behavior**
When a Kafka principal has `DeveloperRead` RBAC permission for a specific topic, and AKHQ's `roles.yaml` is configured with an exact regex pattern matching that topic, the topic should be visible to users logged in with that principal's associated AKHQ role.

**Actual Behavior**
A topic with a name like `my_application_service_DATA.TopicTest.AKHQ.dev` is not visible in AKHQ when the `roles.yaml` pattern is set to its exact literal regex equivalent. However, the topic becomes visible when a broader wildcard pattern is used, indicating a potential issue with exact regex matching for topic names containing multiple literal dots.

**Steps to Reproduce**

**Kafka RBAC Configuration:**
Assume the following Confluent RBAC permission is in place for a principal (e.g., a service account or group):

$ confluent iam rbac rb list --principal Group:my-team-service-account --kafka-cluster my-kafka-cluster-id
-------------------------------------------------------------------+----------------+---------------+----------------------
 Group:my-team-service-account                                     | DeveloperRead  | Topic         | my_application_service_DATA.TopicTest.AKHQ.dev        | LITERAL
(This indicates `Group:my-team-service-account` has `DeveloperRead` on the exact topic my_application_service_DATA.TopicTest.AKHQ.dev).

**AKHQ `roles.yaml` Configuration (Attempt 1 - Not Working):**
The AKHQ `roles.yaml` is configured with the following specific pattern (including proper escaping for literal dots and start/end anchors) for the relevant AKHQ role:

YAML

```
my-team-service-account-developerread-topic:
  - role: developerReadTopic # This role is configured in AKHQ to grant 'TOPIC:READ' action and other necessary permissions.
    patterns:
      - "^my_application_service_DATA\\.TopicTest\\.AKHQ\\.dev$"
```
(Note: Using quotes around the pattern `""` was also tested, with no change in behavior).

**AKHQ `roles.yaml` Configuration (Attempt 2 - Working):**
When the `roles.yaml` is updated to a broader prefix wildcard pattern for the same AKHQ role:

YAML

```
my-team-service-account-developerread-topic:
  - role: developerReadTopic
    patterns:
      - "my_application_service_DATA\\.TopicTest\\.AKHQ\\.dev.*"
```
With this pattern, the topic `my_application_service_DATA.TopicTest.AKHQ.dev` becomes visible in AKHQ.

**Additional Context**

- The topic `my_application_service_DATA.TopicTest.AKHQ.dev` is confirmed to exist in Kafka and is visible in other Kafka tools like Conduktor.
- The AKHQ user/group authentication to Kafka is confirmed to be working, as topics are listed when a broad wildcard pattern is used.
- The `developerReadTopic` role in AKHQ has been verified to grant the necessary `TOPIC:READ` and other relevant permissions (`TOPIC_DATA:READ`, `CONSUMER_GROUP:READ`).
- AKHQ was restarted after each `roles.yaml` change.
- This behavior suggests there might be a nuance in how AKHQ's regex engine handles exact matches for topic names containing multiple literal dots (`.`) when backslash-escaped.
