### ISSUE TITLE
Feature request: Topic configurations by cluster

### ISSUE THREAD

**Issue by samcarpentier** [tchiotludo/akhq#254]
### Description

Given that AKHQ allows to manage multiple clusters, it would be great to be able to specify topics configurations by cluster.

The most striking example of this is the following: I have 2 clusters registered in AKHQ. One has 12 nodes, the other has 6 nodes. I want to be able to specify a default replication factor that's different for each cluster.

See the proposed configuration example below.

### Current configuration

```yaml
# ...
  connections:
    kafka-cluster1:  # 12 nodes
      properties:
        bootstrap.servers: kafka-cluster1.example.com:9092
    kafka-cluster2:  # 6 nodes
      properties:
        bootstrap.servers: kafka-cluster2.example.com:9092

  topic:
    replication: 4
    partitions: 3
# ...
```

### Proposed configuration

```yaml
# ...
  connections:
    kafka-cluster1:  # 12 nodes
      properties:
        bootstrap.servers: kafka-cluster1.example.com:9092
    kafka-cluster2:  # 6 nodes
      properties:
        bootstrap.servers: kafka-cluster2.example.com:9092

  topic:
    kafka-cluster1:
      replication: 8
      partition: 3
    kafka-cluster2:
      replication: 4
      partition: 3
# ...
```

**Comment by samcarpentier** [comment]
@tchiotludo Let me know what you think about this and what would be the effort to implement this.

**Comment by tchiotludo** [comment]
not really complicated, just need to think the proper way to deal with the configuration files. 
maybe add a `defaults:` to be clear that's the default one, and allow override on the `connections` part.
Not really sure right now :thinking:

**Comment by samcarpentier** [comment]
Oh, that's a good point. Didn't think of that. So it would look something like this:

```yaml
# ...
  connections:
    kafka-cluster1:  # 12 nodes
      properties:
        bootstrap.servers: kafka-cluster1.example.com:9092
    kafka-cluster2:  # 6 nodes
      properties:
        bootstrap.servers: kafka-cluster2.example.com:9092

  topic:
    default:
      retention: 172800000
      partition: 3
      default-view: HIDE_INTERNAL
      internal-regexps:
        - "^_.*$"
        - "^.*_schemas$"
        - "^.*connect-config$"
        - "^.*connect-offsets$1"
        - "^.*connect-status$"
      stream-regexps:
        - "^.*-changelog$"
        - "^.*-repartition$"
        - "^.*-rekey$"
      skip-consumer-groups: false
    kafka-cluster1:
      replication: 8
    kafka-cluster2:
      replication: 4
# ...
```
