### ISSUE TITLE
Feature request: obfuscation of sensitive data

### ISSUE THREAD

**Issue by alwibrm** [tchiotludo/akhq#257]
It would be useful to have the ability to obfuscate sensitive data in the "Data" tab in the topic view. For the identification of sensitive data, custom regex patterns and their respective replacement strategy (`FULL`, `PART`, `HASH_SHA256`,...) could be provided.

**Examples for sensitive data:** (especially with regard to GDPR)

- Credit card numbers
- E-Mail addresses
- Phone numbers
- ...

**Example for configuration:**

```
akhq:
  topic-data:
    - obfuscation:
        pattern: [A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}
        replacement: PARTIAL
    - obfuscation:
        pattern: ^(?:4[0-9]{12}(?:[0-9]{3})?
        replacement: FULL
    - obfuscation:
        pattern: ([(+]*[0-9]+[()+. -]*)
        replacement: HASH_SHA2
```
Expected output would be something like:
```
#####om@gmail.com
#### #### #### ####
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
