### ISSUE TITLE
akhq with required authentication exposes names of the cluster to unauthenticated users

### ISSUE THREAD

**Issue by ankon** [tchiotludo/akhq#267]
Assume a configuration like this:

```yaml
micronaut:
  security:
    # Explicitly enable security to override dangerous micronaut defaults
    enabled: true

akhq:
  connections:
    name-of-my-cluster:
      # Settings here

  security:
    # Nothing available for unauthenticated users
    default-group: no-roles

    groups:
      # Settings for groups

    # Authenticated users
    basic-auth:
      # Users with explicitly assigned groups
```

When opening the akhq root, say through https://akhq.dev.example.com, it will redirect to https://akhq.dev.example.com/name-of-my-cluster/topic (and then show an exception right now -- #261, or hopefully a login page when that is fixed). 
But: At that point a potential attacker has learned the name of the cluster in the configuration, which may be unexpected.

Somewhat obvious fix/work-around: Use a generic cluster name like "kafkahq", but that may not always be wanted or feasible.
