### ISSUE TITLE
Can't connect to my kafka

### ISSUE THREAD

**Issue by 1411643015** [tchiotludo/akhq#272]
I think the description of the configuration file is not very friendly to novices, I hope it can be more specific.
I set up a three kafka cluster on the server, and run akhq on my development machine by running the Jar package. My kafka cluster is not configured with any security. Now I can't connect to my cluster, can you give me the simplest configuration？
Thank you very much！

**Comment by tchiotludo** [comment]
hello, 

here is a simplest configuration that is working : 
```yaml 
akhq:
    connections:
    local:
        properties:
        bootstrap.servers: "local:9092"
```

**Comment by 1411643015** [comment]
> hello,
> 
> here is a simplest configuration that is working :
> 

> ```yaml
> akhq:
>     connections:
>     local:
>         properties:
>         bootstrap.servers: "local:9092"
> ```
This is my current configuration file：
![image](https://user-images.githubusercontent.com/35264598/79849388-f8580b80-83f4-11ea-9cc3-86fc38aff4ab.png)
I‘m running akhq on my development machine by running the Jar package. He will still report an error：
![image](https://user-images.githubusercontent.com/35264598/79849476-1b82bb00-83f5-11ea-9e27-ad63213c03b4.png)
![image](https://user-images.githubusercontent.com/35264598/79849535-2dfcf480-83f5-11ea-9a13-550385dbe516.png)

**Comment by tchiotludo** [comment]
oups I failed the indentation, sorry.

The good one : 
```yaml
akhq:
  connections:
    local:
      properties:
        bootstrap.servers: "local:9092"
```
