### ISSUE TITLE
Underscore in basic-auth username not working

### ISSUE THREAD

**Issue by klDen** [tchiotludo/akhq#277]
Hi!

First, thanks for the nice tool! I like it a lot!

I am unable to login with

### Basic auth configuration _with underscore_ in username
```yaml
basic-auth:
  foo_bar:
    password: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8 
    groups: # Groups for the user
      - admin
```

but the same hash works with

### Basic auth configuration _without underscore_ in username
```yaml
basic-auth:
  foobar:
    password: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8 
    groups: # Groups for the user
      - admin
```

I have tried quoting the username using both single/double quotes and faced the same issue.

Thanks!

**Comment by tchiotludo** [comment]
Hi, 
This is a normal behavior.
I don't think about this when I add the basic auth but micronaut transform all the key in yaml to kebab-case.
I need to change the format of the config files to allow underscore to work ...
BC changes ...

**Comment by klDen** [comment]
If it's by design and not a bug, we can add a comment like https://github.com/tchiotludo/akhq/blob/dev/application.example.yml#L35 stating **(letter, number, _, -, ... dot are not allowed here)**

**Comment by tchiotludo** [comment]
or I can changed to this : 
```yaml 
    # Basic auth configuration
    basic-auth:
      - username: user: # Username
        password: pass # Password in sha256
        groups: # Groups for the user
          - admin
          - topic-reader
```
that can be more friendly to understand :tada: :smile:

**Comment by klDen** [comment]
> or I can changed to this :
> 
> ```yaml
>     # Basic auth configuration
>     basic-auth:
>       - username: user # Username
>         password: pass # Password in sha256
>         groups: # Groups for the user
>           - admin
>           - topic-reader
> ```
> 
> that can be more friendly to understand tada smile

yup! that's a good idea!

**Comment by terryf82** [comment]
+1 for this, the current setup prevents both `@` and `.` from being used in usernames too.

**Comment by tchiotludo** [comment]
I just think that you can make it work with that : 
```yaml 
    # Basic auth configuration
    basic-auth:
      user:
        username: "user-nam.e@bla.com" # Username
        password: pass # Password in sha256
        groups: # Groups for the user
          - admin
          - topic-reader
```
The key will be ignored I think. 
If it's works maybe we can change the only the doc to avoid BC ?

**Comment by terryf82** [comment]
@tchiotludo that setup works perfectly, I recommend updating the docs to that standard. Thanks for the great product!

**Comment by terryf82** [comment]
@tchiotludo after further testing it seems like this solution may work only for one user -

With one username:
```
    basic-auth:
      user:
        username: "user-nam.e@bla.com" # Username
        password: pass # Password in sha256
        groups: # Groups for the user
          - admin
          - topic-reader
```

everything works correctly. If I add a second:
```
    basic-auth:
      user:
        username: "user-nam.e@bla.com" # Username
        password: pass # Password in sha256
        groups: # Groups for the user
          - admin
          - topic-reader
      user:
        username: "a-different-user-nam.e@bla.com" # Username
        password: pass # Password in sha256
        groups: # Groups for the user
          - admin
          - topic-reader
```

it seems like the accounts aren't created properly, and neither user can now log in?
