### ISSUE TITLE
issue with basic auth

### ISSUE THREAD

**Issue by ideal2545** [tchiotludo/akhq#281]
i'm trying to setup very basic auth:

    security:
      default-group: admin
    # Basic auth configuration
    basic-auth:
        user: # Username
          password: d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1
          groups:
            - admin

 username should be: user - and password should be: pass

but when I navigate to http://localhost:8080/login and try to use those credentials it doesn't work. I didnt setup anything special with the admin group, I am just trying to use the default admin which is access to all. 

Thank you!
Jon

**Comment by tchiotludo** [comment]
Hello, 
I think you have formatting issue on your yaml. 
must be : 

```yaml 
akhq:
  security:
    basic-auth:
      user: 
        password: d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1
        groups: 
          - admin
```

basic-auth is not indented as expected

**Comment by ideal2545** [comment]
Thank you that helped, the only thing I noticed is that the logged in user didnt get 'admin' access. I was hoping to use the predefined admin roles.

**Comment by ideal2545** [comment]
Thank yo so much that worked!

**Comment by Ranganath9979** [comment]
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: false
      logout:
        enabled: false
akhq:
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]" # Logger format

  # default kafka properties for each clients, available for admin / producer / consumer (optional)
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed

  # list of kafka cluster available for akhq
  connections:
    my-cluster-plain-text: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "dtl01XXXXXXXXXXXXXXXX:9092"

  pagination:
    page-size: 25 # number of elements per page (default : 25)
    threads: 16 # Number of parallel threads to resolve page

  # Topic list display options (optional)
  topic:
    retention: 172800000 # default retention period when creating topic
    partition: 3 #  default number of partition when creating topic
    replication: 3 # default number of replicas when creating topic
    default-view: HIDE_INTERNAL # default list view (ALL, HIDE_INTERNAL, HIDE_INTERNAL_STREAM, HIDE_STREAM)
    internal-regexps: # list of regexp to be considered as internal (internal topic can't be deleted or updated)
      - "^_.*$"
      - "^.*_schemas$"
      - "^.*connect-config$"
      - "^.*connect-offsets$1"
      - "^.*connect-status$"
    stream-regexps: # list of regexp to be considered as internal stream topic
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"
    skip-consumer-groups: false # Skip loading consumer group information when showing topics

  # Topic display data options (optional)
#  topic-data:
#    sort: OLDEST # default sort order (OLDEST, NEWEST) (default: OLDEST)
#    size: 50 # max record per page (default: 50)
#    poll-timeout: 1000 # The time, in milliseconds, spent waiting in poll if data is not available in the buffer.
# Auth & Roles (optional)
  security:
  basic-auth:
     username: xxxxxxxxxxxx
     password: 0696fa9c6a4bbd67998be4553be79923446e41c2668d8d6f10e617652bdca90f
        groups:
  default-group : reader # Default groups for all the user even unlogged user
    # Groups definition
#    groups:
#      - name: admin # Group name
#        roles:  # roles for the group
#          - topic/read
#          - node/read
#          - group/read
#        attributes:
          # Regexp to filter topic available for group
#          topics-filter-regexp: "test.*"

**Comment by Ranganath9979** [comment]
trying to set up login with ID And PW unable to set up could please help

**Comment by Ranganath9979** [comment]
```
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
 enabled: true
akhq:
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]" # Logger format

  # default kafka properties for each clients, available for admin / producer / consumer (optional)
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed

  # list of kafka cluster available for akhq
  connections:
    my-cluster-plain-text: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "xxxxxxxxxxxxxxxxxxxxxxxxxx"

  pagination:
    page-size: 25 # number of elements per page (default : 25)
    threads: 16 # Number of parallel threads to resolve page

  # Topic list display options (optional)
  topic:
    retention: 172800000 # default retention period when creating topic
    partition: 3 #  default number of partition when creating topic
    replication: 3 # default number of replicas when creating topic
    default-view: HIDE_INTERNAL # default list view (ALL, HIDE_INTERNAL, HIDE_INTERNAL_STREAM, HIDE_STREAM)
    internal-regexps: # list of regexp to be considered as internal (internal topic can't be deleted or updated)
      - "^_.*$"
      - "^.*_schemas$"
      - "^.*connect-config$"
      - "^.*connect-offsets$1"
      - "^.*connect-status$"
    stream-regexps: # list of regexp to be considered as internal stream topic
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"
    skip-consumer-groups: false # Skip loading consumer group information when showing topics

  # Topic display data options (optional)
#  topic-data:
#    sort: OLDEST # default sort order (OLDEST, NEWEST) (default: OLDEST)
#    size: 50 # max record per page (default: 50)
#    poll-timeout: 1000 # The time, in milliseconds, spent waiting in poll if data is not available in the buffer.
# Auth & Roles (optional)
  security:
  basic-auth:
     username: xxxxxxxxxxx
     password: 0696fa9c6a4bbd67998be4553be79923446e41c2668d8d6f10e617652bdca90f
        groups:
  default-group : reader # Default groups for all the user even unlogged user
    # Groups definition
#    groups:
#      - name: admin # Group name
roles:  # roles for the group
#          - topic/read
#          - node/read
#          - group/read
#        attributes:
          # Regexp to filter topic available for group
#          topics-filter-regexp: "test.*"
```

**Comment by tchiotludo** [comment]
```yaml
  basic-auth:
     - username: xxxxxxxxxxx
       password: 0696fa9c6a4bbd67998be4553be79923446e41c2668d8d6f10e617652bdca90f
``` 
is an array with last version 0.16.0
