### ISSUE TITLE
[BUG] enabling ingress: infinity loop - ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by vutkin** [tchiotludo/akhq#292]
Hi all,

when I deployed akhq to kubernetes and enable ingress without tls support, i've got a problem:

The browser says:
This page isn’t working: akhq.test.io redirected you too many times.
ERR_TOO_MANY_REDIRECTS

Does anybody know how to resolve a problem?

values.yaml:
```
akhq:
  image:
    tag: 0.14.1
  service:
    port: 8090
  ingress:
    enabled: true
    paths:
      - "/"
    hosts:
      - 'akhq.test.io'
```
