### ISSUE TITLE
Minimal config example!

### ISSUE THREAD

**Issue by aadrian** [tchiotludo/akhq#313]
Hi,

Please add a minimal config example for a local Kafka as it runs according to the default Kafka quickstart.

This would allow to use this UI on localhost right away.

The https://github.com/tchiotludo/akhq/blob/dev/application.example.yml contains just too many settings, and it takes quite allot of time until one gets a version working correctly :( .

Thank you.

**Comment by tchiotludo** [comment]
Maybe  the good start will be :
```yaml 
akhq:
  connections:
    local:
      properties:
        bootstrap.servers: "localhost:9092"
``` 
This will connect to local cluster, but no schema registry, no connect configuration.

To be honest, it's really hard to find minimal configuration !
