### ISSUE TITLE
Session expiration with Ldap

### ISSUE THREAD

**Issue by apellegr06** [tchiotludo/akhq#318]
Hello,

Is it possible to change the session expiration time when using ldap in kafka hq ?

Regards
Alain

**Comment by tchiotludo** [comment]
```yaml
micronaut:
  session:
    http:
      cookie-max-age:25m
```
I think it will do the trick ;)

**Comment by apellegr06** [comment]
Great ! I will try right now.

Thanks

**Comment by apellegr06** [comment]
Unfortunatly it doesn't work.

**Comment by diarworld** [comment]
We faced with same issue. It seems that it is not a session expiration but inactivity timeout (default 30 minutes):
https://docs.micronaut.io/latest/guide/configurationreference.html#io.micronaut.session.SessionConfiguration
try to set:
```yaml
micronaut:
  session:
    http:
      max-inactive-interval:2h
```
