### ISSUE TITLE
Question: security groups sometimes do not extend each other

### ISSUE THREAD

**Issue by xakassi** [tchiotludo/akhq#321]
Hello!
Thank you very much for your app, it's really great! I have a small question to clarify about security groups.

I have a security configuration like as follow:
```
security:
              default-group: no-roles # Default groups for all the user even unlogged user
              # Groups definition
              groups:
                health-admin: # Group name
                  roles:  # roles for the group
                    - topic/read
                    - topic/insert
                    - topic/delete
                    - topic/config/update
                    - node/read
                    - node/config/update
                    - topic/data/read
                    - topic/data/insert
                    - topic/data/delete
                    - group/read
                    - group/delete
                    - group/offsets/update
                    - registry/read
                    - registry/insert
                    - registry/update
                    - registry/delete
                    - registry/version/delete
                    - acls/read
                    - connect/read
                    - connect/insert
                    - connect/update
                    - connect/delete
                    - connect/state/update
                  attributes:
                    # Regexp to filter topic available for group
                    topics-filter-regexp: ".*health.*"
             
              ldap:
                group:
                  mathematicians:
                    groups:
                      - admin
                  scientists:
                    groups:
                      - reader
                user:
                  tesla:
                    groups:
                      - reader
                      - health-admin
                  gauss:
                    groups:
                      - reader
                      - admin
```

When I log in as "gauss" user I have "admin" rights because "admin" group extends the "reader" group.

But when I log in as "tesla" user I have only "health-admin" rights, so I see only "health" topics and can manage them. But I expected to see all topics (because I have a "reader" group) and be able to manage "health" topics (because I have a "health-admin" group).

Is it ok and by design? Or is it a bug and should be improved?

**Comment by tchiotludo** [comment]
not really sure to understand clearly. 
But `topics-filter-regexp`, is the list of topic available for this group, so will see only topic that match the regexp.

I've the feeling that you must add a ` topics-filter-regexp` on **READER** with negative match on health topic. 

Does it make sense ?

**Comment by xakassi** [comment]
Yes, `topics-filter-regexp` is the list of topics available for this group, and I have `topics-filter-regexp: ".*health.*"` for **HEALTH-ADMIN** group. But I have no any `topics-filter-regexp` for **READER** group. So I expected to see all topics since **READER** group does not have any `topics-filter-regexp` options.

But `topics-filter-regexp` on **READER** with negative match on health topic will not help me to see all topics.

So I'd like just to clarify that `topics-filter-regexp` option for a single user group will affect all user rights regardless of his other groups.

**Comment by xakassi** [comment]
I mean `tesla` user has both groups **HEALTH-ADMIN** and **READER**, so how should they be merged? 
I believed that **HEALTH-ADMIN** roles which allow us to see and manage only health topics should be extended by **READER** roles which allow us to see all other topics.

**Comment by xakassi** [comment]
And I have the second question, I'm not sure maybe it's better to create another issue for that...

I have deployed AKHQ to Openshift and created a liveness and readiness probes like this:
```
livenessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 80
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 90
  timeoutSeconds: 3
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 5
```

And now my logs are full of access logs like this:
`2020-06-22 09:23:30,552 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2020-06-22T09:23:30.54029Z] [Duration: 2 ms] [Url: GET /health HTTP/1.1] [Status: 200] [Ip: x.x.x.x] [Length: 214] [Port: 8080]`

I see that I can disable access-log... But I'd like to see all cases of access except the access to `/health` endpoint.
Is there any way to specify endpoints which should be monitored for access-log? 

Or maybe this feature can be added in the future?
