### ISSUE TITLE
akhq not able to list topics over tls configuration

### ISSUE THREAD

**Issue by Josbrafe** [tchiotludo/akhq#323]
How to I configure the bootstrap servers for tls communication. 

documentation followed: https://raw.githubusercontent.com/tchiotludo/akhq/16c3a781e66732cbe0f93b5885bf7e6e942a296f/application.example.yml

helm configure: 
```
image:
  repository: tchiotludo/akhq
  tag: 0.14.0


configuration: |
  akhq:
    server:
      access-log: 
        enabled: false 
        name: org.akhq.log.access


secrets: |
 akhq:
    connections:
      akhq-exmpl-test:
        properties:
          bootstrap.servers: "SSL://1-kafka.example:9094,SSL://2-kafka.example:9094,SSL://3-kafka.example:9094"
          security.protocol: SSL
          ssl.truststore.location: /kafka/truststore.jks
          ssl.truststore.password: 12838038508508350
          ssl.keystore.location: /kafka/keystore.jks
          ssl.keystore.password: 12838038508508350
          ssl.key.password: 

        schema-registry:
          url: "http://kafka-exmpl1-cp-schema-registry:8081"
          # Basic Auth user / pass
          #basic-auth-username: basic-auth-user
          #basic-auth-password: basic-auth-pass
          #properties: # standard kafka properties (optional)
            #ssl.protocol: TLS

        connect:
          - name: Connect-Service
            url: "http://kafka-exmpl1-cp-kafka-connect:8083"
            # Basic Auth user / pass (optional)
            #basic-auth-username: basic-auth-user
            #basic-auth-password: basic-auth-pass
            # ssl store configuration (optional)
            #ssl-trust-store: /app/truststore.jks
            #ssl-trust-store-password: trust-store-password
            #ssl-key-store: /app/truststore.jks
            #ssl-key-store-password: key-store-password


extraVolumes:
   - name: certificate
     secret:
       secretName: certificate


extraVolumeMounts:
  - name: certificate
    mountPath:  /kafka
```
Error listing topics:
Error below: 
java.lang.RuntimeException: Error for List topics
	at org.akhq.utils.Logger.call(Logger.java:26)
	at org.akhq.modules.AbstractKafkaWrapper.listTopics(AbstractKafkaWrapper.java:52)
	at org.akhq.modules.$KafkaWrapperRequestScopeDefinition$$exec2.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:60)
	at org.akhq.modules.$KafkaWrapperRequestScopeDefinition$Intercepted.listTopics(Unknown Source)
	at org.akhq.repositories.TopicRepository.all(TopicRepository.java:70)
	at org.akhq.repositories.TopicRepository.list(TopicRepository.java:62)
	at org.akhq.controllers.TopicController.list(TopicController.java:121)
	at org.akhq.controllers.$TopicControllerDefinition$$exec1.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2995)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:286)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$16(RoutingInBoundHandler.java:1474)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap.subscribeActual(FlowableSwitchMap.java:49)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at 
Caused by: org.apache.kafka.common.config.ConfigException: Missing required configuration "bootstrap.servers" which has no default value.
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:477)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:467)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
	at org.apache.kafka.clients.admin.AdminClientConfig.<init>(AdminClientConfig.java:208)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:59)
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:39)
	at org.akhq.modules.KafkaModule.getAdminClient(KafkaModule.java:100)
	at org.akhq.modules.AbstractKafkaWrapper.lambda$listTopics$1(AbstractKafkaWrapper.java:53)
	at org.akhq.utils.Logger.call(Logger.java:19)
