### ISSUE TITLE
Type NodePort not working

### ISSUE THREAD

**Issue by marcoacarvalho** [tchiotludo/akhq#328]
I've set service type to NodePort but keeps creating service type ClusterIP, there is anything that I'm missing?
(I'm using flux/helm-operator)
```yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: akhq
  namespace: mrebel-dev
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: akhq
  chart:
    repository: https://akhq.io/
    name: akhq
    version: 0.1.2
  values:
    secrets: |
      akhq:
        connections:
          mrebel-dev-plain-text:
            properties:
              bootstrap.servers: "kafka:9092"
    service:
      enabled: true
      type: NodePort
      port: 80
```
```bash
 kubectl get service akhq
NAME   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
akhq   ClusterIP   172.20.185.240   <none>        80/TCP    10m
```
