### ISSUE TITLE
AKHQ and Connect Distributed?

### ISSUE THREAD

**Issue by walkamongus** [tchiotludo/akhq#338]
Dow AKHQ support connections to Connect when it is run in distributed mode? If so is there an example config? I've tried using known working SSL keystore/truststore but run into `PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

Typically when I connect to my mTLS-secured distributed Connect clusters I do so with simple HTTP passing a client cert and key, but I'm not clear on how AKHQ is making this connection.

**Comment by walkamongus** [comment]
It appears to be something to do with loading the keystore from a file. I only trigger the error when adding `ssl-key-store` to the connect config and I see no incoming connections in my Connect logs. I tested connecting to my Connect URL with the truststore and keystore from my `application.yml` using https://github.com/ChristopherSchultz/ssltest and the connection works.

**Comment by tchiotludo** [comment]
Sorry holidays times for me ⛱️
Will look at next week 🤪

**Comment by tchiotludo** [comment]
Here in [application.example.yml](https://github.com/tchiotludo/akhq/blob/dev/application.example.yml) an example configuration : 
```yaml 
      connect:
        - name: connect-1
          url: "http://connect:8083"
          # Basic Auth user / pass (optional)
          basic-auth-username: basic-auth-user
          basic-auth-password: basic-auth-pass
          # ssl store configuration (optional)
          ssl-trust-store: /app/truststore.jks
          ssl-trust-store-password: trust-store-password
          ssl-key-store: /app/truststore.jks
          ssl-key-store-password: key-store-password
```

Can you provide your configuration files please ?

**Comment by walkamongus** [comment]
My configuration looks like this:
```
 connect:
        - name: connect-1
          url: "https://my-connect.my-domain.com:8083"
          ssl-trust-store: /path/to/system/truststore
          ssl-trust-store-password: truststore-password
          ssl-key-store: /path/to/system/keystore
          ssl-key-store-password: keystore-password
```
