### ISSUE TITLE
Do not display login button when login is disabled or add an option to hide it

### ISSUE THREAD

**Issue by haidaraM** [tchiotludo/akhq#361]
Hello. First of all, thank you for your work on AKHQ :-)

We are using an AWS ALB in front of AKHQ. The ALB is responsible for authentication with Cognito. We use a dedicated default group in AKHQ. 
In our case, the login button in the UI is then useless since no authentication is done inside AKHQ. I'm wondering if there is way to completely disable/hide the login button is that case ? We already disabled the login :
```yaml
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: false
      logout:
        enabled: false
```
I can work on implementing this feature if needed :-). Just need to know where to start
