### ISSUE TITLE
LDAP Configuration

### ISSUE THREAD

**Issue by ritheshrithu** [tchiotludo/akhq#371]
Hi 

Thanks for the great Tool.

I am trying to use LDAP authentication with my own LDAP Docker setup. But in Login Page if i try to login with the credentials, it stays in the same login page.

I have checked the logs but it says nothing.

`akhq_1               | 2020-08-26 11:27:22,637 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2020-08-26T11:27:22.631071Z] [Duration: 5 ms] [Url: POST /login 303] [Status: 0] [Ip: 192.168.48.1] [Length: 8080] [Port: {}]`

Below is my AKHQ config.

```
akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        micronaut:
                security:
                    ldap:
                    default:
                        enabled: true
                        context:
                            server: 'ldap://localhost:389'
                            managerDn: 'cn=admin,dc=akhq,dc=io'
                            managerPassword: 'test1234'
                        search:
                            base: "dc=akhq,dc=com"
                        groups:
                            enabled: true
                            base: "dc=akhq,dc=com"
        akhq:
         connections:
           kafka-cluster:
             properties:
                bootstrap.servers: "kafka:9092"
         security:
                ldap:
                    group:
                        group-ldap-1:
                        name: "developer"
                        groups:
                            - developer
                    user:
                        dev:
                        groups:
                            - developer
    ports:
      - 8081:8080
    links:
      - kafka
```

Could you please help here.

Thanks in advance

**Comment by tchiotludo** [comment]
Hi, 
can you format the yaml part please ? 

Also have you tried the debugging part : 
```bash 
curl -i -X POST -H "Content-Type: application/json" \
       -d '{ "configuredLevel": "TRACE" }' \
       http://localhost:8080/loggers/io.micronaut.configuration.security
```

**Comment by tchiotludo** [comment]
As i can see there is a lot of indent trouble in your config files. 

Try to fix the indent first ;)

**Comment by ritheshrithu** [comment]
Thanks for the response. I am checking the trace log.

**Comment by ritheshrithu** [comment]
Here is the response from the curl.

`$ curl -i -X POST -H "Content-Type: application/json" -d '{ "configuredLevel": "TRACE" }' http://localhost:8081/loggers/io.micronaut.configuration.security                                                        HTTP/1.1 200 OK                                                                                                                                                                                                    Date: Wed, 26 Aug 2020 11:46:22 GMT                                                                                                                                                                                connection: keep-alive                                                                                                                                                                                             transfer-encoding: chunked`

**Comment by tchiotludo** [comment]
The curl activate the debug log, look at the akhq log when you try to login to have more insight. 
And the ident is still wrong, must be like that I think : 
```yaml
akhq:
  image: tchiotludo/akhq
  environment:
    AKHQ_CONFIGURATION: |
      micronaut:
        security:
          ldap:
          default:
            enabled: true
            context:
              server: 'ldap://localhost:389'
              managerDn: 'cn=admin,dc=akhq,dc=io'
              managerPassword: 'test1234'
            search:
              base: "dc=akhq,dc=com"
            groups:
              enabled: true
              base: "dc=akhq,dc=com"
      akhq:
        connections:
          kafka-cluster:
            properties:
              bootstrap.servers: "kafka:9092"
        security:
          ldap:
            group:
              group-ldap-1:
              name: "developer"
              groups:
                  - developer
            user:
                dev:
                  groups:
                      - developer
  ports:
    - 8081:8080
  links:
    - kafka
```
