### ISSUE TITLE
Configuration LDAP

### ISSUE THREAD

**Issue by gerardgorrion** [tchiotludo/akhq#394]
Hi all,

We are deploying AKHQ and want to loggin via LDAP.

Here the config added to helm\akhq\values.yml file:

```
micronaut:
  security:
    # Ldap authentificaton configuration
    ldap:
      default:
        enabled: true
        context:
          server: 'ldap://ourldapcompany:389'
          managerDn: "CN=user,OU=CORP,OU=USERS,DC=company,DC=CORP"
          managerPassword: 'pass'
        search:
          base: "ou=SMSGROUPS,dc=company,dc=corp"
        groups:
          enabled: true
          base: "CN=groupname,OU=Listas de Distribucion,OU=GROUPS,DC=company,DC=corp"

 akhq:
    server:
      access-log:
        enabled: false
    security:
      default-group: reader
      groups:
        reader:
          roles:
            - topic/read
            - node/read
            - topic/data/read
            - group/read
            - registry/read
            - connect/read
      basic-auth:
        admin:
          password: # echo -n "<YOUR_PASSWORD>" | sha256sum
          groups:
            - admin
      ldap:
        group:
          group-ldap-1:
            name: "groupname"
            groups: # Akhq groups list
              - reader
```

When we test the connection via LDAP tester (LDP.exe as example), the connection was established. 
Now we need to test, deploying locally (via Docker), but when try to log only recieve this message:

```
2020-09-10 11:58:55,553 INFO pGroup-1-2 org.akhq.log.access [Date: 2020-09-10T11:58:55.546773Z] [Duration: 6 ms] [Url: POST /login 303] [Status: 0] [Ip: 172.19.0.1] [Length: 8080] [Port: {}]

2020-09-10 11:58:55,576 INFO pGroup-1-3 org.akhq.log.access [Date: 2020-09-10T11:58:55.566723Z] [Duration: 9 ms] [Url: GET /api/me 200] [Status: 574] [Ip: 172.19.0.1] [Length: 8080] [Port: {}]
```
and the login page didn't change.

How can we test the LDAP connection result on Docker and AKHQ installed locally?

Regards,

**Comment by tchiotludo** [comment]
Debuging ldap connection can be done with
```bash
curl -i -X POST -H "Content-Type: application/json" \
       -d '{ "configuredLevel": "TRACE" }' \
       http://localhost:8080/loggers/io.micronaut.configuration.security
```

**Comment by gerardgorrion** [comment]
Thanks for your answer,

Here the curl:
```
$ curl -i -X POST -H "Content-Type: application/json"        -d '{ "configuredLevel": "TRACE" }'        http://localhost:8080/loggers/io.micronaut.configuration.security
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    30    0     0  100    30      0    909 --:--:-- --:--:-- --:--:--   967HTTP/1.1 200 OK
Date: Mon, 14 Sep 2020 06:00:35 GMT
connection: keep-alive
transfer-encoding: chunked
```
And the docker log:
```
akhq_1             | 2020-09-14 06:02:06,499 INFO  pGroup-1-5 org.akhq.log.access        [Date: 2020-09-14T06:02:06.48981Z] [Duration: 9 ms] [Url: POST /loggers/io.micronaut.configuration.security 200] [Status: 0] [Ip: 172.18.0.1] [Length: 8080] [Port: {}]
```
If the answer it http/1.1 200 ok should be work, right? Maybe some bad configuration on yml file?

Regards,

**Comment by tchiotludo** [comment]
After you enabled the log, you need to try to login and you will have a lot of logs about ldap, that will help you to understand what's happening.

**Comment by gerardgorrion** [comment]
And if nothing was showed? Bad configuration on values.yml file?

**Comment by gerardgorrion** [comment]
Hi again,

We connect LDAP via 389.
Now we try to connect via TLS,  Steps to do it:

Verify jdk version:

```
# java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment 18.9 (build 11.0.8+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10, mixed mode)
```
Locate cacert of jvm version:

```
/usr/lib/jvm/java-1.11.0-openjdk-amd64/lib/security/cacerts
```

Import cert to cacert:

```
/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/keytool -keystore  cacerts  -importcert -alias SERtifOTPService -file  /app/ldap.cer
```

Add jvm options configure:
```
#SSL trustStore
-Djavax.net.ssl.trustStore="/usr/lib/jvm/java-1.11.0-openjdk-amd64/lib/security/cacerts"
-Djavax.net.ssl.trustStorePassword="passwordofcacertsfile"
```

Here the application.yml
```
micronaut:
  security:
    ldap:
      default:
        enabled: true
        context:
          server: 'ldaps://ourldap.corp:636'
          managerDn: 'username'
          managerPassword: 'password'
        search:
          enabled: true
          base: "OU=CORP,OU=USERS,DC=company,DC=corp"
          filter: "sAMAccountName={0}"
        groups:
          enabled: true
          subtree: true
          base: 'OU=securitygroups,OU=GROUPS,DC=company,DC=corp'
          filter: 'member={0}'
akhq:
  connections:
    docker-kafka-server:
      properties:
        bootstrap.servers: "kafka:9092"
      schema-registry:
        url: "http://schema-registry:8085"
      connect:
        url: "http://connect:8083"
configuration:
  akhq:
    security:
      ldap:
        group:
          adgroupname:
            groups:
              - reader
```

Debug log:

```
2020-09-21 07:23:50,165 DEBUG pGroup-1-4 LdapAuthenticationProvider Starting authentication with configuration [default]

2020-09-21 07:23:50,166 DEBUG pGroup-1-4 LdapAuthenticationProvider Attempting to initialize manager context

2020-09-21 07:23:50,311 DEBUG pGroup-1-4 LdapAuthenticationProvider Failed to create manager context. Returning unknown authentication failure. Encountered {}

javax.naming.CommunicationException: ourldap.corp:636
```

Is correct this config? 

Thanks

**Comment by tchiotludo** [comment]
I think the issue is here : 
> Locate cacert of jvm version:
You don't need the jvm certificate, you need to CA that sign your ldaps server to be imported in the truststore.
So you need to get this CA certificate from the ldaps server admin in order to add this on the truststore

**Comment by gerardgorrion** [comment]
I used this certificate of our AD extracted from LDAPs via Apache directory studio connecting in port 636.

```
-RootCompCA
  -SubCompCA
```
We located it into docker image at route:
```
/app/ldap.cer
```
and imported into cacert of our jvm with this command:
```
/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/keytool -keystore  cacerts  -importcert -alias SERtifOTPService -file  /app/ldap.cer
```
And then, we indicate the location of our jvm cacert with the ldaps certificate, into jvm.options
```
#SSL trustStore
-Djavax.net.ssl.trustStore="/usr/lib/jvm/java-1.11.0-openjdk-amd64/lib/security/cacerts"
-Djavax.net.ssl.trustStorePassword="passwordofcacertsfile"
```

What cacert do you reffer when you say "So you need to get this CA certificate from the ldaps server admin in order to add this on the truststore"?jvm cacert or another? we check version of jvm and add ldaps cert.

**Comment by gerardgorrion** [comment]
solved:

Import ldap sub CAroot cert
Import ldap CAroot cert
```
/usr/local/openjdk-11/bin/keytool -keystore  ../lib/security/cacerts  -importcert -alias Ldap -file  /app/ldap.cer
/usr/local/openjdk-11/bin/keytool -keystore  ../lib/security/cacerts  -importcert -alias Ldap2 -file  /app/ldap2.cer
```
change jvm.options configure
```
#SSL trustStore
-Djavax.net.ssl.trustStore=/usr/local/openjdk-11/lib/security/cacerts
-Djavax.net.ssl.trustStorePassword=password
```
we don't need to use "".

and the application.yml:
```
micronaut:
  security:
    ldap:
      default:
        enabled: true
        context:
          server: 'ldaps://ourldap.corp:636'
          managerDn: 'username'
          managerPassword: 'password'
        search:
          enabled: true
          base: "OU=CORP,OU=USERS,DC=company,DC=corp"
          filter: "sAMAccountName={0}"
        groups:
          enabled: true
          subtree: true
          base: 'OU=securitygroups,OU=GROUPS,DC=company,DC=corp'
          filter: 'member={0}'
akhq:
  connections:
    docker-kafka-server:
      properties:
        bootstrap.servers: "kafka:9092"
      schema-registry:
        url: "http://schema-registry:8085"
      connect:
        url: "http://connect:8083"
configuration:
  akhq:
    security:
      ldap:
        group:
          adgroupname:
            groups:
              - reader
```

Thanks!!!
