### ISSUE TITLE
Micronaut config to login

### ISSUE THREAD

**Issue by gerardgorrion** [tchiotludo/akhq#410]
Hi all,

We already configured ldap micronaut config to loggin, debug was ok and get token from access:

```
set-cookie: SESSION=YTU2YTk5MmYtMDNhOS00YWJjLWE3MzMtMzA3OTE3ZjE5ZTc3; Path=/; HTTPOnly
```
In a short lapsus time, up the screen show a correct login in green color. 

![login](https://user-images.githubusercontent.com/35425181/94163596-54cdc400-fe88-11ea-8480-c5c78be3abda.PNG)

The problem is that nothing happens after login, and we can't navigate for other akhq resources, like /ui page.

What is the minium configuration to log into akhq at micronaut? We test with:

```
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
        path: "http://localhost:8080/login"
      logout:
        enabled: true
        path: "http://localhost:8080/logout"
        get-allowed: true
    session:
      enabled: true
      login-success-target-url: "http://localhost:8080/"
      logout-target-url: "http://localhost:8080/"
      forbidden-target-url: "http://localhost:8080/login/forbidden"
      unauthorized-target-url: "http://localhost:8080/login/unauthorized"
      login-failure-target-url: "http://localhost:8080/login/failed"
    ldap: #after here there is ldap config
```

Thanks a lot!

**Comment by tchiotludo** [comment]
Mostly there is a lot of changes on`dev` version, we rewrite all the login part. 
Can you try with this version ? (no more session and jwt cookie) 

Thanks

**Comment by gerardgorrion** [comment]
dev version is no longer work, we run with (port 8081 to run with the other container with "latest" version with port 8080 active):

```
docker run -p 8081:8080 -v C:\Users\myuser\akhq\application\application.yml:/app/application.yml tchiotludo/akhq:dev
```
I verifyed the application.yml file and is in /app, but the http page doesn't load and log show:

```
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by gerardgorrion** [comment]
![dev](https://user-images.githubusercontent.com/35425181/94167123-6dd87400-fe8c-11ea-90c0-a339d488c034.PNG)

**Comment by tchiotludo** [comment]
really surprise, I use it everyday and it's working well ! 
please provide the full stacktrace :)

**Comment by gerardgorrion** [comment]
```
2020-09-24 15:38:37,115 INFO  main       i.m.runtime.Micronaut      Startup completed in 3019ms. Server Running: http://990253823adb:8080
2020-09-24 15:38:57,974 ERROR pGroup-1-2 .s.n.RoutingInBoundHandler Unexpected error occurred: Failed to inject value for field [connect] of class: org.akhq.configs.Connection

Message: Error resolving field value [akhq.connections.docker-kafka-server.connect]. Property doesn't exist or cannot be converted
Path Taken: new KafkaWrapperFilter([KafkaModule kafkaModule]) --> KafkaModule.connections --> Connection.connect
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [connect] of class: org.akhq.configs.Connection

Message: Error resolving field value [akhq.connections.docker-kafka-server.connect]. Property doesn't exist or cannot be converted
```

**Comment by gerardgorrion** [comment]
seem like the config file need:
```
2020-09-24 15:49:50,820 ERROR pGroup-1-2 .s.n.RoutingInBoundHandler Unexpected error occurred: Couldn't find any clusters on your configuration file, please ensure that the configuration file is loaded correctly
```
We are testing in docker without kafka cluster?

**Comment by tchiotludo** [comment]
can you provide a full configuration files ? seems weird

**Comment by gerardgorrion** [comment]
```
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
        path: "http://localhost:8080/login"
      logout:
        enabled: true
        path: "http://localhost:8080/logout"
        get-allowed: true
    session:
      enabled: true
      login-success-target-url: "http://localhost:8080/"
      logout-target-url: "http://localhost:8080/"
      forbidden-target-url: "http://localhost:8080/login/forbidden"
      unauthorized-target-url: "http://localhost:8080/login/unauthorized"
      login-failure-target-url: "http://localhost:8080/login/failed"
  ldap:
    default:
      enabled: true
      context:
        server: 'ldaps://ourldap:636'
        managerDn: 'username'
        managerPassword: 'pass'
      search:
        enabled: true
        base: "OU=CORP,OU=USERS,DC=company,DC=corp"
        filter: "sAMAccountName={0}"
      groups:
        enabled: true
        subtree: true
        base: 'OU=securitygroup,OU=GROUPS,DC=company,DC=corp'
        filter: 'member={0}'
akhq:
  connections:
    docker-kafka-server:
      properties:
        bootstrap.servers: "kafka:9092"
      schema-registry:
        url: "http://schema-registry:8085"
      connect:
        url: "http://connect:8083"
configuration:
  akhq:
    security:
      ldap:
        groups:
          IC_Operator:
            groups:
              - reader
```

**Comment by tchiotludo** [comment]
``yaml
      connect:
        url: "http://connect:8083"
```
must be 
```yaml
      connect:
        - url: "http://connect:8083"
```

**Comment by gerardgorrion** [comment]
correct, now the akhq page is loaded, but access to login is not possible!
![error](https://user-images.githubusercontent.com/35425181/94172977-80a27700-fe93-11ea-8ab7-88e30bba361e.PNG)
when put http://127.0.0.1:8080/ui/login, show this error and no login page loaded.

We lose on dev environment test possibility withouth kafka?

**Comment by gerardgorrion** [comment]
```
2020-09-24 16:25:13,844 WARN pGroup-1-5 org.akhq.log.access [Date: 2020-09-24T16:25:13.826995Z] [Duration: 16 ms] [Url: GET /api/docker-kafka-server/topic?search=&show=HIDE_INTERNAL&page=1] [Status: 500] [Ip: 172.19.0.1] [Length: 1093] [Port: 8080]

2020-09-24 16:25:16,617 INFO pGroup-1-2 org.akhq.log.access [Date: 2020-09-24T16:25:16.585863Z] [Duration: 31 ms] [Url: GET /api/auths] [Status: 200] [Ip: 172.19.0.1] [Length: 42] [Port: 8080]

2020-09-24 16:25:16,685 ERROR pGroup-1-2 o.a.c.ErrorController Failed to create new KafkaAdminClient

org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
```

**Comment by tchiotludo** [comment]
![image](https://user-images.githubusercontent.com/2064609/94173824-c01d9300-fe94-11ea-90de-9a8419c5ca56.png)

the kafka url seems to be wrong

**Comment by gerardgorrion** [comment]
```
2020-09-24 16:42:36,676 INFO pGroup-1-4 org.akhq.log.access [Date: 2020-09-24T16:42:36.639768Z] [Duration: 33 ms] [Url: GET /api/auths] [Status: 200] [Ip: 172.19.0.1] [Length: 42] [Port: 8080]
2020-09-24 16:42:36,750 WARN 1-thread-2 o.a.k.clients.ClientUtils Couldn't resolve server kafka:9092 from bootstrap.servers as DNS resolution failed for kafka
2020-09-24 16:42:36,754 ERROR pGroup-1-4 o.a.c.ErrorController Failed to create new KafkaAdminClient
org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
```

Only is possible to test with kafka server listening??

**Comment by tchiotludo** [comment]
Yes :smile: it's a kafka app :laughing: that don't have any sense without kafka :smile:

**Comment by gerardgorrion** [comment]
ok, tomorrow I will try to clone dev code, apply my application.yml and deploy docker compose with all servers, should be work fine with this, right?

**Comment by tchiotludo** [comment]
Don't understand, why not use the `dev` docker image ?

**Comment by gerardgorrion** [comment]
I use the dev docker image to test, but we need kafka cluster to avoid the error and with docker-compose kafka is ready to use, right?

**Comment by gerardgorrion** [comment]
Oook, i tested these 3 versions:

1 - download last dev version from github, launch docker-compose and try to login
2 - Create a container with oficial akhq dev image, put in the same network of docker compose create (akhq bridge)
3 - launch a container with docker akhq dev image and use our dev kafka to test

After these 3 test, the java error dissapear. But the problem with login button is the same at 3 scenarios: from any link, when click at loguin, page show in a short time login page and return into http://127.0.0.1:8080/ui/development/topic

![get](https://user-images.githubusercontent.com/35425181/94237259-dbc57f80-ff0e-11ea-847f-d71711d72893.PNG)


```
GET /api/auths HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1:8080/ui/login
Connection: keep-alive


HTTP/1.1 200 OK
Date: Fri, 25 Sep 2020 07:05:09 GMT
Content-Type: application/json
content-length: 42
connection: keep-alive

```

![get](https://user-images.githubusercontent.com/35425181/94237331-fd266b80-ff0e-11ea-9b56-a209cfa0ed95.PNG)

```
GET /api/development/topic?search=&show=HIDE_INTERNAL&page=1 HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1:8080/ui/development/topic
Connection: keep-alive

HTTP/1.1 409 Conflict
Date: Fri, 25 Sep 2020 07:06:09 GMT
Content-Type: application/json
content-length: 256
connection: keep-alive
```

We try with IE, Chrome and Firefox.

Application.yml:
```
micronaut:
  security:
    ldap:
      default:
        enabled: true
        context:
          server: 'ldap://ourldap:389'
          managerDn: 'user'
          managerPassword: 'pass'
        search:
          enabled: true
          base: "OU=CORPHOU=USERS,DC=company,DC=corp"
          filter: "sAMAccountName={0}"
        groups:
          enabled: true
          subtree: true
          base: 'OU=securitygroup,OU=GROUPS,DC=company,DC=corp'
          filter: 'member={0}'
akhq:
  connections:
    development:
      properties:
        bootstrap.servers: "ourkafka:9092"
      schema-registry:
        - url: "http://schema-registry:8085"
      connect:
        - url: "http://connect:8083"
configuration:
  akhq:
    security:
      ldap:
        groups:
          IC_Operator:
            groups:
              - reader
```

Thanks!

**Comment by gerardgorrion** [comment]
![login](https://user-images.githubusercontent.com/35425181/94239747-8c814e00-ff12-11ea-81d1-2822155de954.PNG)

I have take a screenshot of what you see before I load the topics web page, in case it helps.

**Comment by gerardgorrion** [comment]
![get](https://user-images.githubusercontent.com/35425181/94240234-4d9fc800-ff13-11ea-8905-f331bca68733.PNG)

I have take a screenshot of what can see before it load the topics web page, in case it helps.

**Comment by tchiotludo** [comment]
Do you have follow this : 
https://github.com/tchiotludo/akhq#security

We need to enable security and provide a jwt secret with the dev version.

**Comment by gerardgorrion** [comment]
What secret do we need to JWT?

**Comment by tchiotludo** [comment]
this one : https://github.com/tchiotludo/akhq#jwt 
To allow to encrypt the cookie and to secure this one

**Comment by gerardgorrion** [comment]
![get](https://user-images.githubusercontent.com/35425181/94251677-26e98d80-ff23-11ea-8606-60d49ccf5573.PNG)

?¿

**Comment by gerardgorrion** [comment]
Added code:
```
micronaut:
  security:
    enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: 'test'
    ldap: ##same code 
```

**Comment by gerardgorrion** [comment]
Hi, someone can help me please with this issue?

Thanks!

**Comment by gerardgorrion** [comment]
I tested the same application.yml on both environments and :

- We can log into latest version, showing the login ok and no allow to navigate to other page.
- Into dev version showing the AKHQ.io image when go to login page and not allow to log.

rest of the akhq functions are working fine. 
some idea? thaaaanks!

```
micronaut:
  security:
    enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "secreto"
    ldap:
      default:
        enabled: true
        context:
          server: 'ldap://ourldap.corp:389'
          managerDn: 'user'
          managerPassword: 'pass'
        search:
          enabled: true
          base: "OU=CORP,OU=USERS,DC=company,DC=corp"
          filter: "sAMAccountName={0}"
        groups:
          enabled: true
          subtree: true
          base: 'OU=securitygroup,OU=GROUPS,DC=company,DC=corp'
          filter: 'member={0}'
akhq:
  connections:
    development:
      properties:
        bootstrap.servers: "testserver:9092"
      schema-registry:
        - url: "http://schema-registry:8085"
      connect:
        - url: "http://connect:8083"
configuration:
  akhq:
    security:
    default-group: reader
    ldap:
      groups:
        int_operator:
          groups:
            - reader
```

**Comment by tchiotludo** [comment]
You are hitting a Breaking compatibility of dev version ! 

We changed a lot of things here : https://github.com/tchiotludo/akhq/commit/5ab788da22529ede3c7b640f1918304511cea6f0 in the configuration files, the `README.md` is for the dev version ! 

Mostly we used the same name everywhere on last dev since we have a lot of issue reported with that.

My advice, stick on the `dev` version and compare your values with https://github.com/tchiotludo/akhq/blob/dev/application.example.yml

**Comment by tchiotludo** [comment]
You can also see here http://localhost:8080/api/auths if the login really enabled

**Comment by gerardgorrion** [comment]
{"loginEnabled":true,"formEnabled":false}

**Comment by tchiotludo** [comment]
seems to be : 
```yaml
micronaut:
  security:
    enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "secreto"
    ldap:
      default:
        enabled: true
        context:
          server: 'ldap://ourldap.corp:389'
          managerDn: 'user'
          managerPassword: 'pass'
        search:
          enabled: true
          base: "OU=CORP,OU=USERS,DC=company,DC=corp"
          filter: "sAMAccountName={0}"
        groups:
          enabled: true
          subtree: true
          base: 'OU=securitygroup,OU=GROUPS,DC=company,DC=corp'
          filter: 'member={0}'
akhq:
  connections:
    development:
      properties:
        bootstrap.servers: "testserver:9092"
      schema-registry:
        - url: "http://schema-registry:8085"
      connect:
        - url: "http://connect:8083"

  security:
    ldap:
      default-group: reader
      groups:
        - name: int_operator
          groups:
            - reader
```
