### ISSUE TITLE
try to deploy akhq in Standalone and my kafka cluster has not authentication parameter

### ISSUE THREAD

**Issue by chi-miel** [tchiotludo/akhq#415]
Hello,

I try to setup akhq, i follow standalone indication in Readme file.

I use jar file version 0.15.

it is starting well but when i want access to the home page i have java exectpion : 

2020-09-25 19:21:02,255 INFO  main       i.m.runtime.Micronaut      Startup completed in 1463ms. Server Running: http://10.66.85.52:9090
2020-09-25 19:21:18,339 INFO  pGroup-1-2 org.akhq.log.access        [Date: 2020-09-25T19:21:17.970152+02:00] [Duration: 367 ms] [Url: GET /] [Status: 200] [Ip: 611] [Length: 10.66.85.52] [Port: 9090]
2020-09-25 19:21:18,609 WARN  pGroup-1-2 org.akhq.log.access        [Date: 2020-09-25T19:21:18.407265+02:00] [Duration: 201 ms] [Url: GET /static/css/vendor.css] [Status: 404] [Ip: 98] [Length: 10.66.85.52] [Port: 9090]
2020-09-25 19:21:18,611 WARN  pGroup-1-3 org.akhq.log.access        [Date: 2020-09-25T19:21:18.453054+02:00] [Duration: 158 ms] [Url: GET /static/css/main.css] [Status: 404] [Ip: 96] [Length: 10.66.85.52] [Port: 9090]
2020-09-25 19:21:18,612 WARN  pGroup-1-5 org.akhq.log.access        [Date: 2020-09-25T19:21:18.496778+02:00] [Duration: 115 ms] [Url: GET /static/js/main.js] [Status: 404] [Ip: 94] [Length: 10.66.85.52] [Port: 9090]
2020-09-25 19:21:18,610 WARN  pGroup-1-4 org.akhq.log.access        [Date: 2020-09-25T19:21:18.471345+02:00] [Duration: 139 ms] [Url: GET /static/js/vendor.js] [Status: 404] [Ip: 96] [Length: 10.66.85.52] [Port: 9090]
2020-09-25 19:21:18,626 WARN  pGroup-1-2 org.akhq.log.access        [Date: 2020-09-25T19:21:18.621392+02:00] [Duration: 4 ms] [Url: GET /static/img/logo.svg] [Status: 404] [Ip: 96] [Length: 10.66.85.52] [Port: 9090]
2020-09-25 19:21:25,832 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2020-09-25T19:21:25.780537+02:00] [Duration: 52 ms] [Url: GET /akhq] [Status: 307] [Ip: 0] [Length: 10.66.85.52] [Port: 9090]
2020-09-25 19:21:25,848 ERROR pGroup-1-5 o.a.c.ErrorController      null
java.lang.NullPointerException: null
        at io.micronaut.web.router.resource.ReactStaticResourceResolver.resolve(ReactStaticResourceResolver.java:34)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.matchFile(RoutingInBoundHandler.java:630)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:557)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:140)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:196)
        at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:121)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:191)
        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:153)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at org.akhq.middlewares.HttpServerAccessLogHandler.channelRead(HttpServerAccessLogHandler.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

this my config : 
micronaut:

  server:
    port: 9090
    host: "***********"
    context-path: "/akhq" # if behind a reverse proxy, path to akhq without trailing slash (optional). Example: akhq is
                     # behind a reverse proxy with url http://my-server/akhq, set base-path: "/akhq".
                     # Not needed if you're behind a reverse proxy with subdomain http://akhq.my-server/
    
akhq:
```
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [Length: {}] [Port: {}]" # Logger format

  # list of kafka cluster available for akhq
  connections:
    siem: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "eirv-siem-kafka-01.eolas-services.com:9092"
        group.id: "graylog"

  pagination:
    page-size: 25 # number of elements per page (default : 25)
    threads: 16 # Number of parallel threads to resolve page

    # Basic auth configuration
    basic-auth:
      - username: admin # Username
        password: 31f7a65e315586ac198bd798b6629ce4903d0899476d5741a9f32e2e521b6a66 # Password in sha256
        groups: # Groups for the user
          - admin
          - topic-reader
```

My kafka cluster is not configured with authentication.

Someone can help me ?

Thank you

**Comment by tchiotludo** [comment]
I think you should try with [dev](https://github.com/tchiotludo/akhq#development-environment) version.
There is a fix for context-path : https://github.com/tchiotludo/akhq/issues/357

**Comment by chi-miel** [comment]
Thank you for the quick response.

i wil try monday !

**Comment by chi-miel** [comment]
Hello,

It's work with the jar file in dev !

I set basic authentication but when i hit the login portal, i have a warning popup said "page not found" whereas the login portal is displayed.

here my config : 
```

micronaut:
  security:
    enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: *************

  server:
    port: 9090
    host: "*********"
    context-path: "/akhq" # if behind a reverse proxy, path to akhq without trailing slash (optional). Example: akhq is
                     # behind a reverse proxy with url http://my-server/akhq, set base-path: "/akhq".
                     # Not needed if you're behind a reverse proxy with subdomain http://akhq.my-server/
    
akhq:
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [Length: {}] [Port: {}]" # Logger format

  # # default kafka properties for each clients, available for admin / producer / consumer (optional)
  # clients-defaults:
  #   consumer:
  #     properties:
  #       isolation.level: read_committed

  # list of kafka cluster available for akhq
  connections:
    siem: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "eirv-siem-kafka-01.eolas-services.com:9092"

  pagination:
    page-size: 25 # number of elements per page (default : 25)
    threads: 16 # Number of parallel threads to resolve page

  # Topic list display options (optional)
  topic:
    retention: 172800000 # default retention period when creating topic
    partition: 3 #  default number of partition when creating topic
    replication: 3 # default number of replicas when creating topic
    default-view: ALL # default list view (ALL, HIDE_INTERNAL, HIDE_INTERNAL_STREAM, HIDE_STREAM)
    internal-regexps: # list of regexp to be considered as internal (internal topic can't be deleted or updated)
      - "^_.*$"
      - "^.*_schemas$"
      - "^.*connect-config$"
      - "^.*connect-offsets$1"
      - "^.*connect-status$"
    stream-regexps: # list of regexp to be considered as internal stream topic
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"
    skip-consumer-groups: false # Skip loading consumer group information when showing topics

  # Topic display data options (optional)
  topic-data:
    sort: OLDEST # default sort order (OLDEST, NEWEST) (default: OLDEST)
    size: 50 # max record per page (default: 50)
    poll-timeout: 1000 # The time, in milliseconds, spent waiting in poll if data is not available in the buffer.

  # Auth & Roles (optional)
  security:
    default-group: reader # Default groups for all the user even unlogged user
    # Groups definition
    groups:
      - name: admin # Group name
        roles:  # roles for the group
          - topic/read
          - topic/insert
          - topic/delete
          - topic/config/update
          - node/read
          - node/config/update
          - topic/data/read
          - topic/data/insert
          - topic/data/delete
          - group/read
          - group/delete
          - group/offsets/update
          - registry/read
          - registry/insert
          - registry/update
          - registry/delete
          - registry/version/delete
          - acls/read
          - connect/read
          - connect/insert
          - connect/update
          - connect/delete
          - connect/state/update
        # attributes:
        #   # Regexp to filter topic available for group
        #   topics-filter-regexp: "graylog.*"
      # - name: topic-reader # Other group
      #   roles:
      #     - topic/read
      #   attributes:
      #     topics-filter-regexp: "test\\.reader.*"

    # Basic auth configuration
    basic-auth:
      - username: admin # Username
        password: *****************
        groups: # Groups for the user
          - admin

```
