### ISSUE TITLE
Callback URL mismatch

### ISSUE THREAD

**Issue by dblooman** [tchiotludo/akhq#421]
Using Auth0 with OIDC, getting

```sh
Callback URL mismatch.
The provided redirect_uri is not in the list of allowed callback URLs.
```

The URL is correct, its the protocol that is wrong. the redirect_uri is `http://foo.com` instead of `https://foo.com`. Is there an option/header that is required to send the correct protocol to the auth provider?

**Comment by tchiotludo** [comment]
Depending, are you using a reverse proxy in front of akhq ?

If yes, you can tune the parameters here : https://docs.micronaut.io/latest/guide/index.html#hostResolution

**Comment by dblooman** [comment]
It's running on kubernetes behind an AWS ALB

**Comment by tchiotludo** [comment]
I don't have any AWS ALB in order to test, but with GCP k8s LB in need to add this : 

```yaml 
micronaut:
  server:
    host-resolution:
      host-header: Host
      protocol-header: X-Forwarded-Proto
```

GCP don't add a header `X-Forwarded-Host` and keep the original `Host`. 
Maybe it's the same on AWS ?
