### ISSUE TITLE
Skip Consummer Group not working in 0.15.0

### ISSUE THREAD

**Issue by clallavena** [tchiotludo/akhq#430]
Hello there ! 

I'm working with the 0.15.0 version, with the new UI, and my conf look like this:

```yaml
micronaut:
  security:
    enabled: true
    ldap:
      default:
        enabled: true
        context:
          server: "[ldap-server]"
          managerDn: [managerDn]
          managerPassword: [password]
        search:
          base: ...
        groups:
          enabled: true
          base: ...
akhq:
  topic:
    skip-consumer-groups: true
  topic-data:
    size: 15
  pagination:
    page-size: 10
    threads: 128
  server:
    base-path: ""
  security:
    default-group: no-roles
    groups:
      topic-reader:
        roles:
          - topic/read
          - topic/data/read
      topic-pty:
        roles:
          - topic/read
          - topic/insert
          - topic/delete
          - topic/data/delete
          - topic/data/insert
          - topic/data/read
          - connect/read
        attributes:
          topics-filter-regexp: "PTY.*"
      topic-oom:
        roles:
          - topic/read
          - topic/insert
          - topic/delete
          - topic/config/update
          - topic/data/read
          - topic/data/delete
          - topic/data/insert
          - connect/read
          - connect/delete
          - connect/update
          - connect/insert
          - connect/state/update
          - group/read
          - group/offsets/update
        attributes:
          topics-filter-regexp: ".*OOM.*"
      topic-ps9-reader:
        roles:
          - topic/read
          - topic/data/read
        attributes:
          topics-filter-regexp: "PS9.*"

    ldap:
      group:
        ...

  connections:
     ...
```

![image](https://user-images.githubusercontent.com/48352081/94938666-70ad1780-04d1-11eb-92f2-b300b042deed.png)

In previous version (0.14), this option work well and i cannot figure why the this doesn't work now 🤔
