### ISSUE TITLE
Tag to use LDAP login

### ISSUE THREAD

**Issue by gerardgorrion** [tchiotludo/akhq#436]
Hi all,

We want to upgrade our 0.1.2 chart version of AKHQ to use LDAP connection because on 0.1.2 is not allowed to use LDAP  (all pages that we try to access after login not load, only login page).

![image](https://user-images.githubusercontent.com/35425181/95073662-84dd5880-070d-11eb-9d73-85a6066ab467.png)

We are changed the chart version on chart.yaml:

```
apiVersion: v1
appVersion: "1.0"
description: Kafka GUI for Apache Kafka to manage topics, topics data, consumers group, schema registry, connect and more...
name: akhq
version: 0.1.3
keywords:
  - kafka
  - confluent
  - gui
home: https://akhq.io
icon: https://raw.githubusercontent.com/tchiotludo/akhq/master/client/src/images/logo_black.png
sources:
  - https://github.com/tchiotludo/akhq
maintainers:
  - name: tchiotludo
    email: hello@akhq.io
```

What chart version can we use to use LDAP access?
Thanks
