### ISSUE TITLE
Can't give "data/insert" role on some topics

### ISSUE THREAD

**Issue by piif** [tchiotludo/akhq#456]
I want to give read role on any topic to some users and, for some of those users, i want to give them also "data/insert" role on some topics.

Example :
- users A and B can read any topic content
- user B can also write into any topic named "my_topic_prefix..." but not other ones

Thus I tries following config :
```yaml
      my-readers:
        roles:
          - topic/read
          - topic/data/read
        attributes:
          topics-filter-regexp: ".*"
      my-writers:
        roles:
          - topic/read
          - topic/data/read
          - topic/data/insert
        attributes:
          topics-filter-regexp: "my_topic_prefix.*"

    basic-auth:
      A:
        groups:
         - my-readers
      B:
        groups:
         - my-writers
         - my-readers
```

As a result, B can write into any topic.
Did I miss something, or is there an issue with `topics-filter-regexp`  attributes ?

I noticed that `/api/me` returns "topic/data/insert" role, and B is allowed to produce to another topic
