### ISSUE TITLE
Sort topic data OLDEST / NEWEST

### ISSUE THREAD

**Issue by PLarboulette** [tchiotludo/akhq#460]
Hello, 

I think the 
`  topic-data:
    sort: NEWEST
`
is broken. 

Even if the parameter is set to NEWEST, topics are sorted by the default value, OLDEST.

**Comment by tchiotludo** [comment]
Seems that you don't respect yaml indent.
Can you paste the whole file please ?

**Comment by PLarboulette** [comment]
```
akhq:
  server:
    access-log:
      enabled: true
      name: org.akhq.log.access
      format: "[Date: {}] [Duration: {} ms] [Url: {} {} {}] [Status: {}] [Ip: {}]
        [Length: {}] [Port: {}]"
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed
  connections:
    kafka-cluster:
      properties:
        bootstrap.servers: "${KAFKA_BOOTSTRAP_SERVERS}"
      schema-registry:
        url: "${SCHEMA_REGISTRY_URL}"
      connect:
        - name: "${KAFKA_CONNECT_NAME}"
          url: "${KAFKA_CONNECT_URL}"
  pagination:
    page-size: 25
    threads: 16
  topic-data:
    sort: NEWEST
    size: 50
    poll-timeout: 1000
```

topic and pagination are in the same levels as connections or server. When I look the example file, it seems to be the same thing.
