### ISSUE TITLE
Hi trying to add ldap config for the below, as user or with our ID unable to login could you please help

### ISSUE THREAD

**Issue by Ranganath9979** [tchiotludo/akhq#479]

**Comment by tchiotludo** [comment]
Debuging ldap connection can be done with

```curl
curl -i -X POST -H "Content-Type: application/json" \
       -d '{ "configuredLevel": "TRACE" }' \
       http://localhost:8080/loggers/io.micronaut.configuration.security
```` 

and also please format the yaml with triple `

**Comment by Ranganath9979** [comment]
```
micronaut:
  security:
    enabled: true
micronaut:
  security:
    enabled: false
    # Ldap authentificaton configuration
    ldap:
      default:
        enabled: true
        context:
          server: 'ldaps://adldap.na.xxxxxxx.xxx:636'
          managerDn: 'cn=xxxxxxxxxxx,OU=xxxxxxxOU=Users and Groups,DC=na,DC=xxxxx,DC=com'
          managerPassword: 'xxxxxxxxxxxxxxxxx'
        search:
          base: "OU=xxxxxxx,OU=Users and Groups,DC=na,DC=xxxxx,DC=com"
          attributes:
            - "sAMAccountName"
        groups:
          enabled: true
          base: "OU=Groups,OU=xxxxxxxxOU=Users and Groups,DC=na,DC=xxxxxx,DC=com"
akhq:
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]" # Logger format

  # default kafka properties for each clients, available for admin / producer / consumer (optional)
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed

  # list of kafka cluster available for akhq
  connections:
    my-cluster-plain-text: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "dxxxxxxxxxxxx:9092"

  pagination:
    page-size: 25 # number of elements per page (default : 25)
    threads: 16 # Number of parallel threads to resolve page

  # Topic list display options (optional)
  topic:
    retention: 172800000 # default retention period when creating topic
    partition: 3 #  default number of partition when creating topic
    replication: 3 # default number of replicas when creating topic
    default-view: HIDE_INTERNAL # default list view (ALL, HIDE_INTERNAL, HIDE_INTERNAL_STREAM, HIDE_STREAM)
    internal-regexps: # list of regexp to be considered as internal (internal topic can't be deleted or updated)
      - "^_.*$"
      - "^.*_schemas$"
      - "^.*connect-config$"
      - "^.*connect-offsets$1"
      - "^.*connect-status$"
    stream-regexps: # list of regexp to be considered as internal stream topic
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"
    skip-consumer-groups: false # Skip loading consumer group information when showing topics


  # Topic display data options (optional)
  topic-data:
    sort: OLDEST # default sort order (OLDEST, NEWEST) (default: OLDEST)
    size: 50 # max record per page (default: 50)
    poll-timeout: 1000 # The time, in milliseconds, spent waiting in poll if data is not available in the buffer.

  # Auth & Roles (optional)
  security:
    ldap:
      default-group: topic-reader
      groups:
        - name:
          groups: # Akhq groups list
            - topic-reader
        - name: group-ldap-2
          groups:
            - admin
      users:
        - username: riemann # ldap user id
          groups: # Akhq groups list
            - topic-reader
        - username: A1509893
          groups:
            - admin:
```

**Comment by Ranganath9979** [comment]
HI above is config yml file trying to set up ldap config, getting error can you please help

**Comment by tchiotludo** [comment]
missing jwt configuration : https://github.com/tchiotludo/akhq#jwt

or use the new `dev` image that provide a default one

**Comment by Ranganath9979** [comment]
2020-11-23 15:31:35,813 INFO  main       i.m.runtime.Micronaut      Startup completed in 2111ms. Server Running: http://ba0d2f196e01:8080
2020-11-23 15:31:46,287 WARN  pGroup-1-2 org.akhq.log.access        [Date: 2020-11-23T15:31:45.721743Z] [Duration: 559 ms] [Url: POST /login] [Status: 404] [Ip: 82] [User: 172.23.214.64]
2020-11-23 15:31:46,508 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2020-11-23T15:31:46.49064Z] [Duration: 17 ms] [Url: GET /api/me] [Status: 200] [Ip: 574] [User: 172.23.214.64]
2020-11-23 15:31:49,515 WARN  pGroup-1-3 org.akhq.log.access        [Date: 2020-11-23T15:31:49.511036Z] [Duration: 4 ms] [Url: POST /login] [Status: 404] [Ip: 82] [User: 172.23.214.64]
2020-11-23 15:31:49,688 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2020-11-23T15:31:49.683962Z] [Duration: 4 ms] [Url: GET /api/me] [Status: 200] [Ip: 574] [User: 172.23.214.64]
2020-11-23 15:31:53,087 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2020-11-23T15:31:53.04039Z] [Duration: 47 ms] [Url: GET /ui/] [Status: 304] [Ip: -] [User: 172.23.214.64]
2020-11-23 15:31:53,301 INFO  pGroup-1-7 org.akhq.log.access        [Date: 2020-11-23T15:31:53.277592Z] [Duration: 23 ms] [Url: GET /ui/static/css/2.7caccc14.chunk.css] [Status: 304] [Ip: -] [User: 172.23.214.64]
2020-11-23 15:31:53,332 INFO  pGroup-1-6 org.akhq.log.access        [Date: 2020-11-23T15:31:53.308364Z] [Duration: 23 ms] [Url: GET /ui/static/css/main.9be09a44.chunk.css] [Status: 304] [Ip: -] [User: 172.23.214.64]
2020-11-23 15:31:53,351 INFO  pGroup-1-8 org.akhq.log.access        [Date: 2020-11-23T15:31:53.322542Z] [Duration: 28 ms] [Url: GET /ui/static/js/main.9976c937.chunk.js] [Status: 304] [Ip: -] [User: 172.23.214.64]
2020-11-23 15:31:53,583 INFO  pGroup-1-5 org.akhq.log.access        [Date: 2020-11-23T15:31:53.190442Z] [Duration: 392 ms] [Url: GET /ui/static/js/2.8608a7d0.chunk.js] [Status: 200] [Ip: 398841] [User: 172.23.214.64]
2020-11-23 15:31:54,023 INFO  pGroup-1-5 org.akhq.log.access        [Date: 2020-11-23T15:31:54.020058Z] [Duration: 3 ms] [Url: GET /ui/static/js/2.8608a7d0.chunk.js] [Status: 304] [Ip: -] [User: 172.23.214.64]
2020-11-23 15:31:54,082 INFO  pGroup-1-9 org.akhq.log.access        [Date: 2020-11-23T15:31:54.078344Z] [Duration: 3 ms] [Url: GET /ui/static/js/main.9976c937.chunk.js] [Status: 304] [Ip: -] [User: 172.23.214.64]

**Comment by Ranganath9979** [comment]
icronaut:
  security:
    enabled: true
akhq:
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]" # Logger format

  # default kafka properties for each clients, available for admin / producer / consumer (optional)
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed

  # list of kafka cluster available for akhq
  connections:
    my-cluster-plain-text: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "dtl01s8jmq01c.na.com:9092"

  pagination:
    page-size: 25 # number of elements per page (default : 25)
    threads: 16 # Number of parallel threads to resolve page

  # Topic list display options (optional)
  topic:
    retention: 172800000 # default retention period when creating topic
    partition: 3 #  default number of partition when creating topic
    replication: 3 # default number of replicas when creating topic
    default-view: HIDE_INTERNAL # default list view (ALL, HIDE_INTERNAL, HIDE_INTERNAL_STREAM, HIDE_STREAM)
    internal-regexps: # list of regexp to be considered as internal (internal topic can't be deleted or updated)
      - "^_.*$"
      - "^.*_schemas$"
      - "^.*connect-config$"
      - "^.*connect-offsets$1"
      - "^.*connect-status$"
    stream-regexps: # list of regexp to be considered as internal stream topic
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"
    skip-consumer-groups: false # Skip loading consumer group information when showing topics


  # Topic display data options (optional)
  topic-data:
    sort: OLDEST # default sort order (OLDEST, NEWEST) (default: OLDEST)
    size: 50 # max record per page (default: 50)
    poll-timeout: 1000 # The time, in milliseconds, spent waiting in poll if data is not available in the buffer.

  # Auth & Roles (optional)
  # Basic auth configuration
    basic-auth:
      - username: A1509893
        password: f01d2e7ec1ed1d9ac16e3f11fcd61d5a9c1e8293d31089f275c3ac15fe0667d7
        groups:
        - admin

**Comment by Ranganath9979** [comment]
```
micronaut:
  security:
    enabled: true
akhq:
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]" # Logger format

  # default kafka properties for each clients, available for admin / producer / consumer (optional)
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed

  # list of kafka cluster available for akhq
  connections:
    my-cluster-plain-text: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "dtl01s8jmq01c.na.com:9092"

  pagination:
    page-size: 25 # number of elements per page (default : 25)
    threads: 16 # Number of parallel threads to resolve page

  # Topic list display options (optional)
  topic:
    retention: 172800000 # default retention period when creating topic
    partition: 3 #  default number of partition when creating topic
    replication: 3 # default number of replicas when creating topic
    default-view: HIDE_INTERNAL # default list view (ALL, HIDE_INTERNAL, HIDE_INTERNAL_STREAM, HIDE_STREAM)
    internal-regexps: # list of regexp to be considered as internal (internal topic can't be deleted or updated)
      - "^_.*$"
      - "^.*_schemas$"
      - "^.*connect-config$"
      - "^.*connect-offsets$1"
      - "^.*connect-status$"
    stream-regexps: # list of regexp to be considered as internal stream topic
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"
    skip-consumer-groups: false # Skip loading consumer group information when showing topics


  # Topic display data options (optional)
  topic-data:
    sort: OLDEST # default sort order (OLDEST, NEWEST) (default: OLDEST)
   size: 50 # max record per page (default: 50)
    poll-timeout: 1000 # The time, in milliseconds, spent waiting in poll if data is not available in the buffer.

  # Auth & Roles (optional)
  # Basic auth configuration
    basic-auth:
      - username: A1509893
        password: f01d2e7ec1ed1d9ac16e3f11fcd61d5a9c1e8293d31089f275c3ac15fe0667d7
        groups:
        - admin
```

**Comment by Ranganath9979** [comment]
Hi thought to set basic auth with my ID still unable to is my config right, what Ami is missing here?

**Comment by tchiotludo** [comment]
still missing the jwt token like that : 
```yaml
micronaut:
  security:
    enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: <Your secret here>
```

**Comment by Ranganath9979** [comment]
Ok I'm not sure about jwt do we need to generate tokens

**Comment by tchiotludo** [comment]
You need to create a secret (or use default one on `dev` image) in order to encode the session cookie (stored as jwt token). 
Without that, the login can't work

**Comment by Ranganath9979** [comment]
```
micronaut:
  security:
    enabled: true
    # Ldap authentificaton configuration
    ldap:
      default:
        enabled: true
        context:
          server: 'ldaps://adldap.na.bestbuy.com:636'
          managerDn: 'cn=BBY-S-KAFKAHQ-DEV,OU=Best Buy,OU=Users and Groups,DC=na,DC=bestbuy,DC=com'
          managerPassword: 'gAhXxnuqeeJXpH725D3K953wsaTFdH'
        search:
          base: "OU=Best Buy,OU=Users and Groups,DC=na,DC=bestbuy,DC=com"
          attributes:
            - "sAMAccountName"
        groups:
          enabled: true
          base: "OU=Groups,OU=Best Buy,OU=Users and Groups,DC=na,DC=bestbuy,DC=com"
akhq:
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]" # Logger format

  # default kafka properties for each clients, available for admin / producer / consumer (optional)
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed

  # list of kafka cluster available for akhq
  connections:
    my-cluster-plain-text: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "dtl01s8jmq01c.na.com:9092"

  pagination:
    page-size: 25 # number of elements per page (default : 25)
    threads: 16 # Number of parallel threads to resolve page

  # Topic list display options (optional)
  topic:
    retention: 172800000 # default retention period when creating topic
    partition: 3 #  default number of partition when creating topic
    replication: 3 # default number of replicas when creating topic
    default-view: HIDE_INTERNAL # default list view (ALL, HIDE_INTERNAL, HIDE_INTERNAL_STREAM, HIDE_STREAM)
    internal-regexps: # list of regexp to be considered as internal (internal topic can't be deleted or updated)
    - "^_.*$"
      - "^.*_schemas$"
      - "^.*connect-config$"
      - "^.*connect-offsets$1"
      - "^.*connect-status$"
    stream-regexps: # list of regexp to be considered as internal stream topic
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"
    skip-consumer-groups: false # Skip loading consumer group information when showing topics


  # Topic display data options (optional)
  topic-data:
    sort: OLDEST # default sort order (OLDEST, NEWEST) (default: OLDEST)
    size: 50 # max record per page (default: 50)
    poll-timeout: 1000 # The time, in milliseconds, spent waiting in poll if data is not available in the buffer.

  # Auth & Roles (optional)
  # Ldap Groups configuration (when using ldap)
    ldap:
      default-group: topic-reader
      groups:
        - name: KAFKA
          groups:
            - topic-reader
            - admin
      users:
        - username: riemann # ldap user id
          groups: # Akhq groups list
            - group
        - username: A1509893
          groups:
            - admin
```

**Comment by Ranganath9979** [comment]
I'm trying to set up ldap config Ui is coming up unable to login with ID could you please advise?

**Comment by tchiotludo** [comment]
Can you enable debug with that : 

```
curl -i -X POST -H "Content-Type: application/json" \
       -d '{ "configuredLevel": "TRACE" }' \
       http://localhost:8080/loggers/io.micronaut.configuration.security
```

Also remove secret from your post please 😅

**Comment by Ranganath9979** [comment]
I deleted thanks, when I run the above I'm getting 200 Ok still unable to login

**Comment by Ranganath9979** [comment]
HTTP/1.1 200 OK
Date: Tue, 24 Nov 2020 06:27:38 GMT
connection: keep-alive
transfer-encoding: chunked

**Comment by tchiotludo** [comment]
It will only enable a verbose log for ldap.
Now look at the log if akhq to have some insight

**Comment by Ranganath9979** [comment]
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
	... 186 common frames omitted

**Comment by tchiotludo** [comment]
You are using ldaps ?

If yes, you need to add the certificate like here:
https://github.com/tchiotludo/akhq/issues/226#issuecomment-589811445

**Comment by Ranganath9979** [comment]
java -Djavax.net.ssl.keyStore=MyKeystoreFile \
    -Djavax.net.ssl.keyStorePassword=mysecret \
    External

Hi I need to add above in script?

**Comment by Ranganath9979** [comment]
I man in application.yml file right?

**Comment by tchiotludo** [comment]
no in the script launch, depending if you are using docker or jar, but please provide more information if you want help ...

**Comment by Ranganath9979** [comment]
I was trying to set up ldap config Ui is coming up unable to login with ID? and logs getting this error

Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
... 186 common frames omitted

**U referred  me the above link where I need to add the certificate, could you help with this**

**Comment by Ranganath9979** [comment]
Currently I'm using docker but I need to update cookbook script later I think I need use jar file? which is later though thinking to finish with this?

**Comment by tchiotludo** [comment]
so if you are using docker, you need to use `JAVA_OPTS` env var with value `-Djavax.net.ssl.keyStore=MyKeystoreFile  -Djavax.net.ssl.keyStorePassword=mySecret` and mount the sslKeystore in your docker image, changing the MyKeystoreFile and mySecret with your values

**Comment by Ranganath9979** [comment]
```
micronaut:
  security:
    enabled: true
    # Ldap authentificaton configuration
    ldap:
      default:
        enabled: true
        context:
          server: 'ldaps://adldap.na.bestbuy.com:636'
          managerDn: 'cn=-S-KAFKAHQ-DEV,OU=xxxxxxxxx,OU=Users and Groups,DC=na,DC=xxxxxx,DC=com'
          managerPassword: 'xxxxxxxxxx'
        search:
          base: "OU=xxxxxxx,OU=Users and Groups,DC=na,DC=xxxxxxxDC=com"
          attributes:
            - "sAMAccountName"
        groups:
          enabled: true
          base: "OU=Groups,OU=xxxxxxxx,OU=Users and Groups,DC=na,DC=xxxxxxxx,DC=com"
akhq:
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]" # Logger format

  # default kafka properties for each clients, available for admin / producer / consumer (optional)
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed

  # list of kafka cluster available for akhq
  connections:
    my-cluster-plain-text: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "xxxxxxxxxxx"
  JAVA_OPTS
    -Djavax.net.ssl.trustStore=/tmp/truststore.jks
    -Djavax.net.ssl.trustStorePassword=xxxxxxxxxx
  pagination:
    page-size: 25 # number of elements per page (default : 25)
    threads: 16 # Number of parallel threads to resolve page

  # Topic list display options (optional)
  topic:
    retention: 172800000 # default retention period when creating topic
    partition: 3 #  default number of partition when creating topic
    replication: 3 # default number of replicas when creating topic
    default-view: HIDE_INTERNAL # default list view (ALL, HIDE_INTERNAL, HIDE_INTERNAL_STREAM, HIDE_STREAM)
    internal-regexps: # list of regexp to be considered as internal (internal topic can't be deleted or updated)
      - "^_.*$"
      - "^.*_schemas$"
      - "^.*connect-config$"
      - "^.*connect-offsets$1"
      - "^.*connect-status$"
    stream-regexps: # list of regexp to be considered as internal stream topic
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"
   skip-consumer-groups: false # Skip loading consumer group information when showing topics


  # Topic display data options (optional)
  topic-data:
    sort: OLDEST # default sort order (OLDEST, NEWEST) (default: OLDEST)
    size: 50 # max record per page (default: 50)
    poll-timeout: 1000 # The time, in milliseconds, spent waiting in poll if data is not available in the buffer.

  # Auth & Roles (optional)
  # Ldap Groups configuration (when using ldap)
    ldap:
      default-group: topic-reader
      groups:
        - name: group-ldap-1
          groups: # Akhq groups list
            - topic-reader
        - name: group-ldap-2
          groups:
            - admin
      users:
        - username: riemann # ldap user id
          groups: # Akhq groups list
            - xxxxxxxxxxxx
        - username: 
          groups:
            - admin
```

**Comment by Ranganath9979** [comment]
Hi After adding JAva Opts
  -Djavax.net.ssl.keyStore=MyKeystoreFile 
  -Djavax.net.ssl.keyStorePassword=mySecret

it is not starting what went wrong now, it was on after adding these options docker is not turning on could you please help

**Comment by tchiotludo** [comment]
You should replace the `My...`. 
Also please provide a true report, this is not working is not a report :sob: 

Please provide : 
- Installation type (docker or jar) 
- Version used 
- Deploy type (docker / java / k8s / docker-compose / ...) 
- In your case, how you add the java opts, so the command line used 
- Logs 
- Screenshots 
- Any things that allow me to help you more than it's not working ...

**Comment by Ranganath9979** [comment]
Hi

2020-12-08 15:59:53,239 DEBUG pGroup-1-5 LdapAuthenticationProvider Starting authentication with configuration [default]
2020-12-08 15:59:53,239 DEBUG pGroup-1-5 LdapAuthenticationProvider Attempting to initialize manager context
2020-12-08 15:59:53,243 DEBUG pGroup-1-5 LdapAuthenticationProvider Manager context initialized successfully
2020-12-08 15:59:53,243 DEBUG pGroup-1-5 LdapAuthenticationProvider Attempting to authenticate with user [a1509893]
2020-12-08 15:59:53,248 DEBUG pGroup-1-5 LdapAuthenticationProvider User found in context [CN=Chandrashekarappa\, Ranganatha 1509893,OU=Default,OU=Users,OU=Best Buy,OU=Users and Groups,DC=na,DC=bestbuy,DC=com]. Attempting to bind.
2020-12-08 15:59:53,604 DEBUG pGroup-1-5 LdapAuthenticationProvider Successfully bound user [CN=Chandrashekarappa\, Ranganatha 1509893,OU=Default,OU=Users,OU=Best Buy,OU=Users and Groups,DC=na,DC=bestbuy,DC=com]. Attempting to retrieving groups.
2020-12-08 15:59:53,970 DEBUG pGroup-1-5 .DefaultLdapGroupProcessor No groups found!
2020-12-08 15:59:53,971 DEBUG pGroup-1-5 .DefaultLdapGroupProcessor Attempting to add any additional groups...
2020-12-08 15:59:53,971 DEBUG pGroup-1-5 LdapAuthenticationProvider Group search returned [[]] for user [a1509893]
2020-12-08 15:59:53,971 TRACE pGroup-1-5 LdapAuthenticationProvider Attempting to map [a1509893] with groups [[]] to an authentication response.
2020-12-08 15:59:53,971 DEBUG pGroup-1-5 LdapAuthenticationProvider Response successfully created for [a1509893]. Response is authenticated: [true]
2020-12-08 15:59:53,973 INFO  pGroup-1-5 org.akhq.log.access        [Date: 2020-12-08T15:59:53.23656Z] [Duration: 736 ms] [Url: POST /login] [Status: 303] [Ip: 0] [User: 172.23.32.202]

**Comment by Ranganath9979** [comment]
I'm getting this error what changes I have to make?

**Comment by Ranganath9979** [comment]
you wanna C my .yml file?

**Comment by tchiotludo** [comment]
It's seems to be your groups.base that don't match any group for your users. 
I don't have a lot of experience with LDAP and all the configuration that you can provide is here : https://micronaut-projects.github.io/micronaut-security/latest/guide/#ldap

Maybe you could find another people that have successfully use your ldap since it's always the same config for all tools

**Comment by Ranganath9979** [comment]
Hi, My issue with Ldap is resolved...now without login also others in the group can be  able to open Ui and can make changes and even delete topics  what changes I have to made....

Ui should respond only through login what I have to do?

**Comment by tchiotludo** [comment]
:tada: 
https://github.com/tchiotludo/akhq#security : 

```yaml 
akhq:
  security:
    default-group: no-roles
```

**Comment by Ranganath9979** [comment]
it worked thanks for now....

we are setting with, test cluster may need to  set ssl there is it ok check, if reqd. anything?

**Comment by tchiotludo** [comment]
sorry didn't understand

**Comment by Ranganath9979** [comment]
Hi what options I need to use hide data in topics and Schema-registry, and I also need to disable the option to create delete topics as well could you please help

**Comment by Ranganath9979** [comment]
Hi I'm trying disable the option of creating/deleting topics from Akhq Ui could some please help with it?

**Comment by Ranganath9979** [comment]
I fixed it thankyou

**Comment by Ranganath9979** [comment]
I was trying to set standalone, what is the startup script that can be used to start application.yml when we are using ldap config. is it same
java -Dmicronaut.config.files=/path/to/application.yml -jar akhq.jar

**Comment by Ranganath9979** [comment]
sudo docker run -d --env "JAVA_OPTS=-Djavax.net.ssl.trustStore=/app/truststore.jks -Djavax.net.ssl.trustStorePassword=xxxxxxx" -p 8080:8080 -v /tmp/application.yml:/app/application.yml -v /tmp/trust.jks:/app/truststore.jks 456de460c95

This I'm using to start from docker, I need help with standalone?

**Comment by tchiotludo** [comment]
`java -Djavax.net.ssl.trustStore=/app/truststore.jks -Djavax.net.ssl.trustStorePassword=xxxxxxx -Dmicronaut.config.files=/path/to/application.yml -jar akhq.jar` must do the trick

**Comment by Ranganath9979** [comment]
> 🎉
> https://github.com/tchiotludo/akhq#security :
> 
> ```yaml
> akhq:
>   security:
>     default-group: no-roles
> ```

Hi my issue was fixed, I was bale to login, all of sudden I'm not able to login what shall I check below is my yml file

akhq:
  security:
    default-group: no-roles # Default groups for all the user even unlogged user
    # Groups definition
    groups:
      admin: # Group name
        roles:  # roles for the group
          - topic/read
          - node/read
          - topic/data/read
          - group/read
          - group/offsets/update
          - registry/read
          - registry/version/delete

**Comment by tchiotludo** [comment]
@Ranganath9979: use the `dev` image,, we have changed the format of the configuration in last release and it's was a wrong idea. 
So we revert on `dev` one

**Comment by Ranganath9979** [comment]
will try thanks

**Comment by Ranganath9979** [comment]
```
micronaut:
  security:
    enabled: true
    # Ldap authentificaton configuration
    ldap:
      default:
        enabled: true
        context:
          server: 'lXXXXXXXXXXXXXXXXXXXXXX'
          managerDn: 'cn=BBY-S-KAFKAHQ-DEV,OU=System,OU=Best Buy,OU=Users and Groups,DC=na,DC=bestbuy,DC=com'
          managerPassword: 'XXXXXXXXXXXXXXX'
        search:
          enabled: true
          base: "OU=Best Buy,OU=Users and Groups,DC=na,DC=bestbuy,DC=com"
          filter: "sAMAccountName={0}"
        groups:
          enabled: true
          subtree: true
          base: "OU=Groups,OU=Best Buy,OU=Users and Groups,DC=na,DC=bestbuy,DC=com"
          filter: "member={0}"
akhq:
  security:
    default-group: no-roles # Default groups for all the user even unlogged user
    # Groups definition
    groups:
      admin: # Group name
        roles:  # roles for the group
          - topic/read
          - node/read
          - topic/data/
          - group/read
          - group/offsets/update
          - registry/read
          - registry/version/

    ldap:
      group:
        BBY-U-ENT-KAFKA:
          groups:
            - admin
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]" # Logger format

  # default kafka properties for each clients, available for admin / producer / consumer (optional)
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed

  # list of kafka cluster available for akhq
  connections:
    my-cluster-plain-text: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "XXXXXXXXXXXXX:9092"
      schema-registry:
        url: "XXXXXXXXXXXX:8081"
  pagination:
    page-size: 25 # number of elements per page (default : 25)
    threads: 16 # Number of parallel threads to resolve page

  # Topic list display options (optional)
  topic:
    retention: 172800000 # default retention period when creating topic
    partition: 3 #  default number of partition when creating topic
    replication: 3 # default number of replicas when creating topic
    default-view: ALL # default list view (ALL, HIDE_INTERNAL, HIDE_INTERNAL_STREAM, HIDE_STREAM)
    internal-regexps: # list of regexp to be considered as internal (internal topic can't be deleted or updated)
      - "^_.*$"
      - "^.*_schemas$"
      - "^.*connect-config$"
      - "^.*connect-offsets$1"
      - "^.*connect-status$"
    stream-regexps: # list of regexp to be considered as internal stream topic
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"
    skip-consumer-groups: false # Skip loading consumer group information when showing topics

  # Topic display data options (optional)
  topic-data:
    sort:  # default sort order (OLDEST, NEWEST) (default: OLDEST)
    size: 50 # max record per page (default: 50)
    poll-timeout: 1000 # The time, in milliseconds, spent waiting in poll if data is not available in the buffer.

  # Auth & Roles (optional)
  # Ldap Groups configuration (when using ldap)

```

**Comment by Ranganath9979** [comment]
Hey, this is my old application.yml I was using it was working fine, now unable to login as per your instructions I used latest dev image still no luck ,could you please help me right identations

**Comment by tchiotludo** [comment]
I've release a new version yesterday, no need for dev image now

**Comment by Ranganath9979** [comment]
mean directly I can use application.yml file and configure it?

**Comment by tchiotludo** [comment]
Just make a try with latest version to be sure on the version that you are using

**Comment by Ranganath9979** [comment]
```
HI I tried with latest yml file

micronaut:
  security:
    enabled: true
    # Ldap authentificaton configuration
    ldap:
      default:
        enabled: true
        context:
          server: 'ldaps://adldap.na.bestbuy.com:636'
          managerDn: 'cn=BBY-S-KAFKAHQ-DEV,OU=System,OU=Best Buy,OU=Users and Groups,DC=na,DC=bestbuy,DC=com'
          managerPassword: 'gAhXxnuqeeJXpH725D3K953wsaTFdG'
        search:
          enabled: true
          base: "OU=Best Buy,OU=Users and Groups,DC=na,DC=bestbuy,DC=com"
          filter: "sAMAccountName={0}"
        groups:
          enabled: true
          subtree: true
          base: "OU=Groups,OU=Best Buy,OU=Users and Groups,DC=na,DC=bestbuy,DC=com"
          filter: "member={0}"

# Auth & Roles (optional)
  akhq:
    security:
      default-group: no-roles # Default groups for all the user even unlogged user
      # Groups definition
      groups:
        admin: # Group name
          roles:  # roles for the group
            - topic/read
            - node/read
            - topic/data/
            - group/read
            - group/offsets/update
            - registry/read
            - registry/version/

      ldap:
        group:
          BBY-U-ENT-KAFKA:
            groups:
              - admin

  server:
    context-path: "/akhq" # if behind a reverse proxy, path to akhq without trailing slash (optional). Example: akhq is
                     # behind a reverse proxy with url http://my-server/akhq, set base-path: "/akhq".
                     # Not needed if you're behind a reverse proxy with subdomain http://akhq.my-server/
akhq:
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]" # Logger format

  # default kafka properties for each clients, available for admin / producer / consumer (optional)
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed

  # list of kafka cluster available for akhq
  connections:
    my-cluster-plain-text: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "dtl01s8jmq01c.na.bestbuy.com:9092"
      schema-registry:
        url: "http://dtl01s8jmq01c.na.bestbuy.com:8081" # schema registry url (optional)
        type: "confluent" # schema registry type (optional). Supported types are "confluent" (default) or "tibco"

  pagination:
    page-size: 25 # number of elements per page (default : 25)
    threads: 16 # Number of parallel threads to resolve page

  # Topic list display options (optional)
  topic:
    retention: 172800000 # default retention period when creating topic
    partition: 3 #  default number of partition when creating topic
    replication: 3 # default number of replicas when creating topic
    internal-regexps: # list of regexp to be considered as internal (internal topic can't be deleted or updated)
      - "^_.*$"
      - "^.*_schemas$"
      - "^.*connect-config$"
      - "^.*connect-offsets$1"
      - "^.*connect-status$"
    stream-regexps: # list of regexp to be considered as internal stream topic
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"
    skip-consumer-groups: false # Skip loading consumer group information when showing topics
    skip-last-record: false # Skip loading last record date information when showing topics

  # Topic display data options (optional)
  topic-data:
    size: 50 # max record per page (default: 50)
    poll-timeout: 1000 # The time, in milliseconds, spent waiting in poll if data is not available in the buffer.
```
