### ISSUE TITLE
Use secrets as environment variables

### ISSUE THREAD

**Issue by gerardgorrion** [tchiotludo/akhq#482]
Hi all,

We are trying to use secrets (kubernetes) as extraenv to helm chart deploy, but seem like the code is no the correct (values.yml, is the application.yml config):

Here we declare extraenv:
```
extraEnv:
  - name: MANAGERDN
    valueFrom:
      secretKeyRef:
        name: akhq-secrets
        key: managerdn
  - name: MANAGERPASS
    valueFrom:
      secretKeyRef:
        name: akhq-secrets
        key: passworddn
```
Then try to use here:

```
configuration: |
  micronaut:
      ldap:
        default:
          enabled: true
          context:
            server: 'ldaps://ourldap:636'
            managerDn: ${MANAGERDN}
            managerPassword: ${MANAGERPASS}
```
Also, we try with this formats:

```
$MANAGERDN
'$MANAGERDN'
$'{MANAGERDN}'
```
Then deployed the pod, we can log into and call the $MANAGERDN variable, that show the correct value, but can't use into application.yml...

Regards!

**Comment by tchiotludo** [comment]
really weird must be working with this syntax : "${MANAGERDN}"
like explain here : https://docs.micronaut.io/latest/guide/index.html#valueAnnotation, especially in 
> Included PropertySource Loaders

- Have you look at the file on the pods to confirm there is no escape done ? 
- maybe add the quote around ?

**Comment by gerardgorrion** [comment]
kubectl description pod:
```
    Environment:
      MICRONAUT_ENVIRONMENTS:  secrets
      MICRONAUT_CONFIG_FILES:  /app/application.yml,/app/application-secrets.yml
      MANAGERDN:               <set to the key 'managerdn' in secret 'akhq-secrets'>   Optional: false
      MANAGERPASS:             <set to the key 'passworddn' in secret 'akhq-secrets'>  Optional: false
```
Into pod, cat application.yml:

```
    ldap:
      default:
        enabled: true
        context:
          server: 'ldaps://ourldap:636'
          managerDn: ${MANAGERDN}
          managerPassword: ${MANAGERPASS}
```
out the file, if call ${MANAGERPASS}, show error:
```
root@akhq_pod:/app# ${MANAGERPASS}
bash: 'mypass': command not found
```

seems like the variable is up to date inside the pod, but the application.yml file don't get the value of secret
