### ISSUE TITLE
Basic autho configuraition

### ISSUE THREAD

**Issue by eshepelyuk** [tchiotludo/akhq#490]
Hi, I am trying to setup basic auth for AKHQ 
I am using Helm chart in K8S with docker image version 0.16.0.

What is confising

* README and `application-example.yml` has a mismatch 
in README
```
akhq.security:
  basic-auth:
    admin:
      password: "$2a$<hashed password>"
      passwordHash: BCRYPT
      groups: admin
    reader:
      password: "<SHA-256 hashed password>"
      groups: reader
```

in application-example
```
    basic-auth:
      - username: user # Username
        password: pass # Password in sha256
        groups: # Groups for the user
          - admin
          - topic-reader
```

I.e. map vs list 

2. It's not clear is `micronaut.security.enabled` should be set to true or not.

**Comment by tchiotludo** [comment]
Hi, 

1. The right one is the list, that have changed with last version, need to correct the readme ! 
2. `micronaut.security.enabled` need to be set to `true` to activate authentification

**Comment by eshepelyuk** [comment]
Hi, thanks for reply.
Tried to follow both options from above, but still was unable to make basic auth work.
Any additional data I could send you to understnad the bug \ configuration ?

Also the issue - the I only see 2 lines of logs from my pod. Is there a way to enable the logs, so maybe I could debug myself.

**Comment by tchiotludo** [comment]
I see that you use `akhq.security`, I'm not really sure it works. 
Try to expand to:
```yaml
akhq: 
  security:
```
You can also send the full configuration if you want some help

**Comment by eshepelyuk** [comment]
Actually i hadn't posted *own* configuration yet. The `akhq.security` one liner is a snippet from  urrent README.
But as for me - I already use beforementioned config structure as you recommended.
I will attach entire config later, actually I ll attach my helm values, because config is generated from them.

**Comment by eshepelyuk** [comment]
Here's my Helm `values.yaml` with some fields masked

```
image:
  tag: 0.16.0
configuration: |
  akhq:
    server:
      access-log:
        enabled: false
        name: org.akhq.log.access

    connections:
      hrzn01-dev:
        properties:
          bootstrap.servers: "*******"
        schema-registry:
          url: "http://******:8081"
        connect: []

    security:
      basic-auth:
        - username: hrzn
          password: "3d5392078959707c4f09f7531c244d78ed0e342a412dd47b29092583b00c8168"
          groups:
            - admin

secrets: ""
```
