### ISSUE TITLE
Release don't tag latest docker image

### ISSUE THREAD

**Issue by toanpt3** [tchiotludo/akhq#496]
Hi
After installed akhq from docker(tchiotludo/akhq:latest), my config have enable OIDC(google) but not see on UI login.
My config:
```
micronaut:
  security:
    oauth2:
      enabled: true
      clients:
        google:
          client-id: "xxxxxxxxxxxxxxxxx.apps.googleusercontent.com"
          client-secret: "xxxxxxxxxxxxxxxxxxxxxx"
          openid:
            issuer: "https://accounts.google.com"
akhq:
  connections:
    plain11:
      properties:
        bootstrap.servers: "kafka:9092"
      schema-registry:
        url: "http://schema-registry:8085"
      connect:
      - url: "http://connect:8083"
  security:
    default-group: no-roles
    oidc:
      enabled: true
      providers:
        google:
          label: "Login with Google"
          username-field: email
          groups-field: roles
          default-group: no-roles
          users:
            some-admin:
              username: abc@gmail.com
              groups:
                - admin
```

![image](https://user-images.githubusercontent.com/16619605/98225498-59a58d80-1f87-11eb-97c2-40a8e5c0aa3b.png)

**Comment by tchiotludo** [comment]
hi, do you have activated the security from micronaut & jwt token 
https://github.com/tchiotludo/akhq#security


```yaml
micronaut:
  security:
    enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: <Your secret here>
```
it don't seems to be the case ?
