### ISSUE TITLE
Unable to login to akhq in 0.16

### ISSUE THREAD

**Issue by clallavena** [tchiotludo/akhq#500]
Hi there !

I trying to update my version of akhq with the new one, I've update the configuration file also to the new format, and yet i cannot connected to the UI.

When i'm logging in, the page just refresh and keep redirect me to the login page, indefinitely.

my configuration:

```yaml
micronaut:
  security:
    enabled: true
    ldap:
      default:
        enabled: true
        context:
          server: "...."
          managerDn: '....'
          managerPassword: '...'
        search:
          base: "..."
        groups:
          enabled: true
          base: "...."

akhq:
  topic:
    skip-consumer-groups: true
  topic-data:
    size: 15
  pagination:
    page-size: 20
    threads: 128
  server:
    #base-path: ""
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]" # Logger format
  security:
    default-group: no-roles
    groups:
      - name: topic-reader
        roles:
          - topic/read
          - topic/data/read
      - name: topic-pty
        roles:
          - topic/read
          - topic/insert
          - topic/delete
          - topic/data/delete
          - topic/data/insert
          - topic/data/read
          - connect/read
        attributes:
          topics-filter-regexp: "PTY.*"
      - name: topic-oom
        roles:
          - topic/read
          - topic/insert
          - topic/delete
          - topic/config/update
          - topic/data/read
          - topic/data/delete
          - topic/data/insert
          - connect/read
          - connect/delete
          - connect/update
          - connect/insert
          - connect/state/update
          - group/read
          - group/offsets/update
        attributes:
          topics-filter-regexp: ".*OOM.*"
      - name: topic-ps9-reader
        roles:
          - topic/read
          - topic/data/read
        attributes:
          topics-filter-regexp: "PS9.*"

    basic-auth:
      - username: admin
        password: "..."
        groups:
          - admin


    ldap:
      default-group: reader
      groups:
        - name: ...
          groups:
            - admin
        - name: ...
          groups:
            - topic-reader
        - name: ...
          groups:
            - topic-pty
        - name: ...
          groups:
            - topic-oom
            - topic-ps9-reader


  connections:
    cqt-cluster:
      properties:
        bootstrap.servers: "..."
        security.protocol: "..."
        sasl.mechanism: "..."
        sasl.jaas.config: '...'
      schema-registry:
        url: "..."
      connect:
        - name: cqt-connect
          url: "..."
          basic-auth-username: ...
          basic-auth-password: ...

    indus-cluster:
      properties:
        bootstrap.servers: "..."
        security.protocol: "..."
        sasl.mechanism: "..."
        sasl.jaas.config: '...'
        ssl.truststore.location: "..."
        ssl.truststore.password: "..."
        ssl.keystore.location: "..."
        ssl.keystore.password: "..."
      schema-registry:
        url: "..."
        properties:
          kafkastore.bootstrap.servers: "..."
          kafkastore.security.protocol: "..."
          kafkastore.security.protocol: "..."
          ssl.keystore.type: JKS
          ssl.keystore.location: "..."
          ssl.keystore.password: "..."
          ssl.key.password: "..."
          ssl.truststore.type: JKS
          ssl.truststore.location: "..."
          ssl.truststore.password: "..."
      connect:
        - name: indus-connect
          url: "..."
          basic-auth-username: ...
          basic-auth-password: ...
```

And neither the basic auth and the ldap authentification works.

I'm trying to figure it out since a long time now, but I can't find out 🤔  Can you give me a thought ? 

It's kinda the same problem that #485 i think but I already check my configuration and I can't find out.

TY!

**Comment by tchiotludo** [comment]
Just a quick thought : 
- are you using docker image or java jar ? 
- can you try url `/api/auths` to see if it auth seems to be enabled ?

**Comment by clallavena** [comment]
I use java jar of 0.16 and yes it seem's enabled:

![image](https://user-images.githubusercontent.com/48352081/98533496-5b22ce80-2283-11eb-8df5-a7df7049cab3.png)

**Comment by tchiotludo** [comment]
I've reduced with configuration files to this (and that works)  : 
```yaml 
micronaut:
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: >-
                pleasechangeme!pleasechangeme!pleasechangeme!pleasechangeme!
                pleasechangeme!pleasechangeme!pleasechangeme!pleasechangeme!
                pleasechangeme!pleasechangeme!pleasechangeme!pleasechangeme!
                pleasechangeme!pleasechangeme!pleasechangeme!pleasechangeme!
                pleasechangeme!pleasechangeme!pleasechangeme!pleasechangeme!
                pleasechangeme!pleasechangeme!pleasechangeme!pleasechangeme!
                pleasechangeme!pleasechangeme!pleasechangeme!pleasechangeme!
                pleasechangeme!pleasechangeme!pleasechangeme!pleasechangeme!
  server:
    port: 28080

akhq:
  security:
    default-group: no-roles
    basic-auth:
      - username: user
        password: d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1
        groups:
          - admin



  connections:
    cqt-cluster:
      properties:
        bootstrap.servers: "local:9092"

```
It's seems that you don't defined the jwt secret that is needed for last release.
I think I really need to add this : #470 to help onboarding

**Comment by clallavena** [comment]
I've try add the jwt token in the configuration, but still, the problem is the same :/ login in and then redirect to the login page..
And I don't understand what the jwt token is usefull for in the configuration ?

**Comment by tchiotludo** [comment]
see here : https://github.com/tchiotludo/akhq/issues/485#issuecomment-725911018

And please try the latest dev version also, there is a default one that can fix your issue

**Comment by clallavena** [comment]
I'm currently on the dev version and still i can't understand why it keep acting like that :/ 

See the logs of what happen's

![image](https://user-images.githubusercontent.com/48352081/98928479-1e9ce000-24da-11eb-8627-a72e6275a586.png)

nb: i'm using the default jwt token

**Comment by tchiotludo** [comment]
Ok so it's not the JWT token .. 
Have you try my configuration, does it work  ?

**Comment by clallavena** [comment]
Your configuration work just fine! But I try to check on my configuration for understanding what's wrong about it and I can't find out what's wrong 🤔

**Comment by tchiotludo** [comment]
Let do step by step. 
Maybe just try with a simple configuration with only basic auth working. 
After add ldap in order to figure out where it's wrong ?

**Comment by clallavena** [comment]
I've made a little test, and it look like this part is the problem:

```yaml
    groups:
      - name: topic-reader
        roles:
          - topic/read
          - topic/data/read
      - name: topic-pty
        roles:
          - topic/read
          - topic/insert
          - topic/delete
          - topic/data/delete
          - topic/data/insert
          - topic/data/read
          - connect/read
        attributes:
          topics-filter-regexp: "PTY.*"
      - name: topic-oom
        roles:
          - topic/read
          - topic/insert
          - topic/delete
          - topic/config/update
          - topic/data/read
          - topic/data/delete
          - topic/data/insert
          - connect/read
          - connect/delete
          - connect/update
          - connect/insert
          - connect/state/update
          - group/read
          - group/offsets/update
        attributes:
          topics-filter-regexp: ".*OOM.*"
      - name: topic-ps9-reader
        roles:
          - topic/read
          - topic/data/read
        attributes:
          topics-filter-regexp: "PS9.*"
```

When I add it in the config, same problem as before, but idk why 🤔 

NB: the skip-consumer-group seems not work either but it's another pb

**Comment by tchiotludo** [comment]
For the skip consumer, we already have an issue here #466 and #464 to talk about the reintroduction of the feature. 

Don't see the issue for look.
Look at `/env` endpoint to have a clue of configured value resolve by micronaut maybe ?

**Comment by apellegr06** [comment]
Hi,

I have the same problem, and I succeed to display the login page when using the url http://<host>:<port>/ui/login, insted of http://<host>:<port>/login

**Comment by clallavena** [comment]
Hi there @tchiotludo,
I did not have the time to dig into it since this day, I will this week, sry for the late answer.

**Comment by clallavena** [comment]
Hello again,

I look into it and it seem's like the problem was, indeed, the security.groups in the configuration:

```yaml
security:
    default-group: no-roles
    groups:
    - name: topic-reader
      roles:
        - topic/read
        - topic/data/read
    - name: topic-pty
      roles:
        - topic/read
        - topic/insert
        - topic/delete
        - topic/data/delete
        - topic/data/insert
        - topic/data/read
        - connect/read
      attributes:
        topics-filter-regexp: "PTY.*"
    - name: topic-oom
      roles:
        - topic/read
        - topic/insert
        - topic/delete
        - topic/config/update
        - topic/data/read
        - topic/data/delete
        - topic/data/insert
        - connect/read
        - connect/delete
        - connect/update
        - connect/insert
        - connect/state/update
        - group/read
        - group/offsets/update
      attributes:
        topics-filter-regexp: ".*OOM.*"
    - name: topic-ps9-reader
      roles:
        - topic/read
        - topic/data/read
      attributes:
        topics-filter-regexp: "PS9.*"
```

I think the indentation was bad ^^ since, this work
