### ISSUE TITLE
Config parameter "akhq.topic.default-view" being ignored in 0.15.0

### ISSUE THREAD

**Issue by lheeb** [tchiotludo/akhq#506]
Hi,

I'm using version 0.15.0 of AKHQ with the following config:
```
akhq:
  [...]
  pagination:
    page-size: 50
  topic:
    default-view: HIDE_STREAM
    stream-regexps:
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"
     [...]
```
It seems that setting default-view to "HIDE_STREAM" isn't showing any effect. The dropdown inside the UI always defaults back to "HIDE_INTERNAL" / "Hide internal topics".

Thanks in advance!
