### ISSUE TITLE
default-group: reader allows update on schema-registry

### ISSUE THREAD

**Issue by larvinloy** [tchiotludo/akhq#515]
I have the following config:
```
  configuration: |
    akhq:
      server:
        access-log: 
          enabled: false 
          name: org.akhq.log.access
      security:
        default-group: reader
```

I can see `update` option available and seem to be able to run updates for schema-registry.

`tchiotludo/akhq:0.16.0`
