### ISSUE TITLE
Login Page keeps refreshing when basic-auth enabled

### ISSUE THREAD

**Issue by rbr101** [tchiotludo/akhq#522]
Hi,

I'm running AKHQ on kubernetes and everything works fine except when enabling basic-auth.  Tried several different configs but when i apply the config with "default-group: no-roles" the login page keeps refreshing preventing me to logon. When i remove that part everything works fine again except the Login button on the right. If i click on it nothing happens.

My config regarding the auth is 

```
   security:
     default-group: no-roles
     basic-auth:
       - username: admin
         password: passhash
         groups:
           - admin
```

**Comment by tchiotludo** [comment]
Hi,

can you try with `dev` version please ? 
Must be the JWT token issue #470

**Comment by rbr101** [comment]
Thanks for your fast response, any idea how i can use the dev version when installing with helm ?

**Comment by tchiotludo** [comment]
Just use the image tag `dev` :+1:

**Comment by rbr101** [comment]
Now running akhq:dev but still the same behavior. Tested in firefox and chrome but same problem.

**Comment by tchiotludo** [comment]
do you have enable micronaut security ? https://github.com/tchiotludo/akhq#security ?

**Comment by rbr101** [comment]
yes, i added config to the values.yaml

```
micronaut:
  security:
    enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "some_key"
```

If i click on logon i get the error "KafkaAdminClient" which is from the kafka connection defined in the application-secrets.yml.
Somehow the helm installer merges the default config with my own connections. Maybe that is causing the behavior i have?
I don't know how to get rid of the that part of the config.
