### ISSUE TITLE
New ACLS systems ! Need feedback 

### ISSUE THREAD

**Issue by tchiotludo** [tchiotludo/akhq#523]
There is many features request about acls: #451 #456 #291 #254.
You want to have more fine grained acl ! 

Now how ! I create this issue more to have feedback from you ! 
There is many ways to handle it, so since I want this to be last rework on AKHQ ACL! 
For every comment, can you add a :+1:  or others reaction in order to track the most wanted and also you can add some comments about the reason and special idea you may have ! 

Thanks for your help !

**Comment by tchiotludo** [comment]
One way will be to have this kind of configurations : 
```yaml
group:
  - name: my-group-name 
    roles: 
     - topic/read
    conditions: 
     - type: cluster
       value: 
       - prd 
     - type: topic 
       value 
       - "test\\.reader.*"
     - type: group
       value:
       - "group\\.reader.*"
       - "group\\.writer.*"
     - type: connect-cluster
       value:
       - "connect\\.reader.*"
     - type: connect-task
       value:
       - "connect\\.task.*
```

I think you will be able to to do anythings you want, and it will be extensible in the future

**Comment by tchiotludo** [comment]
One more standard ways will be : 
```yaml
groups:
  - name: admin
    cluster: prd 
    topics: 
      - "topic.*prd.*"
    groups: 
      - "group\\.reader.*"
      - "group\\.writer.*"
    connect-cluster: 
      - cluster-1
    connect-task: 
      - "task\\.jdbc.*"
    roles:  
      - topic/read
      - topic/insert
      - topic/delete
      - topic/config/update
```

**Comment by tchiotludo** [comment]
Any suggest ?

**Comment by twobeeb** [comment]
Let me expose some use case I might have in the next few months.
As a reminder, we use AKHQ for read-only purpose on topics and connects.

For a given LDAP group, I want to be able : 
- allow all topics prefixed with "something.*" to be visible on all clusters (or a rather big list)
- allow some topics to be visible in certain clusters
- allow other topics to be visible in other clusters

I believe that solution 2 is clearer than solution 1. In both scenario my use-case is covered.
Example with solution 2:
````yaml
akhq:
  security:
    groups:
      - name: project_1-cluster1
        cluster: cluster1
        topics: 
          - "project_1.*"
          - "fixed_topic_001"
        roles:  
          - topic/read
      - name: project_1-cluster2
        cluster: cluster2
        topics: 
          - "project_1.*"
          - "fixed_topic_002"
        roles:  
          - topic/read
    ldap:
      groups:
        - name: LDAP-PROJECT-1
          groups:
            - project_1-cluster1
            - project_1-cluster2
````



Yet one important use case which I suspect people may eventually ask you to cover : 
- I own some topics (so I Read/Write into it) but I can only Read some other topics which I don't own

Again, I don't need it, never will
