### ISSUE TITLE
Logging in with OIDC still redirects me to login page

### ISSUE THREAD

**Issue by schen2315** [tchiotludo/akhq#534]
Hey guys,
I setup oidc and after authenticating am brought back to the login page (login with xxxx) and can't access the actual application. When i go to /api/me i see logged is set to true, my username is there and the roles that my company org returned. Do the roles returned by my provider have to match exactly to the roles used by akhq (e.g. topic/read, topic/insert, etc. ). I am on 0.16.0 

Here's my config:
```yaml
micronaut:
  security:
    enabled: true
    oauth2:
      enabled: true
      clients:
        bsso-oauth2:
          client-id: <MY_CLIENT_ID>
          client-secret: <MY_CLIENT_SECRET>
          openid:
            issuer: <MY_PROVIDER>
security:
  default-group: no-roles
  oidc:
    enabled: true
    providers:
      bsso-oauth2:
        label: "Login with MY_PROVIDER"
        username-field: preferred_username
        groups-field: roles
        default-group: reader
```

**Comment by tchiotludo** [comment]
Is this the full configuration ? 
I see that you use default group and there is an issue https://github.com/tchiotludo/akhq/pull/526 that can impact you ?

**Comment by schen2315** [comment]
i only put the parts that i thought were relevant, only other part of my config is my kafka connections. Ill take a look at #526

**Comment by schen2315** [comment]
i updated my config to use the suggestion made in #526 :
```yaml
security:
  default-group: no-roles
  groups:
  - name: admin
    roles:
    - topic/read
    - topic/insert
    - topic/delete
    - topic/config/update
    - node/read
    - node/config/update
    - topic/data/read
    - topic/data/insert
    - topic/data/delete
    - group/read
    - group/delete
    - group/offsets/update
    - registry/read
    - registry/insert
    - registry/update
    - registry/delete
    - registry/version/delete
    - acls/read
    - connect/read
    - connect/insert
    - connect/update
    - connect/delete
    - connect/state/update
  - name: reader
    roles:
    - topic/read
    - node/read
    - topic/data/read
    - group/read
    - registry/read
    - acls/read
    - connect/read
  - name: no-roles
    roles: []
  oidc:
    enabled: true
    providers:
      oauth2:
        label: "Login with MY_PROVIDER"
        username-field: preferred_username
        groups-field: roles
        groups:
          - name: ROLE_RETURNED_BY_PROVIDER
            groups:
              - reader
```
However, after logging in i still get redirected to the login page (login with xxxx). When i go to /api/me i get something like:
```json
{"logged":true,"username":"schen2315","roles":["ROLE_1", "ROLE_2", "ROLE_3"]}
```
Is there something wrong with my config?

**Comment by tchiotludo** [comment]
Not really sure to have understand ? 
Are you using role from akhq group ? or role coming from OIDC provider ? 

Seems to be confusing here ! 

Just see also that you mix akhq & micronaut configuration.
```yaml
akhq: 
  security:
    default-group: no-roles
    groups: 
``` 
default & group, groups, .... are akhq configuration, not the micronaut one.

**Comment by schen2315** [comment]
my bad, im pasting what i think are relevant parts. My config does have security under akhq.
This is what my full config looks like:
```yaml
    micronaut:
      security:
        enabled: true
        oauth2:
          enabled: true
          clients:
            oauth2:
              client-id: MY_CLIENT_ID
              client-secret: MY_CLIENT_SECRET
              openid:
                issuer: MY_PROVIDER
    akhq:
      connections:
        kafkasub:
          properties:
            bootstrap.servers: <MY_KAFKA_BROKER>
      topic-data:
        poll-timeout: 10000
      security:
        default-group: no-roles
        groups:
        - name: admin
          roles:
          - topic/read
          - topic/insert
          - topic/delete
          - topic/config/update
          - node/read
          - node/config/update
          - topic/data/read
          - topic/data/insert
          - topic/data/delete
          - group/read
          - group/delete
          - group/offsets/update
          - registry/read
          - registry/insert
          - registry/update
          - registry/delete
          - registry/version/delete
          - acls/read
          - connect/read
          - connect/insert
          - connect/update
          - connect/delete
          - connect/state/update
        - name: reader
          roles:
          - topic/read
          - node/read
          - topic/data/read
          - group/read
          - registry/read
          - acls/read
          - connect/read
        - name: no-roles
          roles: []
        oidc:
          enabled: true
          providers:
            oauth2:
              label: "Login with MY_PROVIDER"
              username-field: sub
              groups-field: roles
              groups:
                - name: ROLE_1
                  groups:
                    - reader
```
Im using the role coming from my oidc provider. My understanding is that 
```yaml
              groups:
                - name: ROLE_1
                  groups:
                    - reader
```
means assign a user whose role `ROLE_1` coming from the oidc provider is given the group `reader` coming from akhq

**Comment by tchiotludo** [comment]
to be honest, I never try this part, since I don't have any custom OIDC provider, i only try standard openid, @jniebuhr do it and maybe he have more information about this ?
As I understand, the OIDC custom provider must return group and not role to be working. 
Maybe you can try ?

**Comment by schen2315** [comment]
so we should set our oidc provider to return something like: 
```json
{"logged":true,"username":"schen2315","groups":["ROLE_1", "ROLE_2", "ROLE_3"]}
```
i believe for ldap, you are able to map groups returned by the ldap server to custom groups created in akhq. Is it not the same for oidc?

**Comment by tchiotludo** [comment]
As I understand here : 
https://github.com/tchiotludo/akhq/blob/5ab788da22529ede3c7b640f1918304511cea6f0/src/main/java/org/akhq/modules/OidcUserDetailsMapper.java#L106

The default return was more like that : 
```
{"logged":true,"username":"schen2315","roles":["AKHQGROUP1", "AKHQGROUP2", "AKHQGROUP2"]}
```

Not really sure about that here, sorry ! 
We need more docs about that ;)

**Comment by jniebuhr** [comment]
@schen2315 You are correct, OIDC contains the same logic as LDAP. So the mapping is OIDC Groups -> AKHQ Groups -> AKHQ Roles. So it should work. There might be a conflict if the OIDC Claim is called `roles`. But I thought I put something in there to solve that.

**Comment by hoeggi** [comment]
I'm working on this exact same issue right now too. I found this comment: https://github.com/tchiotludo/akhq/issues/485#issuecomment-719603022 saying that using the role name instead of a group should work. Can anyone confirm this for oidc? I'm unable to check this myself because of a bug in keycloak that prevents roles with a `/` in the name. 

I will try to change the claim field to something else form the default `role` but not sure yet if this is possible in keycloak.

My config looks pretty much the same as the one from @schen2315  except that i also have a jwt token in my config:

```yaml
        micronaut:
          security:
            enabled: true
            oauth2:
              enabled: true
              clients:
                oidc:
                  client-id: "akhq-ui"
                  client-secret: "XXX-XXX-XXX"
                  openid:
                    issuer: "https://XXX-XXX-XXX/auth/realms/infrastructure/"
            token:
              jwt:
                signatures:
                  secret:
                    generator:
                      secret: XXX-XXX-XXX
```
