### ISSUE TITLE
basic-auth does not work even with the simplest configuration

### ISSUE THREAD

**Issue by Shitovdm** [tchiotludo/akhq#535]
Hi guys!
Can you please help with a working configuration with simple authorization. 
I have been trying for several hours to get the authorization module to work but I keep getting the error. I use image version 0.16.0, and everything works fine except for the authorization module. I have tried many configuration options already and studied a few other issues, but there is no result yet.
This is the simplest configuration:
```
    micronaut:
      security:
        enabled: true
        token:
          jwt:
            enabled: true
            signatures:
              secret:
                generator:
                  secret: >-
                    pleasechangeme
    akhq:
      security:
        default-group: admin
        basic-auth:
          - username: admin
            password: 3ef411623fc41f2528234c7522c7d52eacc96bdbb18f3194ddf8b511a53d43a1
            groups:
              - admin
      connections:
        development:
          properties:
            bootstrap.servers: "kafka.local:9092"
          schema-registry:
            url: "http://kafka.local:8081"
```
I also tried to create an authorization module with LDAP configuration, but this did not lead to positive results(
All my attempts end with an error "Wrong Username or Password!" on the login page. Also, I noticed that all requests for the authorization form end with 303 statuses, I don’t know, maybe this is normal?

**Comment by tchiotludo** [comment]
Hi @Shitovdm .

I think you hit this issue https://github.com/tchiotludo/akhq/pull/526. 
With last version, the groups have changed from map to list and seems that is a really bad idea. 

You can confirm that you configuration is applied [/env](https://github.com/tchiotludo/akhq#monitoring-endpoint] endpoint. 
First look at this endpoint to see if all the configuration are discovered. 

I try on my side : 
![image](https://user-images.githubusercontent.com/2064609/101398255-157f1300-38ce-11eb-8089-ec67318fd401.png)
the response code is correct and redirect to the ui.

Just try with this : 
```yaml
    basic-auth:
      - username: user
        password: d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1
        groups:
          - admin
```
with login user / pass to be sure that the password is right encoded !

**Comment by Shitovdm** [comment]
Hello @tchiotludo 
Thanks for your quick feedback.
I tried accessing the endpoint /env via curl, but got a 500 error. The error message started with "io.micronaut.security.errors.OauthErrorResponseException", after that I tried to remove the token section from micronaut.security and now everything works fine!
Apparently, from the moment when you wrote about the mandatory addition of a jwt token in other issues, something has changed and maybe you added jwt token initialization inside the application.
Here is a complete example of the simplest working configuration:
```
micronaut:
  security:
    enabled: true
akhq:
  security:
    default-group: admin
    basic-auth:
      - username: user
        password: d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1
        groups:
          - admin
  connections:
    development:
      properties:
        bootstrap.servers: "kafka.local:9092"
      schema-registry:
        url: "http://kafka.local:8081"
```
