### ISSUE TITLE
skip-consumer-groups now working

### ISSUE THREAD

**Issue by vgulch** [tchiotludo/akhq#538]
Hello everyone and thank you for this project.
I'm using 0.16.0 with helm chart 0.1.3
I have many consumer groups and have problem with topic list view

I've tried to disable consumer groups column according to [application.example.yml](https://github.com/tchiotludo/akhq/blob/dev/application.example.yml)
but with no success
tried these locations
`              akhq:

                topic:

                  skip-consumer-groups: true

                ui-options:

                  topic:

                    skip-consumer-groups: true

                connections:

                  kafka1:

                    ui-options:

                      topic:

                        skip-consumer-groups: true

`

**Comment by tchiotludo** [comment]
You should try with dev version / image. 
The documentation is based on dev version and not release for now. 

This is a new options not available on stable image

**Comment by vgulch** [comment]
i've tried with 'latest' and no success
what dev tags better to use for this?

**Comment by tchiotludo** [comment]
the tag `tchiotludo/akhq:dev` contains non release version with your options

**Comment by vgulch** [comment]
idd, this one works. thanks a lot!

**Comment by tchiotludo** [comment]
closing since it works

**Comment by terryf82** [comment]
Even after swapping to the `dev` image, we're still unable to hide the consumer groups from the ui.

Something that might be relevant is that we're deploying via the helm charts, so all config settings are supplied as an env var called `AKHQ_CONFIGURATION` (but this has worked fine for all other settings):

```
extraEnv:
  - name: AKHQ_CONFIGURATION
    value: |
        micronaut:
          security:
            enabled: true
        akhq:
          ui-options.topic.skip-consumer-groups: true
          connections:
            default:
              properties:
              ....
```

Have also tried:
```
...
akhq:
  ui-options:
    topic:
      skip-consumer-groups: true
```

as well as nesting under `akhq.topic` and within the cluster settings `akhq.connections.default`.

Any suggestions?
