### ISSUE TITLE
Read only roles still able to update schema configs

### ISSUE THREAD

**Issue by evaisman-tc** [tchiotludo/akhq#539]
Hey!
I've been playing around with akhq for the past few days and noticed that when using the `reader` security group we are still able to make some changes to the schema registry. You can reproduce this by navigating to the schemas in the UI and setting the default group to reader.
```
akhq:
  security:
    default-group: reader
```

from here you can browse an existing schema and change the compatibility from say `BACKWARDS` to `FORWARDS` and hitting `UPDATE`.

I also tried creating my own reader role with the following roles:
```
akhq:
  security:
    default-group: readers
    groups:
      - name: readers
        roles:
          - topic/read
          - node/read
          - group/read
          - topic/data/read
          - registry/read
          - acls/read
          - connect/read
```
And i'm still able to change the compatibility as well.

I haven't tried updating a schema but i imagine it may work too.
