### ISSUE TITLE
internal server error on topic overview page

### ISSUE THREAD

**Issue by jorgheymans** [tchiotludo/akhq#549]
Using dev branch, after logging in (LDAP auth) a red banner appears during load of the topic overview screen. It seems as if it's trying to access the `/login` page repeatedly ?

![image](https://user-images.githubusercontent.com/193792/102620925-179f6800-413f-11eb-8967-4a51f6f0ca22.png)

**Comment by tchiotludo** [comment]
I've changed (I know again :cry:) the format of the configuration files due to this issue : https://github.com/tchiotludo/akhq/pull/526. 
Mostly I think it's the reason ...

**Comment by jorgheymans** [comment]
But we manage to login, indeed the change for a group to have both name and a key attribute we already found out and corrected so i don't think it's this. Here is the complete security config:

```
 # Auth & Roles (optional)
  security:
    default-group: no-roles
    groups:
      akhq-user:
        name: akhq-user
        roles:
          - topic/read
          - node/read
          - topic/data/read
          - group/read
          - registry/read
          - acls/read
          - connect/read
        attributes:
          topics-filter-regexp: ".*"
    ldap:
      groups:
        - name: ADM
          groups:
            - akhq-user
```
