### ISSUE TITLE
AKHQ server on k8s keeps getting terminated without explicit error message

### ISSUE THREAD

**Issue by neolunar7** [tchiotludo/akhq#580]
I'm getting the error messages below when deploying the akhq helm chart.
```
│ akhq 2021-02-02 10:27:20,044 INFO  main       i.m.c.e.DefaultEnvironment Established activ
│ e environments: [k8s, cloud, ec2, secrets]
│ akhq 2021-02-02 10:27:52,847 INFO  main       i.m.runtime.Micronaut      Startup completed
│  in 34299ms. Server Running: http://my-akhq-6bf77f777d-vqw8r:8080
│ akhq stream closed
```

I use override value file as below. The only configuration I give is my bootstrap server. 
```
secrets: |
  akhq:
    connections:
      my-cluster-plain-text:
        properties:
          bootstrap.servers: "MSK_BROKER_ENDPOINTS"
```

I can't figure out what is the problem, as the log isn't that informational.. Any suggestions ?
