### ISSUE TITLE
What's the difference between using this repository, and using the artifacts hub ?

### ISSUE THREAD

**Issue by neolunar7** [tchiotludo/akhq#581]
Hi, I'm curious what's the difference between using `helm/akhq` directory after cloning this repository, and using the helm chart from artifacts hub. 

I have this `override.yaml` file as below.

```
secrets: |
  akhq:
    connections:
      my-cluster-plain-text:
        properties:
          bootstrap.servers: "MY_BROKER_SERVERS"
        connect:
          - name: "kafka-connect-sink"
            url: "kafka-connect.kafka-connect-sink.svc.cluster.local:8083"
resources:
  limits:
   cpu: 0.4
   memory: 1024Mi
  requests:
   cpu: 0.4
   memory: 1024Mi
```

Installing the chart with command `helm install akhq akhq/akhq --version 0.1.3 -n akhq --values override.yaml` successfully sets up AKHQ. 
However, installing after cloning this repository with command `helm install akhq -f override.yaml helm/akhq -n akhq` is not successful. (Server terminates without explicit error message - thus it prevents me from debugging..)

Any help plz ?
