### ISSUE TITLE
Unable to login with credentials I specified

### ISSUE THREAD

**Issue by neolunar7** [tchiotludo/akhq#582]
Hi, configuration regarding the auth is as below. However, I'm unable to login with username: admin, password: password. Any suggestions please?

```
configuration: |
  akhq:
    server:
      access-log:
        enabled: true
        name: org.akhq.log.access
    security:
      default-group: no-roles
      basic-auth:
        - username: admin
          password: password
          groups:
            - admin
  micronaut:
    security:
      enabled: true
      token:
        jwt:
          signatures:
            secret:
              generator:
                secret: "some-secret"
```
