### ISSUE TITLE
Login with google always showing the same page

### ISSUE THREAD

**Issue by neolunar7** [tchiotludo/akhq#583]
Hi, I'm trying to configure Google login with OIDC. The override value is as below.

```
secrets: |
  akhq:
    connections:
      my-cluster-plain-text:
        properties:
          bootstrap.servers: "MY_MSK_BOOTSTRAP_SERVERS"
        connect:
          - name: "kafka-connect-sink"
            url: "kafka-connect.kafka-connect-sink.svc.cluster.local:8083"
resources:
  limits:
   cpu: 0.5
   memory: 512Mi
  requests:
   cpu: 0.5
   memory: 512Mi

service:
  enabled: true
  type: ClusterIP
  port: 80

configuration: |
  akhq:
    server:
      access-log:
        enabled: true
        name: org.akhq.log.access
    security:
      default-group: no-roles
      oidc:
        enabled: true
        providers:
          google:
            label: "Login with Google"
            username-field: email
            groups-field: roles
            default-group: no-roles
            users:
              some-admin:
                username: "neolunar@mycompany.co"
                groups:
                  - admin
  micronaut:
    security:
      enabled: true
      oauth2:
        enabled: true
        clients:
          google:
            client-id: "blahblah.apps.googleusercontent.com"
            client-secret: "blahblah2"
            openid:
              issuer: "https://accounts.google.com"
      token:
        jwt:
          signatures:
            secret:
              generator:
                secret: "o9z7UhTo1dfXjtH0YLq3jwV1yiCQCPOwX3PmQyV"
```

However, after I click the `Login with Google` button, the page always shows the page below, as if I didn't login at all.

![image](https://user-images.githubusercontent.com/39179896/106610976-bde9e480-65aa-11eb-8f46-8fef8a30c51a.png)

Any solutions ?

**Comment by tchiotludo** [comment]
Here is a working one : 

```yaml
akhq:
    oidc:
      enabled: true
      providers:
        google:
          label: "Login with Google"
          username-field: email
          default-group: no-roles
          users:
            - username: email@gmail.com
              groups:
                - admin
```

It's seems that your users is map (on your example) but it need to be an array.
