### ISSUE TITLE
Health checks fail with helm install

### ISSUE THREAD

**Issue by krjackso** [tchiotludo/akhq#584]
We are installing akhq using helm chart `0.1.3` and docker image tag `dev` to get some enhancements to memory management that were not available on `0.16.0`. There have been some changes to the dev image that apparently make the Deployment health check fail on the 0.1.3 chart. 

Kubernetes events on the pod (pod ip is 10.12.14.199 in this case):

```
Readiness probe failed: HTTP probe failed with statuscode: 404
Readiness probe failed: Get http://10.12.14.199:8080/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Readiness probe failed: Get http://10.12.14.199:8080/health: dial tcp 10.12.14.199:8080: connect: connection refused
Liveness probe failed: dial tcp 10.12.14.199:8080: connect: connection refused
```

Can we get a new tag on the Docker image and a new helm release that work together so we can pin to a version with the memory improvements, and a helm version with the newest updates to health checks?

**Comment by SrikanthNiketh** [comment]
Facing similar issue. We are not seeing the latest config in the deployment.
Chart version: 0.1.3
Image tag: dev

Thank you.

**Comment by tchiotludo** [comment]
Really complicated ! 
To avoid thinking, the new release is out ;) 

enjoy :smile:

**Comment by terryf82** [comment]
Unfortunately I don't think `0.17.0` fixes this, we are having the same issue of the pod never reaching a healthy status due to a failing readiness check:
```
Readiness probe failed: Get /login: stopped after 10 redirects
```

Our values.yaml file looks like this (edited out credentials etc):
```
image:
  repository: tchiotludo/akhq
  tag: 0.17.0
  annotations: {}
  extraEnv:
  - name: AKHQ_CONFIGURATION
    value: |
        micronaut:
          security:
            enabled: true
        akhq:
          connections:
            default:
              properties:
                bootstrap.servers: "confluent-cp-kafka.confluent.svc.cluster.local:9092"
              connect:
                - name: kafka-connect
                  url: "http://confluent-cp-kafka-connect.confluent.svc.cluster.local:8083"
            lab:
              properties:
                bootstrap.servers: "kafka.us-west-2.test.lab.example.com:6000"
                security.protocol: "SSL"
                ssl.truststore.location: /usr/share/kafka-lab-certs/truststore.jks
                ssl.truststore.password: 123456789
                ssl.keystore.type: JKS
                ssl.keystore.location: /usr/share/kafka-lab-certs/keystore.jks
                ssl.keystore.password: 123456789
                ssl.key.password: 123456789
                ssl.endpoint.identification.algorithm : ""
          topic:
            retention: 14400000
            replication: 3
            partition: 6
          security:
            default-group: no-roles
            basic-auth:
              - username: "user1"
                password: abcdefghijklmnopqrstuvwxyz
                groups:
                  - admin
              - username: "user2"
                password: abcdefghijklmnopqrstuvwxyz
                groups:
                  - admin
```

This exact configuration works perfectly if we change the tag line to:
```
tag: lateset
```

but then we don't have access to the new settings & features. Any help appreciated.
