### ISSUE TITLE
Can't authenticate on kerberized Hortonworks Schema Registry

### ISSUE THREAD

**Issue by orull95** [tchiotludo/akhq#589]
Hello,

I trying to configure a kerberized Hortonworks Schema Registry to akhq but I always get this message:
```
io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 2]; error code: 50005
```

After some research, this message indicates that the authentication given to access the Schema Registry was invalid. I can validate this with a tcpdump and see a 401 http message.

I didn't find an example how to configure with a kerberos authentification. I tried some properties like sasl.mechanism, security.protocol or sasl.jaas.config without success.

Have you any tips about to authenticate on kerberized schema registry ?

Version details:
HDF : 3.5.1.0
Schema Registry : 0.8.1
Kafka: 1.2.0.3.5
akhq: from master

Regards

**Comment by tchiotludo** [comment]
To be honest, I don't know. 
Do you have a sample application in java that connect to this registry ?

**Comment by orull95** [comment]
Thanks for your reply.

> Do you have a sample application in java that connect to this registry ?

I don't have. It's an other team that developes application. I installed AKHQ for them.
I use this to check connexion:

`java -Djava.security.auth.login.config=kafka_client_jaas.conf -jar avro-examples-0.7.0.3.4.1.1-4.jar -cm -c kafka-consumer.props`

With kafka_client_jaas.conf :
```
KafkaClient {
  com.sun.security.auth.module.Krb5LoginModule required
  useTicketCache=false
  useKeyTab=true
  storeKey=true
  serviceName="kafka"
  keyTab="keytab"
  principal="USER@REALM";
};

RegistryClient {
  com.sun.security.auth.module.Krb5LoginModule required
  useTicketCache=false
  useKeyTab=true
  storeKey=true
  keyTab="keytab"
  principal="USER@REALM";
};

Client {
  com.sun.security.auth.module.Krb5LoginModule required
  useTicketCache=false
  useKeyTab=true
  storeKey=true
  serviceName="zookeeper"
  keyTab="keytab"
  principal="USER@REALM";
};
```
kafka-consumer.props:
```
topic=topic_name
bootstrap.servers=server1:6667,server2:6667,server3:6667
schema.registry.url=http://schema.registry:7788/api/v1
security.protocol=SASL_PLAINTEXT
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=com.hortonworks.registries.schemaregistry.serdes.avro.kafka.KafkaAvroDeserializer
group.id=group_id
auto.offset.reset=earliest
```

It works with that. I tried to add this propreties in application.yml, client-defaults/consumer/properties or schema-registry/properties but without success.

**Comment by orull95** [comment]
Hi,

I did some tests with kerberos.
I installed krb5-workstation in docker and got a local ticket. The authentification passed then ended with an error. With tcpdump I see a kerberos error. Here traces: 
```
GET./subjects.HTTP/1.1..Content-Type:.application/vnd.schemaregistry.v1+json..Cache-Control:.no-cache..Pragma:.no-cache..User-Agent:.Java/11.0.2..Host:.schema.registry:7788..Accept:.text/html,.image/gif,.image/jpeg,.*;.q=.2,.*/*;.q=.2..Connection:.keep-alive....
 ```

```
HTTP/1.1.401.Authentication.required..Date:.Thu,.04.Feb.2021.09:04:30.GMT..WWW-Authenticate:.Negotiate..Set-Cookie:.hadoop.auth=;.Expires=Thu,.01-Jan-1970.00:00:00.GMT;.HttpOnly..Cache-Control:.must-revalidate,no-cache,no-store..Content-Type:.text/html;charset=iso-8859-1..Content-Length:.268....<html>.<head>.<meta.http-equiv="Content-Type".content="text/html;charset=utf-8"/>.title>Error.401.Authentication.required</title>.</head>.<body><h2>HTTP.ERROR.401</h2>.<p>Problem.accessing./subjects..Reason:.<pre>....Authentication.required</pre></p>.</body>.</html>.
```

```
GET./subjects.HTTP/1.1..Content-Type:.application/vnd.schemaregistry.v1+json..Cache-Control:.no-cache..Pragma:.no-cache..User-Agent:.Java/11.0.2..Host:.schema.registry:7788..Accept:.text/html,.image/gif,.image/jpeg,.*;.q=.2,.*/*;.q=.2..Connection:.keep-alive..Authorization:.Negotiate.YIICuAYGKwYBBQUCoIICrDCCAqigDTALBgkqhkiG9xIBAgKhBAMCAXaiggKPBIICi2CCAocGCSqGSIb3EgECAgEAboICdjCCAnKgAwIBBaEDAgEOogcDBQAgAAAAo4IBeGGCAXQwggFwoAMCAQWhDBsKREVWQklHREFUQaIxMC+gAwIBAKEoMCYbBEhUVFAbHmNucDMxZGV2aG9ydG9ubmlmaS5naWRuLnJlY291dqOCASYwggEioAMCARGhAwIBAqKCARQEggEQohWxAknoHN0h3NFbmVJJczGQ2ZAenIfuYjcqvqMEX5xaMic+IuvaoYGGDtaKDSYlrgSxIQYZbzjcLLl9nr9jBni/u0Ks2WRW8h0utDrvOcQKsyDrb/wEggIymBEh9IEE0Zqu6qTE5w6nIVE5TeBYhg8YSkd3SwLEqMG8MtSHtGO+JvXq7blYpiejGDQRT1FC11G5APFPl2LWtlNM6MLghiuNtgyv9K5+SzQqLbXmZn28gJXM2Fk89cALenqu99RnNyXCRS7TlMU+hdq2HobNzfon76qkGG4R23+j07khcACGgVS6EICjdRNcRT3YFyznBgWB4l4ddhAMJnu8fFNE7KPFbGJnfWDpYN6myt6qdlCkgeAwgd2gAwIBEqKB1QSB0gDP7w/fBy43aQM82Dlu2Mvoyhe+zeG6GGO0VyO73tQxNva4BTms24Ja0N9SNrIKnBiFYmTKGht8sAfYATqofN6pqzBc2a1eBQgrxfuPsaDFoA83zTiymgKcyqI/urTS+SVxJbG10aJcfW99H9UM9GbRS3gUqAe9vRlBdrMtpVUhCMo4eAAQ2b+27ERMJqaBHpsAWtUvoEMcV7JIMzZEuO/eZT8j0LSAj2BZGYEOTJqY4in+zjoDuXSFTa4e0/CgxCPY6JYFB3wZp5AU0MHPG21nCg==....
```

```
HTTP/1.1.403.GSSException:.Failure.unspecified.at.GSS-API.level.(Mechanism.level:.Request.is.a.replay.(34))..Date:.Thu,.04.Feb.2021.09:04:30.GMT..WWW-Authenticate:.Negotiate.oYH1MIHyoAMKAQChCwYJKoZIhvcSAQICom4EbGBqBgkqhkiG9xIBAgICAG9bMFmgAwIBBaEDAgEPok0wS6ADAgESokQEQjDNDJZOLN56UeMtZBXMQgZX2QxslrE/wTTNROlQd8tbi2nomTsuWDDwrgCUNf8tgS4amzvahGXkkthJRJjdeXUG3qNuBGxgagYJKoZIhvcSAQICAgBvWzBZoAMCAQWhAwIBD6JNMEugAwIBEqJEBEIwzQyWTizeelHjLWQVzEIGV9kMbJaxP8E0zUTpUHfLW4tp6Jk7Llgw8K4AlDX/LYEuGps72oRl5JLYSUSY3Xl1Bt4=..Set-Cookie:.hadoop.auth="u=USER@REALM&p=USER@REALM&t=kerberos&e=1612465470986&s=kNeRfb0Jo207RcVJP4KJ6PyLy90=";.Expires=Thu,.04-Feb-2021.19:04:30.GMT;.HttpOnly..Set-Cookie:.hadoop.auth=;.Expires=Thu,.01-Jan-1970.00:00:00.GMT;.HttpOnly..Cache-Control:.must-revalidate,no-cache,no-store..Content-Type:.text/html;charset=iso-8859-1..Content-Length:.427....<html>.<head>.<meta.http-equiv="Content-Type".content="text/html;charset=utf-8"/>.<title>Error.403.GSSException:.Failure.unspecified.at.GSS-API.level.(Mechanism.level:.Request.is.a.replay.(34))</title>.</head>.<body><h2>HTTP.ERROR.403</h2>.<p>Problem.accessing./api/v1/confluent/subjects..Reason:.<pre>....GSSException:.Failure.unspecified.at.GSS-API.level.(Mechanism.level:.Request.is.a.replay.(34))</pre></p>.</body>.</html>.
```

With -Dsun.security.krb5.debug=true option, I can see the ticket is taken but during request I get Mechanism.level:.Request.is.a.replay.(34) error message.

Have you any idea?

Regards.

**Comment by tchiotludo** [comment]
Not really for now. 
Kerberos is a hard animal :cry: 

Can you provide the application.yml that you are using ?

**Comment by orull95** [comment]
Here a part of application.yml:
```yaml
micronaut:
  security:
    # Ldap authentificaton configuration
    ldap:
      default:
        enabled: true
        context:
          server: 'xxxxx'
          managerDn: 'xxxxxxx'
          managerPassword: 'xxxxxxxx'
        search:
          base: "xxxxxxx"
        groups:
          enabled: true
          base: "xxxxxx"
          filter: "xxxxxx"

akhq:
  server:
    base-path: "" # if behind a reverse proxy, path to akhq without trailing slash (optional). Example: akhq is
                  # behind a reverse proxy with url http://my-server/akhq, set base-path: "/akhq".
                  # Not needed if you're behind a reverse proxy with subdomain http://akhq.my-server/
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {} {}] [Status: {}] [Ip: {}] [Length: {}] [Port: {}]" # Logger format

  # default kafka properties for each clients, available for admin / producer / consumer (optional)
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed

  # list of kafka cluster available for akhq
  connections:
    HDFDEV: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "xxxxxxx"
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: GSSAPI
        sasl.jaas.config: com.sun.security.auth.module.Krb5LoginModule required renewTGT=true doNotPrompt=true useKeyTab=true keyTab="xxxxxx" storeKey=true useTicketCache=true serviceName="kafka" principal="xxxx@REALM" ;

      schema-registry:
        url: "http://schema.registry:7788"
        properties:
#          security.protocol: SASL_PLAINTEXT
#          sasl.mechanism: GSSAPI
# I must add this line to catch the local ticket done by a kinit
          sasl.jaas.config: com.sun.security.auth.module.Krb5LoginModule required renewTGT=false doNotPrompt=true useKeyTab=false storeKey=false useTicketCache=true;
# This not working
#          sasl.jaas.config: com.sun.security.auth.module.Krb5LoginModule required renewTGT=true doNotPrompt=true useKeyTab=true keyTab="keytab" storeKey=true useTicketCache=false  principal="user@REALM" ;
....
```

Thanks for help :)
