### ISSUE TITLE
Routes health, info ..

### ISSUE THREAD

**Issue by PLarboulette** [tchiotludo/akhq#590]
Hello, 

In the last version, 0.17.0, the routes : 
- health
- info
- metrics
- prometheus
- loggers 

Are no longer available. 

In the micronaut documentation, it seems we have to add a new section "endpoints", I try to add it to the application.yml file with no success :/ 
(https://docs.micronaut.io/snapshot/guide/index.html#healthEndpoint) 

``` 
endpoints:
    health:
        enabled: Boolean
        sensitive: Boolean
        details-visible: String 
        status:
            http-mapping: Map<String, HttpStatus>
``` 

Thanks
