### ISSUE TITLE
Setting oidc.providers.google.default-group as reader results in 307 status, and fails to run

### ISSUE THREAD

**Issue by neolunar7** [tchiotludo/akhq#592]
Hi, installing akhq with the configurations below results in logs below. Pod status is 'false'. However, changing the `oidc.providers.google.default-group` from `reader` to `no-roles` is successful. Any comments on this issue ?
```
│ akhq 2021-02-08 03:47:57,891 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2021-02-08
│ 03:47:57.891513Z[] [Duration: 0 ms] [Url: GET /login] [Status: 307] [Ip: /10.0.60.238] [Us
│ r: Anonymous[]
│ akhq 2021-02-08 03:47:57,893 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-02-08
│ 03:47:57.893456Z[] [Duration: 0 ms] [Url: GET /login] [Status: 307] [Ip: /10.0.60.238] [Us
│ r: Anonymous[]
```

```
secrets: |
  akhq:
    connections:
      my-cluster-plain-text:
        properties:
          bootstrap.servers: "${BOOTSTRAP_SERVERS}"
        connect:
          - name: "kafka-connect-sink"
            url: "kafka-connect.kafka-connect-sink.svc.cluster.local:8083"
resources:
  limits:
   cpu: 0.5
   memory: 512Mi
  requests:
   cpu: 0.5
   memory: 512Mi

service:
  enabled: true
  type: ClusterIP
  port: 80

configuration: |
  akhq:
    server:
      access-log:
        enabled: true
        name: org.akhq.log.access
    security:
      default-group: no-roles
      oidc:
        enabled: true
        providers:
          google:
            label: "Login with Google"
            username-field: email
            groups-field: roles
            default-group: reader
            users:
              - username: "myemail@something.co"
                groups:
                  - admin
  micronaut:
    security:
      enabled: true
      oauth2:
        enabled: true
        clients:
          google:
            client-id: "${CLIENT_ID}"
            client-secret: "${CLIENT_SECRET}"
            openid:
              issuer: "https://accounts.google.com"
      token:
        jwt:
          signatures:
            secret:
              generator:
                secret: "${SOME_SECRET}"
```
