### ISSUE TITLE
Login page does not appear with basic auth and no-roles config

### ISSUE THREAD

**Issue by alozano3** [tchiotludo/akhq#593]
Hi, I am trying to set basic authentication with **_no-roles_** as the default group. The Login page does not appear and it seems it gets stuck in a loop. When I set the default-group to _admin_ , it does not ask for credentials and directly shows the dashboard.

Config:
```yaml
    # Auth & Roles (optional)
    security:
      default-group: no-roles # Default groups for all the user even unlogged user
      basic-auth:
        - username: admin
          password: XXX # Password in sha256
          groups:
            - admin
```

This is the error that I am seeing int the browser console.
![image](https://user-images.githubusercontent.com/31214345/107212280-02400f00-6a07-11eb-9531-7b2398d16cdb.png)

**Comment by tchiotludo** [comment]
What version of AKHQ are you using ? 
Can you provide a full application.yml example ?

**Comment by alozano3** [comment]
Hi, I  already fix the problem. I migrated from 0.14.0 to 0.17.0 and I had to add the below conf:

```yaml
  micronaut:
    security:
      enabled: true
```
