### ISSUE TITLE
Where can I find Kafka Connect in AKHQ UI?

### ISSUE THREAD

**Issue by neolunar7** [tchiotludo/akhq#594]
Hi, where can I monitor `kafka-connect` in UI ? I specified the connect url as below. 

```
secrets: |
  akhq:
    connections:
      my-cluster-plain-text:
        properties:
          bootstrap.servers: ${MY_SERVERS}
        connect:
          - name: "kafka-connect-sink"
            url: "kafka-connect.kafka-connect-sink.svc.cluster.local:8083"
```

However, I think there is no section for Kafka Connect in AKHQ (See the image below)

![image](https://user-images.githubusercontent.com/39179896/107305352-2adb0e00-6ac6-11eb-830d-1f2499ec6c80.png)

Any help please?

**Comment by tchiotludo** [comment]
Really strange, here is a working configuration on my side : 
```
akhq:
  connections:
    local:
      properties:
        bootstrap.servers: "local:9092"
      schema-registry:
        url: "http://schema-registry:8085"
      connect:
        - name: connect-1
          url: "http://connect:8083"
          basic-auth-username: test_user
          basic-auth-password: test_pass
        - name: connect-2
          url: "http://connect:8083"
          basic-auth-username: test_user
          basic-auth-password: test_pass
``` 

maybe you control that you don't mix space & tabs on your configuration files ?

**Comment by niklasdoerflerkrone** [comment]
Hello, 
I have encountered exactly the same problem. Installation is done in a Kubernetes cluster via the provided Helm chart. 
The Kafka Connect is also correctly deployed and accessible, yet the "Connects" menu item does not show up in the akhq ui. 
The config was included directly in the `values.yml` via Helm as follows:

```yml
configuration:
  akhq:
    server:
      access-log:
        enabled: false
        name: org.akhq.log.access
    connections:
      kafka-k8s-cluster:
        properties:
          bootstrap.servers: "kafka-broker.svc.cluster.local:9092"
        connect:
        - name: kafka-connect
          url:  "kafka-connect.svc.cluster.local:8083"
```

I've checked that there are no mixed spaces and tabs in the configuration.

Do you have any other advice on what could be causing this problem? Thanks!
