### ISSUE TITLE
Helm - Prometheus annotation NOT in the pod template section

### ISSUE THREAD

**Issue by zheng-liang** [tchiotludo/akhq#618]
Prometheus monitoring items for the pods that Helm chart created are unable to generate automatically. Looking at the deployment itself, the annotations for Prometheus in fact are not in the pod template section but in deployment section, which is causing the issue.
Current:
```
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    prometheus.io/path: /prometheus
    prometheus.io/port: '8081'
    prometheus.io/scrape: 'true'
```
Expected to be:
```
kind: Deployment
apiVersion: apps/v1
spec:
  template:
    metadata:
      annotations:
        prometheus.io/path: /prometheus
        prometheus.io/port: '8081'
        prometheus.io/scrape: 'true'
    spec:
```
