### ISSUE TITLE
Invalid redirect URI for OAuth when using reverse proxy

### ISSUE THREAD

**Issue by mommys-little-hacker** [tchiotludo/akhq#643]
I am setting up OAuth for AKHQ with GitLab provider. When trying to authorize the following error pops up from GitLab:
```
The redirect URI included is not valid.
```

I have noticed that request to GitLab from AKHQ uses HTTP schema instead of HTTPS in redirect URI:
```
https://gitlab.domain.tld/oauth/authorize?scope=openid+email+profile&response_type=code&redirect_uri=http%3A%2F%2Fakhq.dev.cloud.domain.tld%2Foauth%2Fcallback%2Fgitlab&state=eyJyZWRpcmVjdFVyaSI6Imh0dHA6Ly9ha2hxLmRldi5jbG91ZC56ZHJhdmNpdHkucnUvb2F1dGgvY2FsbGJhY2svZ2l0bGFiIiwibm9uY2UiOiJjMzY4YTMwMy1hM2JkLTRkNzctYmMzZS1jZWJiYzZmNmYyZGIifQ%3D%3D&nonce=9bda71fd-ca22-43f2-8546-964057639652&client_id=669576c329bf201ff3b8f41357e379da85375d7942c4733ed3bd0a0304c153b2
```

I use Nginx as reverse proxy for AKHQ to terminate TLS.

Below is configuration of AKHQ:
```
akhq:
  connections:
    app:
      connect:
      - basic-auth-password: ****
        basic-auth-username: ****
        name: connect
        url: http://connect:8083
      properties:
        bootstrap.servers: kafka:9091
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule
          required username="****" password="****";
        sasl.mechanism: SCRAM-SHA-256
        security.protocol: SASL_SSL
        ssl.keystore.location: /app/keystore.jks
        ssl.keystore.password: ****
      schema-registry:
        basic-auth-password: ****
        basic-auth-username: ****
        url: http://schema-registry:8081
  security:
    groups:
      default-group: no-roles
    oidc:
      enabled: true
      providers:
        gitlab:
          default-group: no-roles
          groups:
          - groups:
            - admin
            name: my-group
          groups-field: groups
          label: Log in with GitLab
          username-field: nickname
  server:
    access-log:
      enabled: false
micronaut:
  security:
    enabled: true
    oauth2:
      clients:
        gitlab:
          client-id: ****
          client-secret: ****
          authorization:
            redirect-uri: https://akhq.dev.cloud.domain.tld/oauth/callback/gitlab
          openid:
            issuer: https://gitlab.domain.tld
      enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ****
```

Nginx server block:
```
server {
  listen 80;
  server_name akhq.dev.cloud.domain.tld;

  listen 443 ssl http2;
  ssl_certificate /etc/letsencrypt/live/web/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/web/privkey.pem;

  if ( $scheme != "https" ) {
    rewrite /* https://$http_host$request_uri permanent;
  }

  location / {
    proxy_pass http://localhost:8080;

    proxy_redirect off;

    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Real-IP $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
```

**Comment by tchiotludo** [comment]
Hi, 
I think you need to tweak the micronaut detection part behind a reverse proxy: 
```yaml
micronaut:
  server:
    host-resolution:
    host-header: Host
   protocol-header: X-Forwarded-Proto
````

Here is an example I used in the past, maybe need some tunning ;)

**Comment by mommys-little-hacker** [comment]
@tchiotludo 
Thanks a lot it helped! The URI protocol shipped within is now correct, here is the configuration snippet:
```
micronaut:
  server:
    host-resolution:
      protocol-header: X-Forwarded-Proto
      host-header: Host
```
OAuth still not working though. Error is the same: `The redirect URI included is not valid.`. I will investigate the issue and get back with functional configuration if I succeed.

**Comment by tchiotludo** [comment]
Reopen if needed

**Comment by MalteKud** [comment]
If someone else ever comes across this issue, here is my solution to working OAuth:

Additionally to the tweak to the micronaut detection part (in my case behind an AWS ALB), I had to explicitly configure the oauth2 callback-uri on micronaut to match the https scheme:

```yaml 
 micronaut:
   security:
     oauth2:
       callback-uri: https://${HOST_NAME}/oauth/callback/oidc
```

**Comment by tchiotludo** [comment]
or you can use this: 
```yaml 
micronaut:
  server:
    host-resolution:
      host-header: Host
      protocol-header: X-Forwarded-Proto
```
to have a native host resolution

**Comment by MalteKud** [comment]
Hi @tchiotludo,
that was the "micronaut detection part" which I mentioned on my comment. So my complete working configuration behind an AWS LB is this:
```yaml
  micronaut:
    security:
      enabled: true
      oauth2:
        callback-uri: https://${HOST_NAME}/oauth/callback/oidc
    server:
      host-resolution:
        host-header: Host
        protocol-header: X-Forwarded-Proto
```
Otherwise the https scheme wouldn't match.
