### ISSUE TITLE
How to specify base url when using ingress controller

### ISSUE THREAD

**Issue by rbr101** [tchiotludo/akhq#644]
Hi,

I don't get the ingress working for AKHQ
I'm using HELM repo for kubernetes.

When i specify the ingress part in the values.yml the page gets redirected to /ui. 
I think the base url or path should be defined somewhere. I want AKHQ to be available on https://hostname/akhq

I tried both:

```
micronaut
  server:
    context-path "/akhq"
```
and

```
akhq:
  server:
    base-path: "/akhq"
```

I als tried the option rewrite-target, but no difference.
My ingress config is:

```
  enabled: true
  annotations: {}
    #kubernetes.io/ingress.class: traefik
    #kubernetes.io/tls-acme: "true"
    #ingress.kubernetes.io/rewrite-target: /$2
  paths:
    - /akhq
  hosts:
    - hostname
  tls:
    - secretName: my-default-cert
```

In the AKHQ access logs i see HTTP code 307 (Temp Redis) logged.

What am i doing wrong?

**Comment by tchiotludo** [comment]
The good way is to configured akhq with that : 
```yaml
micronaut: 
  server:
    context-path: "/akhq"
```
It will expose in the pod in `/akhq`. 
Try with that and use `kubectl port-forward` to test the base path is working. 
After the ingress seems to be good I think
