### ISSUE TITLE
default values for topic creation are ignored after update

### ISSUE THREAD

**Issue by BarFoos81** [tchiotludo/akhq#648]
Hi folks,

after updating from 0.14.0 to 0.17.0 our default values for topic creation are ignored.

```yaml
akhq:
  topic:
    retention: 604800000
    partition: 2
    replication: 3
```

It worked fine before and I could not find any changes to that in the application.example.yml.
When creating a new topic, the values are 1 for partition/replication and 86400000 for retention time. 

Any hints? Thank you!
