### ISSUE TITLE
default-group: no-roles seems to have admin privileges

### ISSUE THREAD

**Issue by BarFoos81** [tchiotludo/akhq#649]
Hi,

we are using 0.17.0 and have the following security configuration:

```yaml
security:                                                                                                                                                                                                                                                                        
  default-group: no-roles                                                                                                                                                                                                                                                        
  ldap:                                                                                                                                                                                                                                                                            
    default-group: no-roles
    groups:                                                                                                                                                                                                                                                                          
      - name: kafka-admin
        groups:
          - admin
      - name: kafka-reader                                                                                                                                                                                                                                                             
        groups:                                                                                                                                                                                                                                                                          
          - reader 
```

Users are forced to login, which is fine. We have 2 LDAP-Groups (kafka-admin and kafka-reader) which should map on the default-roles in AKHQ (read/write). 

The problem:
A user who is not member of the mentioned groups can login and has admin privileges (create/delete topic). What is the correct configuration for our desired behaviour? 

I have tried the solutions in #189  and #224  without success. 

Let me know, if you need further information.

Thank you very much. 

Edit:

I tested with an even simplier configuration (see below). Every user can login and has admin rights, although there are only 3 users in the "kafka-admin" group. 

```yaml
security:                                                                                                                                                                                                                                                                        
  default-group: no-roles                                                                                                                                                                                                                                                        
  ldap:                                                                                                                                                                                                                                                                            
    default-group: no-roles
    groups:                                                                                                                                                                                                                                                                          
      - name: kafka-admin
        groups:
          - admin
```

**Comment by BarFoos81** [comment]
We found and fixed the problem. We added the membership-filter in the LDAP-configuration of micronaut according to your documentation. 

````yaml
micronaut:
  security:
    enabled: true
    ldap:
      default:
        groups:
          filter: "member={0}"
````
