### ISSUE TITLE
topicsFilterRegexp doesn't accept List

### ISSUE THREAD

**Issue by twobeeb** [tchiotludo/akhq#656]
Hello,
In order to simplify a long regex with many "or" elements, I looked in the code and figured it was possibly allowing a List
 https://github.com/tchiotludo/akhq/blob/594cda9a82e64028ff34780706740f98c3ea8054/src/main/java/org/akhq/repositories/TopicRepository.java#L171-L178

Such as that the following config : 
````yaml
security:
    groups:
      reader-all:
        name: "reader-all"
        roles:
        - "topic/read"
        - "topic/data/read"
        attributes:
          topics-filter-regexp:
          - "project1.*"
          - "project2.*"
````
would work.
But in fact it's failing during Topic filtering in the repository and when you look at the JWT, this is what we have (list in list)
````yaml
"topicsFilterRegexp": [
    [
      "project1.*",
      "project2.*"
    ]
  ]
````

You specifically check for "instance of List" so is this a bug ? 

Would it make sense to change the configuration from this : 
````yaml
topics-filter-regexp: "^(priv_bsmjlea_|pub_transport-unit|pub_loading|priv_sfr_|quality_result|fabrication|consumption).*"
````
to this ?
````yaml
topics-filter-regexp:
- priv_bsmjlea_
- pub_transport-unit
- pub_loading
- priv_sfr_
- quality_result
- fabrication
- consumption
````

Obviously applies to topics, connects and group regex.

Happy to contribute if you're fine with this change.
