### ISSUE TITLE
ingress redirect to wrong path

### ISSUE THREAD

**Issue by survivant** [tchiotludo/akhq#664]
I want to enable ingress for that application

I put this in values.yaml

````
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    paths:
    - /akhq(/|$)(.*)
    hosts:
      - ""
````

when I enter this URL : http://10.1.34.6/akhq   I'm redirected to http://10.1.34.6/ui   (404)

the Ingress yaml look like this

````
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: akhq
    meta.helm.sh/release-namespace: default
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app.kubernetes.io/instance: akhq
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: akhq
    helm.sh/chart: akhq-0.2.1
 name: akhq
 namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: akhq
            port:
              name: http
        path: /akhq(/|$)(.*)
        pathType: ImplementationSpecific
````

I have other Ingress resources that works

````
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring-stack
    meta.helm.sh/release-namespace: default
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app.kubernetes.io/instance: monitoring-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.4.3
    helm.sh/chart: grafana-6.6.3
  name: monitoring-stack-grafana
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: monitoring-stack-grafana
            port:
              number: 80
        path: /grafana(/|$)(.*)
        pathType: Prefix

````

if I enter this : http://10.1.34.6/grafana   I'm forwarded to : http://10.1.34.6/grafana/login

**Comment by tchiotludo** [comment]
Do you have setup this configuration `micronaut.server.context-path` ? 
This one allow you to change the base path of akhq

**Comment by survivant** [comment]
No, what should I put?

Le jeu. 8 avr. 2021 15 h 57, Ludovic DEHON ***@***.***> a
écrit :

**Comment by tchiotludo** [comment]
As I understand : 
```yaml 
micronaut:
  server:
    context-path: /akhq
``` 
should do the trick ;)

**Comment by survivant** [comment]
can that be configured in values.yaml ?  I didn't see where I should put that section.

under this ?

````
configuration: |
    akhq:
      server:
        access-log:
          enabled: false
          name: org.akhq.log.access
      connections:
        kafka-server:
          properties:
            bootstrap.servers: "kafka-cp-kafka:9092"
          schema-registry:
            url: "http://kafka-cp-schema-registry:8081"
          connect:
            - name: "connect"
              url: "http://kafka-cp-kafka-connect:8083"
````

**Comment by survivant** [comment]
it return this instead

{"message":"Page Not Found","_links":{"self":{"href":"/","templated":false}}}

**Comment by tchiotludo** [comment]
on which url ?

**Comment by survivant** [comment]
http://10.1.34.6/akhq 

here my config in values.yaml

````
akhq:
  enabled: true
  service:
    type: NodePort
    nodePort: 32000

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    paths:
    - /akhq(/|$)(.*)
    hosts:
      - ""

  configuration: |
    micronaut:
      server:
        context-path: /akhq
    akhq:
      server:
        access-log:
          enabled: false
          name: org.akhq.log.access
      connections:
        kafka-server:
          properties:
            bootstrap.servers: "kafka-cp-kafka:9092"
          schema-registry:
            url: "http://kafka-cp-schema-registry:8081"
          connect:
            - name: "connect"
              url: "http://kafka-cp-kafka-connect:8083"
````

**Comment by tchiotludo** [comment]
Really weird, seems to be the good one (except the nginx ingress I never used so I don't know). 
What is the version of akhq ?

**Comment by survivant** [comment]
- name: akhq
    version: 0.2.1

**Comment by tchiotludo** [comment]
I mean the docker image ?

**Comment by survivant** [comment]
image:
  repository: tchiotludo/akhq
  tag: latest

**Comment by tchiotludo** [comment]
really weird, to you have try to kubectl proxy inside the pod, to see if the application is listening on /akhq ?

**Comment by survivant** [comment]
I'll come back to you later for the port-forwarding. I think the IT put a new network rule to block that..  but I can say that the node port doesn't listen to /akhq  I obtain the same error message..but 
http://10.1.34.10:32002/
works fine.

**Comment by tchiotludo** [comment]
do you have rollout the pods after configuration change ? 
The change of configmap don't rollout pods

**Comment by survivant** [comment]
I do a helm delete... helm install  in between changes and I double check.. the cm is updated

````
root@test-pcl4004:~# kubectl get cm akhq -o yaml
apiVersion: v1
data:
  application.yml: |
    micronaut:
      server:
        context-path: /akhq
    akhq:
      server:
        access-log:
          enabled: false
          name: org.akhq.log.access
      connections:
        kafka-server:
          properties:
            bootstrap.servers: "kafka-cp-kafka:9092"
          schema-registry:
            url: "http://kafka-cp-schema-registry:8081"
          connect:
            - name: "connect"
              url: "http://kafka-cp-kafka-connect:8083"
kind: ConfigMap

````
