### ISSUE TITLE
Filter LDAP group by cluster

### ISSUE THREAD

**Issue by gerardgorrion** [tchiotludo/akhq#668]
There're some way to limit AD group to only access on 1 of the all our clusters? currently have 4 clusters but we want to delegate some right to AD group but only in dev cluster.

config:
```
          ldap:
            default:
              enabled: true
              context:
                server: 'ldaps://server:port'
                managerDn: '${VAR1}'
                managerPassword: '${VAR2}'
              search:
                enabled: true
                base: "OU=ourAD"
                filter: "sAMAccountName={0}"
              groups:
                enabled: true
                subtree: true
                base: 'OU=ouradgroup'
                filter: 'member={0}'
```

Group filters:
```
      akhq:
        server:
          access-log:
            enabled: false
        security:
          default-group: reader
          groups:
            topic-writer:
              name: topic-writer
              roles:
                - topic/read
                - topic/data/read
                - topic/data/insert
                - topic/data/delete
              attributes:
                topics-filter-regexp: "topic2.*|topic1.*"
          ldap:
            groups:
              - name: ad_group
                groups:
                  - topic-writer
```
As can you see, we only want to delegate read, add and delete topics registers, but currently they can access to all clusters.

Regards,
