### ISSUE TITLE
deser primitive avro

### ISSUE THREAD

**Issue by raphaelauv** [tchiotludo/akhq#700]
with a primitive string avro schema for key 
```json
{"type": "string"}
```

**how to reproduce :** 

```yaml
  akhq:
    image: tchiotludo/akhq:0.17.0
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka-broker:29092"
              schema-registry:
                url: "http://schema-registry:8081"
    ports:
      - 9023:8080
      - 9024:8081
```

create a topic test_topic

produce a key schema for this topic with the schema-registry : 

```shell
curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
  --data '{"schema": "{\"type\": \"string\"}"}' \
  http://localhost:8081/subjects/test_topic-key/versions
```
![Screenshot from 2021-05-14 19-15-39](https://user-images.githubusercontent.com/10202690/118306021-16554a00-b4e9-11eb-99f9-2f293c2b0fa8.png)

produce an event in the topic with the key schema ( message value can be null )

![Screenshot from 2021-05-14 19-16-36](https://user-images.githubusercontent.com/10202690/118306006-0f2e3c00-b4e9-11eb-8e7d-09763ccb72e7.png)

there is a warning for message using the avro primitive schema ->

![Screenshot from 2021-05-14 19-16-46](https://user-images.githubusercontent.com/10202690/118306039-1ce3c180-b4e9-11eb-8ba5-032c96447400.png)

```
class java.lang.String cannot be cast to class org.apache.avro.generic.GenericRecord (java.lang.String is in module java.base of loader 'bootstrap'; org.apache.avro.generic.GenericRecord is in unnamed module of loader 'app')
```

**Comment by raphaelauv** [comment]
Impossible to reproduce vith `tchiotludo/akhq:0.17.0` or `tchiotludo/akhq:dev`

I really don't know what happened, but there is still a deserialization warning

![Screenshot from 2021-05-15 17-12-21](https://user-images.githubusercontent.com/10202690/118366866-c33ece00-b5a0-11eb-8c5c-000e12f6da64.png)

**Comment by tchiotludo** [comment]
Can you provide the full stacktrace (if you have one) on the server logs ?

**Comment by raphaelauv** [comment]
I'm doing all of this in local with docker-compose

```yaml
  akhq:
    image: tchiotludo/akhq:0.17.0
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
           my_kafka:
              properties:
                bootstrap.servers: "kafka-broker:29092"
              schema-registry:
                url: "http://schema-registry:8081"
    ports:
      - 9023:8080
```

And I can't find a way to change log_level , cause the container only log acces and there is nothing specific to the WARN that appear in the UI

```shell
curl -i -X POST -H "Content-Type: application/json" \
       -d '{ "configuredLevel": "TRACE" }' \
       http://localhost:9023/loggers/org.akhq.configs
```

return 

```json
{"message":"Page Not Found","_links":{"self":{"href":"/loggers/org.akhq.configs","templated":false}}}
```
