### ISSUE TITLE
"Size: NaN undefined" with 0.18.0

### ISSUE THREAD

**Issue by erkexzcx** [tchiotludo/akhq#749]
How it looks:
![image](https://user-images.githubusercontent.com/5955795/124072999-31a0f800-da4a-11eb-8fae-33c948e63534.png)

Let me know if additional information is needed.

**Comment by tchiotludo** [comment]
I don't have the issue on my side, how it's show on 0.17.0 ?

**Comment by erkexzcx** [comment]
On 0.17.0 it shows zeroes only:
![image](https://user-images.githubusercontent.com/5955795/124082362-4cc53500-da55-11eb-8e54-bebd1575bf72.png)

At this point I am not sure if it worked on 0.17.0 - maybe I haven't noticed (and I do not need `size` column to be honest..).

**Comment by erkexzcx** [comment]
In case it helps you to narrow down the issue:
1. I am using (currently latest stable) Kafka 2.8
2. How I connect to it (taken from akhq config file):
```yaml
  connections:
    mycluster:
      properties:
        bootstrap.servers: "srv1,srv2,srv3"
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="myuser" password="mypass";
        ssl.endpoint.identification.algorithm: ""
        ssl.keystore.location: /path/to/keystore.jks
        ssl.keystore.password: mypass
        ssl.key.password: mypass
        ssl.truststore.location: /path/to/truststore.jks
        ssl.truststore.password: mypass
```
3. User used for connecting to Kafka has the following ACLs given:
```
kafka-acls.sh --bootstrap-server $BTSTRP --command-config $CCFG --add --allow-principal "User:myuser" --topic "*" --operation Describe
kafka-acls.sh --bootstrap-server $BTSTRP --command-config $CCFG --add --allow-principal "User:myuser" --topic "*" --operation DescribeConfigs
kafka-acls.sh --bootstrap-server $BTSTRP --command-config $CCFG --add --allow-principal "User:myuser" --topic "*" --operation Read
kafka-acls.sh --bootstrap-server $BTSTRP --command-config $CCFG --add --allow-principal "User:myuser" --group "*" --operation Describe
kafka-acls.sh --bootstrap-server $BTSTRP --command-config $CCFG --add --allow-principal "User:myuser" --group "*" --operation Read
```

Am I missing anything? Everything else seem to work just fine, except this bug. :)
