### ISSUE TITLE
Mutual TLS Connection with Schema Registry

### ISSUE THREAD

**Issue by sdedijer** [tchiotludo/akhq#759]
Hi,

Thank you for the nice job with AKHQ.

May I kindly ask you for help with Mutual TLS Connection with Schema Registry. I am using helm charts that you provided, and I have added `truststore` and `keystore` to `values.yaml` file like this:
```
configuration:
  akhq:
   server:
     access-log:
       enabled: true
       name: org.akhq.log.access

   connections:
     development:
       properties:
         bootstrap.servers: <bootstrap-servers>
         security.protocol: SSL
         ssl.truststore.location: /app/certificates/truststore.jks
         ssl.truststore.password: <truststor-password>
         ssl.keystore.location: /app/certificates/keystore.jks
         ssl.keystore.password: <keystore-password>
       schema-registry:
         url: <schema-registry-url>
         properties:
           schema.registry.ssl.truststore.location: /app/certificates/schema-registry-truststore.jks
           schema.registry.ssl.truststore.password: <schema-registry-truststor-password>
           schema.registry.ssl.keystore.location: /app/certificates/schema-registry-keystore.jks
           schema.registry.ssl.keystore.password: <schema-registry-keystore-password>
```
But I am getting following error
```
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
```

Mutual TLS connection with Kafka Brokers is working, but with Schema Registry unfortunately not.

Could you please help me here? Is mutual TLS at all supported in connection with Schema Registry by AKHQ?
And could you please tell me how is possible to have more detailed logs, because I don't see so much in kubernetes container logs.

Thank you very much in advance and best regards.
