### ISSUE TITLE
Unable to fetch data on the topic, however the details of the topic such as partitions , etc are displayed

### ISSUE THREAD

**Issue by karthikanumakonda** [tchiotludo/akhq#764]
Hi, Thanks to all the Development team for making such a wonderful tool. 
The issue I am facing is I am unable to fetch the data on the topic however able to see the details at topic level such as partitions, count, etc.. 

My connection details :
 connections:
    Demo_dev:
      properties:
        bootstrap.servers: "Confluent Broker URL"
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="XXX" password="XXX";
      schema-registry:
        url: "Confluent schema registry URL" 
        type: "confluent" 
        # Basic Auth user / pass
        basic-auth-username: XXX
        basic-auth-password: XXX

Error / Issue:
![image](https://user-images.githubusercontent.com/42262283/126378502-f6d3c0a7-1697-411c-82ee-ae8e1779b3d7.png)

I actually suspected if AKHQ is not fetching schema Registry details and to test that I have removed the schema registry details from the configuration file and launched AKHQ, but still I am seeing "No Data Available error".

Can you please let me know if any one has faced similar issue and the probable fix for this issue. 
thanks in Advance.

**Comment by karthikanumakonda** [comment]
To add more details to the existing issue, we tried in other laptops using the same Jar and Application.yml file.. Some of them were able to see the data whereas some of them were unable to see the data on the topic, but able to see topic details.. All machines are using Java 11. 
Are there any prerequisites that are needed.. 
Is there any configuration that needs to be configured at system/java.. 
BTW, we are using confluent cloud kafka..

**Comment by tchiotludo** [comment]
maybe a timeout ? 
you can increase it with this configuration : 
```yaml
akhq:
  topic-data:
    poll-timeout: 60000
```
Are you sure that the topic has data also ? 
Kafka Api don't allow me to know that the topic contains data.

**Comment by shnplr** [comment]
Not sure if this is relevant, but using default config I needed to change the filter for the admin group topics.

```
  security:
    default-group: admin
    groups:
      admin:
...     
        attributes:
          # Regexp list to filter topic available for group
          topics-filter-regexp:
            # - "test.*"
```
