### ISSUE TITLE
AKHQ ACLs doesn't apply 0.18.0

### ISSUE THREAD

**Issue by gundam-zeta** [tchiotludo/akhq#769]
Hello.
I would like harden AKHQ acls in my configuration, in my setup ACLS doesn't seem to apply properly.

I started using default group **reader** and **no-roles**.
What doesn't seem normal is that even using no-roles, i can create/delete topics and visualize everything in any menu.
Here is my configuration file:

```
micronaut:
  security:
    enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "xxxx"
akhq:
  connections:
    int:
      properties:
        bootstrap.servers: "xxxxx"
      schema-registry:
        url: "xxxx"
      connect:
        - name: int
          url:  "xxxxx"
      security:
        default-group: no-roles
      ui-options:
        topic:
          default-view: ALL  
          skip-consumer-groups: true 
          skip-last-record: true  
        topic-data:
          sort: NEWEST 
```

Idealy i would like to make a group that forbid the access to kafka-connect configuration for a group of user, is it possible ?
I tried to create a custom group with these permissions below, but the user cannot log to the UI if i don't grant him the group "reader" . Any idea why ?

Thank you in advance for your support.
