### ISSUE TITLE
Helm installed pod gives Read-only file system on /app/application.yml ?

### ISSUE THREAD

**Issue by iangregsondev** [tchiotludo/akhq#775]
Hi,

Can anyone help, I think I have done it correctly. It seemed pretty straight forward but I am having problems.

```
/usr/local/bin/docker-entrypoint.sh: 6: /usr/local/bin/docker-entrypoint.sh: cannot create /app/application.yml: Read-only file system
```

I get the above in the container crash.

My values file is really simple, it is stored in a configmap

```
image:
  repository: tchiotludo/akhq
  tag: latest

extraEnv:
  - name: AKHQ_CONFIGURATION
    value: |
      akhq:
       secrets:
         docker-kafka-server:
           properties:
             bootstrap.servers: "kafka:9092"
```

I am using fluxcd to deploy but this shouldn't a problem but for clarity I will place some extra info here, I am storing the values like this (I know its working as if I leave out the connections then it contains that there is no kafa servers)

```
configMapGenerator:
  - name: kafka-akhq-values
    files:
      - files/values.yaml

generatorOptions:
  disableNameSuffixHash: true
```

and in my release (from fluxcd) - I am adding them like so

```
  valuesFrom:
    - kind: ConfigMap
      name: kafka-akhq-values
```

I am confused, is there something special I should be doing ?

**Comment by iangregsondev** [comment]
I tried adding secrets instead i.e

```
secrets:
  akhq:
    connections:
      my-cluster-plain-text:
        properties:
          bootstrap.servers: "kafka:9092"
```


but now i get

```
Helm upgrade failed: template: akhq/templates/secret.yaml:13:46: executing "akhq/templates/secret.yaml" at <b64enc>: wrong type for value; expected string; got map[string]interface {} Last Helm logs: preparing upgrade for kafka-akhq resetting values to the chart's original version
```

It is expecting a string ?

**Comment by tchiotludo** [comment]
what version of helm charts are you using ?

**Comment by iangregsondev** [comment]
Yep 0.2.3

```
spec:
  releaseName: kafka-akhq
  chart:
    spec:
      chart: akhq
      sourceRef:
        kind: HelmRepository
        name: akhq
        namespace: flux-system
      version: "0.2.3"
```

**Comment by iangregsondev** [comment]
Also the source of the helm chart, for clarity, is :-

```
  url: https://akhq.io
```

**Comment by tchiotludo** [comment]
for the secrets, in the current [version](https://github.com/tchiotludo/akhq/blob/master/helm/akhq/templates/secret.yaml) is was a string, on the [next one (unreleased)](https://github.com/tchiotludo/akhq/blob/dev/helm/akhq/templates/secret.yaml) is will be yaml. 
Hope it can help

**Comment by iangregsondev** [comment]
@tchiotludo Thanks - yes looking closer, the default branch on the pager is DEV and not master... Anyway, I did update that... but this isn't fixing the issue and I noticed it was  closed ?

```
/usr/local/bin/docker-entrypoint.sh: 6: /usr/local/bin/docker-entrypoint.sh: cannot create /app/application.yml: Read-only file system
```


My file is simple now . its just this

```
#image:
#  repository: tchiotludo/akhq
#  tag: 0.2.3

## You can put directly your configuration here... or add java opts or any other env vars
extraEnv:
- name: AKHQ_CONFIGURATION
  value: |
     akhq:
       secrets:
         docker-kafka-server:
           properties:
             bootstrap.servers: "kafka:9092"
```
