### ISSUE TITLE
Login page not displayed when OIDC is enabled (0.18.0)

### ISSUE THREAD

**Issue by archetec** [tchiotludo/akhq#788]
My config was working with 0.17.0 but doesn't work with 0.18.0.

```
  micronaut:
    server:
      host-resolution:
        host-header: X-Forwarded-Host
        protocol-header: X-Forwarded-Proto
    security:
      enabled: true
      ldap:
        enabled: false
      oauth2:
        enabled: true
        clients:
          oidc:
            client-id: "#{clientId}#"
            client-secret: "#{clientSecret}#"
            openid:
              issuer: "#{issuer}#"
      token:
        jwt:
          enabled: true
          cookie:
            enabled: true
          signatures:
            secret:
              generator:
                secret: #{tokenSecret}#

...

    security:
      default-group: topic-reader
      groups:
        LOB-admin:
          name: LOB-admin
          roles:
            - topic/read
            - topic/insert
            - topic/delete
            - topic/config/update
            - node/read
            - topic/data/read
            - topic/data/insert
            - topic/data/delete
            - group/read
            - group/delete
            - group/offsets/update
            - registry/read
            - registry/insert
            - registry/update
            - registry/delete
            - registry/version/delete
            - acls/read
            - connect/read
            - connect/insert
            - connect/update
            - connect/delete
            - connect/state/update      
          attributes:
            topics-filter-regexp: 
              - "#{topic.filter}#"
        LOB-reader:
          name: LOB-reader
          roles:
            - topic/read
            - topic/data/read
            - group/read
            - node/read
            - registry/read
            - acls/read
            - connect/read
          attributes:
            topics-filter-regexp: 
              - "#{topic.filter}#"
        LOB-writer:
          name: LOB-writer
          roles:
            - topic/read
            - topic/data/read
            - topic/data/insert
            - group/read
            - node/read
            - registry/read
            - acls/read
            - connect/read          
          attributes:
            topics-filter-regexp: 
              - "#{topic.filter}#"
      oidc:
        enabled: true
        providers:
          oidc:
            label: "Login with AAD"
            groups-field: roles
            username-field: unique_name
            groups:
              - name: #{admin.role.name}#
                groups:
                  - LOB-admin
              - name: #{reader.role.name}#
                groups:
                  - LOB-reader
              - name: #{writer.role.name}#
                groups:
                  - LOB-writer
```

I left out parts that are not related to security for readability.

When I try to access AKHQ I end up with a black page and the "Login with AAD" button that used to be there isn't anymore.  I checked logs, enabled TRACE, I see nothing.  The requests aren't being logged, and there are no error messages.  I'm not sure where to look.

Did I miss something in the changes for 0.18.0?  Something that I need to apply in my configuration?

If not, I see there were some modifications around the login form activation and LDAP, could that have an unwanted effect on OIDC?

TIA
