### ISSUE TITLE
UI Options does not work in v0.18.0

### ISSUE THREAD

**Issue by Argonus** [tchiotludo/akhq#798]
Hello, first thanks for amazing work :)

I'm adding a AKHQ PoC for my Kafka cluster, and I've started with image version **v0.18.0**
What's noticed it that UI options are not working there both with global & cluster options

Example:
```yaml
akhq:
  ui-options:
    topic:
      default-view: HIDE_INTERNAL_STREAM
      skip-consumer-groups: true
    topic-data:
        sort: NEWEST
  connections:
    my-cluster:
      ui-options:
        topic:
          default-view: HIDE_INTERNAL_STREAM
          skip-consumer-groups: true
        topic-data:
          sort: NEWEST
```

But when I've downgraded to the **v0.17.0** version all works as expected ;) 

I am not really sure where is the issue but maybe this info will be helpful but this could be related to localStorage of the app.
When I've opened a card with incognito mode, I've consumer groups visible. 
But when I open it in a normal card, with all cache removed before... it displays me consumer groups.
