### ISSUE TITLE
Redirect to login page when user session/token expires

### ISSUE THREAD

**Issue by gquintana** [tchiotludo/akhq#801]
1. I have an AKHQ with security enabled plugged to an LDAP directory. 
2. I successfully log into AKHQ using AKHQ login page
3. I sucessfully use AKHQ ui for a while
4. Something expires: in AKHQ 0.17 I got "500 Internal Server Error" notifications, on AKHQ 0.18 nothing happens anymore but all the screens remain empty. Anonymous connection has no rights at all in my case, so I guess API calls return nothing or timeout.
5. I have to click on the Logout button to show the login page

I'd like the login page to appear automatically when the user token expires, or at least be properly notified that expiration occured and force logout.

**Comment by tchiotludo** [comment]
The better will be to used true [JWT token](https://micronaut-projects.github.io/micronaut-security/latest/guide/#jwt) on the UI side I think (not the cookie one) but as I remember we can't because of OIDC connect (the redirect is on backend as I remember).
So we need to add the expiration time `/me` and maybe add [refresh](https://micronaut-projects.github.io/micronaut-security/latest/guide/#refresh) or at least a simple redirect.

**Comment by jheinitz** [comment]
Good morning,

is there any news on this one? As some kind of workaround might it be possible to increase the timeout?

Thanks ad best regards

Jens

**Comment by tchiotludo** [comment]
You can raise the timeout of the using this configuration : 
```yaml 
    micronaut:
      security:
        token:
          jwt:
            generator:
              access-token-expiration: 36000
              access-token:
                expiration: 36000
            cookie:
              cookie-max-age: 10h
```
