### ISSUE TITLE
IAM MSK support

### ISSUE THREAD

**Issue by tooptoop4** [tchiotludo/akhq#810]
Support for https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html

**Comment by tchiotludo** [comment]
For aws part, I don't have any AWS account, so this one will need a PR for people using it.

**Comment by tooptoop4** [comment]
already works.

application.yml:
```
micronaut:
  server:
    port: 8089
    host: "0.0.0.0"
akhq:
  connections:
    my-cluster-sasl:
      properties:
        bootstrap.servers: "redact:9098"
        security.protocol: SASL_SSL
        sasl.mechanism: AWS_MSK_IAM
        sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
        sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
        ssl.truststore.location: /home/user/kafka.client.truststore.jks
        ssl.truststore.password: changeit
        ssl.keystore.location: /home/user/kafka.client.truststore.jks
        ssl.keystore.password: changeit
      schema-registry:
        url: "http://localhost:8081"
```

```
java -Dmicronaut.config.files=application.yml -cp /home/user/iamjar/aws-msk-iam-auth-1.1.1-all.jar:/home/user/iamjar/akhq.jar org.akhq.App
```
