### ISSUE TITLE
its possible disable Anonymous login

### ISSUE THREAD

**Issue by bmcentos** [tchiotludo/akhq#820]
Hi, I'm using "tchiotludo/akhq" image to connect to my Kafka Brokers and Ldap to autenticate users. This is working Fine, and when i get "/" from my frontend, i get my login page, but, if access again in anon browser mode, i get full access as Anonymous user, as below:

```
akhq_1  | 2021-09-20 17:53:20,038 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-09-20T17:53:20.038076Z] [Duration: 0 ms] [Url: GET /ui/static/js/main.98abc9ad.chunk.js] [Status: 200] [Ip: /10.xx.xx.xx] [**User: Anonymous**]
akhq_1  | 2021-09-20 17:53:21,039 INFO  r-thread-2 org.akhq.log.access        [Date: 2021-09-20T17:53:21.026963Z] [Duration: 12 ms] [Url: GET /api/kafka-server/group/topics] [Status: 200] [Ip: /10.xx.xx.xx] [**User: Anonymous**]
akhq_1  | 2021-09-20 17:53:21,134 INFO  r-thread-1 org.akhq.log.access        [Date: 2021-09-20T17:53:21.027574Z] [Duration: 106 ms] [Url: GET /api/kafka-server/topic/last-record] [Status: 200] [Ip: /10.xx.xx.xx] [**User: Anonymous**]

```

My security app is:

```
akhq:
  security:
    enabled: true
    default-groups:
      - no-roles
    ldap:
#GRUPOS LDAP
      groups:
        - name: Administrators 
          groups: 
            - admin

```
My ideia is  completly remove access from Anonymous user. Its is possible?

Thanks

**Comment by tchiotludo** [comment]
You use a mistake on `default-group`, it's not an array but a string : 
```yaml 
    default-group: no-roles
```

**Comment by bmcentos** [comment]
Hi, thank you for repply. I had try like this, but maybe in a wrong location in file. 

Like this, as you said work fine.

```
akhq:
  security:
#DESABILITA ACESSO ANONYMO
    default-group: no-roles
    enabled: true

```

Thank you.
