### ISSUE TITLE
Topics options are not taken into account

### ISSUE THREAD

**Issue by c-houis** [tchiotludo/akhq#821]
Using AKHQ v 0.18.0.

It seems that topics options are not taken into account.

Here is my configuration:

```yaml
akhq:
  topic:
    partition: 12
    replication: 3
    retention: 1209600000
```

But in the UI, I still got default values when creating a new topic.

Am I missing something ?

Thank for your support,

  Cédric
