### ISSUE TITLE
Callback URI from login is HTTP Want to Change to HTTPS

### ISSUE THREAD

**Issue by sunnvsp** [tchiotludo/akhq#830]
Can we add a feature for the callback URL with HTTPS, since my ingress was blocked by the HTTP?

**Comment by tchiotludo** [comment]
Micronaut try to detect if behind a reverse proxy the scheme of the callback url. 
If your ingress use a non standard Header, you can customize it to match the headers. Here is an example that make it work for GKE ingress  : 
```yaml 
    micronaut:
      server:
        host-resolution:
          host-header: Host
          protocol-header: X-Forwarded-Proto

````
