### ISSUE TITLE
Not being able to deploy basic auth with Helm

### ISSUE THREAD

**Issue by caebozzini** [tchiotludo/akhq#832]
Using AKHQ v 0.18.0.
Chart ver.: 0.2.3

If deployed without `micronaut.security.disabled`, AKHQ is working as intended, without a login screen, and connecting to a Kafka Confluent broker through `akhq.connections.servername.properties`

If I enable security and follow README instructions, I always get this error on the logs:

```java
pGroup-1-4 .s.n.RoutingInBoundHandler Unexpected error occurred: Failed to inject value for parameter [basicAuth] of method [setBasicAuth] of class: org.akhq.configs.SecurityProperties 

Message: Error resolving property value [akhq.security.basic-auth]. Property doesn't exist           

Path Taken: new SecurityFilter([Collection securityRules],Collection authenticationFetchers,SecurityConfiguration securityConfiguration) --> SecuredAnnotationRuleWithDefault.securityProperties --> SecurityProperties.setBasicAuth([List basicAuth])

io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [basicAuth] of method [setBasicAuth] of class: org.akhq.configs.SecurityProperties

Message: Error resolving property value [akhq.security.basic-auth]. Property doesn't exist

Path Taken: new SecurityFilter([Collection securityRules],Collection authenticationFetchers,SecurityConfiguration securityConfiguration) --> SecuredAnnotationRuleWithDefault.securityProperties --> SecurityProperties.setBasicAuth([List basicAuth])
```

And then the application just won't work, I won't be able to access it.

Current `values.yaml ` snippets(copied from another issue with similar problems, error remains the same):

```yaml
configuration:
  akhq:
    server:
      access-log:
        enabled: true
        name: org.akhq.log.access
    security:
      basic-auth:
        admin:
          password: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
          groups:
            - admin
        readonly:
          password: 3d0941964aa3ebdcb00ccef58b1bb399f9f898465e9886d5aec7f31090a0fb30
          groups:
            - topic-reader
      default-groups:
            -
      groups:
        admin:
         roles:
           - topic/read
           - topic/insert
           - topic/delete
           - topic/config/update
           - node/read
           - topic/data/read
           - topic/data/insert
           - topic/data/delete
           - group/read
           - group/delete
           - group/offsets/update
           - registry/read
           - registry/insert
           - registry/update
           - registry/delete
           - registry/version/delete
      attributes:
        topics-filter-regexp: "test.*"

        topic-reader:
          roles:
           - topic/read
           - topic/config/update
           - node/config/update
           - node/read
           - topic/data/read
           - group/read
           - group/offsets/update
           - registry/read
           - acls/read
           - connect/read
           - connect/state/update
           - registry/update
          attributes:
            topics-filter-regexp: "test\\.reader.*"
```
```yaml
secrets:
  micronaut:
    security:
      enabled: true
  akhq:
    connections:
      kafkaname:
        properties:
          bootstrap.servers: MY_KAFKA_BROKER
          sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="username" password="password";
          sasl.mechanism: PLAIN
          ssl.endpoint.identification.algorithm: https
          security.protocol: SASL_SSL
```
Note: I've already tried moving each part of the configurations between `configuration` and `secret` just to be sure this isn't a placement issue, to no avail; both `application.yml` and `application-secrets.yml` are present in `MICRONAUT_CONFIG_FILES` when checking environment variables inside the deployed container.

Any help is appreciated, thank you.

**Comment by tchiotludo** [comment]
I think it's because  `basic-auth` properties is an array, not an map : 
```yaml 
    basic-auth:
      - username: user
        password: d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1
        groups:
          - admin
```
