### ISSUE TITLE
AKHQ behind AWS ELB

### ISSUE THREAD

**Issue by caebozzini** [tchiotludo/akhq#836]
Using AKHQ v 0.18.0.
Chart ver.: 0.2.3

Sorry if this is a newbie issue (again), but I can't find a way to make AKHQ to load with a Kubernetes Ingress behind a AWS (internal) ELB.

As of now, I'm doing this:

```yml
micronaut:
    server:
      host-resolution:
        host-header: Host
        protocol-header: X-Forwarded-Proto
```
and this
```yml
ingress:
  enabled: true
  paths:
    - /
  hosts:
    - subdomain.domain.foo.bar
 ```

And this is what I see in the browser:
![Screen Shot 2021-09-29 at 18 45 41](https://user-images.githubusercontent.com/13447086/135353078-087ffbd4-0c43-4cfe-bc80-19858d6c5805.png)
![Screen Shot 2021-09-29 at 18 43 53](https://user-images.githubusercontent.com/13447086/135353006-c37a94e4-1154-4693-8542-3edadd2c406f.png)
![Screen Shot 2021-09-29 at 18 44 29](https://user-images.githubusercontent.com/13447086/135353014-72ea3185-ebd7-4a8a-829e-e02b89ccf8a2.png)
![Screen Shot 2021-09-29 at 18 44 33](https://user-images.githubusercontent.com/13447086/135353022-1c56af07-cc97-4a96-bb39-b2e758380c68.png)

What am I missing?
Thanks and again sorry if this has an obvious response.
