### ISSUE TITLE
Login with azureAD - can't match the reply URLs

### ISSUE THREAD

**Issue by jiyangtw** [tchiotludo/akhq#837]
Using AKHQ v 0.18.0.

For the security, we configure like this:
```
configuration:
  akhq:
    security:
      default-group: no-roles
      oidc:
        enabled: true
        providers:
          azuread:
            label: "Login with SSO"
            username-field: unique_name
            groups-field: groups
            default-group: reader
micronaut:
    security:
      enabled: true
      oauth2:
        enabled: true
        clients:
          azuread:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            client-credentials:
              scope: openid profile email user.read
            openid:
              issuer: https://login.microsoftonline.com/<tenant-id>
              response-type: id_token code token
```

But when I tried to login with azureAD, it can't be login successfully.
![image](https://user-images.githubusercontent.com/89758094/135401487-59702c45-5c7c-4d45-b538-f7fefa2b9bfc.png)

And I found that the redirect_uri in url changed to be 'http', not the 'https'.

**Comment by tchiotludo** [comment]
The error is telling that you need to configure redirect_url on azure side.

**Comment by jiyangtw** [comment]
> The error is telling that you need to configure redirect_url on azure side.

In fact, I have configured the redirect_url on azure side. It only support https url, but the akhq redirect_url  shows the http, so the error happened.
The main problem is akhq generate a http redirect_url.I don't know why

**Comment by tchiotludo** [comment]
Are you behind a reverse proxy ?
If yes, you probably need to help micronaut to understand your scheme. Here is an example with GKE load balancer :
```yaml
micronaut:
    server:
      host-resolution:
        host-header: Host
        protocol-header: X-Forwarded-Proto
```
