### ISSUE TITLE
Sort topic data

### ISSUE THREAD

**Issue by jjoyson** [tchiotludo/akhq#841]
The topic data sorting option does not seem to work for me. Am I doing something wrong?

Here is my configuration:
```
akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: ...
              schema-registry:
                url: ...
              connect:
                - name: ...
                  url: ...
              options:
                topic-data:
                  sort: NEWEST
                ui-options:
                  topic-data:
                    sort: NEWEST
          topic-data:
            sort: NEWEST
          ui-options:
            topic-data:
              sort: NEWEST
```
             
I tried all the different combinations from the documentation and some responses from posts here. But always sorts by OLDEST when the compose is run
