### ISSUE TITLE
kafka-long key(with avro value) is mis-parsed as avro type

### ISSUE THREAD

**Issue by uqix** [tchiotludo/akhq#842]
![image](https://user-images.githubusercontent.com/10142314/135744327-420c6298-961d-416b-bb8e-5c950ad01f15.png)

**Comment by tchiotludo** [comment]
Can you try with dev version please, there is a fix about primitive avro type

**Comment by uqix** [comment]
Sorry for ambiguity, the message key type is kafka builtin long, and the value type is avro.

**Comment by tchiotludo** [comment]
Ok but it's always an primitive, please try with dev branch please

**Comment by uqix** [comment]
Will do later, thanks

**Comment by uqix** [comment]
It seems that the kafka-long key is still parsed as avro-long type:

![image](https://user-images.githubusercontent.com/10142314/135787530-f53424bb-83d9-4ca3-b20b-c0b4959b9709.png)

**Comment by uqix** [comment]
Maybe the UI could let us select key/value type?

**Comment by tchiotludo** [comment]
Long doesn't exist for Kafka key since key are always store as bytes.
If AKHQ display this message, it means that the first bytes of your key message is the special format for schema registry message with an id (in your case 0).

Maybe you can try with kafkacat or kafka-console-consumer but I'm pretty sure that the same error will be displayed on these tool meaning an incorrect message store on Kafka

**Comment by uqix** [comment]
Long keys are consumed well by Conduktor:

![image](https://user-images.githubusercontent.com/10142314/135798246-9ec8e20d-7aed-4db8-853f-ce702cd4d3b5.png)

**Comment by tchiotludo** [comment]
Can you try with other tools I mentioned ?
conduktor is closed source and I can't figure how it's handle.
Or can you provide a way to reproduce the issues ? I don't know how to produce this kind of message and I need to exact message on my side to fix that.

**Comment by uqix** [comment]
@tchiotludo FYI, here's our spring-boot kafka properties:

```yaml
spring.kafka:
  properties:
    schema.registry.url: http://schema-registry.kafka
    specific.avro.reader: true
  consumer:
    keyDeserializer: org.apache.kafka.common.serialization.LongDeserializer
    valueDeserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  producer:
    keySerializer: org.apache.kafka.common.serialization.LongSerializer
    valueSerializer: io.confluent.kafka.serializers.KafkaAvroSerializer
```
