### ISSUE TITLE
ldap group membership attribute not working properly

### ISSUE THREAD

**Issue by dominicwenig** [tchiotludo/akhq#848]
Version: 0.18.0

**From the documentation**
In Case your LDAP groups do not use the default UID for group membership, you can solve this using
```
micronaut:
  security:
    enabled: true
    ldap:
      default:
        search:
          base: "OU=UserOU,dc=example,dc=com"
          attributes:
            - "cn"
        groups:
          enabled: true
          base: "OU=GroupsOU,dc=example,dc=com"
          filter: "member={0}"
```
Replace
```
attributes:
  - "cn"
```
with your group membership attribute

My configuration
```
micronaut:
  security:
    enabled: true
    ldap:
      default:
        enabled: true
        context:
          server: 'ldap://<IP>:389'
          managerDn: 'XXX,dc=helenic,dc=local'
          managerPassword: 'XXX'
        search:
          base: "ou=people,dc=helenic,dc=local"
          attributes:
            - "cn"
        groups:
          enabled: true
          base: "ou=group,dc=helenic,dc=local"
          filter: "(&(objectClass=posixGroup)(memberUid={0}))"
```

However in the tcpdump the query looks like it is querying the whole DN (with uid=...ou=...dc=...)
```
E..e.]@.@..g...9...E......o.L...P....&..0;...`6....+uid=akhq-ldap,ou=people,dc=helenic,dc=local..akhq
...
E....`@.@......9...E......Tp.`$.P.......0.....c....ou=group,dc=helenic,dc=local
...
............U....objectClass.
posixGroup.8.   memberUid.+uid=akhq-ldap,ou=people,dc=helenic,dc=local0...cn..0...2.16.840.1.113730.3.4.2

```
```
E..`.H@.@......9...E."..OlE.....P....!..06...`1....&uid=akhq,ou=people,dc=helenic,dc=local..akhq
...
E....g@.@......9...E......U..`$_P.......0.....c....ou=group,dc=helenic,dc=local
...
............P....objectClass.
posixGroup.3.   memberUid.&uid=akhq,ou=people,dc=helenic,dc=local0...cn..0...2.16.840.1.113730.3.4.2
```

**My LDAP group**
```
# akhq, group, helenic.local
dn: cn=akhq,ou=group,dc=helenic,dc=local
...
objectClass: posixGroup
...
cn: akhq
...
memberUid: akhq
memberUid: akhq-ldap
```

Currently I fixed this by adding whole DN of the user to the group, e.g.
```
memberUid: uid=akhq,ou=people,dc=helenic,dc=local
```
