### ISSUE TITLE
LDAD Connectios

### ISSUE THREAD

**Issue by javier-torres** [tchiotludo/akhq#887]
Hi,

We have chosen your application to maintain our MSK on AWS. We have managed to set up basic authentication but with LDAP we are having problems. We have checked that there is connectivity with LDAP. Attached is the configuration:

```yaml
micronaut:
  security:
    enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: dgTXXXXXXXXXXXXXXXXXXXdg3$GHgfj
    ldap:
      default:
        enabled: true
        context:
          server: 'ldap://ibr-dev-mad.ibr.local:389'
          managerDn: 'CN=akhq,OU=AKHQ,OU=Applications,OU=XXX Data,OU=IBR_USER_REPO,DC=IBR,DC=LOCAL'
          managerPassword: 'password'
        search:
          base: "OU=AKHQ,OU=Applications,OU=XXX Data,OU=IBR_USER_REPO,DC=IBR,DC=LOCAL"
        groups:
          enabled: true
          base: "OU=AKHQ,OU=Applications,OU=XXX Data,OU=IBR_USER_REPO,DC=IBR,DC=LOCAL"

akhq:
  security:
    default-group: no-roles
    basic-auth:
      - username: admin
        password: a56ad3f2440820608303a0d4a84b1f1858660ead830b8e7df8e8d0b5a7eed13a
        groups:
          - admin
    groups:
      topic-reader:
        name: topic-reader # Group name
        roles: # roles for the group
          - topic/read
        attributes:
          # List of Regexp to filter topic available for group
          # Single line String also allowed
          # topics-filter-regexp: "^(projectA_topic|projectB_.*)$"
          topics-filter-regexp:
            - "^projectA_topic$" # Individual topic
            - "^projectB_.*$" # Topic group
          connects-filter-regexp:
            - "^test.*$"
          consumer-groups-filter-regexp:
            - "consumer.*"
      topic-writer:
        name: topic-writer # Group name
        roles:
          - topic/read
          - topic/insert
          - topic/delete
          - topic/config/update
        attributes:
          topics-filter-regexp:
            - "test.*"
          connects-filter-regexp:
            - "^test.*$"
          consumer-groups-filter-regexp:
            - "consumer.*"
      ldap:
        groups:
          - name: AWS-MSK
            groups:
              - topic-reader
              - topic-writer
        users:
          - username: akhq
            groups:
              - topic-reader
              - topic-writer

  connections:
    Sandbox:
      properties:
        bootstrap.servers: ${BOOTSTRAP_SERVERS}
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username=${SASL_JAAS_CONFIG_USERNAME} password=${SASL_JAAS_CONFIG_PASSWORD};`
```
We have tested the same configuration with an LDAP client and it works perfectly. However when we go to log into the application we get the following WATN in the log:

WARN  r-thread-1 u.LoginFailedEventListener Login failed reason USER_NOT_FOUND, username unknown, message User Not Found

This is a screenshot of the same configuration for LDAP testing:

![image](https://user-images.githubusercontent.com/59615952/139261432-d1c7d52a-6e2a-446c-a5e7-d9b160190b21.png)

Could you please help us?

Thank you,
Javier Torres
