### ISSUE TITLE
`null` username when using GitLab as OIDC provider.

### ISSUE THREAD

**Issue by pawelrubin** [tchiotludo/akhq#900]
When connecting to **AKHQ** using GitLab OIDC, the username field is null
```json
{
    "logged": true,
    "username": "null"
}
```
 despite setting the `username-field` to `nickname`. According to GitLab [docs](https://docs.gitlab.com/ee/integration/openid_connect_provider.html#shared-information), the `nickname` field should be available.

`AKHQ_CONFIGURATION` file:
```yml
akhq:
  connections:
    ...

  security:
    default-group: no-roles
    oidc:
      enabled: true
      providers:
        gitlab:
          label: Log in with GitLab
          default-group: reader
          groups-field: groups
          username-field: nickname

micronaut:
  security:
    enabled: true
    oauth2:
      enabled: true
      clients:
        gitlab:
          client-id: <oidc-id>
          client-secret: <oidc-secret>
          scopes:
            - openid
            - profile
            - email
          openid:
            issuer: <gitlab-url>
```
