### ISSUE TITLE
AKHQ configuration parameters not taken into account

### ISSUE THREAD

**Issue by thibthibus** [tchiotludo/akhq#904]
Hi, I added the following parameters in my application.yaml in AKHQ 0.19.0 but they are not taken into account. Any idea ?
            **skip-consumer-groups: false
            skip-last-record: false
          topic-data:
            sort: NEWEST
          ui-options:
            topic:
              skip-consumer-groups: true
              skip-last-record: true
            topic-data:
              sort: NEWEST**

The application.yaml looks like this:
```
akhq:
  security:
    default-group: reader
  connections:
    cluster-main-devl:
      schema-registry:
        url: https://<schema-registry.url>
      properties:
        bootstrap.servers: <bootstrap.servers.host>:<bootstrap.servers.port>
        security.protocol: SSL
        ssl.truststore.location: /etc/tls/truststore/ca.p12
        ssl.truststore.type: pkcs12
        ssl.truststore.password: ${SSL_TRUSTSTORE_PASSWORD}
        ssl.keystore.location: /etc/tls/keystore/user.p12
        ssl.keystore.type: pkcs12
        ssl.keystore.password: ${SSL_KEYSTORE_PASSWORD}
        ssl.key.password: ${SSL_KEY_PASSWORD}
  topic:
    stream-regexps:
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"
      - "^.*-subscription-registration-topic$"
      - "^.*-subscription-response-topic$"
      - "^.*-KTABLE-FK-JOIN-SUBSCRIPTION-REGISTRATION-\\d+-topic$"
      - "^.*-KTABLE-FK-JOIN-SUBSCRIPTION-RESPONSE-\\d+-topic$"
    skip-consumer-groups: false
    skip-last-record: false
  topic-data:
    sort: NEWEST
    ui-options:
      topic:
        skip-consumer-groups: true
        skip-last-record: true
      topic-data:
        sort: NEWEST
```
Regards,

Thibaut
