### ISSUE TITLE
Need to Login twice 

### ISSUE THREAD

**Issue by shnplr** [tchiotludo/akhq#907]
Hi Testing Helm deploy with basic auth 

After clicking "Logout" get displayed login page (good). But when logging in again (same or different user) the application show briefly and then goes back to the login screen.  Login 2nd time it is OK.  Why would need to logon twice after logging out?

```
appVersion: "0.19.0"

configuration:
  micronaut:
    security:
      enabled: true
      token:
        jwt:
          signatures:
            secret:
              generator:
                secret: bc45ffbcf429017c46a2724b64907261f46b413e541e7963e6520a19d5d460f8
...
  akhq:
...
    security:
      default-group: no-roles # Default groups for all the user even unlogged user
      # Groups definition
      groups:
        admin: # unique key
          name: admin # Group name
          roles:  # roles for the group
            - topic/read
            - etc
...
      basic-auth:
        - username: admin
          password: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918 # Password in sha256
          groups: # Groups for the user
            - admin
```
