### ISSUE TITLE
 Unable to start Micronaut server on port: 8080

### ISSUE THREAD

**Issue by thedje** [tchiotludo/akhq#921]
Hi,

I wanted to change version of akhq (from 0.16.0 to 0.19.0) and I have the following error: 
```
akhq    | 2021-11-24 09:22:58,943 ERROR main       i.m.runtime.Micronaut      Error starting Micronaut server: Unable to start Micronaut server on port: 8080
akhq    | io.micronaut.http.server.exceptions.ServerStartupException: Unable to start Micronaut server on port: 8080
akhq    |       at io.micronaut.http.server.netty.NettyHttpServer.bindServerToHost(NettyHttpServer.java:505)
akhq    |       at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:323)
akhq    |       at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:114)
akhq    |       at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:77)
akhq    |       at java.base/java.util.Optional.ifPresent(Unknown Source)
akhq    |       at io.micronaut.runtime.Micronaut.start(Micronaut.java:75)
akhq    |       at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
akhq    |       at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
akhq    |       at org.akhq.App.main(App.java:27)
akhq    | Caused by: java.net.BindException: Address already in use
```
At the level of my docker-compose, I only changed the version: 
```
diff docker-compose-0-16-0.yml docker-compose.yml
5c5
<     image: tchiotludo/akhq:0.16.0
---
>     image: tchiotludo/akhq:0.19.0
15a16
>
```

At the micronaut conf level, I put :
```
micronaut:
  security:
    enabled: true
    # LDAP configuration
    ldap:
      default:
        enabled: true
        context:
          server: 'ldaps://xxxxxx'
          managerDn: 'cn=xxxxx'
          managerPassword: 'xxxxxx'
        search:
          base: "ou=Utilisateurs,dc=maif,dc=local"
        groups:
          enabled: true
          base: "ou=Utilisateurs,dc=maif,dc=local"

akhq:
  connections:
```
Did I forget something?
