### ISSUE TITLE
Disabling all auth methods except basic-auth on akhq 0.19 does not seem to be honoured

### ISSUE THREAD

**Issue by nightswimmings** [tchiotludo/akhq#936]
I am trying to configure akhq so it only accepts basic-auth, and so far I assumed the proper way to do it is providing the following configuration on the helm chart

```
     micronaut:
        security:           # NOT HONOURED?: https://micronaut-projects.github.io/micronaut-security/2.5.0/guide/configurationreference.html
          enabled: true
          endpoints:
            login:
              enabled: false
            logout:
              enabled: false
            oauth:
              enabled: false
          oauth2:
            enabled: false
          token:
            enabled: false
            jwt:
              enabled: false
              bearer:
                enabled: false
              signatures:
                secret:
                  generator:
                    secret: thissecretisjustsetupforavoidingdefaultsecretwarningatstartup.
```
+ akhq.security.basic-auth (...)

but It is apparently not honouring the setup. The login page shows up in the UI, and the warning message about the default secret is at startup even though i just disabled both token and jwt security.
Is this expected? Am I doing something wrong?
