### ISSUE TITLE
UI-options don't seem to work at all.

### ISSUE THREAD

**Issue by dezka** [tchiotludo/akhq#994]
I have the following docker setup:

```
  akhq:
    image: tchiotludo/akhq
    hostname: kafkahq
    container_name: kafkahq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          ui-options:
            topic:
              default-view: ALL
              skip-last-record: true
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
              schema-registry:
                url: "http://schema-registry:8081"
```

Note I'm trying to set `default-view` to `ALL` and `skip-last-record` to `true`. However, when I load the UI these don't seem to take effect:

![Screen Shot 2022-01-26 at 11 15 43 AM](https://user-images.githubusercontent.com/17245526/151202094-a29c74dc-9c2c-43d0-9ced-21e2f0d44752.png)

I've noticed similar behavior for `akhq.ui-options.topic.show-all-consumer-groups` as well.
