### ISSUE TITLE
Failed to read configuration file

### ISSUE THREAD

**Issue by techpassionx** [tchiotludo/akhq#998]
When I try to deploy AKHQ on AKS I get an error:
```
022-01-27 14:07:06,353 ←[1;31mERROR←[0;39m ←[35mmain      ←[0;39m ←[36mi.m.runtime.Micronaut     ←[0;39m Error starting Micronaut server: Failed to read configuration file: /app/application.yml
```

The configuration file(```application.yml```) looks like this:

```
akhq:
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]" # Logger format

# list of kafka cluster available for akhq
  connections:
    kafka-cluster-ssl:
      properties:
        bootstrap.servers: "wn0-dev0-q.amn0sjl2biwu1com4pmdmwwd0c.ax.internal.cloudapp.net:9093,wn1-dev0-q.amn0sjl2biwu1com4pmdmwwd0c.ax.internal.cloudapp.net:9093,wn2-dev0-q.amn0sjl2biwu1com4pmdmwwd0c.ax.internal.cloudapp.net:909"
        security.protocol: SSL
        ssl.truststore.location: /app/truststore.jks
        ssl.truststore.password: PWD
        ssl.keystore.location: /app/keystore.jks
        ssl.keystore.password: PWD
        #ssl.key.password: PWD
```

```
```
